import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const pageSource = readFileSync(
  join(process.cwd(), "src/app/reports/[reportId]/page.tsx"),
  "utf8",
);
const compatibilityViewSource = readFileSync(
  join(process.cwd(), "src/app/reports/[reportId]/CompatibilityReportView.tsx"),
  "utf8",
);
const source = `${pageSource}\n${compatibilityViewSource}`;

describe("report result page source", () => {
  it("renders generated report draft sections and safe fallback states", () => {
    const requiredMarkers = [
      "사주×MBTI 종합 리포트",
      "draft.openingTitle",
      "draft.openingSummary",
      "draft.coreLine",
      "draft.sections.filter",
      "draft.chapters.map",
      "ManseRyeokCommonTable",
      "buildManseRyeokCommonTableData",
      "normalizePillarGridForManseRyeokTable",
      "MbtiCommonProfileTable",
      "buildMbtiCommonProfileTableData",
      "getMbtiSourceByType",
      "defaultOpen={true}",
      "만세력 및 명리학 표",
      "profile.fourPillarGrid",
      "profile.yearPillar",
      "profile.monthPillar",
      "profile.dayPillar",
      "profile.hourPillar",
      "profile.dayMaster",
      "profile.fiveElementSummary",
      "profile.fiveElementBadges",
      "profile.tenGodSummary",
      "profile.majorSinsal",
      "profile.gwiinGilshin",
      "profile.sinsal",
      "profile.gwiin",
      "element-bg--",
      "신살 요약",
      "귀인/길신 요약",
      "사주 원국 요약",
      "MBTI 입력 요약",
      "리포트 본문",
      "chapter.titleKo",
      "chapter.headline",
      "chapter.hitReadingLines",
      "chapter.body",
      "chapter.solutionLines",
      "renderV2IntegratedChapterProse",
      "<details",
      "section.titleKo",
      "section.oneLine",
      "section.body",
      "분석 근거 보기",
      "사주 근거",
      "MBTI 참고",
      "최종 조언",
      "isCompatibilityReportDraft",
      "renderGeneratedCompatibilityState",
      "사주×MBTI 궁합 리포트",
      "CompatibilityTable",
      "buildCompatibilityTableData",
      "buildCompatibilityTopTableData",
      "mapCompatibilityTableRelationCategory",
      "buildCompatibilityPersonTableInput",
      "buildCompatibilityFourPillarGrid",
      "getMbtiSourceByType",
      "buildMbtiCommonProfileTableData",
      "두 사람 만세력 비교",
      "관계 유형",
      "종합 궁합 점수",
      "draft.personALabel",
      "draft.personBLabel",
      "formatCompatibilityRelationshipType(draft.relationshipType)} 궁합",
      "sanitizeCompatibilityVisibleText",
      "getCompatibilityRelationshipTypeLabel",
      "getCompatibilityScoreCaution",
      "getCompatibilityScoreDisplayLabels",
      "getCompatibilityScoreExplanation",
      "draft.scoreSummary.scoreLabel",
      "getCompatibilityScoreCaution(",
      "compatibilityScoreOrder",
      "scoreLabels[key]",
      "relationshipType: draft.relationshipType",
      "category: key",
      "핵심 결",
      "주의 결",
      "formatDayPillarLabel",
      "formatBirthTimeReflectionLabel",
      "시주 반영",
      "시주 미반영",
      "filterPublicChartLabels",
      "getDraftDeepSajuBridge",
      "renderDeepSajuStructureCard",
      "두 사람 사이에 생기는 명리학 구조",
      "두 원국이 만났을 때 새로 생기는 관계",
      "expandedDeepSajuNoteLimit",
      "더 살펴볼 구조",
      "계산값:",
      "deepSajuBridge.notes",
      "day_master_relation",
      "element_complement",
      "plainKoreanSummary",
      "principleExplanation",
      "relationshipTranslation",
      "positiveExpression",
      "riskExpression",
      "everydayScene",
      "actionRule",
      "명리학적으로는",
      "두 사람에게는",
      "좋게 쓰면",
      "조심할 점",
      "실제 장면",
      "관계 운영법",
      "draft.scoreSummary.breakdown",
      "draft.chartComparison.personA",
      "draft.chartComparison.personB",
      "왜 끌리는지",
      "잘 맞는 지점",
      "부딪히는 지점",
      "관계 규칙",
      "items.slice(0, 3)",
      "반복될 수 있는 장면",
      "실전 조언",
      "chapter.directHitScenes.map",
      "chapter.practicalAdvice.map",
      "finalAdviceLabels",
      "finalAdviceAllowedLabelsByRelationshipType",
      "finalAdviceKnownPrefixes",
      "finalAdviceLabelPriority",
      "getFinalAdviceLabel",
      "normalizeCompatibilityFinalAdviceItem",
      "normalizeCompatibilityFinalAdviceItems",
      "inferFinalAdviceLabel",
      "getAllowedFinalAdviceLabel",
      "resolveDuplicateFinalAdviceLabel",
      "formatCompatibilitySafetyNote",
      "sanitizeCompatibilityKoreanCopy",
      "sanitizeCompatibilityVisibleText(text, relationshipType)",
      "대화 규칙",
      "생활 리듬",
      "생활 기준",
      "도움 요청",
      "갈등 회복",
      "관계 속도",
      "대화 습관",
      "대화 리듬",
      "도움 방식",
      "오해 회복",
      "경계선",
      "오래 가는 규칙",
      "돈과 자원",
      "피드백 규칙",
      "갈등 조정",
      "신뢰 관리",
      "업무 기준",
      "협업 시너지",
      "데이트",
      "연애",
      "normalizedAdvice.body",
      "body.startsWith(`${candidate}:`)",
      "draft.finalAdvice",
      "draft.safetyNotes.map",
      "리포트 준비 완료",
      "결제가 완료되었고 리포트가 생성되었습니다.",
      "상세 리포트 생성 대기 중입니다.",
      "리포트를 찾을 수 없습니다.",
      "결제가 완료된 리포트만 조회할 수 있습니다.",
      "리포트 정보가 올바르지 않습니다.",
      "저장된 리포트 형식을 확인할 수 없습니다.",
      "getPaidReportResult",
    ];
    const blockedMarkers = [
      "callOpenAIReportWriter",
      "generateComprehensiveReportDraft",
      "saveComprehensiveReportDraftSnapshot",
      "confirmTossPayment",
      "payment" + "Key",
      "provider" + "PaymentId",
      "provider" + "_payment" + "_id",
      "input" + "Snapshot",
      "input" + "_snapshot",
      "share" + "Token",
      "access" + "TokenHash",
      "OPENAI" + "_API" + "_KEY",
      "SUPABASE" + "_SERVICE" + "_ROLE",
      "service" + "_role",
      "현" + "침살",
      "망" + "신살",
      "백" + "호대살",
      "홍" + "염살",
      "재" + "다신약",
      "제" + "다신약",
      "바" + "넘",
      "Bar" + "num",
      "만세력 요약",
      "이런 장면 있지 않나요?",
      "이렇게 쓰면 좋습니다",
      "renderV2KeyPhrases",
      "branch.animalKo",
    ];

    for (const marker of requiredMarkers) {
      expect(source).toContain(marker);
    }

    for (const marker of blockedMarkers) {
      expect(source).not.toContain(marker);
    }

    expect(compatibilityViewSource).not.toContain("preview snapshot");
    expect(source).not.toContain("사주×MBTI 종합 리포트 v1.0");
    expect(source).not.toContain("사주×MBTI 궁합 리포트 v1.0");
    expect(compatibilityViewSource).not.toContain(">상태<");
    expect(compatibilityViewSource).not.toContain("mutual element complement");
    expect(compatibilityViewSource).not.toContain("출생시간 입력");
    expect(compatibilityViewSource).not.toContain("찔리는 장면");
    expect(compatibilityViewSource).not.toContain("Chapter");
    expect(compatibilityViewSource).not.toContain("{note.layer}</");
    expect(compatibilityViewSource.indexOf("<CompatibilityTable")).toBeGreaterThan(
      compatibilityViewSource.indexOf("</dl>"),
    );
    expect(compatibilityViewSource.indexOf("<CompatibilityTable")).toBeLessThan(
      compatibilityViewSource.indexOf("{renderCompatibilityScoreCards(draft)}"),
    );
  });
});
