import { Cover, MbtiPage, NatalTable, ShareIcon } from "./BookPages";
import { BOOKS } from "./model";
import type { BookData, BookNote, BookPage } from "./bookTypes";
import s from "./book.module.css";
import type { ReactNode } from "react";
import { PeriodGanji } from "./BookPeriodData";

export function BookInputSummary({ data }: { data: BookData }) {
  return <><div className={s.personSpread} data-pair={data.people.length === 2}>{data.people.map(p => <section key={p.role}><p className={s.micro}>{p.role}</p><h2>{p.name}</h2><dl className={s.coreSummary}>
    <div><dt>생년월일</dt><dd>{p.birth}</dd></div><div><dt>출생시간</dt><dd>{p.timeLabel}</dd></div><div><dt>MBTI</dt><dd>{p.mbti || "모름"}</dd></div>
    <div><dt>성별</dt><dd>{p.gender === "FEMALE" ? "여성" : p.gender === "MALE" ? "남성" : "미선택"}</dd></div>
  </dl></section>)}</div><dl className={s.coreSummary}>{data.context.filter(c => c.value).map(c => <div key={c.label}><dt>{c.label}</dt><dd>{c.value}</dd></div>)}</dl></>;
}

export function BookReader({ data, page, onNote, onShare, onPage, backAction, shareActions }: { data: BookData; page: BookPage; onNote: (note: BookNote) => void; onShare: (text: string) => void; onPage: (page: number, anchor?: string) => void; backAction?: ReactNode; shareActions?: ReactNode }) {
  const book = BOOKS.find(b => b.id === data.bookId)!;
  if (page.kind === "contents") return <><p className={s.eyebrow}>{data.title}</p><h1>{page.title}</h1><ol className={s.bookContents}>{page.entries.map(entry => <li key={entry.targetId}><button onClick={() => onPage(entry.page, entry.targetId)} data-target-chapter={entry.targetId}><span>{entry.title}</span><small>{String(entry.page + 1).padStart(2, "0")} ↗</small></button></li>)}</ol></>;
  if (page.kind === "score") return <><p className={s.eyebrow}>{data.names}</p><h1>{page.title}</h1><p className={s.compatibilityScore}><strong>{page.total}</strong> / 100</p><dl className={s.coreSummary}>{page.scores.map(score => <div key={score.label}><dt>{score.label}</dt><dd>{score.value} / {score.max}</dd></div>)}</dl><p className={s.profileLead}>{page.verdict}</p><p className={s.hint}>{page.notice}</p><details className={s.periodDetails}><summary>지수를 읽는 기준</summary>{page.limitations.map(line => <p key={line}>{line}</p>)}</details></>;
  if (page.kind === "cover") return <div className={s.readerCover}><Cover book={book} title={data.title} name={data.names} /><h1>{page.headline}</h1></div>;
  if (page.kind === "input") return <><p className={s.eyebrow}>PERSONAL EDITION</p><h1>{page.title}</h1><BookInputSummary data={data} /></>;
  if (page.kind === "manse") return <><p className={s.eyebrow}>{data.people[page.person].timeLabel}</p><h1 className={s.dataTitle}>{page.title}</h1><NatalTable data={data.people[page.person].table} /></>;
  if (page.kind === "mbti") return <MbtiPage data={data.people[page.person].table.mbti} name={data.people[page.person].name} />;
  if (page.kind === "pair") return <><p className={s.eyebrow}>{page.category} · {data.names}</p><h1>{page.title}</h1><BookInputSummary data={data} /><div className={s.pairPortraits}>{page.characters.map(p => <section key={p.name}><h2>{p.name}</h2><p>{p.core}</p><p>{p.strength}</p><p>{p.relationship}</p></section>)}</div>
<p className={s.hint}>두 사람 사이의 기운 · {page.relations.join(" · ") || "서로에게 주는 영향"}</p><ol className={s.transitions}>{page.directions.map(d => <li key={d.title}><button onClick={() => onPage(d.page)}><strong>{d.title} ↗</strong><span>{d.effect}</span>{d.term && <small>{d.term}</small>}</button></li>)}</ol></>;
  if (page.kind === "timeline") return <><p className={s.eyebrow}>{page.years[0].year} — {page.years.at(-1)!.year}</p><h1>{page.title}</h1><p className={s.hint}>최근 3년 · 지금 · 앞으로 10년</p>
    <ol className={s.transitions}>{page.transitions.map((t, i) => <li key={i}><button onClick={() => onPage(t.page)}><strong>{t.date}</strong><span>{t.before} → {t.after} · 전환 이야기 ↗</span></button>{t.exact && t.exact !== t.date ? <details className={s.periodDetails}><summary>계산 구간 보기</summary><p>{t.exact}</p></details> : null}</li>)}</ol>
    <ol className={s.yearLedger}>{page.years.map(y => <li key={y.year} data-year={y.year} data-now={y.time === "지금"} data-impact={y.importance}><div><b>{y.year}</b><span>{y.age}세 · {y.time}</span></div><section><div className={s.periodPair}><span>대운 <PeriodGanji value={y.cycle} /></span><span>세운 <PeriodGanji value={y.annual} /></span></div><button onClick={() => onPage(y.page)}>{y.title} ↗</button><p>{y.theme}</p><p className={s.hint}>좋은 힘 · {y.good}</p>{y.caution ? <p className={s.hint}>살필 점 · {y.caution}</p> : null}{y.transition ? <strong className={s.transitionLabel}>{y.transition} · 대운 전환</strong> : null}</section></li>)}</ol></>;
  if (page.kind === "months") return <><p className={s.eyebrow}>{data.title}</p><h1>{page.title}</h1>{page.map?.length ? <dl className={s.yearMap}>{page.map.map(group => <div key={group.label}><dt>{group.label}</dt><dd>{group.months.map(month => <button key={month} onClick={() => onPage(page.months.find(m => m.month === month)!.page)}>{month}월 ↗</button>)}</dd></div>)}</dl> : null}<p className={s.hint}>달력월과 절기월은 경계가 달라요. 현재 달은 지금 지나고 있는 구간을 먼저 보여줍니다.</p><ol className={s.monthLedger}>{page.months.map(m => <li key={m.month} data-month={m.month} data-now={m.time === "지금"} data-impact={m.importance}><div><b>{m.month}월</b><span>{m.time}</span></div><section><button onClick={() => onPage(m.page)}>{m.title} ↗</button><p>{m.theme}</p><div className={s.periodPair}><PeriodGanji value={m.ganji} /><span>{m.gods}</span></div>{m.good ? <p className={s.hint}>좋은 힘 · {m.good}</p> : null}{m.caution ? <p className={s.hint}>살필 점 · {m.caution}</p> : null}{m.boundary ? <details className={s.periodDetails}><summary>{m.boundary.label} · 구간 보기</summary><p>{m.boundary.explanation}</p>{m.boundary.segments.map(segment => <p key={segment.start}>{segment.ganji} · {segment.start} ~ {segment.end} 직전</p>)}</details> : null}{m.markers.length ? <p className={s.hint}>{m.markers.join(" · ")}</p> : null}</section></li>)}</ol></>;
  if (page.kind === "appendix") {
    const stageMeanings = new Set(page.items.filter(item => item.group === "십이운성").map(item => item.meaning));
    const sharedStageMeaning = stageMeanings.size === 1 ? [...stageMeanings][0] : undefined;
    return <><p className={s.eyebrow}>APPENDIX · {page.total}개 기운</p><h1>{page.title}</h1>{page.items.some(item => item.group === "지장간") ? <p className={s.hint}>지장간은 지지 안에 담긴 천간입니다. 아래는 각 천간이 내 일간에 대해 갖는 십성의 뜻이에요. 위치는 만세력표에서 볼 수 있습니다.</p> : null}{sharedStageMeaning ? <p className={s.hint}>십이운성 · {sharedStageMeaning}</p> : null}<ol start={page.from} className={s.glossary}>{page.items.map((item, i) => <li key={i}><span className={s.micro}>{String(page.from + i).padStart(2, "0")}</span><div><small>{item.group ?? "명리 기운"}{item.core ? " · 본문 핵심" : ""}</small><h2>{item.name}</h2>{item.group !== "십이운성" || item.meaning !== sharedStageMeaning ? <p>{item.meaning}</p> : null}</div></li>)}</ol></>;
  }
  if (page.kind === "back") return <div className={s.backContent}><span className={s.micro}>PERSONAL EDITION / FIN</span><h1>{data.title}</h1><p data-final-line>{page.finalLine}</p>{shareActions ?? <section className={s.sharePreview} aria-label="이 책 공유하기 미리보기"><h2>이 책 공유하기</h2><p className={s.shareTitle}>{data.share.title}</p><div>{["카카오톡", "공유", "링크 복사"].map((label, i) => <button type="button" key={label} onClick={() => onShare(`${data.share.title} · ${label} 미리보기입니다. 실제 공유나 복사는 실행하지 않습니다.`)}><ShareIcon kind={i} /><span>{label}</span></button>)}</div></section>}{backAction}<span className={s.micro}>END OF BOOK</span></div>;
  const titleLines = page.title.split("\n");
  return <><p className={s.eyebrow}>{titleLines.length > 1 ? titleLines[0] : `PERSONAL EDITION / ${data.names}`}</p><h1>{titleLines.length > 1 ? titleLines.slice(1).join("\n") : page.title}</h1><div className={s.prose}>{page.paragraphs.map((p, i) => <section key={i} id={p.anchorId}>{p.heading ? <h2>{p.heading}</h2> : null}<p data-narrative-paragraph>{p.text}{p.notes.map(n => <sup key={n}><button type="button" onClick={() => onNote(page.notes[n - 1])} aria-label={`각주 ${n} ${page.notes[n - 1].name}`}>{n}</button></sup>)}</p></section>)}</div>
    {page.notes.length ? <section className={s.chapterNotes} aria-label="이 장의 각주"><ol>{page.notes.map((note, i) => <li key={i}><span>{i + 1}.</span><div><strong>{note.name}</strong><p>{note.text}</p></div></li>)}</ol></section> : null}</>;
}
