const PRODUCT_PRICE_KO = "1,290원";
const PRODUCT_PRICE_AMOUNT = 1290;
const PRODUCT_POLICY_SUMMARY_KO =
  "무형재화/디지털 콘텐츠 · 결제 완료 후 즉시 생성, 최대 24시간 이내 제공 · 생성일로부터 90일 온라인 열람";
const PRODUCT_REFUND_SUMMARY_KO =
  "리포트 생성 전에는 결제일로부터 7일 이내 환불 가능하며, 생성 시작 또는 결과 제공 후에는 디지털 콘텐츠 특성상 환불이 제한될 수 있습니다. 미제공·중복결제·시스템 오류는 환불 또는 재제공합니다.";
const PRODUCT_CAUTION_KO =
  "본 서비스는 사용자가 입력한 정보를 바탕으로 자동 생성되는 유료 디지털 리포트입니다. 사람에 의한 1:1 상담 서비스가 아니며, 의료·법률·투자 자문을 제공하지 않습니다. 결과물은 자기이해와 참고 목적의 정보입니다.";

export const GYEOL_PRODUCTS = [
  {
    id: "comprehensive",
    productType: "saju_mbti_full",
    paymentProductType: "saju_mbti_full",
    slug: "saju-mbti-full",
    nameKo: "사주×MBTI 종합 리포트",
    fullNameKo: "사주×MBTI 종합 리포트",
    versionBadgeKo: "판매 상품",
    priceKo: PRODUCT_PRICE_KO,
    priceLabelKo: PRODUCT_PRICE_KO,
    listPriceKo: PRODUCT_PRICE_KO,
    listPriceLabelKo: PRODUCT_PRICE_KO,
    salePriceKo: `판매가 ${PRODUCT_PRICE_KO}`,
    priceAmount: PRODUCT_PRICE_AMOUNT,
    listPriceAmount: PRODUCT_PRICE_AMOUNT,
    salePriceAmount: PRODUCT_PRICE_AMOUNT,
    paymentAmount: PRODUCT_PRICE_AMOUNT,
    currency: "KRW",
    status: "available",
    isPurchasable: true,
    href: "/report/new?product=saju-mbti-full",
    ctaHref: "/report/new?product=saju-mbti-full",
    badgeKo: "구매 가능",
    visualKey: "comprehensive",
    deliveryTypeKo: "결제 후 온라인 리포트 생성/열람",
    formatKo: "자동 생성 디지털 리포트",
    retentionKo: "생성일로부터 90일 열람",
    servicePeriodKo: "결제 완료 후 즉시 생성, 최대 24시간 이내 제공",
    refundSummaryKo: PRODUCT_REFUND_SUMMARY_KO,
    policySummaryKo: PRODUCT_POLICY_SUMMARY_KO,
    summaryKo:
      "명리 구조와 MBTI 행동 패턴을 함께 읽는 자기이해 리포트입니다. 결제 후 입력값을 바탕으로 자동 생성되며 온라인에서 열람할 수 있습니다.",
    cautionKo: PRODUCT_CAUTION_KO,
  },
  {
    id: "career_money_study_report",
    productType: "career_money_study",
    paymentProductType: "career_money_study",
    slug: "career-money-study",
    nameKo: "직업·커리어·돈·학업 리포트",
    fullNameKo: "직업·커리어·돈·학업 리포트",
    versionBadgeKo: "판매 상품",
    priceKo: PRODUCT_PRICE_KO,
    priceLabelKo: PRODUCT_PRICE_KO,
    listPriceKo: PRODUCT_PRICE_KO,
    listPriceLabelKo: PRODUCT_PRICE_KO,
    salePriceKo: `판매가 ${PRODUCT_PRICE_KO}`,
    priceAmount: PRODUCT_PRICE_AMOUNT,
    listPriceAmount: PRODUCT_PRICE_AMOUNT,
    salePriceAmount: PRODUCT_PRICE_AMOUNT,
    paymentAmount: PRODUCT_PRICE_AMOUNT,
    currency: "KRW",
    status: "available",
    isPurchasable: true,
    href: "/report/new?product=career-money-study",
    ctaHref: "/report/new?product=career-money-study",
    badgeKo: "구매 가능",
    visualKey: "career_money_study",
    deliveryTypeKo: "결제 후 온라인 리포트 생성/열람",
    formatKo: "자동 생성 디지털 리포트",
    retentionKo: "생성일로부터 90일 열람",
    servicePeriodKo: "결제 완료 후 즉시 생성, 최대 24시간 이내 제공",
    refundSummaryKo: PRODUCT_REFUND_SUMMARY_KO,
    policySummaryKo: PRODUCT_POLICY_SUMMARY_KO,
    summaryKo:
      "타고난 직업성, 돈을 다루는 방식, 투자·저축 성향, 공부 루틴을 하나의 흐름으로 정리합니다.",
    cautionKo: PRODUCT_CAUTION_KO,
  },
  {
    id: "love_marriage_child_report",
    productType: "love_marriage_child",
    paymentProductType: "love_marriage_child",
    slug: "love-marriage-child",
    nameKo: "연애·결혼·자녀 리포트",
    fullNameKo: "연애·결혼·자녀 리포트",
    versionBadgeKo: "판매 상품",
    priceKo: PRODUCT_PRICE_KO,
    priceLabelKo: PRODUCT_PRICE_KO,
    listPriceKo: PRODUCT_PRICE_KO,
    listPriceLabelKo: PRODUCT_PRICE_KO,
    salePriceKo: `판매가 ${PRODUCT_PRICE_KO}`,
    priceAmount: PRODUCT_PRICE_AMOUNT,
    listPriceAmount: PRODUCT_PRICE_AMOUNT,
    salePriceAmount: PRODUCT_PRICE_AMOUNT,
    paymentAmount: PRODUCT_PRICE_AMOUNT,
    currency: "KRW",
    status: "available",
    isPurchasable: true,
    href: "/report/new?product=love-marriage-child",
    ctaHref: "/report/new?product=love-marriage-child",
    badgeKo: "구매 가능",
    visualKey: "love_marriage_child",
    deliveryTypeKo: "결제 후 온라인 리포트 생성/열람",
    formatKo: "자동 생성 디지털 리포트",
    retentionKo: "생성일로부터 90일 열람",
    servicePeriodKo: "결제 완료 후 즉시 생성, 최대 24시간 이내 제공",
    refundSummaryKo: PRODUCT_REFUND_SUMMARY_KO,
    policySummaryKo: PRODUCT_POLICY_SUMMARY_KO,
    summaryKo:
      "관계에서 드러나는 표현 방식, 결혼 생활 리듬, 책임 방식과 가족 역할을 참고용으로 봅니다.",
    cautionKo: PRODUCT_CAUTION_KO,
  },
  {
    id: "compatibility_report",
    productType: "saju_mbti_compatibility",
    paymentProductType: "saju_mbti_compatibility",
    slug: "compatibility",
    nameKo: "궁합 리포트",
    fullNameKo: "궁합 리포트",
    versionBadgeKo: "판매 상품",
    priceKo: PRODUCT_PRICE_KO,
    priceLabelKo: PRODUCT_PRICE_KO,
    listPriceKo: PRODUCT_PRICE_KO,
    listPriceLabelKo: PRODUCT_PRICE_KO,
    salePriceKo: `판매가 ${PRODUCT_PRICE_KO}`,
    priceAmount: PRODUCT_PRICE_AMOUNT,
    listPriceAmount: PRODUCT_PRICE_AMOUNT,
    salePriceAmount: PRODUCT_PRICE_AMOUNT,
    paymentAmount: PRODUCT_PRICE_AMOUNT,
    currency: "KRW",
    status: "available",
    isPurchasable: true,
    href: "/report/new?product=compatibility",
    ctaHref: "/report/new?product=compatibility",
    badgeKo: "구매 가능",
    visualKey: "compatibility",
    deliveryTypeKo: "결제 후 온라인 리포트 생성/열람",
    formatKo: "자동 생성 디지털 리포트",
    retentionKo: "생성일로부터 90일 열람",
    servicePeriodKo: "결제 완료 후 즉시 생성, 최대 24시간 이내 제공",
    refundSummaryKo: PRODUCT_REFUND_SUMMARY_KO,
    policySummaryKo: PRODUCT_POLICY_SUMMARY_KO,
    summaryKo:
      "연애, 결혼, 부모·자식, 동료, 상사·부하, 사업·협업, 친구 관계까지 두 사람의 연결 구조와 조율 포인트를 봅니다.",
    cautionKo: PRODUCT_CAUTION_KO,
  },
  {
    id: "daewoon_report",
    productType: "major_fortune",
    paymentProductType: "major_fortune",
    slug: "major-fortune",
    nameKo: "대운 리포트",
    fullNameKo: "대운 리포트",
    versionBadgeKo: "판매 상품",
    priceKo: PRODUCT_PRICE_KO,
    priceLabelKo: PRODUCT_PRICE_KO,
    listPriceKo: PRODUCT_PRICE_KO,
    listPriceLabelKo: PRODUCT_PRICE_KO,
    salePriceKo: `판매가 ${PRODUCT_PRICE_KO}`,
    priceAmount: PRODUCT_PRICE_AMOUNT,
    listPriceAmount: PRODUCT_PRICE_AMOUNT,
    salePriceAmount: PRODUCT_PRICE_AMOUNT,
    paymentAmount: PRODUCT_PRICE_AMOUNT,
    currency: "KRW",
    status: "available",
    isPurchasable: true,
    href: "/report/new?product=major-fortune",
    ctaHref: "/report/new?product=major-fortune",
    badgeKo: "구매 가능",
    visualKey: "daewoon",
    deliveryTypeKo: "결제 후 온라인 리포트 생성/열람",
    formatKo: "자동 생성 디지털 리포트",
    retentionKo: "생성일로부터 90일 열람",
    servicePeriodKo: "결제 완료 후 즉시 생성, 최대 24시간 이내 제공",
    refundSummaryKo: PRODUCT_REFUND_SUMMARY_KO,
    policySummaryKo: PRODUCT_POLICY_SUMMARY_KO,
    summaryKo:
      "10년 단위의 큰 흐름과 현재 시기의 배경 변화를 일, 돈, 관계의 행동 기준으로 정리합니다.",
    cautionKo: PRODUCT_CAUTION_KO,
  },
  {
    id: "saewoon_report",
    productType: "annual_fortune",
    paymentProductType: "annual_fortune",
    slug: "annual-fortune",
    nameKo: "세운 리포트",
    fullNameKo: "세운 리포트",
    versionBadgeKo: "판매 상품",
    priceKo: PRODUCT_PRICE_KO,
    priceLabelKo: PRODUCT_PRICE_KO,
    listPriceKo: PRODUCT_PRICE_KO,
    listPriceLabelKo: PRODUCT_PRICE_KO,
    salePriceKo: `판매가 ${PRODUCT_PRICE_KO}`,
    priceAmount: PRODUCT_PRICE_AMOUNT,
    listPriceAmount: PRODUCT_PRICE_AMOUNT,
    salePriceAmount: PRODUCT_PRICE_AMOUNT,
    paymentAmount: PRODUCT_PRICE_AMOUNT,
    currency: "KRW",
    status: "available",
    isPurchasable: true,
    href: "/report/new?product=annual-fortune",
    ctaHref: "/report/new?product=annual-fortune",
    badgeKo: "구매 가능",
    visualKey: "saewoon",
    deliveryTypeKo: "결제 후 온라인 리포트 생성/열람",
    formatKo: "자동 생성 디지털 리포트",
    retentionKo: "생성일로부터 90일 열람",
    servicePeriodKo: "결제 완료 후 즉시 생성, 최대 24시간 이내 제공",
    refundSummaryKo: PRODUCT_REFUND_SUMMARY_KO,
    policySummaryKo: PRODUCT_POLICY_SUMMARY_KO,
    summaryKo:
      "선택 연도의 흐름과 월운을 상반기·하반기 기준으로 읽고 행동 기준을 정리합니다.",
    cautionKo: PRODUCT_CAUTION_KO,
  },
] as const;

export const GYEOL_COMING_SOON_PRODUCTS = [] as const;

export const GYEOL_HOME_PRODUCT_GRID = GYEOL_PRODUCTS;

export type GyeolProduct = (typeof GYEOL_PRODUCTS)[number];
export type GyeolComingSoonProduct = {
  readonly badgeKo: string;
  readonly nameKo: string;
  readonly shortDescriptionKo: string;
};
export type GyeolProductGridItem = (typeof GYEOL_HOME_PRODUCT_GRID)[number];
