// Local-only fixture server. Exports are generated by completedReadingExperience.test.tsx.
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { readFileSync } from 'node:fs';
import { pathToFileURL, fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const vitePath = require.resolve('vite', { paths: [dirname(require.resolve('vitest/package.json'))] });
const { createServer } = await import(pathToFileURL(vitePath).href);
const root = dirname(fileURLToPath(import.meta.url));
const server = await createServer({
  configFile: false, root, define: { 'process.cwd': '(() => "")' },
  resolve: { alias: { 'next/link': resolve(root, '../postpayment/link.tsx'), 'node:fs': resolve(root, 'localSources.ts'), 'node:path': resolve(root, 'localSources.ts') } },
  server: { host: '127.0.0.1', port: 3103, strictPort: true, fs: { allow: [resolve(root, '../../..')] } },
  plugins: [{ name: 'local-reading-fixtures', configureServer(server) {
    server.middlewares.use('/fixtures', (request, response) => {
      const url = new URL(request.url, 'http://localhost');
      const name = url.pathname.slice(1);
      if (!/^(snapshots\.json|(?:saju-mbti-full|career-money-study|love-marriage-child|major-fortune|annual-fortune|compatibility-(?:love|parentChild|businessPartner))\.html)$/.test(name)) { response.statusCode = 404; response.end(); return; }
      const directory = url.searchParams.get('phase') === 'before' ? '/tmp/result-qa-before' : '/tmp/result-qa-after';
      response.setHeader('Content-Type', name.endsWith('.json') ? 'application/json' : 'text/html; charset=utf-8');
      response.end(readFileSync(resolve(directory, name), 'utf8'));
    });
  } }],
});
await server.listen(); server.printUrls();
