import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const source = readFileSync(
  join(process.cwd(), "docs/report-knowledge-architecture.md"),
  "utf8",
);

describe("report knowledge architecture document", () => {
  it("documents the REPORT-01 knowledge-base boundary", () => {
    const requiredMarkers = [
      "사주가 1차 근거",
      "MBTI는 보조 근거",
      "RAG/source collection is for DB building, not output copying",
      "내 MBTI가 이래서 그런 줄 알았는데, 사주에도 이 구조가 있었네",
      "OpenAI generation later",
      "REPORT-01 does not implement final content",
      "REPORT-02 expands Saju DB first",
      "사주 단독 해석 is required",
      "오행, 십성, 신살",
      "귀인, 일주 are first-class knowledge",
      "MBTI remains secondary",
      "source/RAG collection is used for DB refinement",
      "REPORT-03 expands MBTI DB",
      "reinforce, contrast, and personalize Saju interpretation",
      "All 16 types are structured",
      "No copied source paragraphs",
      "사주에는 이런 구조가 있고",
      "REPORT-04 expands fusion rules",
      "A reinforcement rule is used",
      "A contrast rule is used",
      "A compensation rule is used",
      "Before OpenAI generation",
      "The evidence packet is not final prose",
      "Saju remains primary",
      "MBTI supports and contrasts",
      "REPORT-05 maps computed Saju facts to knowledge entry ids",
      "Computed facts are not invented",
      "Mapping happens before evidence packet",
      "full manse calculation is separate from mapping",
      "REPORT-06 uses OpenAI only as writer",
      "OpenAI does not calculate Saju facts",
      "evidence packet comes before generation",
      "structured JSON draft is validated",
      "DB save/rendering happens later",
      "REPORT-07 persists validated draft JSON",
      "OpenAI generation happens before persistence",
      "DB save is separate from result rendering",
      "Validated snapshot only",
      "no result page rendering yet",
      "REPORT-08 renders saved validated snapshot",
      "OpenAI generation is not called here",
      "DB save already happened in REPORT-07",
      "Result page rendering is separate from generation and payment",
      "safe placeholder state",
      "REPORT-09 orchestrates generation and persistence",
      "computed facts to evidence packet",
      "OpenAI writer",
      "validated draft",
      "snapshot persistence",
      "result page can render after save",
      "Payment flow wiring happens later",
      "REPORT-10 improves draft quality guardrails",
      "internal meta copy",
      "Unsupported Saju terms are rejected",
      "Display sections are separated from interpretation",
      "MBTI-first phrasing is rejected",
      "REPORT-11 improves comprehensive report UX and content density",
      "Saju summary card and MBTI summary card",
      "Evidence UI is secondary",
      "deeper Saju term explanation",
      "generated-section density checks",
      "REPORT-12 converts the comprehensive report",
      "comprehensive_v2_draft",
      "eight long-form chapters",
      "Saju terms, MBTI support, and fusion",
      "V2 validator enforces narrative chapter density",
      "Migration 0012 supports saving and reading",
      "V1 snapshots remain readable",
      "renders V2 without analysis evidence blocks",
      "REPORT-13 adds hit-reading and prescription",
      "compact deterministic manseok/profile table",
      "체감형 명중 문장",
      "concrete scene examples",
      "practical prescriptions",
      "이렇게 쓰면 좋습니다",
      "피해야 할 패턴",
      "공부/일 루틴",
      "certificates, professional books",
      "직무 학습",
      "사업 학습",
      "partner fit criteria",
      "bad match patterns",
      "element-based remedies",
      "payment or Toss flow wiring is still separate",
      "REPORT-15A adds a 명리학 Feature Taxonomy",
      "Feature Scoring ranks available computed Saju features",
      "Chapter Feature Selector maps scored features to V2 chapters",
      "Future MBTI Bridge Needs",
      "emotional_buffer",
      "expression_support",
      "OpenAI does not invent Saju features",
      "OpenAI receives selected feature evidence",
      "Feature taxonomy enables richer and more varied report generation",
      "REPORT-15B expands the 신살·귀인·길신 knowledge layer",
      "십이신살, 주요 신살",
      "They are not fixed sentence templates",
      "Strong metaphor is allowed",
      "The forbidden expression policy blocks certainty",
      "MBTI bridge needs are assigned where useful",
      "REPORT-15C adds a 60갑자 일주 지식 DB",
      "Day pillar data is the identity anchor",
      "this chart has this 일주",
      "The day pillar knowledge maps into the same feature scoring model",
      "The 금지 표현 정책 also applies to day pillar fields",
      "OpenAI should not invent day pillar meanings",
      "connected to report generation in a later task",
      "REPORT-15D connects the feature warehouse to V2 generation evidence",
      "computed saju facts -> feature id extraction",
      "selectedSajuFeatureEvidence",
      "Feature extraction from computed facts only maps facts that were actually",
      "If a feature such as 반안살, 백호대살, 천을귀인, or",
      "문창귀인 is not present in computed facts, it is not included",
      "Chapter-level feature evidence is grouped by V2 chapter",
      "The prompt size cap keeps opening at four features",
      "OpenAI feature invention prevention is explicit",
      "use only provided 명리학 feature",
      "not to invent missing 신살, 귀인, 길신, 일주 meanings",
      "REPORT-15E expands deterministic computed feature extraction",
      "SAJU_FEATURE_EXTRACTION_RULESET_VERSION",
      "Computed Feature Extraction receives available pillars",
      "ComputedSajuFeatureExtractionResult",
      "The V1 twelve-sinsal calculation uses the day branch",
      "four",
      "twelve_sinsal_banan",
      "twelve_sinsal_jangseong",
      "gwiin_cheoneul",
      "gwiin_munchang",
      "gwiin_geumyeorok",
      "gwiin_amrok",
      "Day-pillar tables detect",
      "feature-id merge and de-duplication",
      "No feature invention policy remains unchanged",
      "REPORT-15F adds a diagnostic path",
      "computed saju feature ids",
      "selected saju feature evidence by chapter",
      "excluded high scoring",
      "selected evidence narrowness warning",
      "십이신살",
      "주요 신살",
      "귀인/길신",
      "selectedSajuFeatureEvidence[chapterId]",
      "relationship copy should not",
      "REPORT-15G Feature Spotlight and Signature Scenes",
      "sajuFeatureSpotlight",
      "sajuSignatureScenes",
      "good_fortune",
      "talent",
      "caution",
      "balance",
      "signature scene titles",
      "OpenAI must not invent missing feature ids",
    ];

    for (const marker of requiredMarkers) {
      expect(source).toContain(marker);
    }
  });
});
