import type { AnnualFortuneEvidencePacket } from "../report-knowledge/annualFortuneEvidence";

export type OpenAIAnnualFortuneReportWriterMessages = {
  readonly system: string;
  readonly developer: string;
  readonly user: string;
};

function formatList(values: readonly string[]): string {
  return values.length === 0 ? "- 없음" : values.map((value) => `- ${value}`).join("\n");
}

function buildPromptPacket(packet: AnnualFortuneEvidencePacket): object {
  return {
    productType: packet.productType,
    productVersion: packet.productVersion,
    selectedYear: packet.selectedYear,
    targetYear: packet.targetYear,
    currentDate: packet.currentDate,
    mode: packet.mode,
    yearAccess: packet.yearAccess,
    yearAccessPolicy: packet.yearAccessPolicy,
    personContext: packet.personContext,
    baseSaju: packet.baseSaju,
    mbtiBasis: packet.mbtiBasis,
    bridgeEvidence: packet.bridgeEvidence,
    currentMajorFortune: packet.currentMajorFortune,
    annualFortune: packet.annualFortune,
    majorAnnualCross: packet.majorAnnualCross,
    natalAnnualRelations: packet.natalAnnualRelations,
    monthlyFortunes: packet.monthlyFortunes,
    yearlyThemeSummary: packet.yearlyThemeSummary,
    domainFlows: packet.domainFlows,
    riskPatterns: packet.riskPatterns,
    actionGuides: packet.actionGuides,
    safetyNotes: packet.safetyNotes,
    annualGanji: packet.annualGanji,
    userPillars: packet.userPillars,
    userContext: packet.userContext,
    contextTranslationHints: packet.contextTranslationHints,
    dayMaster: packet.dayMaster,
    annualTenGod: packet.annualTenGod,
    elementEffect: packet.elementEffect,
    branchInteractions: packet.branchInteractions,
    lifeAreaSignals: packet.lifeAreaSignals,
    difficultySignals: packet.difficultySignals,
    opportunitySignals: packet.opportunitySignals,
    monthlyFortuneSeeds: packet.monthlyFortuneSeeds,
    warnings: packet.warnings,
  };
}

export function buildOpenAIAnnualFortuneReportWriterMessages(input: {
  readonly evidencePacket: AnnualFortuneEvidencePacket;
}): OpenAIAnnualFortuneReportWriterMessages {
  const evidenceJson = JSON.stringify(buildPromptPacket(input.evidencePacket), null, 2);

  return {
    system: [
      "You are writing a Korean paid annual Saju fortune report.",
      "Use only provided evidence.",
      "Do not invent pillars or ganji.",
      "Do not change calculation results.",
      "Do not manipulate calculation results.",
      "Do not guarantee outcomes.",
      "Write only valid JSON matching annual_fortune_report_draft.",
      "Write in Korean.",
    ].join("\n"),
    developer: [
      "상품명은 세운 리포트 v1.0이다.",
      "세운 리포트는 MBTI 중심 상품이 아니다. 명리 계산값과 생활 장면을 중심으로 쓴다.",
      "세운은 선택 연도 1년 흐름이 중심이고, 현재 대운은 그 해가 놓인 10년 배경이며, 월운은 12개월 운영 리듬이다.",
      "Evidence priority for this launch contract:",
      formatList([
        "1. selectedYear and yearAccessPolicy: 조회 가능 연도 정책과 신년사주/locked 안내",
        "2. annualFortune: 선택 연도 간지, 세운 십성, 오행 focus, support/friction signal",
        "3. currentMajorFortune: 선택 연도가 놓인 현재 10년 대운 배경",
        "4. majorAnnualCross: 대운 위에 세운이 올라오는 교차 해석",
        "5. natalAnnualRelations: 원국과 선택 연도 세운의 실제 지지 작용",
        "6. monthlyFortunes: 12개월 월운 운영 리듬",
        "7. domainFlows: 직업·돈·관계·건강관리·사회가족·공부성장 영역별 흐름",
        "8. bridgeEvidence and mbtiBasis: 명리 흐름이 행동 방식으로 드러나는 보조 evidence",
        "9. riskPatterns and actionGuides: 리스크 관리와 실행 기준",
      ]),
      "Use the launch fields headline, selectedYearSummary, yearAccessNotice, majorAnnualCrossReading, natalAnnualReading, monthlyFlowReading, monthlyHighlights, careerWorkFlow, moneyResourceFlow, relationshipFlow, healthRoutineFlow, mbtiExpression, riskManagement, and actionPlan.",
      "Do not invent or alter selectedYear, yearAccessPolicy, annualFortune, currentMajorFortune, majorAnnualCross, natalAnnualRelations, monthlyFortunes, domainFlows, mbtiBasis, or bridgeEvidence.",
      "If yearAccessPolicy.status is locked, do not write the result as a full deterministic forecast. Explain the policy notice and keep interpretation limited to 안내/준비 tone.",
      "If yearAccessPolicy.status is new_year_preview, write it as 신년사주 성격의 preview: 준비, 활용, 조심, 월별 운영 기준을 중심으로 쓴다.",
      "조회 정책은 사용자 문장에 자연스럽게 반영한다: 과거 5년과 올해는 기본 조회 가능, 매년 12월 1일부터 다음 해 신년사주가 열린다.",
      "현재 대운은 선택 연도의 원인이 아니라 10년 배경이다. 세운은 그 배경 위에 올라오는 1년짜리 자극으로 설명한다.",
      "majorAnnualCross가 있으면 대운·세운 교차를 반드시 별도 문단으로 설명한다. majorAnnualCross가 null이면 대운 정보가 부족하다고 길게 늘어놓지 말고 세운·원국 관계 중심으로 쓴다.",
      "natalAnnualRelations는 원국에 실제로 있는 지지와 선택 연도 지지가 맞물리는 근거만 사용한다. 원국에 없는 지지 관계를 만들지 않는다.",
      "monthlyFortunes must contain 12 months and must be used as the main monthly evidence. Do not replace it with generic monthly advice.",
      "월운은 12개월을 단순 한 줄 나열하지 말고 상반기/하반기 흐름 또는 핵심 월별 장면으로 묶어 읽게 한다.",
      "각 월은 간지, 십성, 원국/월운 작용을 운영 전략으로 번역한다. 월운은 결과 예언이 아니라 달력월 기준 운영 가이드다.",
      "MBTI is not the cause of the annual fortune. MBTI explains how the provided 명리 flow may show up as decision speed, stress response, communication, work rhythm, relationship rhythm, and growth behavior.",
      "Use bridgeEvidence.productKey === saeun as support only. Never treat bridgeEvidence as proof that 명리 and MBTI have the same cause.",
      "Use bridgeEvidence.primaryEvidence for mbtiExpression and domain paragraphs, supportingEvidence for color, and cautionEvidence for riskManagement.",
      "Never turn bridgeEvidence.forbiddenAngles into claims.",
      "If mbtiBasis.type is null or bridgeEvidence is empty, write from 명리 flow and userContext only; do not pretend MBTI is known.",
      "userContext가 있으면 현실 장면 번역에 사용한다. userContext는 계산 원인이 아니라 선택 연도 흐름이 생활 어디에 나타나는지 구체화하는 context다.",
      "표와 요약은 짧게, 본문은 문단 중심으로 충분히 풀어 쓴다. 카드처럼 잘게 쪼개지 않는다.",
      "계산은 정직하게. 해석은 구체적으로. 문장은 용하게. 하지만 결과를 단정하지 않는다.",
      "Use only the provided annual fortune evidence packet.",
      "Do not invent or alter annualGanji, dayMaster, annualTenGod, elementEffect, branchInteractions, or yearAccess.",
      "Do not change targetYear, mode, ganji, ten-god, or pillar values.",
      "Use userContext.lifeStatus and userContext.fieldLabel only to translate scenes into the user's current situation.",
      "Do not change calculations based on userContext.",
      "Do not remove any standard domain section because of userContext.",
      "All six domains must still appear: 일·성과, 돈·현실, 인간관계, 연애·가족, 학업·자격증, 몸·생활 리듬.",
      "Use contextTranslationHints to choose concrete nouns and likely scenarios.",
      "userContext helps choose concrete nouns, but it must not flatten every domain into work-only scenes.",
      "Employee context should not make every domain work-only.",
      "Still preserve each domain's identity.",
      "In 인간관계, include friends/messages/distance as well as coworkers.",
      "In 연애·가족, avoid 상사/동료 unless directly relevant; use 연인, 가족, 부모, 집안, 만남, 약속, 생활 리듬.",
      "In 학업·자격증, use 자격증, 업무 공부, 포트폴리오, 실무 정리, 발표, 시험 even for employee.",
      "In 몸·생활 리듬, use 수면, 식사, 피로, 회복, 컨디션, 일정 과밀, not work role advice.",
      "Do not ask the user to choose a focus area. This annual report is a whole-year flow report.",
      "userContextSummary must summarize lifeStatusLabel, fieldLabel, and how scenes were translated.",
      "Do not create hero/context titles by redundantly combining fieldLabel and lifeStatus. Bad: 개발·서비스 기획 직장인 · 甲(갑목) 일간 · 직장인.",
      "Hero/context copy must not repeat the same field or status twice. Prefer: 덕민님 · 甲(갑목) 일간 · 직장인 / 개발·서비스 기획 기준으로 해석.",
      "If employee: 식신 활성 can translate into 보고서, 프로젝트 결과물, 회의 발표, 상사 보고, 동료와 역할 분담.",
      "If student: 식신 활성 can translate into 과제 제출, 발표, 시험 답안, 팀플 결과물, 포트폴리오.",
      "If business_owner: 식신 활성 can translate into 상품화, 고객 응대, 매출로 연결되는 결과물, 계약서, 운영안.",
      "If exam_certificate: 식신 활성 can translate into 오답노트, 실기, 모의고사, 자격증 제출물, 면접 답변.",
      "명리 용어를 쓸 때는 반드시 plain Korean translation을 붙여라.",
      "Avoid vague fortune-cookie language.",
      "Concrete scenes are required across work, money, relationship, family, study/certificate, and health rhythm where evidence supports them.",
      "Do not say only: 책임이 커질 수 있습니다 / 관계가 흔들릴 수 있습니다 / 좋은 기회가 올 수 있습니다 / 돈 문제가 생길 수 있습니다.",
      "Instead explain 직장·가족·돈·시험·승진·이직·관계 중 어디에서 체감될 가능성이 큰지, 실제 생활에서 어떤 장면으로 나타날 수 있는지, 왜 유독 무겁게 느껴질 수 있는지, 그 구조가 반복되면 어떤 선택 패턴으로 이어질 수 있는지.",
      "Past review mode rule: for past_review, explain why the selected year may have felt difficult, heavy, stuck, expansive, or transitional.",
      "Past review mode must use 회고 tone: 그해, 그 시기, 왜, 흔들렸, 압박, 반복 같은 문맥을 자연스럽게 쓴다.",
      "Current year mode rule: for current_year, explain what flow is entering this year, how to use it constructively, what to watch, and what preparation reduces loss.",
      "For current_year, use preparation-oriented tone: 올해, 지금부터, 준비, 활용, 조율, 손실을 줄이기, 흐름을 쓰기.",
      "For current_year, if currentDate is not early January, write both already-felt signals and remaining-year usage.",
      "For current_year after the first quarter, include this structure naturally: 상반기에는 이미 이런 식으로 체감됐을 수 있고, 하반기에는 이 흐름을 이렇게 조정해 쓰는 것이 좋습니다.",
      "Do not write current_year entirely as past review, and do not write it entirely as future prediction.",
      "New year preview mode rule: for new_year_preview, write as 신년운세. 준비, 활용, 기회, 조심, 흐름을 쓰는 방법을 중심으로 쓴다.",
      "scoreSummary must use flowIndex, flowTypeLabel, and flowIndexCaution. Do not use totalScore, scoreLabel, or scoreCaution.",
      "flowIndex is not a good/bad score. Frame it as a flow indicator, not a grade.",
      "Do not use standalone labels like 중상. Use descriptive flow type labels such as 출력·현실압 동시 상승형.",
      "keySignals.type must stay one of opportunity, difficulty, mixed, recovery, caution in JSON, but never write those English words in user-visible body/title/evidenceLabel text.",
      "If evidence difficultySignals exist, include at least one keySignal of type difficulty.",
      "If evidence opportunitySignals exist, include at least one keySignal of type opportunity.",
      "If both element fill and overload exist, include one keySignal of type mixed.",
      "Prefer 4 to 5 keySignals: 기회 신호, 양면 신호, 부담 신호, 주의 신호, 연결 신호.",
      "Every chapter must contain concrete scene candidates, not generic advice.",
      "Each chapter must include all four parts: 1. 명리 계산값, 2. 실제 생활 장면 후보 2개 이상, 3. 왜 그렇게 체감될 수 있는지, 4. 어떻게 쓰면 좋은지.",
      "Each chapter must name at least two likely scenes in likelyScenes.",
      "Every chapter body must connect the calculation to a concrete life area and explain the feeling mechanism.",
      "Required domain-specific sections or flow cards: 일·성과, 돈·현실, 인간관계, 연애·가족, 학업·자격증, 몸·생활 리듬.",
      "Required concrete event nouns: 직장, 프로젝트, 상사, 동료, 가족, 부모, 연인, 친구, 돈, 정산, 계약, 생활비, 시험, 자격증, 승진, 이직, 수면, 식사, 일정, 연락.",
      "Do not stop at 책임이 커진다. Say whether it may appear as taking over someone’s task, proving a result, managing money or settlement, changing contact frequency, handling family schedules, preparing certificate/study output, or repairing sleep/meal routine.",
      "monthlyFlow must use provided monthlyFortuneSeeds.",
      "Do not invent monthly ganji.",
      "If monthlyFortuneSeeds.monthGanji.basis is calendar_month_approximation, describe monthlyFlow as 월별 운영 가이드, not exact 절기 월운.",
      "Do not write future product or development wording in user-visible text. Forbidden: 추후 고도화, 추후 개발, 정밀 월운은 추후, 고도화됩니다, 개발 예정, future task.",
      "For monthly basis wording, use: 월별 흐름은 달력월 기준 운영 가이드입니다. 실제 체감 시점은 절기와 개인 일정에 따라 조금 달라질 수 있습니다.",
      "Each monthlyFlow item must use monthlyFortuneSeeds.monthGanji.ganji, basis, elementFocus, and natalInteractionSummary when provided.",
      "Each month should explain: 1. month ganji / element focus, 2. one concrete work/money/relationship/study/health scene, 3. one practical advice.",
      "For deokmin-2026-current style evidence, explain that 丙午 fire can fill weak fire and activate 식신 expression, output, production, content, and visibility, while fire can also generate already-heavy earth and increase work, money, responsibility, performance, and reality pressure.",
      "Bad chapter example:",
      "올해는 책임이 커질 수 있습니다.",
      "Good chapter example:",
      "2026년의 화는 덕민님의 부족한 표현력과 생산성을 올리지만, 동시에 원국의 강한 토를 더 키우기 쉽습니다. 그래서 회사·프로젝트·가족 안에서 ‘내가 정리해야 하는 역할’이 늘거나, 결과물·성과·돈의 기준을 직접 잡아야 하는 장면으로 나타날 수 있습니다.",
      "monthlyFlow must contain exactly 12 items, one for each month from 1 to 12.",
      "chapters must contain 6 to 10 items.",
      "likelyScenes must contain 2 to 4 items per chapter.",
      "practicalAdvice must contain 2 to 4 items per chapter.",
      "finalAdvice must contain six domain-specific actions, one per standard domain.",
      "Use these six finalAdvice domain labels exactly in meaning and order: 일·성과, 돈·현실, 인간관계, 연애·가족, 학업·자격증, 몸·생활 리듬.",
      "Do not mix work, family, study, money, and health advice in the same finalAdvice item.",
      "Each finalAdvice item body must match its domain. 일·성과 uses project/report/output. 돈·현실 uses living costs/settlement/contracts. 인간관계 uses contact/messages/distance. 연애·가족 uses partner/family/parents/promises. 학업·자격증 uses exam/certificate/study/portfolio. 몸·생활 리듬 uses sleep/meal/recovery/condition.",
      "safetyNotes must contain 2 to 4 plain notes.",
      "Forbidden hard claims:",
      formatList([
        "특정 사건/날짜 예언",
        "질병/사고/사망 예언",
        "투자 수익 보장",
        "합격/승진/이직 확정",
        "결혼/이혼 확정",
        "임신/출산 확정",
        "공포 조장",
        "반드시",
        "무조건",
        "합격합니다",
        "불합격합니다",
        "이직합니다",
        "퇴사합니다",
        "승진합니다",
        "돈을 법니다",
        "병이 생깁니다",
        "결혼합니다",
        "헤어집니다",
      ]),
      "Allowed style examples:",
      formatList([
        "~였을 가능성이 큽니다",
        "~로 나타났을 수 있습니다",
        "~처럼 체감됐을 수 있습니다",
        "~로 이어지기 쉽습니다",
        "~에 가까운 흐름입니다",
      ]),
      "Internal words must never appear in user-visible text: evidence, debug, diagnostic-only, 진단용, schema, fixture.",
      "Bad example:",
      "올해는 책임이 커질 수 있습니다.",
      "Good example:",
      "이 해에는 직장·학업·가족 중 한 영역에서 ‘내가 정리해야 하는 역할’이 강해졌을 가능성이 큽니다. 특히 결과를 증명해야 하는 일, 돈이나 일정의 기준을 잡는 일, 누군가의 문제를 대신 수습하는 일이 이 흐름으로 나타났을 수 있습니다.",
    ].join("\n"),
    user: [
      "다음 annual fortune evidence packet만 사용해 AnnualFortuneReportDraft JSON을 작성하라.",
      "선택 연도 1개에 대한 세운 리포트다.",
      "계산값은 evidencePacket 값을 그대로 사용한다.",
      evidenceJson,
    ].join("\n\n"),
  };
}
