import type { WritingMode } from "./comprehensiveStorytelling";

export const GOD_PERSONA: Readonly<Record<string, string>> = {
  ten_god_bijian: "자기가 납득한 기준이 생기면 남의 반응에 쉽게 방향을 바꾸지 않습니다. 함께 있어도 자기 판단의 자리는 남겨 두는 사람입니다.",
  ten_god_jie_cai: "주변의 움직임을 보고 자기 안의 의욕이 살아나는 사람입니다. 비슷한 사람이 어디까지 갔는지가 자극이 되지만 마지막에는 직접 해봐야 마음이 놓입니다.",
  ten_god_shi_shen: "머릿속 생각을 손에 잡히는 무언가로 꺼낼 때 본래 힘이 살아납니다. 좋아하는 것을 꾸준히 익히고 다듬는 과정 자체가 자기 표현이 되는 사람입니다.",
  ten_god_shang_guan: "남들이 익숙하게 받아들이는 것에도 왜 그래야 하는지 묻는 사람입니다. 거슬리는 차이를 발견하고 더 나은 표현을 찾는 눈이 있습니다.",
  ten_god_pian_cai: "익숙한 울타리 밖의 사람과 새로운 가능성에 눈이 갑니다. 한 가지에 머물기보다 서로 다른 자원을 어떻게 연결할지 보는 감각이 있습니다.",
  ten_god_zheng_cai: "막연히 좋아 보이는 것보다 자기 생활 안에서 이어갈 수 있는 것을 소중히 봅니다. 작은 약속과 반복되는 일상을 돌보며 마음의 기반을 만드는 사람입니다.",
  ten_god_qi_sha: "막상 일이 닥치면 피하기보다 정면으로 움직이는 사람입니다. 평소의 생각보다 필요한 순간의 결단에서 자신의 힘을 확인하는 쪽입니다.",
  ten_god_zheng_guan: "기분에 따라 쉽게 달라지는 말보다 지켜지는 태도를 믿습니다. 스스로 옳다고 여긴 선을 오래 유지하고 가까운 사람에게도 믿을 만한 사람이 되고 싶어 합니다.",
  ten_god_pian_yin: "겉에 드러난 답을 받아들이기 전에 그 뒤에 무엇이 있는지 혼자 들여다보는 사람입니다. 남에게는 낯선 관점도 자기 안에서 연결되면 쉽게 놓지 않습니다.",
  ten_god_zheng_yin: "새로운 것을 만나면 서둘러 판단하기보다 그 뜻을 충분히 받아들이려 합니다. 이해한 것이 쌓일수록 마음이 놓이고 자기 방식의 바탕이 단단해지는 사람입니다.",
};

export const PEOPLE_SCENES = [
  { trait: "mbti:INFP:traits:relationships:emotional_distance", signals: ["ten_god_pian_yin", "ten_god_bijian"], title: "따뜻한 사람에게도 닫아둘 방은 있습니다", body: "상대의 기분을 이해하는 것과 내 안을 모두 보여 주는 것은 다릅니다. 혼자 생각하고 자기 기준을 지키는 결에 INFP의 심리적 거리가 겹쳐, 다정하게 대하면서도 가장 안쪽 이야기는 천천히 건넵니다. 친해졌다는 이유로 마음을 모두 설명하라는 요구에는 부담을 느낍니다.", action: "혼자 간직하고 싶은 부분은 숨겨야 할 결함이 아닙니다. 말하기 편한 것과 아직 시간이 필요한 것을 구분해 알려 주세요." },
  { trait: "mbti:ISTP:traits:relationships:comfortable_people_only", signals: ["ten_god_bijian", "ten_god_zheng_cai"], title: "함께 있어도 애쓰지 않아도 되는 사람", body: "많은 사람을 알아두는 것보다 몇 사람과 편하게 지내는 쪽이 중요합니다. 자기 영역을 지키는 힘에 ISTP의 관계 선택이 겹쳐, 대화를 계속 이어가려고 애쓰지 않아도 되는 사람에게 마음이 갑니다. 침묵을 채우라는 압박이 적을수록 오히려 오래 곁에 남습니다.", action: "편해서 자꾸 다음으로 미루는 사람이 있다면 먼저 시간을 잡아보세요. 부담을 주지 않는 관계에도 서로를 위해 비워 둔 자리는 필요합니다." },
  { trait: "mbti:ENFJ:traits:relationships:wide_social_bonding", signals: ["sinsal_dohwa", "ten_god_bijian", "gwiin_cheoneul"], title: "사람이 모이면 그 사이의 흐름이 보입니다", body: "누가 아직 대화에 들어오지 못했는지, 어떤 말에 분위기가 풀리는지에 관심이 갑니다. 접점과 도움의 기운에 ENFJ의 관계 형성 방식이 겹쳐 모임 안에서 연결을 만드는 역할이 자연스럽습니다. 하지만 즐거운 자리였어도 모두를 살핀 뒤에는 혼자 쉴 시간이 필요합니다.", action: "모임의 분위기를 혼자 책임지지 마세요. 누군가 조용히 있는 것을 바로 풀어야 할 문제로 받아들이지 않아도 됩니다." },
  { trait: "mbti:ESTP:traits:relationships:wide_social_circle", signals: ["ten_god_bijian", "ten_god_shi_shen", "sinsal_dohwa"], title: "같이 해볼 일이 생기면 금세 가까워집니다", body: "처음부터 속마음을 길게 나누기보다 함께 웃고 움직이며 거리를 좁힙니다. 동료와 표현의 기운에 ESTP의 넓은 교류가 더해져 낯선 사람에게도 말을 붙이는 출발점이 생깁니다. 가볍게 시작한 관계가 늘어날수록 오래 이어갈 사람은 따로 알아볼 필요가 있습니다.", action: "새로운 사람을 소개받는 재미와 기존 친구의 안부를 함께 챙겨 보세요. 넓어진 관계에 모두 같은 친밀함을 약속하지 마세요." },
] as const;

/** Authored comprehensive scenes. Sources are the existing taxonomy, day-pillar
 * meanings and the exact MBTI trait IDs below, not invented traditional lore. */
export const GIFT_SCENES: Readonly<Record<string, { mode: WritingMode; title: string; body: string; action: string; discovery: string }>> = {
  gwiin_cheoneul: { mode: "gift", title: "혼자 다 푸는 사람이 될 필요는 없습니다", body: "막힌 문제를 끝까지 혼자 안고 가야만 자기 실력이 되는 것은 아닙니다. 사람을 통해 막힌 길을 잇는 천을의 패가 있습니다. 중요한 것은 누군가 나타날 때까지 기다리는 일이 아니라, 내 질문을 들고 연결의 문을 두드리는 일입니다.", action: "답을 대신 정해 줄 사람보다 내가 놓친 관점을 짚어 줄 사람을 가까이 두세요. 받은 조언을 어디에 써봤는지 다시 전하면 일회성 도움도 오래 가는 인연이 됩니다.", discovery: "help-as-perspective" },
  twelve_sinsal_banan: { mode: "image", title: "안장에 오른 뒤에는 갈 곳을 고르세요", body: "반안의 좋은 방향은 자리와 인정입니다. 이름이 걸린 역할을 맡았을 때, 그 이름에 맞게 자신을 드러낼 힘이 있습니다. 하지만 좋은 안장은 오래 앉아 버티라고 있는 물건이 아닙니다. 그 자리에서 어디까지 가고 싶은지가 더 중요합니다.", action: "모임이든 일이든 자신의 기여가 분명히 남는 역할을 하나 고르세요. 남이 주는 호칭보다 스스로 자랑스럽게 설명할 경험을 남기세요.", discovery: "recognition-as-authorship" },
  twelve_sinsal_jangseong: { mode: "contrast", title: "깃발은 들되, 모두의 짐까지 들지는 마세요", body: "사람들이 망설일 때 먼저 방향을 잡는 사람이 필요합니다. 장성의 힘은 그런 순간에 빛납니다. 잘 쓰면 주변이 중심을 찾고, 과하게 쓰면 자신이 정하지 않은 선택까지 불편해집니다. 존중받는 것과 모든 것을 통제하는 것은 다릅니다.", action: "함께 움직일 때 큰 방향만 제안하고 구체적인 방법 하나는 상대에게 맡겨 보세요. 다른 방식으로도 같은 곳에 도착하는 경험이 리더십의 폭을 넓힙니다.", discovery: "leadership-allows-difference" },
  gwiin_jaego: { mode: "criterion", title: "얼마나 모았는지보다 무엇이 다시 쓰이는지", body: "재고의 창고에는 돈만 들어가지 않습니다. 써본 도구, 몸에 익은 기술, 다시 만날 사람도 자산입니다. 이미 얻은 것을 다음 선택의 기반으로 남기는 패이므로, 새것을 계속 더하기보다 가진 것의 쓰임을 발견하는 데서 힘이 납니다.", action: "오래 보관한 것 하나를 실제로 꺼내 쓰세요. 쓰임 없이 쌓인 것과 내 삶을 가볍게 만드는 기반을 구분하세요.", discovery: "assets-circulate" },
  sinsal_cheonmunseong: { mode: "reversal", title: "작은 사건에서 큰 흐름을 읽는 눈", body: "겉으로는 별개인 일인데 어딘가 이어진다고 느끼는 순간이 있습니다. 천문은 그런 패턴과 큰 구조를 읽는 데 쓰는 패입니다. 멀리 보는 눈의 가치는 그럴듯한 설명의 크기가 아니라, 복잡했던 일이 한눈에 들어오는 순간에 드러납니다.", action: "알아챈 연결을 한 장의 그림으로 남겨 보세요. 연결되지 않는 사례도 옆에 두면 통찰과 넘겨짚기를 가르는 자기 기준이 생깁니다.", discovery: "pattern-counterexample" },
  twelve_sinsal_hwagae: { mode: "image", title: "조용한 방은 뒤처지는 자리가 아닙니다", body: "화개의 덮개 아래에서는 밖의 소리가 잠시 작아집니다. 혼자 머무는 시간에 취향과 생각이 숙성되는 것이 이 패의 좋은 쓰임입니다. 모두가 즐거워하는 자리에서 잠시 빠져나오고 싶다는 이유로 자기 리듬을 이상하게 여기지 마세요.", action: "오롯이 좋아서 하는 활동을 일정에 남기세요. 성과를 설명하지 않아도 좋은 취향 하나가 삶의 안쪽을 단단하게 만듭니다.", discovery: "private-taste" },
  gwiin_cheondeok: { mode: "contrast", title: "갈등 속에서 관계가 돌아올 길을 남기는 힘", body: "천덕은 날카로운 관계 사이에 완충을 두는 좋은 패입니다. 누가 이겼는지만 남는 대화에서 양쪽이 다시 이야기할 통로를 찾는 데 빛납니다. 다만 분위기를 지키려고 자기 불편까지 지워서는 안 됩니다.", action: "중재할 때는 양쪽의 공통 요구 하나부터 말하세요. 화해를 돕는 사람이지 양쪽의 잘못을 대신 책임질 사람은 아닙니다.", discovery: "mediation-with-self" },
  gwiin_woldeok: { mode: "gift", title: "한 번의 호의를 오래 가는 신뢰로", body: "함께한 사람에게서 다시 도움을 잇는 월덕의 패가 있습니다. 큰 인연만 찾기보다 이미 잘 맞춰 본 사람을 알아보는 것이 중요합니다. 관계의 자산은 얼마나 많은 연락처가 있는지가 아니라 서로의 기여를 얼마나 기억하는지에 남습니다.", action: "고마웠던 도움을 구체적으로 말해 주세요. 다음에는 내가 건넬 작은 도움이 무엇인지 찾아보세요.", discovery: "reciprocity-memory" },
  sinsal_dohwa: { mode: "gift", title: "시선이 머무는 자리를 직접 고르세요", body: "도화는 매력을 새로 만들어야 한다는 숙제가 아닙니다. 자신을 드러낼 때 사람의 시선이 머무는 좋은 패입니다. 모두에게 좋은 반응을 얻으려 애쓰기보다, 어떤 취향과 생각으로 기억되고 싶은지 정하는 편이 이 힘을 잘 씁니다.", action: "사진이나 소개 글 하나에 남의 유행 대신 내 취향을 드러내 보세요. 주목받는 나와 내가 좋아하는 내가 너무 멀어지지 않게 하세요.", discovery: "attention-as-expression" },
  sinsal_hongyeom: { mode: "reversal", title: "큰 말보다 오래 남는 온도", body: "홍염의 매력은 멀리서 많은 사람을 모으는 것과 결이 다릅니다. 가까이 마주한 사람에게 표정과 말투, 작은 배려가 깊이 남는 쪽입니다. 자신이 대수롭지 않게 건넨 따뜻함도 상대에게는 특별한 신호가 됩니다.", action: "좋아하는 마음은 구체적으로 전하되, 원하지 않는 약속까지 따뜻함으로 대신하지 마세요.", discovery: "warmth-is-specific" },
};

export const FELT_QUESTIONS: Readonly<Record<string, string>> = {
  sinsal_hyeonchim: "남들은 그냥 지나치는 허점이나 말의 모순이 먼저 보이지 않으신가요?",
  ten_god_jie_cai: "혼자 할 때보다 누가 먼저 치고 나가는 모습을 볼 때 갑자기 속도가 붙는 편이지 않으신가요?",
  ten_god_pian_yin: "사람들과 이야기를 나눠도 중요한 생각은 결국 혼자 정리해야 풀리는 편 아닌가요?",
  ten_god_zheng_yin: "답만 외울 때보다 왜 그런지 이해했을 때 비로소 마음이 놓이지 않으신가요?",
  ten_god_bijian: "남들이 좋다고 해도 내가 납득하지 못하면 쉽게 움직이지 않는 편 아닌가요?",
  ten_god_zheng_guan: "큰 말보다 작은 약속을 반복해서 지키는 사람에게 더 마음이 가지 않으신가요?",
  ten_god_qi_sha: "급할 때는 침착하게 움직였는데 다 끝난 뒤에야 긴장이 몰려오는 편이지 않으신가요?",
};

export const LOVE_SCENES: readonly { id: string; trait: string; additionalTraits?: readonly string[]; signals: readonly string[]; mode: WritingMode; title: string; paragraphs: readonly string[]; action: string }[] = [
  { id: "entj-affection", trait: "mbti:ENTJ:traits:love:planned_intense_romance", additionalTraits: ["mbti:ENTJ:traits:love:independence_support_need"], signals: ["ten_god_qi_sha", "sinsal_hongyeom", "sinsal_dohwa"], mode: "judgment", title: "좋아하면 마음을 앞으로 움직입니다", paragraphs: ["마음이 생기면 상대가 알아주기만 기다리기보다 함께할 시간을 만들고 먼저 다가갑니다. 압박에도 움직이는 기질에 ENTJ의 적극적인 연애 방식이 겹쳐, 애정이 의지와 행동으로 드러납니다. 사랑하는 사람과 지금보다 넓은 세계를 경험하고 싶은 쪽입니다.", "자기 삶이 있고 서로의 방향을 존중하는 관계가 편합니다. 상대도 자기 목표를 지닌 채 서로를 지지할 때 마음이 놓입니다. 다만 둘의 관계를 혼자 앞서 완성하면 상대는 초대받기보다 따라가는 기분을 느낍니다."], action: "함께하고 싶은 계획을 말한 뒤에는 상대가 무엇을 기대하는지도 기다려 주세요. 이끄는 애정 안에 초대받는 여유가 있어야 합니다." },
  { id: "entj-hearing", trait: "mbti:ENTJ:traits:love:feedback_expectation_love", additionalTraits: ["mbti:ENTJ:traits:relationships:useful_support_style"], signals: ["ten_god_zheng_guan", "ten_god_qi_sha"], mode: "reversal", title: "고쳐 주고 싶은 마음이 위로를 앞설 때", paragraphs: ["사랑하는 사이일수록 솔직한 피드백이 도움이 된다고 생각합니다. 약속을 진지하게 대하는 명리의 결에 개선을 원하는 ENTJ의 습관이 겹치면, 상대의 답답함을 듣자마자 해결할 지점부터 찾습니다. 본인에게는 관심의 증거지만 상대는 자기 마음이 평가받았다고 느끼기 쉽습니다.", "사랑에서 잘하는 것은 문제를 외면하지 않는 일입니다. 스스로 관계를 어렵게 만드는 순간은 감정에도 정답을 요구할 때입니다. 속상한 사람에게 필요한 첫 반응은 더 나은 방법이 아니라 그 일이 왜 아팠는지 함께 머무는 시간입니다."], action: "서운하다는 말을 들으면 해명보다 먼저 그 마음을 들었다고 답하세요. 사랑은 서로를 완성시키는 시험이 아니라, 미완성인 채로도 곁에 있을 자리를 만드는 일입니다." },
  { id: "infp-inner-language", trait: "mbti:INFP:traits:love:deep_emotional_bond", signals: ["ten_god_zheng_yin", "sinsal_dohwa", "sinsal_hongyeom"], mode: "image", title: "마음의 언어가 통하는 사람", paragraphs: ["사랑은 일정을 자주 맞추는 일보다 내 안의 이야기를 건넬 수 있는지에 가깝습니다. 받아들이고 깊이 이해하려는 기질에 INFP의 정서적 교감이 겹쳐, 사소한 말에도 둘만 아는 의미가 쌓입니다. 진심으로 소중히 여긴 사람에게는 오래 마음을 씁니다.", "편한 관계는 감정을 빨리 설명하라고 재촉하지 않는 관계입니다. 반대로 내 마음을 가볍게 웃어넘기는 순간에는 함께 있어도 멀어집니다. 상대가 알아주기를 기다리는 시간이 길어질수록 서운함도 속으로 자랍니다."], action: "알아주길 바라는 마음 하나를 짧게 말로 꺼내세요. 마음을 보여 주는 일은 낭만을 깨는 것이 아니라 상대가 가까이 올 문을 여는 일입니다." },
  { id: "infp-softness", trait: "mbti:INFP:traits:love:criticism_sensitive_love", signals: ["ten_god_zheng_yin", "sinsal_dohwa"], mode: "contrast", title: "섬세함을 지키되 혼자 결론내리지 않기", paragraphs: ["작은 배려를 오래 기억하는 만큼 무심한 말도 깊이 남습니다. INFP의 민감한 수용 방식과 정서적 의미를 품는 힘은 사랑을 섬세하게 만들지만, 상처받은 이유를 혼자 해석하면 상대가 바로잡을 기회까지 사라집니다."], action: "그 말을 들었을 때 어떤 마음이었는지와 상대가 무엇을 뜻했는지를 나누어 이야기하세요. 느낀 감정은 진짜지만 상대의 의도까지 이미 정해진 것은 아닙니다." },
  { id: "istp-freedom", trait: "mbti:ISTP:traits:love:freedom_love_boundary", signals: ["ten_god_bijian", "ten_god_jie_cai", "twelve_sinsal_yeokma"], mode: "judgment", title: "가까워져도 각자의 자리는 남아 있어야 합니다", paragraphs: ["사랑한다고 하루 전체를 서로 설명해야 하는 관계는 편하지 않습니다. 자기 영역을 지키는 힘과 ISTP의 자율성이 겹쳐, 함께 있을 때 편안하고 떨어져 있을 때도 믿는 관계를 원합니다. 상대를 억지로 바꾸려 들지 않는 것은 이 사랑의 장점입니다.", "답답해지는 순간은 관심이 확인과 감시로 바뀔 때입니다. 다만 간섭하지 않는 마음만으로 상대가 사랑받는다고 느끼는 것은 아닙니다. 필요한 순간 곁에 있겠다는 신호까지 줄여 버리면 자유가 무관심으로 읽힙니다."], action: "혼자 보낼 시간은 지키되 함께하기로 한 시간에는 다른 일을 내려놓으세요. 묶어 두지 않으면서도 믿고 돌아올 곳이 되어 주세요." },
  { id: "istp-overwhelm", trait: "mbti:ISTP:traits:relationships:emotion_distance_when_overwhelmed", signals: ["ten_god_pian_yin"], mode: "reversal", title: "마음이 없어서가 아니라 말이 막혀서 멀어집니다", paragraphs: ["속으로 정리하는 힘에 ISTP의 감정 과부하 거리두기가 겹치면, 다툼이 커질수록 설명보다 침묵이 먼저 나옵니다. 혼자 가라앉힌 뒤 돌아오려는 마음이어도 상대는 혼자 남았다고 느낍니다."], action: "잠깐 쉬겠다는 말과 다시 이야기할 시간을 함께 남기세요. 침묵의 끝을 알려 주는 것이 관계를 놓지 않았다는 표현입니다." },
  { id: "enfj-future", trait: "mbti:ENFJ:traits:love:full_hearted_love", signals: ["ten_god_zheng_yin", "sinsal_hongyeom", "ten_god_zheng_guan"], mode: "gift", title: "좋아하는 사람의 내일에도 마음이 갑니다", paragraphs: ["사랑이 시작되면 지금의 즐거움뿐 아니라 함께할 미래까지 마음에 들어옵니다. 보살피고 관계를 지키는 힘에 ENFJ의 온전한 몰입이 더해져 상대의 작은 변화에도 관심을 기울입니다. 사랑받는다는 확신을 주는 데 좋은 패가 있습니다.", "마음이 오가는 대화가 편하고, 관계의 방향을 혼자 추측해야 할 때 답답해집니다. 상대가 힘들어 보이면 먼저 더 해주려 하지만 그 노력이 상대의 몫까지 대신하면 결국 자신만 지칩니다."], action: "해주고 싶은 것과 상대가 실제로 원하는 것을 맞춰 보세요. 사랑은 한쪽의 큰 마음보다 두 사람이 계속 건네는 작은 마음으로 오래 갑니다." },
  { id: "enfj-confirmation", trait: "mbti:ENFJ:traits:love:emotional_confirmation_need", signals: ["ten_god_zheng_yin", "ten_god_shi_shen"], mode: "contrast", title: "확인하고 싶은 마음과 재촉하는 마음 사이", paragraphs: ["ENFJ의 감정 확인 욕구는 관계를 세심하게 돌보는 힘과 연결됩니다. 잘 쓰면 서로의 온도를 놓치지 않지만, 답이 늦을 때마다 같은 질문을 하면 사랑이 확인 시험처럼 느껴집니다."], action: "상대의 말투 하나보다 최근 함께 지킨 약속을 보세요. 원하는 애정 표현은 직접 말하고, 상대가 자기 방식으로 답할 시간도 남기세요." },
  { id: "estp-together", trait: "mbti:ESTP:traits:love:fun_active_love", signals: ["twelve_sinsal_yeokma", "ten_god_shi_shen", "sinsal_dohwa"], mode: "image", title: "함께 움직일 때 가까워지는 사랑", paragraphs: ["나란히 앉아 마음을 오래 설명하는 것보다 같이 해본 경험이 사랑을 실감하게 합니다. 움직임과 표현의 기운에 ESTP의 활동적인 연애 방식이 겹쳐 웃고 시도하는 순간에 거리가 가까워집니다. 관계에 활력을 불어넣는 것이 잘하는 부분입니다.", "서로의 자유를 존중하면서 새로운 경험을 나누는 사람이 편합니다. 모든 시간을 묶어 두려는 요구에는 숨이 막히지만, 재미가 줄었다고 관계의 깊이까지 사라진 것은 아닙니다. 조용한 날을 견디는 힘도 사랑의 일부입니다."], action: "즐거운 활동 뒤에 좋았던 순간을 하나 말해 주세요. 같이 보낸 시간이 어떤 마음으로 남았는지까지 전하면 경험이 친밀함으로 쌓입니다." },
  { id: "estp-repair", trait: "mbti:ESTP:traits:relationships:low_grudge_high_motion", signals: ["ten_god_shi_shen", "ten_god_shang_guan"], mode: "reversal", title: "다시 웃는 것과 다 풀린 것은 다릅니다", paragraphs: ["표현을 행동으로 옮기는 기질에 ESTP의 빠른 회복 방식이 더해지면 다툰 뒤에도 다시 만나고 움직이며 풀고 싶어집니다. 분위기를 되살리는 장점이 있지만 상대는 아직 듣지 못한 사과를 기다립니다."], action: "즐거운 제안을 하기 전에 무엇이 서운했는지 한 번은 끝까지 들으세요. 다음 장면으로 넘어가기 전에 이전 장면의 마음부터 닫아 주세요." },
];
