import type { BridgeSceneRule } from "./interactionScenes";

// Reviewed pairings of existing facts and source traits. Copy is conditional interpretation,
// not a new calculation or a claim that the two systems have a common cause.
export const BRIDGE_SCENE_RULES: readonly BridgeSceneRule[] = [
  { id: "intj-model-check", mbti: "INTJ", requires: { allOf: [["ten_god_pian_yin"]] }, traits: [["thinkingStyle", "system_first_thinking"]], type: "amplification", contexts: ["identity", "career"],
    meaning: "편인의 탐구 신호와 INTJ의 구조 검토 습관이 겹치면, 빠른 동의보다 설명의 연결이 맞는지 먼저 확인할 수 있습니다.",
    scene: "회의에서 좋은 제안이라는 반응이 나와도, 비용 가정과 실행 순서가 서로 맞는지 도식으로 다시 그려 보는 장면입니다.",
    strength: "겉으로 매끄러운 계획 안의 빠진 조건을 발견하는 데 유용합니다.", risk: "검토가 길어지면 상대는 제안 전체를 거절당했다고 느낄 수 있습니다.", practice: "바꿔야 할 가정 한 개와 유지할 장점 한 개를 같이 말하세요." },
  { id: "intj-affection-contrast", mbti: "INTJ", requires: { allOf: [["sinsal_hongyeom"]] }, traits: [["love", "slow_high_standard_love"]], type: "tension", contexts: ["love", "conflict"],
    meaning: "홍염의 호감 표현 신호가 있어도 INTJ의 관계 판단은 삶의 방향을 오래 살피는 쪽이라, 친근한 반응과 관계 결정의 속도가 다를 수 있습니다.",
    scene: "즐겁게 대화한 뒤 상대가 다음 약속을 빠르게 잡으려 할 때, 혼자 돌아와 장기적으로 맞는 관계인지 다시 생각하는 장면입니다.",
    strength: "순간의 끌림과 오래 지킬 조건을 나눠 볼 수 있습니다.", risk: "상대는 좋은 분위기를 확답으로 받아들여 뒤늦게 혼란스러울 수 있습니다.", practice: "함께한 시간이 좋았다는 말과 더 알아갈 시간이 필요하다는 말을 동시에 전하세요." },
  { id: "intp-return-to-output", mbti: "INTP", requires: { allOf: [["ten_god_shi_shen"]] }, traits: [["thinkingStyle", "ti_internal_model"]], type: "compensation", contexts: ["study", "career"],
    meaning: "INTP의 내부 검증이 길어질 때 식신의 결과물 표현 신호를 활용하면, 생각을 완결한 뒤가 아니라 작은 산출물부터 밖에 내놓는 통로가 생깁니다.",
    scene: "자료를 더 읽고 싶은 공부 시간에 예제 한 개를 풀어 설명해 보니, 이해한 부분과 설명이 막히는 부분이 갈리는 장면입니다.",
    strength: "모델의 빈틈을 실제 출력으로 확인할 수 있습니다.", risk: "완벽한 설명만 내놓으려 하면 출력의 장점도 검토 안에 갇힙니다.", practice: "완성 노트 대신 오늘 설명할 수 있는 예제 하나를 먼저 남기세요." },
  { id: "entj-work-home-switch", mbti: "ENTJ", requires: { allOf: [["ten_god_zheng_guan"]] }, traits: [["career", "executive_natural_habitat"], ["love", "planned_intense_romance"]], type: "context-switch", contexts: ["career", "love", "family"],
    meaning: "정관의 역할 기준은 ENTJ에게 업무에서는 명확한 책임 분담으로, 가까운 관계에서는 함께할 시간을 계획하는 방식으로 표현될 수 있습니다. 같은 운영 감각도 상대가 원하는 자율권에 따라 다르게 받아들여집니다.",
    scene: "회사에서는 일정표 덕분에 팀이 편해지지만, 집에서 데이트 순서까지 정했을 때 상대는 먼저 의견을 묻기를 바라는 장면입니다.",
    strength: "약속을 실행 가능한 일정으로 옮기는 데 강점을 쓸 수 있습니다.", risk: "일의 효율 기준을 그대로 관계에 가져오면 돌봄이 관리처럼 들릴 수 있습니다.", practice: "업무에서는 담당자를, 사적인 계획에서는 상대가 고를 부분을 먼저 확인하세요." },
  { id: "entj-water-pause", mbti: "ENTJ", requires: { allOf: [["element_water_missing"]], noneOf: ["element_water", "element_water:excess"] }, traits: [["growth", "eq_as_strategy"]], type: "compensation", contexts: ["identity", "recovery", "conflict"],
    meaning: "수 부족을 감정 결핍으로 단정할 수는 없습니다. 다만 회복의 여백을 점검하는 명리 관점에 ENTJ의 감정 고려 전략을 붙이면, 결론을 멈추고 상대 반응을 확인하는 구체적인 기준을 만들 수 있습니다.",
    scene: "업무가 끝난 뒤에도 해결책을 생각하다가, 가족의 말을 듣는 순간까지 다음 지시를 준비하고 있음을 알아차리는 장면입니다.",
    strength: "상대의 부담을 확인하는 과정을 의도적인 판단 단계로 만들 수 있습니다.", risk: "감정 확인마저 일을 빨리 끝내는 기술로만 쓰면 대화가 다시 평가로 돌아갑니다.", practice: "답을 제안하기 전에 지금은 공감과 해결 중 무엇이 필요한지 물으세요." },
  { id: "entp-boundary-experiment", mbti: "ENTP", requires: { allOf: [["ten_god_zheng_guan"]] }, traits: [["thinkingStyle", "possibility_scanning"]], type: "tension", contexts: ["identity", "career"],
    meaning: "정관의 기준 준수 신호와 ENTP의 대안 탐색 습관은 방향이 다를 수 있습니다. 규칙을 이해하면서도 더 나은 방법이 보이면 시험하고 싶어지는 긴장입니다.",
    scene: "회의에서 정해진 절차를 확인한 직후, 다른 방식으로 하면 시간을 줄일 수 있겠다며 실험안을 꺼내는 장면입니다.",
    strength: "지켜야 할 책임과 바꿀 수 있는 방법을 분리하면 개선의 폭이 생깁니다.", risk: "합의된 절차를 먼저 건너뛰면 제안의 타당성보다 신뢰 문제가 커집니다.", practice: "책임 범위는 유지하고 바꿀 방법 하나만 시험 기간과 함께 제안하세요." },
  { id: "entp-cash-close", mbti: "ENTP", requires: { allOf: [["ten_god_zheng_cai"]] }, traits: [["money", "opportunity_money_sense"]], type: "compensation", contexts: ["money"],
    meaning: "새 기회를 먼저 보는 ENTP의 돈 감각에 정재의 반복 관리 신호를 붙이면, 가능성을 실제 정산 조건으로 내려놓는 보완이 가능합니다.",
    scene: "새 프로젝트가 매력적으로 보일 때 예상 매출만 적는 대신, 입금일과 고정 비용을 같은 종이에 쓰는 장면입니다.",
    strength: "흥미로운 기회 중 실제로 감당할 수 있는 범위를 가려낼 수 있습니다.", risk: "아직 들어오지 않은 돈을 이미 쓸 수 있는 돈처럼 취급하면 판단이 흔들립니다.", practice: "착수 전에 받을 금액, 받을 날짜, 먼저 나갈 비용을 분리하세요." },
  { id: "infj-verify-impression", mbti: "INFJ", requires: { allOf: [["ten_god_pian_yin"]] }, traits: [["thinkingStyle", "ni_pattern_prediction"]], type: "amplification", contexts: ["identity", "conflict"],
    meaning: "편인의 깊이 읽기와 INFJ의 패턴 연결이 겹치면, 한 번의 대화에서도 그 뒤의 흐름까지 생각할 수 있습니다.",
    scene: "상대의 짧은 답장을 보고 이전 대화들을 연결하다가, 아직 묻지 않은 이유까지 혼자 설명하고 있는 장면입니다.",
    strength: "여러 경험의 공통점을 찾아 관계의 반복을 돌아볼 수 있습니다.", risk: "그럴듯한 해석이 상대가 실제로 말한 사실을 대신할 수 있습니다.", practice: "관찰한 문장과 내가 추측한 이유를 나눈 뒤 확인 질문 하나를 보내세요." },
  { id: "infj-meaning-budget", mbti: "INFJ", requires: { allOf: [["ten_god_zheng_cai"]] }, traits: [["money", "meaning_first_income_risk"]], type: "tension", contexts: ["career", "money"],
    meaning: "정재의 생활 안정 기준과 INFJ의 의미 중심 선택은 서로 다른 질문을 던집니다. 가치 있는 일인지와 지속해서 생활할 수 있는 일인지를 함께 봐야 합니다.",
    scene: "하고 싶은 제안을 받았을 때 보람을 길게 설명하면서도, 보수와 작업 시간을 묻는 일은 미루는 장면입니다.",
    strength: "생활 조건을 확인하면 의미 있는 일을 더 오래 지속할 기반이 됩니다.", risk: "조건을 묻는 것을 속물적이라고 느끼면 책임과 보상의 균형이 흐려집니다.", practice: "수락 전에 최소 보수와 제공할 시간을 한 쌍으로 정하세요." },
  { id: "infp-expression-value", mbti: "INFP", requires: { allOf: [["ten_god_shi_shen"]] }, traits: [["study", "storytelling_learning"]], type: "agreement", contexts: ["identity", "study"],
    meaning: "식신의 표현 신호와 INFP의 이야기로 이해하는 학습 방식이 같은 방향을 지지하면, 외운 문장을 자기 사례로 바꾸는 과정에서 이해가 깊어질 수 있습니다.",
    scene: "낯선 개념을 그대로 반복하기보다 소설의 장면이나 자신의 경험에 대입해서 짧은 설명을 만드는 장면입니다.",
    strength: "추상적인 정보를 오래 기억할 개인적인 연결 고리를 만들 수 있습니다.", risk: "이야기가 생생해도 원래 개념의 조건을 빼먹으면 시험 답이나 설명은 어긋날 수 있습니다.", practice: "만든 비유 옆에 원래 정의와 예외 조건을 함께 적으세요." },
  { id: "infp-self-family-switch", mbti: "INFP", requires: { allOf: [["ten_god_bijian"]] }, traits: [["thinkingStyle", "fi_inner_alignment"], ["marriage", "freedom_romance_marriage"]], type: "context-switch", contexts: ["identity", "marriage", "family", "recovery"],
    meaning: "비견의 자기 기준은 INFP의 가치 정리에서는 흔들리지 않는 선택으로, 공동생활에서는 개인 시간과 의미를 지키려는 요청으로 드러날 수 있습니다.",
    scene: "혼자 할 일은 분명하게 고르면서도 가족 일정이 몰린 주말에는 창작이나 휴식 시간을 말없이 양보했다가 답답해지는 장면입니다.",
    strength: "소중한 활동을 알아야 가족과 함께할 시간도 자발적으로 선택할 수 있습니다.", risk: "자기 시간을 원한다는 말을 관계를 덜 사랑한다는 뜻으로 오해할 수 있습니다.", practice: "함께할 일정과 혼자 지킬 시간을 각각 약속으로 표시하세요." },
  { id: "enfj-care-boundary", mbti: "ENFJ", requires: { allOf: [["ten_god_zheng_yin"]] }, traits: [["career", "teacher_facilitator_fit"]], type: "amplification", contexts: ["identity", "career", "family"],
    meaning: "정인의 지원 신호와 ENFJ의 성장 지원 습관이 겹치면, 상대가 해낼 조건까지 마련하고 싶어질 수 있습니다.",
    scene: "동료가 어려움을 말했을 때 방법을 알려주는 데서 멈추지 않고 자료와 연습 일정까지 챙기는 장면입니다.",
    strength: "막막한 사람에게 시작할 발판을 제공할 수 있습니다.", risk: "상대의 진척이 느리면 자신이 더 도와야 한다고 느껴 책임이 늘어날 수 있습니다.", practice: "도움을 시작할 때 내가 제공할 것과 상대가 직접 할 것을 나누세요." },
  { id: "enfj-generosity-cap", mbti: "ENFJ", requires: { allOf: [["ten_god_pian_cai"]] }, traits: [["money", "generous_spending"]], type: "expression", contexts: ["money", "love"],
    meaning: "편재의 자원 교류 신호는 ENFJ의 베푸는 소비와 만날 때, 함께하는 경험이나 상대를 위한 지출로 표현될 수 있습니다.",
    scene: "모임을 제안한 사람이 되어 장소와 비용까지 넉넉하게 맡고, 집에 와서 이번 달 남은 예산을 확인하는 장면입니다.",
    strength: "자원을 관계의 경험으로 연결하는 데 의미를 찾을 수 있습니다.", risk: "상대의 만족을 지출 규모로 확인하려 하면 한도가 흔들립니다.", practice: "선물과 모임 예산을 정한 뒤 그 안에서 마음을 표현할 방법을 고르세요." },
  { id: "enfp-idea-branches", mbti: "ENFP", requires: { allOf: [["ten_god_pian_yin"]] }, traits: [["thinkingStyle", "ne_connection_thinking"]], type: "agreement", contexts: ["identity", "career"],
    meaning: "편인의 다른 관점 탐색과 ENFP의 연결 사고가 함께 작동하면, 떨어져 보이는 경험을 하나의 기획으로 묶을 수 있습니다.",
    scene: "누군가의 고민을 듣다가 여행에서 본 장면과 다른 분야의 사례를 연결해 새로운 접근을 떠올리는 장면입니다.",
    strength: "익숙한 문제에 다른 출발점을 제시할 수 있습니다.", risk: "연결이 흥미롭다는 이유만으로 실제 제약까지 해결된 것처럼 느낄 수 있습니다.", practice: "아이디어의 매력과 검증해야 할 가정을 다른 줄에 적으세요." },
  { id: "enfp-experience-budget", mbti: "ENFP", requires: { allOf: [["ten_god_zheng_cai"]] }, traits: [["money", "experience_spending"]], type: "tension", contexts: ["money", "recovery"],
    meaning: "정재의 예측 가능한 관리 기준과 ENFP의 경험 소비는 다른 만족을 지향할 수 있습니다. 안정과 재미 중 하나를 포기하기보다 쓸 수 있는 경계를 만드는 문제입니다.",
    scene: "새 강의나 여행 공지를 보자 바로 참여하고 싶다가도, 고정 지출을 떠올리며 결정을 여러 번 바꾸는 장면입니다.",
    strength: "경험을 고르는 기준이 생기면 지출 뒤의 후회를 줄일 수 있습니다.", risk: "참다가 한꺼번에 쓰는 방식은 안정과 즐거움 모두를 해칩니다.", practice: "경험 예산을 따로 두고 한도를 넘는 제안은 하루 뒤 다시 고르세요." },
  { id: "istj-change-record", mbti: "ISTJ", requires: { allOf: [["sinsal_yeokma"]] }, traits: [["thinkingStyle", "past_data_decision"]], type: "tension", contexts: ["identity", "career"],
    meaning: "역마의 이동·변화 신호가 들어와도 ISTJ는 검증된 경험을 판단 기준으로 삼습니다. 변화를 원하지 않는다기보다 믿을 기록이 있어야 움직이기 편할 수 있습니다.",
    scene: "새 팀이나 도구를 제안받았을 때 먼저 기존 방식과의 차이, 실패했을 때 돌아올 절차를 확인하는 장면입니다.",
    strength: "전환 과정의 누락을 기록으로 줄일 수 있습니다.", risk: "전례가 생길 때까지 기다리면 직접 확인할 작은 기회도 놓칩니다.", practice: "전면 전환보다 되돌릴 수 있는 시험 범위와 확인 날짜를 정하세요." },
  { id: "istj-trust-action", mbti: "ISTJ", requires: { allOf: [["ten_god_zheng_guan"]] }, traits: [["love", "trust_first_love"]], type: "agreement", contexts: ["love", "marriage"],
    meaning: "정관의 약속 기준과 ISTJ의 신뢰 중심 연애는 꾸준히 지킨 행동을 중요하게 본다는 점에서 만날 수 있습니다.",
    scene: "큰 애정 표현보다 약속한 시간에 도착하고 상대가 부탁한 일을 기억해 처리하면서 마음을 전하는 장면입니다.",
    strength: "관계의 안정감을 반복된 행동으로 쌓을 수 있습니다.", risk: "행동으로 충분히 말했다고 생각하면 상대가 필요한 말의 확인을 놓칠 수 있습니다.", practice: "챙긴 일 하나에 그 일을 한 마음 한 문장을 덧붙이세요." },
  { id: "isfj-help-limit", mbti: "ISFJ", requires: { allOf: [["ten_god_qi_sha"]] }, traits: [["growth", "learn_to_say_no"]], type: "compensation", contexts: ["identity", "career", "recovery"],
    meaning: "편관의 압박 대응 신호를 부담을 모두 받아내야 한다는 뜻으로 읽지 않습니다. ISFJ의 거절 기준을 세우는 성장 방향과 연결하면, 책임을 지키면서 자기 용량을 보호하는 연습이 됩니다.",
    scene: "급한 부탁을 받았을 때 바로 맡겠다고 답하기 전에, 이미 약속한 일을 확인하고 가능한 분량만 제안하는 장면입니다.",
    strength: "도움을 계속할 수 있는 범위를 스스로 정할 수 있습니다.", risk: "거절을 뒤로 미루면 결국 기존 약속까지 지키기 어려워집니다.", practice: "지금 가능한 일과 이번에는 어려운 일을 한 문장씩 나눠 답하세요." },
  { id: "isfj-memory-support", mbti: "ISFJ", requires: { allOf: [["ten_god_zheng_yin"]] }, traits: [["thinkingStyle", "sensory_memory_judgment"]], type: "agreement", contexts: ["identity", "study", "family"],
    meaning: "정인의 학습·지원 신호와 ISFJ의 구체적인 경험 기억은, 실제 사례를 축적해 다음 선택에 쓰는 방향에서 만날 수 있습니다.",
    scene: "다시 맡은 일을 시작할 때 지난번 실수와 상대가 편해했던 방식을 먼저 떠올리고 준비물을 챙기는 장면입니다.",
    strength: "작은 필요를 기억해 반복 업무나 돌봄의 누락을 줄일 수 있습니다.", risk: "과거에 도움이 된 방식이 지금도 필요한지 확인하지 않을 수 있습니다.", practice: "이전에 좋았던 방법을 제안하되 이번에도 같은 도움이 필요한지 먼저 물으세요." },
  { id: "estj-correction-temperature", mbti: "ESTJ", requires: { allOf: [["sinsal_hyeonchim"]] }, traits: [["thinkingStyle", "te_fact_execution"]], type: "amplification", contexts: ["identity", "career", "conflict"],
    meaning: "현침의 세밀한 지적 신호와 ESTJ의 기준 중심 판단이 겹치면, 문제의 위치와 담당자를 빨리 짚는 방식으로 나타날 수 있습니다.",
    scene: "보고서의 수치 오류를 발견하자 수정해야 할 칸부터 말했는데, 작성자는 자신의 노력을 전부 부정당했다고 느끼는 장면입니다.",
    strength: "오류와 책임 범위를 명료하게 만들어 재작업을 줄일 수 있습니다.", risk: "문제와 사람에 대한 평가가 한 문장에 섞이면 내용보다 말투가 남습니다.", practice: "수정할 자료를 특정하고 사람 전체에 대한 평가 표현은 빼세요." },
  { id: "estj-household-space", mbti: "ESTJ", requires: { allOf: [["element_earth:excess"]], noneOf: ["element_earth_missing"] }, traits: [["marriage", "structured_household"]], type: "amplification", contexts: ["marriage", "family"],
    meaning: "토 과다의 유지 부담과 ESTJ의 생활 구조화가 겹치면, 집안일이 안정되는 만큼 기존 규칙을 바꾸기 어려워질 수도 있습니다.",
    scene: "가족이 일정을 바꾸자 새 방법의 장점보다 누가 빈자리를 메울지를 먼저 계산하는 장면입니다.",
    strength: "생활의 지속성과 맡은 일의 공백을 세심하게 관리할 수 있습니다.", risk: "모든 예외를 막으면 함께 사는 사람의 선택권이 줄어듭니다.", practice: "꼭 지킬 공동 규칙과 각자 바꿀 수 있는 생활 방식을 구분하세요." },
  { id: "esfj-care-check", mbti: "ESFJ", requires: { allOf: [["nobleman_cheoneul"]] }, traits: [["career", "service_helping_fit"]], type: "expression", contexts: ["identity", "career", "family"],
    meaning: "천을귀인의 도움 통로는 ESFJ의 구체적인 돌봄 행동과 연결해 살펴볼 수 있습니다. 귀인이 있다는 사실만으로 누군가가 반드시 도와준다는 뜻은 아닙니다.",
    scene: "주변에 필요한 정보를 찾아 연결해 주다가 자신에게 필요한 도움은 따로 요청하지 못한 채 일을 마치는 장면입니다.",
    strength: "누가 무엇을 도울 수 있는지 연결망을 구체화할 수 있습니다.", risk: "연결을 맡은 사람이 모든 문제의 담당자가 되면 피로가 쌓입니다.", practice: "소개와 실제 수행의 책임을 구분하고 내 요청도 같은 통로에 올리세요." },
  { id: "esfj-exam-understanding", mbti: "ESFJ", requires: { allOf: [["nobleman_munchang"]] }, traits: [["study", "rote_exam_strength"]], type: "compensation", contexts: ["study"],
    meaning: "문창의 정리·설명 신호를 ESFJ의 반복 학습에 연결하면, 외운 답을 자기 말로 풀어보는 확인 단계가 보완이 됩니다.",
    scene: "용어를 반복해 익힌 뒤 친구에게 그 용어가 실제 상황에서 어떻게 쓰이는지 설명하다가 모호한 부분을 찾는 장면입니다.",
    strength: "익숙한 답과 실제 이해를 구분하며 학습할 수 있습니다.", risk: "정답 문장을 외웠다는 안정감이 응용 문제의 빈틈을 가릴 수 있습니다.", practice: "외운 항목마다 다른 사례 한 개를 만들어 설명하세요." },
  { id: "istp-tool-proof", mbti: "ISTP", requires: { allOf: [["ten_god_shi_shen"]] }, traits: [["study", "hands_on_learning"]], type: "agreement", contexts: ["identity", "study", "career"],
    meaning: "식신의 결과물 표현과 ISTP의 직접 다루는 학습은 실제로 작동하는지를 확인하는 방향에서 만날 수 있습니다.",
    scene: "긴 사용 설명을 모두 읽기 전에 작은 부품이나 예제를 직접 조작하며 어느 단계에서 문제가 생기는지 찾는 장면입니다.",
    strength: "설명을 실제 경험으로 검증하고 수정할 수 있습니다.", risk: "작동했다는 결과만으로 원리를 생략하면 다른 조건에서 같은 오류를 반복할 수 있습니다.", practice: "고친 과정에서 바꾼 조건 한 가지를 기록해 다른 사례에도 적용해 보세요." },
  { id: "istp-space-request", mbti: "ISTP", requires: { allOf: [["ten_god_bijian"]] }, traits: [["love", "freedom_love_boundary"]], type: "amplification", contexts: ["love", "marriage", "recovery"],
    meaning: "비견의 자기 영역과 ISTP의 자율 시간 선호가 겹치면, 가까운 관계에서도 혼자 정리할 공간을 중요하게 볼 수 있습니다.",
    scene: "갈등 직후 혼자 취미에 몰입해 진정하려는데, 상대는 대화를 피한다며 연락을 더 자주 하는 장면입니다.",
    strength: "자기 속도를 회복한 뒤 다시 대화할 여유를 만들 수 있습니다.", risk: "돌아올 시간을 말하지 않은 거리두기는 상대의 불안을 키울 수 있습니다.", practice: "혼자 필요한 시간과 다시 이야기할 시점을 함께 알려 주세요." },
  { id: "isfp-price-voice", mbti: "ISFP", requires: { allOf: [["ten_god_zheng_cai"]] }, traits: [["money", "low_income_risk_due_to_softness"]], type: "compensation", contexts: ["identity", "career", "money"],
    meaning: "정재의 구체적인 보상 기준을 ISFP의 가격 표현 과제에 연결하면, 강하게 밀어붙이지 않고도 작업의 가치를 설명하는 틀이 됩니다.",
    scene: "지인의 부탁으로 작업을 시작하려다 필요한 시간과 수정 횟수를 적으니 말하기 어려웠던 비용을 설명할 근거가 생기는 장면입니다.",
    strength: "관계를 지키면서도 제공할 범위를 명확히 할 수 있습니다.", risk: "친절한 표현을 위해 조건까지 생략하면 추가 요청을 거절하기 어려워집니다.", practice: "가격만 말하지 말고 포함되는 작업과 제외되는 요청을 함께 적으세요." },
  { id: "isfp-warmth-opening", mbti: "ISFP", requires: { allOf: [["sinsal_hongyeom"]] }, traits: [["love", "slow_open_romantic"]], type: "context-switch", contexts: ["love", "conflict"],
    meaning: "홍염의 호감 표현 신호와 ISFP의 천천히 마음을 여는 성향을 함께 보면, 처음의 조심스러움과 가까워진 뒤의 다정함을 같은 사람 안의 다른 상황으로 읽을 수 있습니다.",
    scene: "여럿이 있는 자리에서는 감정을 많이 말하지 않지만, 둘만 있을 때 취향을 기억한 작은 선물을 건네는 장면입니다.",
    strength: "관계가 안전하다고 느낀 뒤 섬세한 애정을 구체적으로 표현할 수 있습니다.", risk: "처음의 침묵을 상대가 관심 없음으로 해석하거나, 가까워진 뒤의 몰입이 자기 생활을 밀어낼 수 있습니다.", practice: "표현을 크게 늘리기보다 호감의 한 문장과 지킬 개인 일정을 함께 남기세요." },
  { id: "estp-field-notice", mbti: "ESTP", requires: { allOf: [["sinsal_hyeonchim"]] }, traits: [["thinkingStyle", "se_now_data"]], type: "expression", contexts: ["identity", "career"],
    meaning: "현침의 세부 포착 신호는 ESTP의 현장 관찰과 만나, 말보다 표정이나 실제 움직임에서 어긋난 부분을 알아차리는 방식으로 표현될 수 있습니다.",
    scene: "고객이 괜찮다고 말해도 제품을 다루는 손이 멈춘 지점을 보고 설명 방식을 바꾸는 장면입니다.",
    strength: "현장에서 확인되는 반응에 맞춰 대응을 조정할 수 있습니다.", risk: "관찰이 빠르다는 이유로 상대의 속마음까지 확정하면 오해가 생깁니다.", practice: "포착한 행동을 짚고 어떤 부분이 불편했는지 직접 물으세요." },
  { id: "estp-review-before-move", mbti: "ESTP", requires: { allOf: [["ten_god_zheng_yin"]] }, traits: [["study", "experiential_learning"]], type: "tension", contexts: ["study", "recovery"],
    meaning: "정인의 흡수·검토 신호와 ESTP의 체험 학습은 시작 순서가 다를 수 있습니다. 직접 해본 뒤 개념으로 돌아오는 순서를 만들면 둘을 버리지 않아도 됩니다.",
    scene: "연습 문제에 바로 도전했다가 틀린 이유를 확인하려고 관련 개념 몇 줄만 다시 읽는 장면입니다.",
    strength: "실패 경험을 다음 시도의 구체적인 자료로 바꿀 수 있습니다.", risk: "다시 도전하는 속도만 높이면 같은 조건에서 계속 막힙니다.", practice: "한 번의 시도 뒤에는 실패 조건 하나를 확인하는 시간을 붙이세요." },
  { id: "esfp-response-energy", mbti: "ESFP", requires: { allOf: [["sinsal_dohwa"]] }, traits: [["career", "entertainment_fit"]], type: "amplification", contexts: ["identity", "career"],
    meaning: "도화의 주목 신호와 ESFP의 현장 반응 선호가 겹치면, 사람들이 반응하는 자리에서 표현의 에너지가 살아날 수 있습니다.",
    scene: "혼자 준비할 때보다 작은 시연이나 발표에서 반응을 보며 설명과 표정을 조절하는 장면입니다.",
    strength: "관객이나 고객의 반응을 받아 표현을 개선할 수 있습니다.", risk: "반응이 조용한 날을 자신의 가치가 낮아진 날로 받아들이면 소모가 커집니다.", practice: "박수나 호응과 별개로 전달할 핵심을 달성했는지 확인하세요." },
  { id: "esfp-routine-play", mbti: "ESFP", requires: { allOf: [["ten_god_zheng_cai"]] }, traits: [["growth", "make_fun_responsible"]], type: "compensation", contexts: ["study", "money", "family"],
    meaning: "정재의 반복 관리 신호를 ESFP의 재미와 책임을 연결하는 습관에 붙이면, 해야 할 일을 작고 끝나는 활동으로 바꿀 수 있습니다.",
    scene: "밀린 생활비 정리를 긴 숙제로 두는 대신 음악 한 곡 동안 이번 주 지출만 분류하고 끝내는 장면입니다.",
    strength: "즐거움을 포기하지 않고 반복 책임을 이어갈 수 있습니다.", risk: "보상이 없으면 멈추는 방식만 남으면 중요한 일의 유지가 어려워집니다.", practice: "짧게 끝낼 최소 단위를 정하고 끝낸 기록을 남기세요." },
];
