import { defineClaim as d, axis as a, axisGate as ag, any } from "./claimCore";

export const FACT_BOMB_CLAIMS = [
  d({ id: "F01_STUBBORN", category: "FACT_BOMB", semanticTheme: "STUBBORNNESS", contexts: ["identity", "work", "social"],
    requiredAxes: [a("PERSISTENCE"), a("AUTONOMY"), a("BOUNDARY")], factBomb: true, exclusivityGroup: "FACT_BOMB_STANDARDS",
    claimsByLevel: { 2: "한번 맞다고 생각한 방향을 쉽게 바꾸지 않는 편입니다.", 3: "고집이 셉니다." } }),
  d({ id: "F02_SHARP_SPEECH", category: "FACT_BOMB", semanticTheme: "SHARP_SPEECH", contexts: ["identity", "work", "social", "love"],
    requiredAxes: [a("PRECISION"), a("COMMUNICATION_STYLE")], preferredFusionIds: ["C060"], factBomb: true, exclusivityGroup: "FACT_BOMB_PRECISION",
    claimsByLevel: { 2: "틀린 걸 보면 말이 바로 나올 때가 있습니다.", 3: "틀린 걸 보면 말이 날카로워질 수 있습니다." } }),
  d({ id: "F03_PERFECTIONISM", category: "FACT_BOMB", semanticTheme: "PERFECTIONISM", contexts: ["work", "identity", "learning"], requiredAxes: [a("PRECISION", "STRONG")],
    requiredConditions: [any(ag("STRUCTURE_STYLE"), ag("GOAL_DRIVE"), ag("DUTY"))], factBomb: true, exclusivityGroup: "FACT_BOMB_PRECISION",
    claimsByLevel: { 2: "잘하고 싶은 마음 때문에 완성도를 너무 신경 쓸 때가 있습니다.", 3: "남들이 충분히 잘됐다고 해도 고칠 부분부터 먼저 보는 편입니다." },
    alternativeLevel3: "잘하고 싶은 마음이 커서 완성도를 너무 신경 쓰다 시작이나 마감이 늦어지기도 합니다." }),
  d({ id: "F04_OVERWORK", category: "FACT_BOMB", semanticTheme: "OVERWORK", contexts: ["work", "stress", "recovery", "identity"],
    requiredAxes: [a("GOAL_DRIVE"), a("DUTY"), a("PERSISTENCE")], factBomb: true, exclusivityGroup: "FACT_BOMB_OVERWORK",
    claimsByLevel: { 2: "해야 할 일이 남아 있으면 쉬면서도 계속 생각할 때가 있습니다.", 3: "일은 끝났는데 머리는 아직 퇴근하지 않을 때가 있습니다." } }),
  d({ id: "F05_OVERTHINKING", category: "FACT_BOMB", semanticTheme: "OVERTHINKING", contexts: ["identity", "work", "learning"], requiredAxes: [a("DEPTH", "STRONG")],
    requiredConditions: [any(ag("CURIOSITY"), ag("PATTERN_SENSE")), { kind: "delay" }], factBomb: true, exclusivityGroup: "FACT_BOMB_SPEED",
    claimsByLevel: { 2: "생각을 충분히 해야 마음이 놓여 결정이 늦어질 때가 있습니다.", 3: "생각이 너무 길어져 시작이 늦어질 때가 있습니다." } }),
  d({ id: "F06_TOO_FAST", category: "FACT_BOMB", semanticTheme: "TOO_FAST", contexts: ["identity", "work", "social"],
    requiredAxes: [a("ACTION_TEMPO", "STRONG"), a("DECISION_STYLE")], factBomb: true, exclusivityGroup: "FACT_BOMB_SPEED",
    claimsByLevel: { 2: "답을 빨리 정해서 다른 사람이 생각을 정리할 시간을 덜 줄 때가 있습니다.", 3: "결론이 빨라서 다른 사람 설명이 끝나기 전에 답을 정할 때가 있습니다." } }),
  d({ id: "F07_OVERCARE", category: "FACT_BOMB", semanticTheme: "OVERCARE", contexts: ["social", "love", "work", "stress"], requiredAxes: [a("CARE", "STRONG")],
    requiredConditions: [any(ag("DUTY"), ag("SOCIAL_ATTUNEMENT"))], factBomb: true, exclusivityGroup: "FACT_BOMB_CARE",
    claimsByLevel: { 2: "사람을 챙기다 자기 할 일까지 늘어날 때가 있습니다.", 3: "남의 일까지 자기 일처럼 챙기다 지칠 때가 있습니다." } }),
  d({ id: "F08_OPPORTUNITY_SCATTER", category: "FACT_BOMB", semanticTheme: "OPPORTUNITY_SCATTER", contexts: ["identity", "work", "money"], requiredAxes: [a("OPPORTUNITY_SENSE", "STRONG")],
    requiredConditions: [any(ag("EXPANSION"), ag("ADAPTABILITY"))], factBomb: true, exclusivityGroup: "FACT_BOMB_OPPORTUNITY",
    claimsByLevel: { 2: "좋은 기회가 여러 개 보이면 한 가지를 오래 붙잡기 어려울 수 있습니다.", 3: "새로운 기회가 계속 보여 한 가지에 충분히 집중하지 못할 때가 있습니다." } }),
];
