import { defineClaim as d, axis as a, axisGate as ag, any, all, family, fortune, synthesis } from "./claimCore";

export const MONEY_CLAIMS = [
  d({ id: "M01_REALISTIC_MONEY_SENSE", category: "MONEY_STYLE", semanticTheme: "MONEY_REALITY", contexts: ["money", "work"],
    requiredAxes: [a("RESOURCE_SENSE"), a("PRACTICALITY")], exclusivityGroup: "MONEY_STYLE_CORE",
    claimsByLevel: { 2: "돈이 실제로 얼마나 남는지를 중요하게 보는 편입니다.", 3: "돈이 들어오는 것보다 실제로 얼마나 남는지 계산하는 감각이 좋습니다." } }),
  d({ id: "M02_ACCUMULATION", category: "MONEY_STYLE", semanticTheme: "MONEY_ACCUMULATION", contexts: ["money", "work"],
    requiredAxes: [a("RESOURCE_SENSE"), a("STABILITY")], exclusivityGroup: "MONEY_STYLE_CORE",
    claimsByLevel: { 2: "버는 것만큼 남기고 쌓아두는 것도 중요하게 생각합니다.", 3: "돈뿐 아니라 기술과 경험도 한번 얻으면 다음에 다시 쓸 밑천으로 남기는 편입니다." } }),
  d({ id: "M03_MONEY_OPPORTUNITY", category: "MONEY_STYLE", semanticTheme: "MONEY_OPPORTUNITY", contexts: ["money", "work"],
    requiredAxes: [a("OPPORTUNITY_SENSE"), a("RESOURCE_SENSE", "SUPPORT")], exclusivityGroup: "MONEY_OPPORTUNITY",
    claimsByLevel: { 2: "새로운 사람이나 상황에서 돈이 될 기회를 찾는 편입니다.", 3: "밖에서 돈이 될 기회를 알아보는 감각이 좋은 편입니다." } }),
  d({ id: "M04_BUSINESS_TRANSACTION_STYLE", category: "BUSINESS", semanticTheme: "BUSINESS_OPPORTUNITY_STYLE", contexts: ["money", "work"],
    requiredAxes: [a("OPPORTUNITY_SENSE"), a("EXPANSION"), a("AUTONOMY", "SUPPORT"), a("RESOURCE_SENSE")], exclusivityGroup: "BUSINESS_STYLE",
    claimsByLevel: { 2: "정해진 방식으로 돈을 버는 것보다 직접 기회를 만들고 넓히는 일에도 관심이 갈 수 있습니다.", 3: "새로운 사람과 시장을 만나 직접 돈의 기회를 만드는 방식에도 잘 맞는 편입니다." } }),
  d({ id: "M05_STABLE_INCOME", category: "MONEY_STYLE", semanticTheme: "STABLE_INCOME", contexts: ["money", "work"],
    requiredAxes: [a("STABILITY"), a("RESOURCE_SENSE"), a("DUTY", "SUPPORT")], exclusivityGroup: "MONEY_STYLE_CORE",
    claimsByLevel: { 2: "한 번 큰돈보다 꾸준히 들어오는 돈이 있어야 마음이 편한 편입니다.", 3: "돈에서는 큰 한 번보다 꾸준히 들어오고 남는 구조를 더 중요하게 생각합니다." } }),
  d({ id: "M06_BIG_MONEY_DESIRE", category: "MONEY_STYLE", semanticTheme: "MONEY_EXPANSION_DESIRE", contexts: ["money", "work"],
    requiredAxes: [a("EXPANSION"), a("RESOURCE_SENSE"), a("GOAL_DRIVE")], exclusivityGroup: "MONEY_DESIRE",
    claimsByLevel: { 2: "돈에서도 지금보다 더 큰 결과를 만들고 싶어 하는 편입니다.", 3: "돈을 단순한 생활비보다 키워야 할 목표처럼 보는 성향이 강합니다." } }),
  d({ id: "M07_MONEY_AND_MEANING", category: "MONEY_STYLE", semanticTheme: "MONEY_AND_MEANING", contexts: ["money", "work"],
    requiredAxes: [a("RESOURCE_SENSE"), a("MEANING")], preferredFusionIds: ["C040"], exclusivityGroup: "MONEY_MEANING",
    claimsByLevel: { 2: "돈도 중요하지만, 이 일을 왜 하는지도 중요하게 생각합니다.", 3: "돈만 많이 주는 일도, 의미만 있고 제대로 보상받지 못하는 일도 오래 만족시키기 어렵습니다." } }),
  d({ id: "M08_GOOD_WEALTH_PATTERN", category: "MONEY_FORTUNE", semanticTheme: "WEALTH_FORTUNE", contexts: ["money", "work"],
    requiredAxes: [a("RESOURCE_SENSE")], requiredConditions: [family("WEALTH"), any(fortune("ACCUMULATION"), synthesis("OUTPUT_TO_WEALTH"), synthesis("SELF_OUTPUT_TO_VALUE"), ag("OPPORTUNITY_SENSE"),
      all({ kind: "source", key: "正財" }, { kind: "source", key: "偏財" }))], minimumIndependentMyeongliFamilies: 2,
    minLevel: 3, maxLevel: 4, fortuneClaim: true, priority: 80, exclusivityGroup: "MONEY_FORTUNE",
    claimsByLevel: { 3: "재물 쪽에는 좋은 근거가 여러 개 겹쳐 있습니다.", 4: "재물 쪽에는 좋은 패가 있습니다." } }),
  d({ id: "M09_WEALTH_OPPORTUNITY_PATTERN", category: "MONEY_STYLE", semanticTheme: "WEALTH_OPPORTUNITY_PATTERN", contexts: ["money", "work"],
    requiredAxes: [a("OPPORTUNITY_SENSE")], requiredConditions: [family("WEALTH")], exclusivityGroup: "MONEY_OPPORTUNITY", priority: 60,
    claimsByLevel: { 2: "익숙한 자리 안에서만 벌기보다 새로운 사람이나 환경에서 돈의 기회를 찾는 편입니다.", 3: "새로운 사람, 시장, 환경이 돈의 기회로 이어지는 구조를 잘 활용할 수 있습니다." } }),
  d({ id: "M10_TOO_MANY_MONEY_OPPORTUNITIES", category: "FACT_BOMB", semanticTheme: "MONEY_OPPORTUNITY_SCATTER", contexts: ["money", "work"],
    requiredAxes: [a("OPPORTUNITY_SENSE", "STRONG"), a("CHANGE_ORIENTATION")], factBomb: true, exclusivityGroup: "FACT_BOMB_OPPORTUNITY",
    claimsByLevel: { 2: "돈이 될 기회가 여러 개 보이면 한 가지에 충분히 집중하지 못할 때가 있습니다.", 3: "돈이 될 일이 많이 보여 오히려 하나를 오래 붙잡기 어려울 수 있습니다." } }),
];
