import { defineClaim as d, axis as a, axisGate as ag, any, fortune } from "./claimCore";

export const SOCIAL_CLAIMS = [
  d({ id: "P01_PEOPLE_LUCK", category: "PEOPLE_LUCK", semanticTheme: "PEOPLE_LUCK", contexts: ["social", "work", "love"], requiredAxes: [],
    requiredConditions: [fortune("HELPER_LUCK"), { kind: "helperCompanion" }], minimumIndependentMyeongliFamilies: 2,
    minLevel: 3, maxLevel: 4, fortuneClaim: true, exclusivityGroup: "PEOPLE_LUCK", priority: 80,
    claimsByLevel: { 3: "사람을 통해 도움이나 길이 열리는 근거가 있습니다.", 4: "사람복이 있습니다." } }),
  d({ id: "P02_GOOD_RELATION_RECIPROCITY", category: "STRENGTH", semanticTheme: "GOOD_RELATION_RECIPROCITY", contexts: ["social", "love", "work"],
    requiredAxes: [a("CARE"), a("SOCIAL_ATTUNEMENT")], preferredFusionIds: ["C049", "C095"], exclusivityGroup: "SOCIAL_CARE",
    claimsByLevel: { 2: "도움을 받기만 하기보다 본인도 사람을 잘 챙겨 좋은 인연을 남기는 편입니다.", 3: "사람을 잘 챙기기 때문에 좋은 인연을 스스로 만들어가는 면도 강합니다." } }),
  d({ id: "P03_NETWORK_OPPORTUNITY", category: "PEOPLE_LUCK", semanticTheme: "NETWORK_OPPORTUNITY", contexts: ["social", "work"],
    requiredAxes: [a("RELATION_STYLE"), a("OPPORTUNITY_SENSE")], exclusivityGroup: "PEOPLE_LUCK",
    claimsByLevel: { 2: "혼자 찾던 기회가 사람의 소개나 연결에서 생길 수 있는 구조가 있습니다.", 3: "사람을 통해 새로운 일이나 기회를 만나는 쪽을 잘 활용할 수 있습니다." } }),
  d({ id: "A01_FIRST_IMPRESSION_CHARM", category: "CHARM", semanticTheme: "FIRST_IMPRESSION_CHARM", contexts: ["social", "love", "identity"],
    requiredAxes: [a("CHARISMA", "SUPPORT")], requiredConditions: [any(fortune("FIRST_IMPRESSION"), fortune("SOCIAL_VISIBILITY"))],
    fortuneClaim: true, exclusivityGroup: "CHARM_VISIBILITY",
    claimsByLevel: { 2: "처음 만나는 자리에서 사람 눈에 들어오는 편입니다.", 3: "처음 만났을 때 사람 눈에 들어오는 매력이 있습니다." } }),
  d({ id: "A02_INTIMATE_CHARM", category: "CHARM", semanticTheme: "INTIMATE_CHARM", contexts: ["love", "social"], requiredAxes: [],
    requiredConditions: [fortune("INTIMATE_CHARM"), any(ag("SOCIAL_ATTUNEMENT"), ag("CARE"))], fortuneClaim: true, exclusivityGroup: "CHARM_INTIMACY",
    claimsByLevel: { 2: "처음보다 가까워졌을 때 매력이 더 잘 보이는 편입니다.", 3: "가까워질수록 더 살아나는 매력이 있습니다." } }),
  d({ id: "A03_EXPRESSIVE_CHARM", category: "CHARM", semanticTheme: "EXPRESSIVE_CHARM", contexts: ["social", "love", "work"], requiredAxes: [a("EXPRESSION"), a("CHARISMA")], exclusivityGroup: "CHARM_VISIBILITY",
    claimsByLevel: { 2: "말하고 표현할 때 매력이 더 잘 드러나는 편입니다.", 3: "말하고 표현할 때 사람을 끌어당기는 매력이 살아납니다." } }),
  d({ id: "A04_QUIET_CHARM", category: "CHARM", semanticTheme: "QUIET_CHARM", contexts: ["social", "love", "identity"], requiredAxes: [a("ENERGY_DIRECTION", "MAIN", -1), a("DEPTH")],
    requiredConditions: [any(ag("CHARISMA", "SUPPORT"), fortune("INTIMATE_CHARM"))], exclusivityGroup: "CHARM_INTIMACY",
    claimsByLevel: { 2: "처음부터 크게 튀기보다 알아갈수록 기억에 남는 편입니다.", 3: "처음보다 알아갈수록 오래 기억되는 매력이 있습니다." } }),
  d({ id: "A05_ROMANTIC_VISIBILITY", category: "CHARM", semanticTheme: "ROMANTIC_VISIBILITY", contexts: ["love", "social"], requiredAxes: [],
    requiredConditions: [any(fortune("FIRST_IMPRESSION"), fortune("INTIMATE_CHARM")), any(ag("CHARISMA"), ag("CARE"), ag("SOCIAL_ATTUNEMENT"))],
    fortuneClaim: true, exclusivityGroup: "CHARM_VISIBILITY", priority: 60,
    claimsByLevel: { 2: "연애에서는 상대에게 매력적으로 보일 요소가 분명한 편입니다.", 3: "연애에서 상대의 눈에 들어오는 매력이 있는 편입니다." } }),
];
