import type { InterpretationContext } from "./semanticCore";
import type { AxisRequirement } from "./fusionCore";

export const FUSION_COMPLEMENT_REGISTRY_VERSION = "cross-system-complement-13d-2b-v1" as const;
export const GROUP_CONTEXTS = {
  THINKING_ANALYSIS: ["identity", "work", "learning"], EXECUTION_STRATEGY: ["identity", "work"],
  LEADERSHIP_STATUS: ["work", "identity"], MONEY_REALITY: ["money", "work"],
  SOCIAL_COMMUNICATION: ["social", "work", "identity"], CREATION_LEARNING: ["learning", "work", "identity"],
  RELATIONSHIP: ["love", "social"], CHANGE_RECOVERY: ["identity", "recovery", "stress", "work"],
} as const satisfies Record<string, readonly InterpretationContext[]>;
export type FusionCompositeRule = {
  id: string; axisA: AxisRequirement; axisB: AxisRequirement; semanticTheme: string;
  group: keyof typeof GROUP_CONTEXTS; contexts: readonly InterpretationContext[]; requiredContext?: boolean;
  sourceDescription: string; positiveMeaning?: string; shadowMeaning?: string;
  priority: number; specificity: "CROSS_AXIS";
};
/** Reviewed closed registry. It supplies meanings, never infers pairs from text. */
export const FUSION_COMPLEMENT_RULES: readonly FusionCompositeRule[] = [
  { id: "C001", axisA: { axis: "PRECISION", direction: 1 }, axisB: { axis: "CARE", direction: 1 }, semanticTheme: "KIND_PRECISION", group: "THINKING_ANALYSIS",
    contexts: ["identity", "work", "learning", "social"], sourceDescription: "문제를 빨리 알아차리면서도 사람을 함부로 몰아붙이지 않는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C002", axisA: { axis: "PRECISION", direction: 1 }, axisB: { axis: "DEPTH", direction: 1 }, semanticTheme: "ROOT_CAUSE_ANALYSIS", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "작은 오류를 찾는 데서 끝나지 않고 왜 그런 문제가 생겼는지까지 파고드는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C003", axisA: { axis: "PRECISION", direction: 1 }, axisB: { axis: "PATTERN_SENSE", direction: 1 }, semanticTheme: "REPEATING_ERROR_SENSE", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "한 번의 실수만 보는 게 아니라 같은 문제가 왜 반복되는지도 알아차리는 쪽으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C004", axisA: { axis: "CURIOSITY", direction: 1 }, axisB: { axis: "PRECISION", direction: 1 }, semanticTheme: "VERIFY_UNTIL_CLEAR", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "궁금한 점이 생기면 대충 넘기기보다 앞뒤가 맞는지 확인할 때까지 파고드는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C005", axisA: { axis: "DEPTH", direction: 1 }, axisB: { axis: "PATTERN_SENSE", direction: 1 }, semanticTheme: "HIDDEN_CONNECTIONS", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "겉으로 떨어져 보이는 일들 사이에서 깊은 연결과 반복을 찾아내는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C006", axisA: { axis: "DEPTH", direction: 1 }, axisB: { axis: "LEARNING", direction: 1 }, semanticTheme: "DEEP_EXPERTISE", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "그냥 아는 데서 끝나지 않고 깊게 이해해 자기 전문성으로 만드는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C007", axisA: { axis: "STRATEGY", direction: 1 }, axisB: { axis: "PATTERN_SENSE", direction: 1 }, semanticTheme: "SEE_NEXT_MOVE", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "지금 상황만 보기보다 반복되는 흐름을 보고 다음에 무슨 일이 생길지 미리 생각하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C008", axisA: { axis: "STRATEGY", direction: 1 }, axisB: { axis: "PRECISION", direction: 1 }, semanticTheme: "DETAILED_STRATEGY", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "큰 방향만 잡는 게 아니라 빠진 조건까지 확인하면서 계획을 세우는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C009", axisA: { axis: "PRACTICALITY", direction: 1 }, axisB: { axis: "PRECISION", direction: 1 }, semanticTheme: "USABLE_ACCURACY", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "정확하기만 한 답보다 실제로 써먹을 수 있고 틀리지 않는 답을 찾는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C010", axisA: { axis: "MEANING", direction: 1 }, axisB: { axis: "DEPTH", direction: 1 }, semanticTheme: "MEANINGFUL_DEPTH", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "겉으로 좋아 보이는 것보다 왜 중요한지까지 이해해야 마음이 움직이는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C011", axisA: { axis: "CURIOSITY", direction: 1 }, axisB: { axis: "PATTERN_SENSE", direction: 1 }, semanticTheme: "IDEA_CONNECTION", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "한 가지 궁금증에서 시작해 서로 다른 정보까지 연결하며 새로운 생각을 만드는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C012", axisA: { axis: "BOUNDARY", direction: 1 }, axisB: { axis: "PRECISION", direction: 1 }, semanticTheme: "CLEAR_STANDARDS", group: "THINKING_ANALYSIS",
    contexts: GROUP_CONTEXTS.THINKING_ANALYSIS, sourceDescription: "무엇이 괜찮고 무엇이 아닌지 자기 기준을 꽤 정확하게 구분하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C013", axisA: { axis: "GOAL_DRIVE", direction: 1 }, axisB: { axis: "INITIATIVE", direction: 1 }, semanticTheme: "START_TOWARD_GOAL", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "목표가 생기면 남이 시작해주길 기다리기보다 직접 움직이는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C014", axisA: { axis: "GOAL_DRIVE", direction: 1 }, axisB: { axis: "PERSISTENCE", direction: 1 }, semanticTheme: "STAY_WITH_GOAL", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "목표를 잡은 뒤 쉽게 바꾸기보다 끝까지 붙드는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C015", axisA: { axis: "GOAL_DRIVE", direction: 1 }, axisB: { axis: "PRACTICALITY", direction: 1 }, semanticTheme: "RESULT_ORIENTED_GOAL", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "목표를 세우는 데서 끝나지 않고 실제 결과가 남아야 만족하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C016", axisA: { axis: "GOAL_DRIVE", direction: 1 }, axisB: { axis: "EXPANSION", direction: 1 }, semanticTheme: "AMBITIOUS_GROWTH", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "하나를 해내면 거기서 멈추기보다 더 큰 목표를 잡고 싶어 하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C017", axisA: { axis: "INITIATIVE", direction: 1 }, axisB: { axis: "ADAPTABILITY", direction: 1 }, semanticTheme: "START_AND_ADJUST", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "일단 시작한 뒤 상황을 보면서 방법을 바꿔 답을 찾는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C018", axisA: { axis: "INITIATIVE", direction: 1 }, axisB: { axis: "STRUCTURE_STYLE", direction: 1 }, semanticTheme: "PLANNED_START", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "시작은 빠르지만 아무렇게나 뛰어들기보다 해야 할 순서를 정하고 움직이는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C019", axisA: { axis: "STRATEGY", direction: 1 }, axisB: { axis: "ADAPTABILITY", direction: 1 }, semanticTheme: "FLEXIBLE_STRATEGY", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "목표는 유지하면서 상황이 바뀌면 방법은 유연하게 바꾸는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C020", axisA: { axis: "DECISION_STYLE", direction: 1 }, axisB: { axis: "PRECISION", direction: 1 }, semanticTheme: "CAREFUL_DECISION", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "결론을 오래 미루지는 않지만 중요한 조건을 확인한 뒤 답을 정하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C021", axisA: { axis: "ACTION_TEMPO", direction: 1 }, axisB: { axis: "STRATEGY", direction: 1 }, semanticTheme: "FAST_BUT_PLANNED", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "움직이는 속도는 빠르지만 다음 순서를 생각하지 않고 덤비는 사람은 아닌 모습으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C022", axisA: { axis: "ACTION_TEMPO", direction: 1 }, axisB: { axis: "PERSISTENCE", direction: 1 }, semanticTheme: "FAST_AND_STEADY", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "시작도 빠르고 한번 시작한 일도 쉽게 놓지 않는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C023", axisA: { axis: "CHANGE_ORIENTATION", direction: 1 }, axisB: { axis: "GOAL_DRIVE", direction: 1 }, semanticTheme: "CHANGE_FOR_GROWTH", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "새로운 것을 찾는 이유가 단순한 재미보다 더 나은 목표와 성장을 향하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C024", axisA: { axis: "STABILITY", direction: 1 }, axisB: { axis: "ADAPTABILITY", direction: 1 }, semanticTheme: "STABLE_ADAPTER", group: "EXECUTION_STRATEGY",
    contexts: GROUP_CONTEXTS.EXECUTION_STRATEGY, sourceDescription: "기본 생활과 기준은 안정적으로 두면서 상황이 바뀌면 방법은 잘 바꾸는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C025", axisA: { axis: "LEADERSHIP", direction: 1 }, axisB: { axis: "CARE", direction: 1 }, semanticTheme: "CARING_LEADER", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "사람을 이끌면서도 결과만 보지 않고 구성원이 어떻게 버티는지도 살피는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C026", axisA: { axis: "LEADERSHIP", direction: 1 }, axisB: { axis: "SOCIAL_ATTUNEMENT", direction: 1 }, semanticTheme: "PEOPLE_AWARE_LEADER", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "사람의 반응을 읽으면서 방향을 정하는 리더로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C027", axisA: { axis: "LEADERSHIP", direction: 1 }, axisB: { axis: "DUTY", direction: 1 }, semanticTheme: "RESPONSIBLE_LEADER", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "앞에 서는 것만 좋아하는 게 아니라 결과에 대한 책임까지 지려는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C028", axisA: { axis: "LEADERSHIP", direction: 1 }, axisB: { axis: "BOUNDARY", direction: 1 }, semanticTheme: "CLEAR_BOUNDARY_LEADER", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "사람을 이끌 때 해야 할 것과 하면 안 되는 것의 기준을 분명하게 정하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C029", axisA: { axis: "LEADERSHIP", direction: 1 }, axisB: { axis: "STRATEGY", direction: 1 }, semanticTheme: "STRATEGIC_LEADER", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "사람을 움직이기 전에 어디로 가야 하는지 다음 수까지 생각하는 리더로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C030", axisA: { axis: "LEADERSHIP", direction: 1 }, axisB: { axis: "PRACTICALITY", direction: 1 }, semanticTheme: "RESULT_LEADER", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "말로 이끄는 데서 끝나지 않고 실제 결과가 나오게 만드는 리더로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C031", axisA: { axis: "STATUS_DRIVE", direction: 1 }, axisB: { axis: "LEADERSHIP", direction: 1 }, semanticTheme: "HIGH_POSITION_DESIRE", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "그냥 잘하는 데서 끝나기보다 높은 직책에서 직접 결정하고 인정받고 싶어 하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C032", axisA: { axis: "STATUS_DRIVE", direction: 1 }, axisB: { axis: "GOAL_DRIVE", direction: 1 }, semanticTheme: "ACHIEVEMENT_RECOGNITION", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "목표를 이루는 것뿐 아니라 그 성과를 제대로 인정받는 것도 중요하게 생각하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C033", axisA: { axis: "STATUS_DRIVE", direction: 1 }, axisB: { axis: "LEARNING", direction: 1 }, semanticTheme: "STATUS_THROUGH_EXPERTISE", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "높은 자리를 원하더라도 실력과 전문성을 쌓아 인정받고 싶어 하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C034", axisA: { axis: "COMPETITION", direction: 1 }, axisB: { axis: "GOAL_DRIVE", direction: 1 }, semanticTheme: "COMPETITIVE_MOTIVATION", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "경쟁자가 생기면 위축되기보다 목표를 더 세게 붙드는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C035", axisA: { axis: "COMPETITION", direction: 1 }, axisB: { axis: "LEADERSHIP", direction: 1 }, semanticTheme: "COMPETITIVE_LEADER", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "경쟁이 있는 상황에서 뒤로 물러나기보다 직접 앞에 서려는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C036", axisA: { axis: "DUTY", direction: 1 }, axisB: { axis: "PRECISION", direction: 1 }, semanticTheme: "RELIABLE_ACCURACY", group: "LEADERSHIP_STATUS",
    contexts: GROUP_CONTEXTS.LEADERSHIP_STATUS, sourceDescription: "맡은 일을 끝내는 것뿐 아니라 틀리지 않게 제대로 끝내려는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C037", axisA: { axis: "RESOURCE_SENSE", direction: 1 }, axisB: { axis: "PRACTICALITY", direction: 1 }, semanticTheme: "REAL_MONEY_SENSE", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "돈이 들어오는지만 보지 않고 실제로 얼마나 남는지 계산하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C038", axisA: { axis: "RESOURCE_SENSE", direction: 1 }, axisB: { axis: "STABILITY", direction: 1 }, semanticTheme: "ACCUMULATE_AND_KEEP", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "돈을 버는 것만큼 지키고 쌓아두는 것도 중요하게 생각하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C039", axisA: { axis: "RESOURCE_SENSE", direction: 1 }, axisB: { axis: "OPPORTUNITY_SENSE", direction: 1 }, semanticTheme: "MONEY_OPPORTUNITY_SENSE", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "새로운 기회를 볼 때 재미뿐 아니라 실제 돈이 될 수 있는지도 함께 보는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C040", axisA: { axis: "RESOURCE_SENSE", direction: 1 }, axisB: { axis: "MEANING", direction: 1 }, semanticTheme: "MONEY_AND_MEANING", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "돈도 중요하지만 의미 없는 일을 하면서 돈만 버는 것으로는 오래 만족하기 어려운 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C041", axisA: { axis: "RESOURCE_SENSE", direction: 1 }, axisB: { axis: "AUTONOMY", direction: 1 }, semanticTheme: "VALUE_OF_MY_TIME", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "돈을 많이 받아도 자기 시간과 선택권을 너무 많이 잃으면 좋은 거래라고 느끼지 않는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C042", axisA: { axis: "RESOURCE_SENSE", direction: 1 }, axisB: { axis: "GOAL_DRIVE", direction: 1 }, semanticTheme: "MONEY_AS_GOAL", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "원하는 수입이나 재산 목표가 생기면 구체적인 목표처럼 관리하고 움직이는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C043", axisA: { axis: "OPPORTUNITY_SENSE", direction: 1 }, axisB: { axis: "EXPANSION", direction: 1 }, semanticTheme: "EXPAND_FOR_OPPORTUNITY", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "새로운 사람과 시장을 만나면서 더 큰 기회를 찾고 싶어 하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C044", axisA: { axis: "OPPORTUNITY_SENSE", direction: 1 }, axisB: { axis: "ADAPTABILITY", direction: 1 }, semanticTheme: "ADAPT_TO_OPPORTUNITY", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "기회가 보이면 처음 정한 방식에 묶이지 않고 방법을 바꿀 줄 아는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C045", axisA: { axis: "PRACTICALITY", direction: 1 }, axisB: { axis: "MEANING", direction: 1 }, semanticTheme: "USEFUL_AND_MEANINGFUL", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "의미만 있는 일도, 돈만 남는 일도 아닌 실제 가치가 있는 일을 하고 싶어 하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C046", axisA: { axis: "RISK_STYLE", direction: -1 }, axisB: { axis: "RESOURCE_SENSE", direction: 1 }, semanticTheme: "CAREFUL_MONEY_DECISION", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "돈 문제에서는 기회보다 손해와 위험을 먼저 확인한 뒤 움직이는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C047", axisA: { axis: "STRATEGY", direction: 1 }, axisB: { axis: "RESOURCE_SENSE", direction: 1 }, semanticTheme: "RESOURCE_STRATEGY", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "돈과 시간을 그때그때 쓰기보다 앞으로 어디에 써야 더 남는지 생각하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C048", axisA: { axis: "EXPANSION", direction: 1 }, axisB: { axis: "PRACTICALITY", direction: 1 }, semanticTheme: "REALISTIC_GROWTH", group: "MONEY_REALITY",
    contexts: GROUP_CONTEXTS.MONEY_REALITY, sourceDescription: "더 크게 성장하고 싶어 하면서도 실제로 감당 가능한지 계산하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C049", axisA: { axis: "SOCIAL_ATTUNEMENT", direction: 1 }, axisB: { axis: "CARE", direction: 1 }, semanticTheme: "NOTICE_AND_CARE", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "사람의 기분 변화를 빨리 알아차리고 실제로 챙기려는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C050", axisA: { axis: "SOCIAL_ATTUNEMENT", direction: 1 }, axisB: { axis: "EXPRESSION", direction: 1 }, semanticTheme: "RESPONSIVE_COMMUNICATION", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "혼자 말하기보다 상대 반응을 보면서 말과 분위기를 조절하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C051", axisA: { axis: "SOCIAL_ATTUNEMENT", direction: 1 }, axisB: { axis: "PRECISION", direction: 1 }, semanticTheme: "READ_SMALL_SIGNALS", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "말의 내용뿐 아니라 작은 표정이나 말투 변화까지 빨리 알아차리는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C052", axisA: { axis: "SOCIAL_ATTUNEMENT", direction: 1 }, axisB: { axis: "BOUNDARY", direction: 1 }, semanticTheme: "EMPATHY_WITH_BOUNDARY", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "사람 기분은 잘 알아차리지만 중요한 기준까지 상대에게 맞추지는 않는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C053", axisA: { axis: "CARE", direction: 1 }, axisB: { axis: "BOUNDARY", direction: 1 }, semanticTheme: "CARE_WITH_LIMITS", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "사람을 잘 챙기면서도 어디까지가 자기 책임인지는 구분하려는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C054", axisA: { axis: "CARE", direction: 1 }, axisB: { axis: "COMMUNICATION_STYLE", direction: 1 }, semanticTheme: "DIRECT_BUT_CARING", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "솔직하게 말하면서도 상대를 상처 주는 게 목적은 아닌 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C055", axisA: { axis: "CARE", direction: 1 }, axisB: { axis: "COMMUNICATION_STYLE", direction: -1 }, semanticTheme: "GENTLE_CARE", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "하고 싶은 말이 있어도 상대가 받아들이기 쉬운 방식으로 부드럽게 말하려는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C056", axisA: { axis: "EXPRESSION", direction: 1 }, axisB: { axis: "CHARISMA", direction: 1 }, semanticTheme: "VISIBLE_EXPRESSION", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "말하고 표현할 때 사람 눈에 잘 들어오고 존재감이 살아나는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C057", axisA: { axis: "EXPRESSION", direction: 1 }, axisB: { axis: "MEANING", direction: 1 }, semanticTheme: "MEANINGFUL_EXPRESSION", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "그냥 많이 말하기보다 자기에게 중요한 생각을 사람들에게 제대로 전하고 싶어 하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C058", axisA: { axis: "CHARISMA", direction: 1 }, axisB: { axis: "SOCIAL_ATTUNEMENT", direction: 1 }, semanticTheme: "SOCIAL_CHARISMA", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "사람 눈에 잘 들어오면서도 그 자리 분위기와 반응을 같이 읽는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C059", axisA: { axis: "RELATION_STYLE", direction: 1 }, axisB: { axis: "AUTONOMY", direction: 1 }, semanticTheme: "CONNECTED_BUT_INDEPENDENT", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "사람과 함께하는 걸 좋아해도 중요한 선택은 자기 기준으로 하고 싶은 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C060", axisA: { axis: "COMMUNICATION_STYLE", direction: 1 }, axisB: { axis: "PRECISION", direction: 1 }, semanticTheme: "PRECISE_DIRECT_SPEECH", group: "SOCIAL_COMMUNICATION",
    contexts: GROUP_CONTEXTS.SOCIAL_COMMUNICATION, sourceDescription: "틀린 부분이나 핵심이 보이면 돌려 말하기보다 정확하게 짚는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C061", axisA: { axis: "CREATION", direction: 1 }, axisB: { axis: "EXPRESSION", direction: 1 }, semanticTheme: "MAKE_AND_SHOW", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "생각만 하는 데서 끝나지 않고 직접 만들어 다른 사람에게 보여주고 싶은 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C062", axisA: { axis: "CREATION", direction: 1 }, axisB: { axis: "PRECISION", direction: 1 }, semanticTheme: "CRAFT_QUALITY", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "무언가를 만드는 것뿐 아니라 작은 부분까지 다듬어 완성도를 높이고 싶은 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C063", axisA: { axis: "CREATION", direction: 1 }, axisB: { axis: "MEANING", direction: 1 }, semanticTheme: "MEANINGFUL_CREATION", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "그냥 결과물을 많이 만들기보다 자기에게 의미 있는 것을 만들고 싶은 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C064", axisA: { axis: "CREATION", direction: 1 }, axisB: { axis: "LEARNING", direction: 1 }, semanticTheme: "LEARN_TO_MAKE", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "배운 것을 머릿속에만 두기보다 실제 결과로 만들어봐야 자기 것이 되는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C065", axisA: { axis: "CREATION", direction: 1 }, axisB: { axis: "DEPTH", direction: 1 }, semanticTheme: "DEEP_TO_OUTPUT", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "깊게 이해한 내용을 결국 글, 기술, 제품 같은 결과로 꺼내고 싶은 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C066", axisA: { axis: "LEARNING", direction: 1 }, axisB: { axis: "EXPRESSION", direction: 1 }, semanticTheme: "EXPLAIN_WHAT_I_KNOW", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "배운 것을 자기만 아는 데서 끝내지 않고 다른 사람이 이해할 수 있게 설명하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C067", axisA: { axis: "LEARNING", direction: 1 }, axisB: { axis: "PRACTICALITY", direction: 1 }, semanticTheme: "USEFUL_LEARNING", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "배우는 것 자체보다 실제로 어디에 써먹을 수 있는지까지 생각하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C068", axisA: { axis: "LEARNING", direction: 1 }, axisB: { axis: "GOAL_DRIVE", direction: 1 }, semanticTheme: "LEARN_FOR_GOAL", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "목표가 생기면 필요한 지식과 기술을 스스로 찾아 배우는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C069", axisA: { axis: "LEARNING", direction: 1 }, axisB: { axis: "AUTONOMY", direction: 1 }, semanticTheme: "LEARN_IN_MY_WAY", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "남에게 배워도 마지막에는 자기 방식으로 이해해야 제대로 알았다고 느끼는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C070", axisA: { axis: "CURIOSITY", direction: 1 }, axisB: { axis: "CREATION", direction: 1 }, semanticTheme: "QUESTION_TO_CREATION", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "궁금한 것을 알아보는 데서 끝나지 않고 새로운 아이디어나 결과로 이어가는 사람으로 발전할 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C071", axisA: { axis: "PATTERN_SENSE", direction: 1 }, axisB: { axis: "CREATION", direction: 1 }, semanticTheme: "PATTERN_TO_IDEA", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "남들이 따로 보는 것들을 연결해서 새로운 아이디어나 결과를 만드는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C072", axisA: { axis: "STRATEGY", direction: 1 }, axisB: { axis: "CREATION", direction: 1 }, semanticTheme: "PLANNED_CREATION", group: "CREATION_LEARNING",
    contexts: GROUP_CONTEXTS.CREATION_LEARNING, sourceDescription: "아이디어만 떠올리는 게 아니라 어떻게 만들고 완성할지까지 계획하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C073", axisA: { axis: "CARE", direction: 1 }, axisB: { axis: "STABILITY", direction: 1 }, semanticTheme: "STEADY_CARE", group: "RELATIONSHIP",
    contexts: GROUP_CONTEXTS.RELATIONSHIP, sourceDescription: "말 한 번보다 오래 챙기고 지켜주는 방식으로 마음을 보여주는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C074", axisA: { axis: "CARE", direction: 1 }, axisB: { axis: "EXPRESSION", direction: 1 }, semanticTheme: "SHOW_AFFECTION", group: "RELATIONSHIP",
    contexts: GROUP_CONTEXTS.RELATIONSHIP, sourceDescription: "좋아하는 마음을 속으로만 가지고 있기보다 말이나 행동으로 보여주려는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C075", axisA: { axis: "DEPTH", direction: 1 }, axisB: { axis: "CARE", direction: 1 }, semanticTheme: "THINK_DEEPLY_ABOUT_PEOPLE", group: "RELATIONSHIP",
    contexts: GROUP_CONTEXTS.RELATIONSHIP, sourceDescription: "가까운 사람의 마음과 말을 오래 생각하고 이해하려는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C076", axisA: { axis: "SOCIAL_ATTUNEMENT", direction: 1 }, axisB: { axis: "STABILITY", direction: 1 }, semanticTheme: "RELATIONSHIP_CONTINUITY", group: "RELATIONSHIP",
    contexts: GROUP_CONTEXTS.RELATIONSHIP, sourceDescription: "상대 반응을 살피면서 관계를 오래 안정적으로 이어가고 싶어 하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C077", axisA: { axis: "AUTONOMY", direction: 1 }, axisB: { axis: "CARE", direction: 1 }, semanticTheme: "LOVE_WITH_SPACE", group: "RELATIONSHIP",
    contexts: GROUP_CONTEXTS.RELATIONSHIP, sourceDescription: "사람을 아끼고 챙기면서도 자기 시간과 선택권은 필요한 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C078", axisA: { axis: "RELATION_STYLE", direction: 1 }, axisB: { axis: "BOUNDARY", direction: 1 }, semanticTheme: "CLOSE_WITH_BOUNDARY", group: "RELATIONSHIP",
    contexts: GROUP_CONTEXTS.RELATIONSHIP, sourceDescription: "가까운 관계를 좋아해도 넘지 말아야 할 선은 분명히 두고 싶은 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C079", axisA: { axis: "MEANING", direction: 1 }, axisB: { axis: "CARE", direction: 1 }, semanticTheme: "MEANINGFUL_RELATIONSHIP", group: "RELATIONSHIP",
    contexts: GROUP_CONTEXTS.RELATIONSHIP, sourceDescription: "관계를 유지하는 것보다 서로에게 어떤 의미가 있는지를 중요하게 보는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C080", axisA: { axis: "SOCIAL_ATTUNEMENT", direction: 1 }, axisB: { axis: "RECOVERY_NEED", direction: 1 }, semanticTheme: "SOCIAL_SENSITIVITY_AND_RECOVERY", group: "RELATIONSHIP",
    contexts: GROUP_CONTEXTS.RELATIONSHIP, sourceDescription: "사람의 반응을 많이 읽는 만큼 사람을 많이 만난 뒤에는 혼자 회복할 시간이 더 필요한 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C081", axisA: { axis: "PRECISION", direction: 1 }, axisB: { axis: "CARE", direction: 1 }, semanticTheme: "DETAILS_IN_LOVE", group: "RELATIONSHIP",
    contexts: ["love", "social"], requiredContext: true, sourceDescription: "좋아하는 사람의 작은 말과 행동까지 잘 기억하고 알아차리는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C082", axisA: { axis: "STABILITY", direction: 1 }, axisB: { axis: "EXPRESSION", direction: 1 }, semanticTheme: "CONSISTENT_AFFECTION", group: "RELATIONSHIP",
    contexts: ["love"], requiredContext: true, sourceDescription: "한 번의 큰 표현보다 꾸준히 연락하고 행동으로 보여주는 사랑을 중요하게 생각하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C083", axisA: { axis: "CHANGE_ORIENTATION", direction: 1 }, axisB: { axis: "OPPORTUNITY_SENSE", direction: 1 }, semanticTheme: "CHANGE_FOR_OPPORTUNITY", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "새로운 환경을 두려워하기보다 그 안에서 새로운 기회를 찾는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C084", axisA: { axis: "CHANGE_ORIENTATION", direction: 1 }, axisB: { axis: "ADAPTABILITY", direction: 1 }, semanticTheme: "COMFORTABLE_WITH_CHANGE", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "상황이 달라져도 기존 방식만 고집하지 않고 빠르게 새 방법을 찾는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C085", axisA: { axis: "STABILITY", direction: 1 }, axisB: { axis: "RECOVERY_NEED", direction: 1 }, semanticTheme: "STABLE_RECOVERY", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "회복할 때는 자극적인 변화보다 익숙하고 안정적인 환경이 필요한 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C086", axisA: { axis: "DEPTH", direction: 1 }, axisB: { axis: "RECOVERY_NEED", direction: 1 }, semanticTheme: "QUIET_RECOVERY", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "쉬는 것만으로는 부족하고 혼자 생각을 정리해야 제대로 회복되는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C087", axisA: { axis: "EXPRESSION", direction: 1 }, axisB: { axis: "RECOVERY_NEED", direction: 1 }, semanticTheme: "OUTWARD_ENERGY_RECOVERY", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "밖에서는 말하고 표현하는 에너지가 크지만 끝난 뒤에는 혼자 쉬어야 다시 힘이 나는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C088", axisA: { axis: "ENERGY_DIRECTION", direction: 1 }, axisB: { axis: "DEPTH", direction: 1 }, semanticTheme: "TALK_AND_REFLECT", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "사람들과 이야기하면서 생각을 넓히고 혼자 있을 때 그 생각을 더 깊게 정리하는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C089", axisA: { axis: "ENERGY_DIRECTION", direction: -1 }, axisB: { axis: "LEADERSHIP", direction: 1 }, semanticTheme: "QUIET_LEADER", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "평소에는 앞에 나서지 않아도 결정이 필요한 순간에는 방향을 잡을 수 있는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C090", axisA: { axis: "STRUCTURE_STYLE", direction: 1 }, axisB: { axis: "ADAPTABILITY", direction: 1 }, semanticTheme: "STRUCTURED_FLEXIBILITY", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "기준과 계획은 분명하지만 상황이 달라지면 방법까지 고집하지는 않는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C091", axisA: { axis: "RISK_STYLE", direction: 1 }, axisB: { axis: "STRATEGY", direction: 1 }, semanticTheme: "CALCULATED_RISK", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "도전은 좋아하지만 아무 생각 없이 뛰어들기보다 다음 수를 계산하고 움직이는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C092", axisA: { axis: "RISK_STYLE", direction: -1 }, axisB: { axis: "OPPORTUNITY_SENSE", direction: 1 }, semanticTheme: "CAREFUL_OPPORTUNITY", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "기회를 잘 보면서도 실제 손해와 위험을 확인한 뒤 움직이는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C093", axisA: { axis: "AUTONOMY", direction: 1 }, axisB: { axis: "MEANING", direction: 1 }, semanticTheme: "MY_OWN_VALUES", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "남들이 좋다고 하는 답보다 자기에게 왜 중요한지 납득되는 선택을 하고 싶은 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C094", axisA: { axis: "AUTONOMY", direction: 1 }, axisB: { axis: "PRACTICALITY", direction: 1 }, semanticTheme: "INDEPENDENT_REALIST", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "자기 방식대로 하고 싶어 하면서도 실제로 되는지 계산하지 않고 움직이는 사람은 아닌 모습으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C095", axisA: { axis: "DUTY", direction: 1 }, axisB: { axis: "CARE", direction: 1 }, semanticTheme: "RESPONSIBLE_CARE", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "사람을 챙기는 마음을 말로만 두지 않고 맡은 책임까지 실제로 지키려는 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
  { id: "C096", axisA: { axis: "EXPANSION", direction: 1 }, axisB: { axis: "STABILITY", direction: 1 }, semanticTheme: "GROW_WITH_BASE", group: "CHANGE_RECOVERY",
    contexts: GROUP_CONTEXTS.CHANGE_RECOVERY, sourceDescription: "더 크게 성장하고 싶어 하면서도 생활과 기반까지 무너뜨리고 싶지는 않은 사람으로 이어질 수 있습니다.", priority: 1, specificity: "CROSS_AXIS" },
];
