import type { FusionRule, FortuneRule, FusionKind, SemanticTag } from "./types";

const rule = (id: string, type: FusionRule["type"], kind: FusionKind, features: readonly string[], myeongliTag: SemanticTag,
  trait: FusionRule["trait"], domains: FusionRule["domains"], sharedTheme: string, insightSeed: string): FusionRule =>
  ({ id, type, kind, features, myeongliTag, trait, domains, sharedTheme, insightSeed });

/** Explicit semantic compatibility. No fuzzy matching or every-feature pairing. */
export function semanticConnection(kind: FusionKind, from: SemanticTag, to: SemanticTag): boolean {
  if (kind === "overlap") return (from === to && from !== "expression-gap") || (from === "precision" && to === "decisive-correction");
  if (kind === "complement") return from === "expression-gap" && to === "expression";
  return [
    "solitude:sociability", "mobility:consistency", "consistency:experimentation",
    "consistency:experience-spending", "intimate-attraction:reserved-affection", "learning:practical-learning",
  ].includes(`${from}:${to}`);
}

// Each row references an existing trait, not a type-letter stereotype. New short
// seeds normalize the interaction; no V3 report prose or MBTI DB is rewritten.
export const FUSION_RULES: readonly FusionRule[] = [
  rule("entj-wealth", "ENTJ", "overlap", ["ten_god_pian_cai", "ten_god_zheng_cai"], "wealth", ["money", "high_earning_orientation", "wealth"], ["money", "success/fortune"], "결과를 돈으로 남기려는 마음",
    "잘했다는 말도 좋지만, 그래서 내 몫이 얼마나 커졌는지가 궁금합니다. 돈 이야기를 피하기보다 실력에 맞는 값을 받고 싶은 사람입니다."),
  rule("entj-pressure", "ENTJ", "overlap", ["ten_god_qi_sha"], "leadership", ["identity", "commanding_goal_builder", "leadership"], ["work", "strengths", "identity"], "급할수록 앞에 서는 사람",
    "다들 우물쭈물하면 결국 내가 순서를 정하고 있습니다. 급한 순간에 더 또렷해지는 힘이 있지만, 쉬는 날까지 지휘할 필요는 없습니다."),
  rule("entj-needle", "ENTJ", "overlap", ["sinsal_hyeonchim"], "precision", ["thinkingStyle", "fast_decisive_filter", "decisive-correction"], ["work", "strengths", "weaknesses"], "보이는 오류를 그냥 두지 않는 사람",
    "오류를 보는 순간 수정안까지 머릿속에 떠오릅니다. 본인은 빨리 해결한 것뿐인데, 상대에게는 말이 꽤 날카롭게 들릴 때가 있습니다."),
  rule("entj-alone", "ENTJ", "contrast", ["twelve_sinsal_hwagae"], "solitude", ["identity", "public_presence_private_distance", "sociability"], ["identity", "relationships"], "앞에 서도 혼자 정리하는 시간",
    "사람들 앞에서는 결론을 이끌지만 중요한 판단 전에는 혼자 있고 싶습니다. 밖에서 보이는 자신감 뒤에, 조용히 생각을 정리하는 시간이 있습니다."),
  rule("intj-inquiry", "INTJ", "overlap", ["ten_god_pian_yin", "sinsal_gwimun"], "inquiry", ["thinkingStyle", "system_first_thinking", "inquiry"], ["study", "identity", "strengths"], "끝까지 납득하고 싶은 사람",
    "다들 이해했다며 넘어가도 혼자 질문 하나가 남습니다. 설명이 앞뒤로 맞아떨어져야 비로소 마음이 놓입니다."),
  rule("intj-charm", "INTJ", "contrast", ["sinsal_hongyeom"], "intimate-attraction", ["love", "slow_high_standard_love", "reserved-affection"], ["love"], "다정함과 관계 결정의 다른 속도",
    "대화는 다정했는데 관계의 문은 아직 천천히 여는 중입니다. 상대는 벌써 가까워졌다고 느끼고, 본인은 이제부터 알아보는 단계입니다."),
  rule("intj-money", "INTJ", "overlap", ["ten_god_zheng_cai"], "consistency", ["money", "cashflow_system_design", "consistency"], ["money"], "돈도 눈에 보이게 정리",
    "머릿속 계산만으로는 마음이 안 놓입니다. 어디에 얼마가 남는지 보일 때 돈 걱정도 조용해집니다."),
  rule("intp-inquiry", "INTP", "overlap", ["sinsal_gwimun", "ten_god_pian_yin"], "inquiry", ["thinkingStyle", "why_question_loop", "inquiry"], ["study", "identity", "strengths"], "질문이 질문을 부르는 몰입",
    "하나만 찾아보려다 관련 글을 다섯 개쯤 열어놓습니다. 답을 아는 것보다 왜 그런지 납득하는 일이 더 재미있습니다."),
  rule("intp-space", "INTP", "overlap", ["ten_god_bijian"], "autonomy", ["love", "freedom_based_attachment", "autonomy"], ["love", "relationships"], "가까워도 남겨두는 자기 자리",
    "좋아하는 사람이어도 하루의 모든 틈을 채워주길 바라지는 않습니다. 혼자 몰입할 시간을 존중받을 때 오히려 오래 마음을 줍니다."),
  rule("intp-expression", "INTP", "complement", ["distribution:output-low"], "expression-gap", ["communication", "topic_triggered_talk", "expression"], ["relationships", "identity"], "관심사가 여는 말문",
    "평소엔 조용한데 관심 있는 이야기가 나오면 말문이 열립니다. 하고 싶은 말이 없는 게 아니라, 내 이야기가 시작되는 문이 따로 있습니다."),
  rule("entp-rules", "ENTP", "contrast", ["ten_god_zheng_guan"], "consistency", ["thinkingStyle", "possibility_scanning", "experimentation"], ["work", "identity"], "책임은 지키고 방법은 바꾸고",
    "약속을 지켜야 한다는 건 압니다. 그런데 더 재미있고 빠른 방법이 보이면, 정해진 순서를 그대로 따르기가 영 심심합니다."),
  rule("entp-needle", "ENTP", "overlap", ["sinsal_hyeonchim"], "precision", ["thinkingStyle", "flaw_detection", "precision"], ["strengths", "work", "weaknesses"], "그럴듯한 말의 빈틈",
    "말은 멋진데 뭔가 앞뒤가 안 맞으면 바로 걸립니다. 다 같이 고개를 끄덕이는 순간에 혼자 질문을 던지는 편입니다."),
  rule("infj-depth", "INFJ", "overlap", ["ten_god_pian_yin", "sinsal_gwimun"], "inquiry", ["thinkingStyle", "private_analysis_loop", "inquiry"], ["identity", "study", "weaknesses"], "혼자 다시 읽는 한마디",
    "짧은 대화가 끝난 뒤에야 생각이 길어집니다. 남들은 잊은 말의 작은 차이를 혼자 다시 들여다보는 편입니다."),
  rule("infj-marriage", "INFJ", "overlap", ["twelve_sinsal_hwagae"], "solitude", ["marriage", "private_time_needed", "solitude"], ["marriage"], "함께 살아도 혼자 숨 쉬는 시간",
    "함께 있는 시간이 좋아도 혼자 조용해질 틈이 필요합니다. 말수가 줄었다고 마음까지 멀어진 건 아닙니다."),
  rule("infp-expression", "INFP", "overlap", ["ten_god_shi_shen"], "expression", ["study", "storytelling_learning", "expression"], ["study", "strengths"], "내 이야기로 바꿀 때 이해",
    "그대로 외우면 안 들어오던 말도 내 경험에 빗대면 선명해집니다. 설명하다 보면 남이 준 답이 아니라 내 이야기가 됩니다."),
  rule("infp-needle", "INFP", "overlap", ["sinsal_hyeonchim"], "precision", ["thinkingStyle", "contextual_truth_detection", "precision"], ["relationships", "weaknesses"], "부드러워도 그냥 안 넘어가는 말",
    "평소에는 넘어가도 말의 진심이 어긋나는 순간은 잘 알아챕니다. 부드러운 사람이 갑자기 날카로워졌다는 말을 듣는 이유입니다."),
  rule("enfj-help", "ENFJ", "overlap", ["ten_god_zheng_yin", "gwiin_cheoneul"], "help", ["identity", "compassionate_facilitator", "help"], ["relationships", "strengths", "work"], "도움이 다시 사람을 부르는 힘",
    "누가 막막해하면 방법만 알려주고 끝내기 어렵습니다. 그 사람이 해내는 모습까지 보고 싶고, 그런 마음이 좋은 사람을 곁에 남깁니다."),
  rule("enfj-expression", "ENFJ", "complement", ["distribution:output-low"], "expression-gap", ["communication", "eloquent_social_speech", "expression"], ["relationships", "work"], "사람 앞에서 열리는 표현",
    "혼자 생각할 때보다 사람 앞에서 이야기를 풀 때 말이 살아납니다. 막막해하는 사람의 마음을 대신 정리해주는 일이 표현의 통로가 됩니다."),
  rule("enfp-connection", "ENFP", "overlap", ["ten_god_pian_yin"], "inquiry", ["thinkingStyle", "ne_connection_thinking", "inquiry"], ["identity", "work", "strengths"], "멀리 떨어진 생각을 잇는 재주",
    "친구 이야기에서 여행 장면이 떠오르고, 거기서 새 아이디어가 나옵니다. 남들에게는 뜬금없어 보여도 내 머릿속에서는 이미 이어져 있습니다."),
  rule("enfp-expression", "ENFP", "complement", ["distribution:output-low"], "expression-gap", ["identity", "expressive_authenticity", "expression"], ["identity", "relationships", "love"], "반응하며 살아나는 표현",
    "혼자서는 정리 안 되던 마음도 좋아하는 사람 앞에서는 표정과 말로 나옵니다. 표현의 힘을 꼭 혼자 짜낼 필요는 없는 사람입니다."),
  rule("enfp-alone", "ENFP", "contrast", ["twelve_sinsal_hwagae", "ten_god_pian_yin"], "solitude", ["identity", "people_centered_energy", "sociability"], ["identity", "relationships"], "사람을 좋아해도 혼자 충전",
    "모임에서는 신나게 이야기하고 집에 오면 아무 말도 하기 싫습니다. 사람에게서 힘을 얻는 마음과 혼자 깊어지는 마음이 같이 있습니다."),
  rule("enfp-budget", "ENFP", "contrast", ["ten_god_zheng_cai"], "consistency", ["money", "experience_spending", "experience-spending"], ["money"], "모으고 싶은 나와 가보고 싶은 나",
    "돈을 차곡차곡 남기고 싶은데 재미있는 여행 공지는 또 그냥 못 넘깁니다. 안정도 경험도 포기하기 싫어서 결제창 앞에서 생각이 많아집니다."),
  rule("istj-needle", "ISTJ", "overlap", ["sinsal_hyeonchim"], "precision", ["thinkingStyle", "efficient_error_detection", "precision"], ["work", "strengths", "study"], "그냥 못 넘기는 작은 오류",
    "다들 괜찮다며 넘긴 자료에서 혼자 숫자 하나가 걸립니다. 어긋난 순서가 보이면 고치기 전까지 마음이 안 놓이는 편입니다."),
  rule("istj-love", "ISTJ", "overlap", ["ten_god_zheng_guan"], "consistency", ["love", "trust_first_love", "consistency"], ["love", "relationships"], "지킨 약속으로 쌓이는 마음",
    "큰 말보다 약속한 시간에 오는 사람이 좋습니다. 본인도 챙겨주고 기억하는 것으로 마음을 다 전했다고 생각하는 편입니다."),
  rule("istj-marriage", "ISTJ", "overlap", ["ten_god_zheng_cai"], "consistency", ["marriage", "fixed_role_and_budget", "consistency"], ["marriage"], "함께 사는 일의 빈칸",
    "누가 할지 정하지 않은 집안일이 자꾸 눈에 들어옵니다. 사랑해도 생활의 약속까지 저절로 맞아지지는 않는다고 느끼는 편입니다."),
  rule("isfj-learning", "ISFJ", "overlap", ["ten_god_zheng_yin"], "learning", ["thinkingStyle", "sensory_memory_judgment", "learning"], ["study", "strengths"], "기억이 다음 사람을 돕는 힘",
    "한번 겪은 실수와 도움이 됐던 방법을 잘 기억합니다. 다시 비슷한 일이 생기면 누구보다 조용히 준비를 챙깁니다."),
  rule("isfj-love", "ISFJ", "overlap", ["ten_god_zheng_guan"], "consistency", ["love", "slow_trust_love", "consistency"], ["love", "relationships"], "조금씩 확인하는 신뢰",
    "좋다는 말 한 번보다 며칠 뒤에도 같은 태도인지 봅니다. 마음이 열리는 속도는 느려도 한번 믿으면 쉽게 가볍게 대하지 않습니다."),
  rule("estj-needle", "ESTJ", "overlap", ["sinsal_hyeonchim"], "precision", ["communication", "corrective_feedback", "precision"], ["work", "weaknesses"], "틀린 곳부터 말하는 습관",
    "수고했다는 말보다 틀린 곳부터 눈에 들어옵니다. 고치면 끝날 일이라고 생각했는데 상대는 그 말투를 오래 기억하기도 합니다."),
  rule("estj-status", "ESTJ", "overlap", ["twelve_sinsal_jangseong"], "leadership", ["identity", "responsible_operator", "leadership"], ["work", "success/fortune", "strengths"], "맡기면 끝을 보는 사람",
    "사람들이 망설일 때 일을 끝까지 맡는 쪽입니다. 덕분에 존재감이 커지지만, 어느새 모든 일이 내 차지가 되면 억울합니다."),
  rule("esfj-help", "ESFJ", "overlap", ["gwiin_cheoneul", "ten_god_zheng_yin"], "help", ["identity", "warm_provider_identity", "help"], ["relationships", "strengths"], "사람을 챙겨서 남는 사람복",
    "누가 잘 못 끼고 있는지 먼저 눈에 들어옵니다. 챙긴 기억이 쌓여서 나도 도움이 필요할 때 부를 사람이 생기는 쪽입니다."),
  rule("esfj-alone", "ESFJ", "contrast", ["twelve_sinsal_hwagae"], "solitude", ["identity", "social_adaptation_engine", "sociability"], ["identity"], "잘 어울리는 나도 쉬어야 합니다",
    "어디서든 잘 맞춰주는 사람처럼 보여도 혼자 조용해질 시간이 필요합니다. 모임을 즐기는 것과 늘 사람 곁에 있고 싶은 건 다른 마음입니다."),
  rule("istp-study", "ISTP", "overlap", ["ten_god_shi_shen"], "practical-learning", ["study", "hands_on_learning", "practical-learning"], ["study", "strengths", "work"], "손으로 만져야 잡히는 답",
    "설명을 오래 듣는 것보다 한번 직접 만져보는 게 빠릅니다. 어디가 안 되는지 손으로 확인할 때 생각도 또렷해집니다."),
  rule("istp-love", "ISTP", "overlap", ["ten_god_bijian", "sinsal_yangin"], "autonomy", ["love", "freedom_love_boundary", "autonomy"], ["love", "relationships"], "좋아해도 숨 쉴 자리는 필요",
    "가까워졌다고 모든 시간을 보고하고 싶지는 않습니다. 간섭이 줄어들면 오히려 먼저 다가갈 마음이 생기는 편입니다."),
  rule("istp-marriage", "ISTP", "overlap", ["twelve_sinsal_hwagae"], "solitude", ["marriage", "space_based_marriage", "solitude"], ["marriage"], "같은 집에서도 각자의 몰입",
    "한집에 있어도 각자 좋아하는 일에 빠질 시간이 있으면 편합니다. 옆에서 말없이 자기 일을 해도 사이가 멀어진 건 아닙니다."),
  rule("isfp-love", "ISFP", "contrast", ["sinsal_hongyeom"], "intimate-attraction", ["love", "slow_open_romantic", "reserved-affection"], ["love", "relationships"], "조심스러운 시작과 가까운 온기",
    "처음에는 마음을 많이 말하지 않습니다. 그런데 가까워지면 상대의 취향을 기억한 작은 챙김에서 매력이 더 또렷해집니다."),
  rule("isfp-needle", "ISFP", "overlap", ["sinsal_hyeonchim"], "precision", ["thinkingStyle", "sensory_truth_detector", "precision"], ["identity", "strengths"], "말보다 먼저 보이는 작은 차이",
    "괜찮다는 말보다 표정의 작은 변화가 먼저 보입니다. 겉으로 크게 말하지 않아도 그냥 지나치지 않는 감각이 있습니다."),
  rule("estp-needle", "ESTP", "overlap", ["sinsal_hyeonchim"], "precision", ["thinkingStyle", "se_now_data", "precision"], ["work", "strengths"], "현장에서 먼저 잡는 반응",
    "상대가 괜찮다고 해도 손이 멈춘 지점은 놓치지 않습니다. 긴 설명보다 지금 보이는 반응에 맞춰 바꾸는 쪽입니다."),
  rule("estp-study", "ESTP", "contrast", ["ten_god_zheng_yin"], "learning", ["study", "experiential_learning", "practical-learning"], ["study"], "먼저 해보고 돌아오는 공부",
    "알아야 안심되는 마음과 일단 해보고 싶은 마음이 같이 있습니다. 직접 부딪힌 뒤 다시 읽으면 처음엔 지루하던 설명도 달라 보입니다."),
  rule("esfp-charm", "ESFP", "overlap", ["sinsal_dohwa"], "first-attraction", ["identity", "spotlight_identity", "first-attraction"], ["identity", "strengths", "success/fortune"], "반응이 오면 더 빛나는 사람",
    "사람들이 반응해주면 표정부터 살아납니다. 가만히 준비할 때보다 직접 보여주는 자리에서 매력이 더 잘 보이는 편입니다."),
  rule("esfp-expression", "ESFP", "complement", ["distribution:output-low"], "expression-gap", ["communication", "honest_self_disclosure", "expression"], ["relationships", "identity"], "나누면서 생기는 말",
    "정리된 말이 있어야만 이야기를 시작하는 건 아닙니다. 먼저 웃고 내 이야기를 나누다 보면 마음이 밖으로 나오는 길이 생깁니다."),
];

export const FORTUNE_RULES: readonly FortuneRule[] = [
  { id: "wealth-and-name", theme: "wealth", allOf: [["ten_god_pian_cai", "ten_god_zheng_cai"], ["ten_god_qi_sha"], ["twelve_sinsal_jangseong"], ["twelve_sinsal_banan"]], seed: "돈과 이름을 같이 노려볼 만한 힘이 있습니다." },
  { id: "recognized-place", theme: "status/honor", allOf: [["twelve_sinsal_jangseong"], ["twelve_sinsal_banan"]], seed: "앞에 서고 인정받는 힘이 있습니다." },
  { id: "lead-under-pressure", theme: "leadership", allOf: [["ten_god_qi_sha"], ["twelve_sinsal_jangseong"]], seed: "급한 순간에 중심을 잡고 사람을 이끄는 힘이 있습니다." },
  { id: "people-support", theme: "helpers/people-luck", allOf: [["gwiin_cheoneul"], ["gwiin_cheondeok", "gwiin_woldeok"]], seed: "사람복이 있습니다. 막힌 일을 함께 풀어주는 도움의 패가 겹칩니다." },
  { id: "two-charms", theme: "charm", allOf: [["sinsal_dohwa"], ["sinsal_hongyeom"]], seed: "첫눈에 남는 매력과 가까워질수록 커지는 매력을 함께 가졌습니다." },
  { id: "lasting-assets", theme: "accumulation", allOf: [["gwiin_jaego"], ["ten_god_zheng_cai", "ten_god_shi_shen"]], seed: "해낸 일이 돈과 기술, 경험으로 남는 축적의 좋은 패가 있습니다." },
  { id: "learning-depth", theme: "learning", allOf: [["ten_god_zheng_yin"], ["gwiin_munchang", "gwiin_hakdang"]], seed: "배운 것이 흩어지지 않고 내 실력으로 쌓이는 힘이 있습니다." },
  { id: "show-your-thought", theme: "expression", allOf: [["ten_god_shi_shen", "ten_god_shang_guan"], ["gwiin_munchang"]], seed: "이해한 것을 내 말과 작품으로 보여주는 좋은 힘이 있습니다." },
  { id: "outside-opportunity", theme: "mobility/opportunity", allOf: [["twelve_sinsal_yeokma"], ["ten_god_pian_cai"]], seed: "바깥에서 만나는 사람과 새로운 장소가 기회의 문이 되는 좋은 패입니다." },
];
