import type { TypeAnnotationManifest } from "./mbtiSemanticCore";

export const SJ_ANNOTATIONS = {
  ISTJ: {
    "identity:verified_order_keeper": ["CHANGE_ORIENTATION", -2, "STRUCTURE_STYLE", 1],
    "identity:adult_like_responsibility": ["DUTY", 2, "PERSISTENCE", 1],
    "identity:quiet_stability": ["ENERGY_DIRECTION", -1, "STABILITY", 2],
    "identity:routine_sensitive": ["STRUCTURE_STYLE", 2, "CHANGE_ORIENTATION", -1],
    "identity:private_inner_world": ["ENERGY_DIRECTION", -2],
    "identity:conservative_filter": ["CHANGE_ORIENTATION", -2, "PRACTICALITY", 1],
    "thinkingStyle:past_data_decision": ["CHANGE_ORIENTATION", -1, "PRACTICALITY", 1],
    "thinkingStyle:efficient_error_detection": ["PRECISION", 2, "PRACTICALITY", 1],
    "thinkingStyle:manual_mastery": ["LEARNING", 1, "PRECISION", 1],
    "thinkingStyle:detail_memory": ["PRECISION", 1],
    "thinkingStyle:narrow_but_deep_focus": ["DEPTH", 2, "PERSISTENCE", 1],
    "career:public_institution_fit": ["STRUCTURE_STYLE", 1, "DUTY", 1],
    "career:precision_profession_fit": "UNSCORED_REFERENCE",
    "career:teacher_favored_student": ["DUTY", 1, "STRUCTURE_STYLE", 1],
    "career:long_term_income_builder": "UNSCORED_REFERENCE",
    "career:stable_independent_worker": ["ENERGY_DIRECTION", -2, "DUTY", 1],
    "career:avoid_chaotic_creative_work": ["STRUCTURE_STYLE", 1, "STABILITY", 1],
    "career:process_quality_operator": ["PRECISION", 2, "STRUCTURE_STYLE", 1],
    "workplace:rule_following_reliability": ["DUTY", 2, "STRUCTURE_STYLE", 1],
    "workplace:time_promise_strictness": ["DUTY", 1, "PRECISION", 1],
    "workplace:controlled_authority_risk": ["STRUCTURE_STYLE", 1, "BOUNDARY", 1],
    "workplace:silent_frustration_explosion": ["COMMUNICATION_STYLE", -1],
    "workplace:instant_error_correction": ["PRECISION", 1, "ACTION_TEMPO", 1],
    "workplace:clear_instruction_boundary": ["STRUCTURE_STYLE", 1, "PERSISTENCE", 1],
    "money:stable_income_preference": ["STABILITY", 2, "DUTY", 1],
    "money:cost_and_contract_mind": ["RESOURCE_SENSE", 1, "STRUCTURE_STYLE", 1, "PRECISION", 1],
    "money:status_realism": ["STATUS_DRIVE", 1, "PRACTICALITY", 1, "STABILITY", 1],
    "money:budget_and_reserve_plan": ["RESOURCE_SENSE", 2, "STRUCTURE_STYLE", 1, "STABILITY", 1],
    "money:family_responsibility_spending": ["DUTY", 2, "CARE", 1],
    "money:informal_money_deal_risk": ["STRUCTURE_STYLE", 2, "BOUNDARY", 1],
    "investment:long_term_accumulation_fit": ["STRUCTURE_STYLE", 1, "RESOURCE_SENSE", 1],
    "investment:avoid_emotional_trading": "ADVICE",
    "investment:verified_method_preference": ["CHANGE_ORIENTATION", -1, "PRECISION", 1],
    "investment:scheduled_review_rule": "ADVICE",
    "investment:family_finance_boundary": ["DUTY", 1, "STABILITY", 1],
    "study:traditional_exam_strength": ["STRUCTURE_STYLE", 1, "LEARNING", 1],
    "study:rote_plus_structure": ["LEARNING", 1],
    "study:manual_learning_curve": ["LEARNING", 1, "PRECISION", 1],
    "study:new_type_adaptation_drill": ["CHANGE_ORIENTATION", -1, "STRUCTURE_STYLE", 1],
    "study:perfectionism_recovery_limit": ["PERSISTENCE", 1, "PRECISION", 1],
    "love:trust_first_love": ["DUTY", 2, "STABILITY", 1],
    "love:reserved_affection": ["CARE", 1, "ENERGY_DIRECTION", -1],
    "love:slow_start_relationship": ["ACTION_TEMPO", -2, "STRUCTURE_STYLE", 1],
    "marriage:stable_household_builder": ["STABILITY", 2, "STRUCTURE_STYLE", 1, "RESOURCE_SENSE", 1],
    "marriage:spouse_control_risk": ["STRUCTURE_STYLE", 2, "BOUNDARY", 1],
    "marriage:fixed_role_and_budget": ["STRUCTURE_STYLE", 2, "RESOURCE_SENSE", 1],
    "marriage:quiet_affection_routine": ["DUTY", 1],
    "marriage:change_buffer_marriage": ["CHANGE_ORIENTATION", -1, "STABILITY", 1],
    "parenting:diligent_responsible_parent": ["DUTY", 2, "STABILITY", 1],
    "parenting:practical_success_parenting": ["STATUS_DRIVE", 1, "STABILITY", 1],
    "parenting:independent_child_conflict": "UNSCORED_REFERENCE",
    "child:responsible_child": ["DUTY", 2, "STRUCTURE_STYLE", 1],
    "child:small_circle_child": ["RELATION_STYLE", -2, "STABILITY", 1],
    "relationships:hard_boundary_after_disrespect": ["BOUNDARY", 2],
    "relationships:few_but_stable_bonds": ["RELATION_STYLE", -2, "STABILITY", 1],
    "relationships:self_withdrawal_when_unready": ["DUTY", 1, "RELATION_STYLE", -1],
    "communication:reserved_directness": ["COMMUNICATION_STYLE", -1],
    "communication:apology_difficulty": "UNSCORED_REFERENCE",
    "strengths:execution_reliability": ["PERSISTENCE", 2, "DUTY", 1],
    "strengths:calm_under_procedure": ["STRUCTURE_STYLE", 1, "PRECISION", 1],
    "risks:rigidity_under_change": ["CHANGE_ORIENTATION", -2],
    "risks:emotional_blind_spot": "UNSCORED_REFERENCE",
    "risks:prejudice_from_experience": ["DECISION_STYLE", 1, "CHANGE_ORIENTATION", -1],
    "growth:feedback_order_upgrade": "ADVICE",
    "growth:controlled_flexibility": "ADVICE",
  },
  ISFJ: {
    "identity:quiet_protector": ["CARE", 2, "BOUNDARY", 1],
    "identity:warm_but_hard_to_define": ["CARE", 1, "BOUNDARY", 1, "DUTY", 1],
    "identity:loyal_inner_circle": ["RELATION_STYLE", -1, "CARE", 2],
    "identity:duty_first_self_image": ["DUTY", 2],
    "identity:modest_reliability": ["ENERGY_DIRECTION", -1, "DUTY", 1],
    "identity:inner_steel": ["PERSISTENCE", 2, "DUTY", 1],
    "thinkingStyle:sensory_memory_judgment": ["PRACTICALITY", 1, "PRECISION", 1],
    "thinkingStyle:detail_first_attention": ["PRECISION", 2, "ACTION_TEMPO", -1],
    "thinkingStyle:social_feeling_scanner": ["SOCIAL_ATTUNEMENT", 2],
    "thinkingStyle:suppressed_inner_logic": ["DUTY", 1, "ENERGY_DIRECTION", -1, "STABILITY", 1],
    "career:service_stability_career": ["STABILITY", 1, "MEANING", 1, "CARE", 1],
    "career:practical_helper_work": ["PRACTICALITY", 2, "CARE", 1],
    "career:structured_care_profession": ["STRUCTURE_STYLE", 1, "CARE", 1],
    "career:behind_the_scenes_worker": ["PRECISION", 1, "ENERGY_DIRECTION", -1],
    "career:stable_org_fit": ["STABILITY", 2, "RISK_STYLE", -1],
    "career:memory_observation_practitioner": ["PRECISION", 1, "PRACTICALITY", 1],
    "career:care_operations_income": ["CARE", 1, "PRECISION", 1],
    "workplace:guideline_micro_manager": ["STRUCTURE_STYLE", 2, "STABILITY", 1],
    "workplace:conflict_avoidance_at_work": ["COMMUNICATION_STYLE", -2, "STABILITY", 1],
    "workplace:work_ethic_overload": ["DUTY", 2, "PERSISTENCE", 1],
    "workplace:quiet_reputation_worker": ["STATUS_DRIVE", 1, "DUTY", 1],
    "workplace:formal_culture_fit": ["CHANGE_ORIENTATION", -1, "STRUCTURE_STYLE", 1],
    "workplace:recognition_and_boundary": ["CARE", 1, "PRECISION", 1, "COMMUNICATION_STYLE", -1],
    "money:frugal_stable_money": ["RESOURCE_SENSE", 2, "STABILITY", 1],
    "money:service_income_fit": "UNSCORED_REFERENCE",
    "money:overgiving_money_leak": ["CARE", 2],
    "money:small_saving_persistence": ["RESOURCE_SENSE", 2, "PERSISTENCE", 1, "STABILITY", 1],
    "money:care_labor_underpricing": ["CARE", 1],
    "money:family_budget_boundary": ["CARE", 2, "DUTY", 1],
    "investment:low_risk_preference": ["RISK_STYLE", -2, "STABILITY", 1],
    "investment:evidence_based_saving": ["RESOURCE_SENSE", 1, "PRACTICALITY", 1],
    "investment:family_safety_priority": ["STABILITY", 2, "CARE", 1],
    "investment:independent_check_needed": "UNSCORED_REFERENCE",
    "investment:loss_tolerance_boundary": ["STABILITY", 1, "DUTY", 1],
    "study:dutiful_study_rhythm": ["DUTY", 1, "PERSISTENCE", 1, "STRUCTURE_STYLE", 1],
    "study:mindmap_connection_need": ["LEARNING", 1],
    "study:safe_school_profile": ["DUTY", 2, "STRUCTURE_STYLE", 1],
    "study:exam_anxiety_scope_lock": ["PRECISION", 1, "DUTY", 1],
    "study:confidence_recall_training": ["LEARNING", 1, "ACTION_TEMPO", -1],
    "love:slow_trust_love": ["ACTION_TEMPO", -2, "DUTY", 1, "CARE", 1],
    "love:devoted_partner": ["CARE", 2, "SOCIAL_ATTUNEMENT", 1],
    "love:low_request_high_duty": ["DUTY", 1, "COMMUNICATION_STYLE", -1],
    "love:gentle_speech_love": ["COMMUNICATION_STYLE", -2, "CARE", 1],
    "marriage:home_stability_builder": ["DUTY", 1, "STRUCTURE_STYLE", 1, "STABILITY", 1],
    "marriage:traditional_family_role": ["CHANGE_ORIENTATION", -1, "DUTY", 1],
    "marriage:gratitude_needed_marriage": ["CARE", 1, "STATUS_DRIVE", 1],
    "marriage:care_reciprocity_rule": ["CARE", 2],
    "marriage:family_money_boundary": ["CARE", 2],
    "parenting:structured_home_parent": ["STRUCTURE_STYLE", 2, "STABILITY", 1],
    "parenting:protective_overinvolvement": ["CARE", 2],
    "parenting:surface_empathy_parenting": ["SOCIAL_ATTUNEMENT", 1],
    "parenting:self_sacrificing_parent": ["DUTY", 1, "CARE", 1],
    "child:model_student_child": ["DUTY", 1, "STRUCTURE_STYLE", 1],
    "child:sensitive_child": "UNSCORED_REFERENCE",
    "child:stable_friendship_child": ["RELATION_STYLE", -1, "CARE", 1],
    "child:practical_imagination_child": ["PRACTICALITY", 1, "CREATION", 1],
    "relationships:hard_to_enter_reliable_once_in": ["ACTION_TEMPO", -1, "CARE", 2],
    "relationships:memory_based_affection": ["CARE", 1, "PRECISION", 1],
    "relationships:secret_keeper": ["BOUNDARY", 1, "DUTY", 1],
    "relationships:relationship_stress_absorber": ["COMMUNICATION_STYLE", -1, "STABILITY", 1],
    "communication:careful_word_choice": ["CARE", 1, "COMMUNICATION_STYLE", -1],
    "communication:small_talk_support": ["SOCIAL_ATTUNEMENT", 1],
    "communication:listen_more_than_speak": ["ENERGY_DIRECTION", -1, "SOCIAL_ATTUNEMENT", 1],
    "strengths:sharp_memory_observation": ["PRECISION", 2, "CARE", 1],
    "strengths:loyal_responsible_execution": ["DUTY", 2, "PERSISTENCE", 1, "PRACTICALITY", 1],
    "strengths:competent_helper": ["CARE", 2, "PRACTICALITY", 1],
    "strengths:role_model_drive": ["DUTY", 1, "STATUS_DRIVE", 1],
    "risks:tradition_lock": ["CHANGE_ORIENTATION", -2, "STABILITY", 1],
    "risks:personalized_criticism": "UNSCORED_REFERENCE",
    "risks:burnout_from_helping": ["CARE", 2],
    "risks:perfectionism_distraction": ["PRECISION", 2],
    "risks:social_complexity_overwhelm": ["STABILITY", 1, "CHANGE_ORIENTATION", -1],
    "growth:learn_to_say_no": "ADVICE",
    "growth:express_feelings_more": ["CARE", 1],
    "growth:controlled_newness": "ADVICE",
    "growth:lighter_rest": "ADVICE",
  },
  ESTJ: {
    "identity:responsible_operator": ["DUTY", 2, "PERSISTENCE", 1],
    "identity:order_and_standard": ["STRUCTURE_STYLE", 2, "BOUNDARY", 1],
    "identity:practical_realist": ["PRACTICALITY", 2],
    "identity:traditional_stability": ["CHANGE_ORIENTATION", -2, "STABILITY", 1],
    "identity:assertive_self_confidence": ["DECISION_STYLE", 1, "LEARNING", 1],
    "identity:work_over_emotion": ["DUTY", 1, "GOAL_DRIVE", 1],
    "thinkingStyle:te_fact_execution": ["DECISION_STYLE", 1, "PRACTICALITY", 1, "ACTION_TEMPO", 1],
    "thinkingStyle:si_verified_process": ["CHANGE_ORIENTATION", -2, "STRUCTURE_STYLE", 1],
    "thinkingStyle:efficiency_filter": ["PRACTICALITY", 2, "GOAL_DRIVE", 1],
    "thinkingStyle:weak_fi_emotional_blindspot": ["DUTY", 1, "PRACTICALITY", 1],
    "thinkingStyle:selective_flexibility": ["ADAPTABILITY", 1, "PRACTICALITY", 1],
    "career:management_leadership_fit": ["LEADERSHIP", 2, "STRUCTURE_STYLE", 1, "GOAL_DRIVE", 1],
    "career:public_order_career": ["STRUCTURE_STYLE", 1, "DUTY", 1],
    "career:law_finance_fit": ["PRECISION", 1, "DUTY", 1],
    "career:education_with_structure": ["STRUCTURE_STYLE", 1, "GOAL_DRIVE", 1],
    "career:healthcare_authority_fit": "UNSCORED_REFERENCE",
    "career:operations_scale_manager": ["LEADERSHIP", 1, "RESOURCE_SENSE", 1, "STRUCTURE_STYLE", 1],
    "workplace:clear_expectations": ["COMMUNICATION_STYLE", 2, "STRUCTURE_STYLE", 1],
    "workplace:micro_management_precision": ["PRECISION", 2, "STRUCTURE_STYLE", 1],
    "workplace:delegation_difficulty": ["DUTY", 1, "BOUNDARY", 1],
    "workplace:hierarchy_comfort": ["STRUCTURE_STYLE", 2, "DUTY", 1],
    "workplace:honesty_and_work_ethic": ["DUTY", 2, "BOUNDARY", 1],
    "workplace:collaborative_but_demanding": ["RELATION_STYLE", 1, "GOAL_DRIVE", 1],
    "workplace:delegation_with_feedback": ["PRECISION", 1, "COMMUNICATION_STYLE", 1],
    "money:economic_stability_drive": ["GOAL_DRIVE", 1, "RESOURCE_SENSE", 1, "STABILITY", 1],
    "money:profit_loss_calculation": ["RESOURCE_SENSE", 2, "PRACTICALITY", 1],
    "money:status_and_security": ["STATUS_DRIVE", 2, "STABILITY", 1],
    "money:operations_income_engine": ["STRUCTURE_STYLE", 1, "RESOURCE_SENSE", 1, "LEADERSHIP", 1],
    "money:asset_control_strength": ["RESOURCE_SENSE", 2, "STRUCTURE_STYLE", 1],
    "money:performance_status_spending": ["STATUS_DRIVE", 2, "DUTY", 1],
    "investment:conservative_asset_style": ["RISK_STYLE", -1, "RESOURCE_SENSE", 1, "STABILITY", 1],
    "investment:risk_control_priority": ["RISK_STYLE", -1, "STRUCTURE_STYLE", 1],
    "investment:objective_metric_rule": ["PRECISION", 1, "RESOURCE_SENSE", 1],
    "investment:concentration_control": ["DECISION_STYLE", 1, "RESOURCE_SENSE", 1],
    "investment:authority_pressure_risk": ["STRUCTURE_STYLE", 1, "BOUNDARY", 1],
    "study:exam_structure_advantage": ["STRUCTURE_STYLE", 1, "LEARNING", 1],
    "study:technical_problem_solving": ["PRACTICALITY", 2],
    "study:routine_and_rule_learning": ["STRUCTURE_STYLE", 2, "PERSISTENCE", 1],
    "study:flexible_concept_review": ["GOAL_DRIVE", 1, "ACTION_TEMPO", 1],
    "study:pace_and_rest_control": ["STRUCTURE_STYLE", 1, "GOAL_DRIVE", 1],
    "love:stable_long_term_love": ["STABILITY", 2, "DUTY", 1],
    "love:love_through_action": ["DUTY", 1, "PRACTICALITY", 1],
    "love:direct_expectations_in_love": ["COMMUNICATION_STYLE", 2],
    "love:traditional_role_pressure": ["CHANGE_ORIENTATION", -1, "STABILITY", 1],
    "marriage:structured_household": ["STRUCTURE_STYLE", 2, "STABILITY", 1],
    "marriage:reliable_partner": ["DUTY", 2, "PERSISTENCE", 1],
    "marriage:control_conflict_in_family": ["LEADERSHIP", 1, "STRUCTURE_STYLE", 1],
    "marriage:joint_finance_authority": ["RESOURCE_SENSE", 1, "STRUCTURE_STYLE", 1],
    "marriage:emotional_leadership_practice": ["PRACTICALITY", 1],
    "parenting:traditional_parenting": ["CHANGE_ORIENTATION", -1, "DUTY", 1],
    "parenting:clear_rules_parent": ["COMMUNICATION_STYLE", 2, "STRUCTURE_STYLE", 1],
    "parenting:realistic_adult_expectation": ["DUTY", 1, "PRACTICALITY", 1],
    "parenting:adolescent_flexibility_need": "ADVICE",
    "child:leader_child": ["LEADERSHIP", 2, "INITIATIVE", 1],
    "child:fair_rule_child": ["DUTY", 1, "STRUCTURE_STYLE", 1],
    "child:mature_hardworking_child": ["DUTY", 2],
    "child:sports_and_competition": ["COMPETITION", 2],
    "relationships:trust_by_reliability": ["DUTY", 2],
    "relationships:solution_first_relation": ["PRACTICALITY", 2, "CARE", 1],
    "relationships:boundary_by_standard": ["BOUNDARY", 2, "DECISION_STYLE", 1],
    "relationships:practical_support": ["PRACTICALITY", 1, "STABILITY", 1],
    "relationships:less_social_extrovert": ["ENERGY_DIRECTION", -1, "AUTONOMY", 1],
    "communication:direct_speech": ["COMMUNICATION_STYLE", 2],
    "communication:logic_over_emotional_appeal": ["PRACTICALITY", 1, "DECISION_STYLE", 1],
    "communication:corrective_feedback": ["COMMUNICATION_STYLE", 2, "PRECISION", 1],
    "communication:conflict_full_response": ["DECISION_STYLE", 2, "BOUNDARY", 1],
    "strengths:execution_power": ["GOAL_DRIVE", 2, "PERSISTENCE", 1, "STRUCTURE_STYLE", 1],
    "strengths:reliable_consistency": ["DUTY", 2, "STABILITY", 1],
    "strengths:early_problem_detection": ["PRECISION", 2, "PRACTICALITY", 1],
    "strengths:crisis_rationality": ["PRACTICALITY", 2, "ADAPTABILITY", 1],
    "risks:rigid_traditionalism": ["CHANGE_ORIENTATION", -2],
    "risks:controlling_tendency": ["STRUCTURE_STYLE", 2, "DUTY", 1],
    "risks:empathy_gap": ["PRACTICALITY", 1],
    "risks:workaholic_burnout": ["GOAL_DRIVE", 1, "DUTY", 1],
    "risks:status_bias": ["STATUS_DRIVE", 2, "STABILITY", 1],
    "growth:soften_directness": ["COMMUNICATION_STYLE", 1],
    "growth:practice_emotional_checkin": "ADVICE",
    "growth:allow_experiment": "ADVICE",
    "growth:delegate_with_trust": "ADVICE",
  },
  ESFJ: {
    "identity:social_adaptation_engine": ["SOCIAL_ATTUNEMENT", 2, "ADAPTABILITY", 1],
    "identity:warm_provider_identity": ["CARE", 2, "INITIATIVE", 1],
    "identity:belonging_first_mind": ["RELATION_STYLE", 2, "STATUS_DRIVE", 1, "STABILITY", 1],
    "identity:visible_emotion_radar": ["SOCIAL_ATTUNEMENT", 2],
    "identity:routine_loyalist": ["CHANGE_ORIENTATION", -2, "STRUCTURE_STYLE", 1],
    "identity:expressive_loyal_helper": ["CARE", 2, "EXPRESSION", 1],
    "thinkingStyle:practical_evidence_need": ["PRACTICALITY", 2, "STRUCTURE_STYLE", 1],
    "thinkingStyle:memory_over_understanding": ["LEARNING", 1, "STRUCTURE_STYLE", 1],
    "thinkingStyle:fe_si_file_cabinet": ["SOCIAL_ATTUNEMENT", 1, "PRECISION", 1],
    "thinkingStyle:weak_abstract_analysis": ["PRACTICALITY", 1],
    "thinkingStyle:quick_social_judgment": ["SOCIAL_ATTUNEMENT", 1, "DECISION_STYLE", 1],
    "career:service_helping_fit": ["CARE", 2],
    "career:structured_future_career": ["STABILITY", 1, "STRUCTURE_STYLE", 1, "CARE", 1],
    "career:organizational_relationship_advantage": ["SOCIAL_ATTUNEMENT", 2],
    "career:repeat_process_strength": ["STRUCTURE_STYLE", 1, "PRECISION", 1],
    "career:public_recognition_motivation": ["STATUS_DRIVE", 2],
    "career:relationship_service_revenue": ["CARE", 1, "SOCIAL_ATTUNEMENT", 1],
    "workplace:team_morale_builder": ["CARE", 1, "INITIATIVE", 1, "EXPRESSION", 1],
    "workplace:punctual_pressure": ["DUTY", 1, "STRUCTURE_STYLE", 1],
    "workplace:visible_leadership": ["LEADERSHIP", 1, "ENERGY_DIRECTION", 1],
    "workplace:perfectionist_completion": ["DUTY", 2, "PERSISTENCE", 1, "PRECISION", 1],
    "workplace:policy_alignment_need": ["STRUCTURE_STYLE", 2, "CHANGE_ORIENTATION", -1],
    "workplace:change_adaptation_limit": ["CHANGE_ORIENTATION", -1, "STABILITY", 1],
    "workplace:praise_boundary_balance": ["STATUS_DRIVE", 1, "DUTY", 1],
    "money:save_and_enjoy": ["RESOURCE_SENSE", 1, "RELATION_STYLE", 1, "STABILITY", 1],
    "money:status_over_money": ["STATUS_DRIVE", 2],
    "money:relationship_spending": ["CARE", 2, "RELATION_STYLE", 1],
    "money:service_community_income": ["CARE", 1, "RELATION_STYLE", 1],
    "money:approval_spending_risk": ["STATUS_DRIVE", 1, "CARE", 1],
    "money:event_family_budget_balance": ["CARE", 1, "DUTY", 1],
    "investment:stability_first_investment": ["RISK_STYLE", -1, "STABILITY", 2],
    "investment:social_proof_risk": ["RELATION_STYLE", 1],
    "investment:relationship_info_filter": ["RELATION_STYLE", 1, "STATUS_DRIVE", 1],
    "investment:family_budget_separation": ["CARE", 1],
    "investment:approval_bias_control": ["STATUS_DRIVE", 1, "STABILITY", 1],
    "study:rote_exam_strength": ["LEARNING", 1, "STRUCTURE_STYLE", 1],
    "study:practical_learning_path": ["PRACTICALITY", 2],
    "study:concept_linking_needed": "ADVICE",
    "study:solo_focus_boundary": ["RELATION_STYLE", 1, "ENERGY_DIRECTION", 1],
    "study:evaluation_anxiety_routine": ["STATUS_DRIVE", 1],
    "love:observing_then_devoted": ["ACTION_TEMPO", -1, "CARE", 2, "EXPRESSION", 1],
    "love:reciprocal_expression_need": ["EXPRESSION", 1, "RELATION_STYLE", 1],
    "love:care_based_romance": ["CARE", 2, "EXPRESSION", 1],
    "love:avoidant_partner_trigger": ["RELATION_STYLE", 1, "STABILITY", 1],
    "marriage:domestic_spouse_pattern": ["CARE", 1, "STRUCTURE_STYLE", 1, "STABILITY", 1],
    "marriage:traditional_role_expectation": ["CHANGE_ORIENTATION", -1, "DUTY", 1],
    "marriage:gratitude_maintenance": ["CARE", 1, "STATUS_DRIVE", 1],
    "marriage:event_and_care_budget": ["CARE", 1, "RELATION_STYLE", 1],
    "marriage:care_without_overreach": ["CARE", 2],
    "parenting:protective_parenting": ["CARE", 2, "STABILITY", 1],
    "parenting:authority_obedience_pressure": ["CHANGE_ORIENTATION", -1, "STRUCTURE_STYLE", 1],
    "parenting:covering_child_mistakes": ["CARE", 1, "STATUS_DRIVE", 1],
    "parenting:harmony_home_pressure": ["STABILITY", 2],
    "child:harmony_sensitive_child": ["SOCIAL_ATTUNEMENT", 2, "ADAPTABILITY", 1],
    "child:predictable_sequence_child": ["STRUCTURE_STYLE", 2, "STABILITY", 1],
    "child:helpful_friend_child": ["CARE", 2],
    "child:high_standard_child": ["PRECISION", 1, "GOAL_DRIVE", 1],
    "relationships:small_talk_bonding": ["RELATION_STYLE", 2],
    "relationships:inclusion_drive": ["CARE", 1, "RELATION_STYLE", 2],
    "relationships:loyalty_boundary": ["CARE", 1, "BOUNDARY", 1],
    "relationships:conservative_partner_preference": ["CHANGE_ORIENTATION", -1, "RELATION_STYLE", 1],
    "relationships:habitual_empathy": ["SOCIAL_ATTUNEMENT", 1],
    "communication:warm_positive_communication": "UNSCORED_REFERENCE",
    "communication:goal_process_instruction": ["STRUCTURE_STYLE", 1],
    "communication:belief_conflict_trigger": ["BOUNDARY", 1, "MEANING", 1],
    "communication:visible_reaction_style": ["EXPRESSION", 2],
    "strengths:practical_thinking": ["PRACTICALITY", 2],
    "strengths:active_expression": ["EXPRESSION", 2, "INITIATIVE", 1],
    "strengths:trust_drawing": ["RELATION_STYLE", 1, "SOCIAL_ATTUNEMENT", 1],
    "strengths:stress_relief_social": ["ENERGY_DIRECTION", 2, "RELATION_STYLE", 1],
    "risks:rejection_sensitivity": "UNSCORED_REFERENCE",
    "risks:rigidity_and_hasty_judgment": ["CHANGE_ORIENTATION", -1, "DECISION_STYLE", 1],
    "risks:need_for_gratitude": ["CARE", 1, "STATUS_DRIVE", 1],
    "risks:social_conformity_bias": ["RELATION_STYLE", 2],
    "risks:logical_partner_friction": "UNSCORED_REFERENCE",
    "growth:separate_care_from_control": "ADVICE",
    "growth:fact_check_before_support": "ADVICE",
    "growth:build_ti_checkpoint": "ADVICE",
    "growth:practice_change_in_small_steps": "ADVICE",
  },
} as const satisfies Record<string, TypeAnnotationManifest>;
