import type { TypeAnnotationManifest } from "./mbtiSemanticCore";

/** Explicit source-ID annotations of plainKo. Advice/unsupported concepts stay
 * unscored; source prose, type stereotypes and bridge hints are not copied here. */
export const NT_ANNOTATIONS = {
  ENTJ: {
    "identity:commanding_goal_builder": ["GOAL_DRIVE", 2, "LEADERSHIP", 2, "STRUCTURE_STYLE", 1],
    "identity:efficiency_order_maker": ["STRUCTURE_STYLE", 2, "INITIATIVE", 1],
    "identity:self_fulfilling_confidence": ["GOAL_DRIVE", 2, "PERSISTENCE", 1, "RISK_STYLE", 1],
    "identity:authority_through_competence": ["PRECISION", 1, "BOUNDARY", 1],
    "identity:public_presence_private_distance": ["STATUS_DRIVE", 1, "RELATION_STYLE", -1, "DEPTH", 1],
    "identity:future_change_leader": ["CHANGE_ORIENTATION", 2, "LEADERSHIP", 1],
    "thinkingStyle:te_ni_strategy": ["PRACTICALITY", 1, "STRATEGY", 2, "GOAL_DRIVE", 1],
    "thinkingStyle:criticism_as_growth": ["LEARNING", 1, "ADAPTABILITY", 1],
    "thinkingStyle:fast_decisive_filter": ["DECISION_STYLE", 2, "ACTION_TEMPO", 1],
    "thinkingStyle:time_attack_processing": ["ACTION_TEMPO", 2, "PRECISION", 1, "PERSISTENCE", 1],
    "thinkingStyle:future_obstacle_logic": ["STRATEGY", 2, "PRECISION", 1],
    "career:executive_natural_habitat": ["COMMUNICATION_STYLE", 1, "LEADERSHIP", 1, "GOAL_DRIVE", 1],
    "career:ownership_priority": ["AUTONOMY", 2, "DUTY", 1],
    "career:large_team_manager": ["LEADERSHIP", 2, "STRUCTURE_STYLE", 1],
    "career:objective_performance_environment": ["GOAL_DRIVE", 2, "BOUNDARY", 1],
    "career:entrepreneurial_income_potential": ["GOAL_DRIVE", 2, "STRATEGY", 1],
    "career:workaholic_drive": ["GOAL_DRIVE", 2, "PERSISTENCE", 2],
    "career:scale_operator": ["STRUCTURE_STYLE", 2, "LEADERSHIP", 1, "EXPANSION", 1],
    "workplace:direct_feedback_leader": ["COMMUNICATION_STYLE", 2, "INITIATIVE", 1],
    "workplace:turnaround_reformer": ["CHANGE_ORIENTATION", 2, "INITIATIVE", 1],
    "workplace:equal_competence_team": ["COMPETITION", 1, "BOUNDARY", 1],
    "workplace:crisis_momentum": ["INITIATIVE", 2, "ADAPTABILITY", 1, "PERSISTENCE", 1],
    "workplace:democratic_until_decision": ["RELATION_STYLE", 1, "DECISION_STYLE", 2],
    "workplace:delegation_pressure_control": ["ACTION_TEMPO", 1, "LEADERSHIP", 1],
    "money:high_earning_orientation": ["GOAL_DRIVE", 2, "EXPANSION", 1],
    "money:capitalist_resource_logic": ["RESOURCE_SENSE", 2, "EXPANSION", 1],
    "money:low_financial_distress_pattern": ["GOAL_DRIVE", 1, "STRUCTURE_STYLE", 1, "INITIATIVE", 1],
    "money:spending_for_speed": ["ACTION_TEMPO", 2, "RESOURCE_SENSE", 1],
    "money:shared_money_authority": ["STRUCTURE_STYLE", 2, "DUTY", 1],
    "money:expansion_reserve_limit": ["EXPANSION", 2, "ACTION_TEMPO", 1, "OPPORTUNITY_SENSE", 1],
    "investment:strategic_risk_taking": ["RISK_STYLE", 2, "EXPANSION", 1, "STRATEGY", 1],
    "investment:objective_metric_investing": ["PRECISION", 1, "GOAL_DRIVE", 1],
    "investment:avoid_overleverage": ["EXPANSION", 1, "GOAL_DRIVE", 1],
    "investment:independent_risk_review": ["DECISION_STYLE", 2, "ACTION_TEMPO", 1, "DUTY", 1],
    "investment:scale_limit_before_push": ["EXPANSION", 2, "RISK_STYLE", 1],
    "study:high_achievement_study": ["GOAL_DRIVE", 2, "COMPETITION", 1, "STATUS_DRIVE", 1],
    "study:math_log_strategy": ["ACTION_TEMPO", 1, "GOAL_DRIVE", 1],
    "study:critique_and_debate_learning": ["CURIOSITY", 1, "DEPTH", 1, "LEARNING", 1],
    "study:score_project_management": ["STRUCTURE_STYLE", 2, "GOAL_DRIVE", 1],
    "study:speed_blindspot_review": ["ACTION_TEMPO", 2, "DECISION_STYLE", 1],
    "love:planned_intense_romance": ["INITIATIVE", 2, "STRUCTURE_STYLE", 1, "CHANGE_ORIENTATION", 1],
    "love:long_term_filter": ["STRATEGY", 1, "BOUNDARY", 1, "DECISION_STYLE", 1],
    "love:feedback_expectation_love": ["LEARNING", 1],
    "love:independence_support_need": ["AUTONOMY", 2, "GOAL_DRIVE", 1],
    "marriage:achievement_partner_marriage": ["GOAL_DRIVE", 2, "STRUCTURE_STYLE", 1],
    "marriage:dominance_marriage_risk": ["DECISION_STYLE", 1, "ACTION_TEMPO", 1],
    "marriage:multi_relationship_load": ["RELATION_STYLE", 2],
    "marriage:decision_authority_agreement": ["DECISION_STYLE", 2, "DUTY", 1],
    "marriage:work_family_boundary": ["GOAL_DRIVE", 2],
    "parenting:serious_responsible_parent": ["DUTY", 2, "STRUCTURE_STYLE", 1],
    "parenting:child_success_projection": ["GOAL_DRIVE", 2, "AUTONOMY", 1],
    "parenting:emotion_gap_parenting": "ADVICE",
    "parenting:independence_test_parent": ["DUTY", 2, "BOUNDARY", 1],
    "child:knowledge_rich_child": ["LEARNING", 2, "DEPTH", 1],
    "child:respect_independent_thinking_child": ["AUTONOMY", 2, "STATUS_DRIVE", 1],
    "child:high_score_competitor_child": ["COMPETITION", 2, "LEARNING", 1],
    "child:athletic_te_se_child": "UNSCORED_REFERENCE",
    "relationships:strategic_friend_filter": ["GOAL_DRIVE", 1, "RELATION_STYLE", -1, "DEPTH", 1],
    "relationships:debate_as_bonding": ["COMPETITION", 1, "RELATION_STYLE", 1],
    "relationships:useful_support_style": ["CARE", 1, "PRACTICALITY", 1],
    "relationships:low_emotional_support_need": "UNSCORED_REFERENCE",
    "communication:clear_assertive_language": ["COMMUNICATION_STYLE", 2, "EXPRESSION", 1],
    "communication:challenge_communication": ["COMPETITION", 2],
    "communication:wait_and_listen_gap": ["ACTION_TEMPO", 1],
    "communication:emotion_not_language": ["COMMUNICATION_STYLE", 2, "RELATION_STYLE", -1],
    "strengths:problem_solver_energy": ["INITIATIVE", 2, "CURIOSITY", 1],
    "strengths:talent_diagnosis": ["SOCIAL_ATTUNEMENT", 1, "CARE", 1],
    "strengths:execution_after_planning": ["INITIATIVE", 2, "STRUCTURE_STYLE", 1, "GOAL_DRIVE", 1],
    "strengths:resilience_under_resistance": ["PERSISTENCE", 2, "INITIATIVE", 1],
    "risks:ruthless_rationality": ["DECISION_STYLE", 2, "GOAL_DRIVE", 1],
    "risks:my_way_or_leave": ["AUTONOMY", 2, "COMPETITION", 1],
    "risks:low_empathy_execution": "UNSCORED_REFERENCE",
    "risks:public_contempt_risk": ["COMMUNICATION_STYLE", 1],
    "risks:rest_and_family_neglect": ["GOAL_DRIVE", 1, "STRUCTURE_STYLE", 1],
    "growth:eq_as_strategy": "ADVICE",
    "growth:slow_down_feedback": "ADVICE",
    "growth:cooperation_over_victory": "ADVICE",
    "growth:social_impact_check": "ADVICE",
  },
  INTJ: {
    "identity:strategic_skeptic": ["CURIOSITY", 1, "CHANGE_ORIENTATION", 1, "AUTONOMY", 1],
    "identity:independent_decision_maker": ["ENERGY_DIRECTION", -2, "DEPTH", 1, "AUTONOMY", 1],
    "identity:bold_dreamer_pessimist": ["GOAL_DRIVE", 1, "EXPANSION", 1],
    "identity:hidden_warmth": ["CARE", 1, "DUTY", 1, "PRACTICALITY", 1],
    "identity:rare_outsider_position": ["AUTONOMY", 1, "RELATION_STYLE", -1],
    "identity:life_as_strategy_board": ["STRATEGY", 2, "GOAL_DRIVE", 1, "RESOURCE_SENSE", 1],
    "thinkingStyle:system_first_thinking": ["PATTERN_SENSE", 2, "DEPTH", 1],
    "thinkingStyle:evidence_based_vision": ["PATTERN_SENSE", 2, "STRATEGY", 1],
    "thinkingStyle:elegant_solution_drive": ["PRECISION", 1, "STRATEGY", 1],
    "thinkingStyle:definition_precision": ["PRECISION", 2],
    "thinkingStyle:future_result_orientation": ["PRACTICALITY", 2, "GOAL_DRIVE", 1],
    "thinkingStyle:hidden_inconsistency_detector": ["PRECISION", 2, "PATTERN_SENSE", 1],
    "career:science_tech_law_fit": ["DEPTH", 1, "PRECISION", 1],
    "career:purpose_over_promotion": ["MEANING", 2, "AUTONOMY", 1],
    "career:small_team_deep_work": ["RELATION_STYLE", -2, "DEPTH", 1],
    "career:meritocracy_expectation": ["GOAL_DRIVE", 1, "BOUNDARY", 1],
    "career:strategic_supervisor": ["LEADERSHIP", 2, "STRATEGY", 1],
    "career:autonomy_required_role": ["AUTONOMY", 2],
    "career:innovation_over_convention": ["CHANGE_ORIENTATION", 1, "PRACTICALITY", 1],
    "career:strategy_to_asset_work": ["STRATEGY", 2, "PERSISTENCE", 1],
    "workplace:anti_politics_work_style": ["BOUNDARY", 1],
    "workplace:boss_challenge_risk": ["COMMUNICATION_STYLE", 1, "BOUNDARY", 1],
    "workplace:free_rider_intolerance": ["DUTY", 1, "AUTONOMY", 1],
    "workplace:private_chatter_drain": ["ENERGY_DIRECTION", -1, "RELATION_STYLE", -1],
    "workplace:flattery_resistant": ["PRECISION", 1],
    "workplace:broad_structure_leadership": ["LEADERSHIP", 2, "STRATEGY", 1, "DUTY", 1],
    "workplace:authority_scope_alignment": ["AUTONOMY", 2, "BOUNDARY", 1],
    "money:expertise_income_path": ["DEPTH", 1, "STRATEGY", 1],
    "money:financial_security_low_priority": ["GOAL_DRIVE", 2, "STRATEGY", 1],
    "money:self_employment_potential": ["AUTONOMY", 2, "DEPTH", 1],
    "money:cashflow_system_design": ["STRUCTURE_STYLE", 2, "RESOURCE_SENSE", 1],
    "money:selective_big_goal_spending": ["GOAL_DRIVE", 2, "RESOURCE_SENSE", 1],
    "money:shared_finance_blind_spot": ["GOAL_DRIVE", 1, "COMMUNICATION_STYLE", 1],
    "investment:anti_hype_investment": ["AUTONOMY", 1, "RISK_STYLE", -1, "PRECISION", 1],
    "investment:long_horizon_strategy": ["STRATEGY", 2, "STRUCTURE_STYLE", 1],
    "investment:scenario_exit_rule": ["STRATEGY", 2],
    "investment:model_overconfidence_risk": ["DEPTH", 2],
    "investment:rebalance_cashflow_guard": "ADVICE",
    "study:hard_discipline_affinity": ["DEPTH", 2, "LEARNING", 1],
    "study:deep_project_learning": ["DEPTH", 2, "PERSISTENCE", 1],
    "study:math_reflection_strategy": "ADVICE",
    "study:anti_shallow_knowledge": ["DEPTH", 2, "PRECISION", 1],
    "study:perfectionism_start_gate": ["STRUCTURE_STYLE", 1, "DEPTH", 1, "ACTION_TEMPO", -1],
    "love:slow_high_standard_love": ["ACTION_TEMPO", -1, "BOUNDARY", 1, "STRATEGY", 1],
    "love:strategic_romance_awkwardness": ["DEPTH", 1, "STRATEGY", 1],
    "love:same_direction_attraction": ["GOAL_DRIVE", 1, "STRATEGY", 1, "AUTONOMY", 1],
    "love:knowledge_display_risk": ["EXPRESSION", 1, "DEPTH", 1],
    "marriage:future_planned_marriage": ["STRUCTURE_STYLE", 2, "STRATEGY", 1],
    "marriage:autonomy_in_marriage": ["AUTONOMY", 2, "RELATION_STYLE", -1],
    "marriage:devotion_without_display": ["DUTY", 2, "CARE", 1, "COMMUNICATION_STYLE", -1],
    "marriage:role_agreement_marriage": ["STRUCTURE_STYLE", 2, "DUTY", 1],
    "marriage:emotional_expression_routine": ["DUTY", 1],
    "parenting:teach_how_to_think": ["LEARNING", 1, "AUTONOMY", 1],
    "parenting:independence_with_responsibility": ["AUTONOMY", 2, "DUTY", 1],
    "parenting:emotional_child_challenge": "UNSCORED_REFERENCE",
    "parenting:knowledge_centered_support": ["LEARNING", 2, "CARE", 1],
    "child:knowledge_rich_child": ["CURIOSITY", 1, "DEPTH", 1, "DECISION_STYLE", 1],
    "child:rule_questioning_child": ["AUTONOMY", 2, "CURIOSITY", 1],
    "child:intellectual_respect_need": ["AUTONOMY", 2, "STATUS_DRIVE", 1],
    "child:single_field_mastery": ["DEPTH", 2, "GOAL_DRIVE", 1],
    "relationships:selective_friendship": ["RELATION_STYLE", -2, "BOUNDARY", 1],
    "relationships:deep_idea_bond": ["DEPTH", 2, "MEANING", 1],
    "relationships:insight_as_care": ["CARE", 1, "STRATEGY", 1, "PATTERN_SENSE", 1],
    "relationships:line_crossing_memory": ["BOUNDARY", 2],
    "communication:blunt_fact_delivery": ["COMMUNICATION_STYLE", 2, "PRECISION", 1],
    "communication:sarcastic_humor": ["COMMUNICATION_STYLE", 1],
    "communication:low_praise_style": ["COMMUNICATION_STYLE", 1],
    "communication:abstract_conversation_preference": ["DEPTH", 1, "MEANING", 1],
    "strengths:rational_under_pressure": ["STRATEGY", 1, "STRUCTURE_STYLE", 1],
    "strengths:intellectual_depth": ["DEPTH", 2, "LEARNING", 1],
    "strengths:independent_creativity": ["AUTONOMY", 2, "CREATION", 1],
    "strengths:original_innovation": ["CREATION", 2, "CHANGE_ORIENTATION", 1],
    "risks:arrogance_risk": ["BOUNDARY", 1, "AUTONOMY", 1],
    "risks:low_sociability_risk": ["COMMUNICATION_STYLE", 2],
    "risks:over_intellectualizing_relationship": ["DEPTH", 1, "STRATEGY", 1],
    "risks:ni_fi_loop_anxiety": "UNSCORED_REFERENCE",
    "risks:sensory_reality_neglect": ["STRATEGY", 1, "DEPTH", 1],
    "growth:sequence_feedback_softly": "ADVICE",
    "growth:practice_small_affection": "ADVICE",
    "growth:invite_real_world_feedback": "ADVICE",
    "growth:build_social_translation": "ADVICE",
  },
  INTP: {
    "identity:quiet_logic_engine": ["ENERGY_DIRECTION", -1, "DEPTH", 1],
    "identity:idea_bank_identity": ["PATTERN_SENSE", 2, "CURIOSITY", 1],
    "identity:lazy_genius_gap": ["DEPTH", 2, "ACTION_TEMPO", -1, "MEANING", 1],
    "identity:self_sufficient_loneliness": ["RELATION_STYLE", -2, "AUTONOMY", 1],
    "identity:calm_outside_volcano_inside": ["ENERGY_DIRECTION", -1, "DEPTH", 1],
    "identity:anti_authority_free_mind": ["AUTONOMY", 2],
    "thinkingStyle:ti_internal_model": ["DEPTH", 1, "AUTONOMY", 1],
    "thinkingStyle:ne_possibility_storm": ["DECISION_STYLE", -2, "CURIOSITY", 1, "PATTERN_SENSE", 1],
    "thinkingStyle:why_question_loop": ["CURIOSITY", 2, "DEPTH", 2],
    "thinkingStyle:proof_before_agreement": ["PRECISION", 1, "ADAPTABILITY", 1],
    "thinkingStyle:big_picture_first": ["PATTERN_SENSE", 1, "DEPTH", 1],
    "thinkingStyle:pattern_leap_risk": ["PATTERN_SENSE", 2, "ADAPTABILITY", 1],
    "career:research_field_fit": ["DEPTH", 2, "CURIOSITY", 1],
    "career:programming_engineering_fit": ["CREATION", 1, "DEPTH", 1],
    "career:late_blooming_income": "UNSCORED_REFERENCE",
    "career:freelance_autonomy_fit": ["AUTONOMY", 2],
    "career:education_for_adults_fit": ["EXPRESSION", 1, "LEARNING", 1],
    "career:esports_and_online_skill": "UNSCORED_REFERENCE",
    "career:model_to_product_bridge": ["DEPTH", 2],
    "workplace:needs_thinking_time": ["ENERGY_DIRECTION", -1, "DEPTH", 2, "ACTION_TEMPO", -1],
    "workplace:anti_bureaucracy_work": ["AUTONOMY", 2],
    "workplace:low_reaction_meeting_drain": ["RECOVERY_NEED", 2],
    "workplace:last_minute_execution": ["ACTION_TEMPO", -1, "STRUCTURE_STYLE", -1],
    "workplace:effort_efficiency_filter": ["PRACTICALITY", 1],
    "workplace:scope_clarity_contract": ["PRECISION", 1, "DEPTH", 1],
    "money:low_material_drive": ["CURIOSITY", 1, "DEPTH", 1],
    "money:knowledge_monetization": "UNSCORED_REFERENCE",
    "money:independent_income_need": ["AUTONOMY", 2, "DEPTH", 1],
    "money:automated_money_routine": ["STRUCTURE_STYLE", 1],
    "money:irregular_income_buffer": ["DEPTH", 1],
    "money:interest_spending_drift": ["CURIOSITY", 2, "LEARNING", 1],
    "investment:research_based_investing": ["DEPTH", 2, "ENERGY_DIRECTION", -1],
    "investment:anti_trend_investing": ["AUTONOMY", 1, "DEPTH", 1],
    "investment:analysis_delay_risk": ["DEPTH", 1, "DECISION_STYLE", -2],
    "investment:simple_rule_portfolio": ["DEPTH", 1],
    "investment:theory_detachment_guard": ["DEPTH", 1],
    "study:math_science_affinity": ["DEPTH", 2, "CURIOSITY", 1],
    "study:high_iq_low_grade_gap": "UNSCORED_REFERENCE",
    "study:math_journal_strategy": "ADVICE",
    "study:indirect_experience_learning": ["LEARNING", 2],
    "study:exam_routine_bridge": "UNSCORED_REFERENCE",
    "love:careful_narrow_love": ["ACTION_TEMPO", -1, "RELATION_STYLE", -1, "BOUNDARY", 1],
    "love:witty_intellectual_attraction": ["DEPTH", 1],
    "love:low_attention_partner_shock": ["RELATION_STYLE", -1],
    "love:freedom_based_attachment": ["AUTONOMY", 2, "DEPTH", 1, "ENERGY_DIRECTION", -1],
    "marriage:marriage_with_space": ["AUTONOMY", 2, "ENERGY_DIRECTION", -1],
    "marriage:household_support_need": ["AUTONOMY", 1, "DEPTH", 1],
    "marriage:emotional_translation_marriage": ["DEPTH", 1],
    "marriage:automated_household_system": ["ENERGY_DIRECTION", -1],
    "marriage:emotional_checkin_frequency": ["RECOVERY_NEED", 1, "RELATION_STYLE", -1],
    "parenting:open_patient_parent": ["CARE", 1, "CURIOSITY", 1],
    "parenting:answering_child_questions": ["CARE", 1, "LEARNING", 1],
    "parenting:parent_needs_alone_time": ["ENERGY_DIRECTION", -1, "RECOVERY_NEED", 1],
    "child:knowledge_rich_but_uneven_child": ["DEPTH", 2],
    "child:socially_detached_child": ["RELATION_STYLE", -2],
    "child:authority_conflict_child": ["AUTONOMY", 1, "ENERGY_DIRECTION", -1],
    "child:math_programming_child": ["CURIOSITY", 1],
    "child:misread_as_disorder_risk": "UNSCORED_REFERENCE",
    "relationships:low_need_for_human_ties": ["RELATION_STYLE", -2, "BOUNDARY", 1],
    "relationships:respect_for_listening_mind": "UNSCORED_REFERENCE",
    "relationships:no_debt_independence": ["AUTONOMY", 2],
    "relationships:quiet_cutoff_pattern": ["COMMUNICATION_STYLE", -1, "RELATION_STYLE", -1],
    "communication:direct_everyday_speech": ["COMMUNICATION_STYLE", 2],
    "communication:learned_social_reactions": ["LEARNING", 1, "SOCIAL_ATTUNEMENT", 1],
    "communication:conclusion_hungry_dialogue": ["DECISION_STYLE", 1],
    "communication:emotion_after_thought": ["DEPTH", 1],
    "communication:topic_triggered_talk": ["EXPRESSION", 1],
    "strengths:creative_intelligence": ["CREATION", 2, "PATTERN_SENSE", 1],
    "strengths:open_criticism_processing": ["ADAPTABILITY", 1, "PRECISION", 1],
    "strengths:lie_and_trick_detection": ["PATTERN_SENSE", 1, "PRECISION", 1],
    "strengths:long_game_thinking": ["STRATEGY", 1, "DEPTH", 1, "ACTION_TEMPO", -1],
    "risks:chronic_laziness": ["ACTION_TEMPO", -2, "CHANGE_ORIENTATION", 1],
    "risks:low_happiness_void": "UNSCORED_REFERENCE",
    "risks:analysis_without_application": ["DEPTH", 2],
    "risks:social_blindness": ["PATTERN_SENSE", 1],
    "risks:passive_aggressive_unhealthy": "UNSCORED_REFERENCE",
    "risks:low_physical_action": "UNSCORED_REFERENCE",
    "growth:find_meaningful_motive": "ADVICE",
    "growth:respect_own_talent": "ADVICE",
    "growth:optimism_from_one_merit": "ADVICE",
    "growth:close_the_loop": "ADVICE",
  },
  ENTP: {
    "identity:rule_breaking_innovator": ["CURIOSITY", 1, "CHANGE_ORIENTATION", 2],
    "identity:witty_light_presence": ["EXPRESSION", 2, "CHARISMA", 1],
    "identity:extroverted_loner": ["ENERGY_DIRECTION", 1, "RECOVERY_NEED", 2, "AUTONOMY", 1],
    "identity:inner_circle_selectivity": ["BOUNDARY", 2, "CARE", 1],
    "identity:anti_authoritarian_spirit": ["AUTONOMY", 2],
    "identity:challenge_seeking_confidence": ["RISK_STYLE", 1, "COMPETITION", 1, "PERSISTENCE", 1],
    "thinkingStyle:possibility_scanning": ["PATTERN_SENSE", 2, "CURIOSITY", 1, "DECISION_STYLE", -1],
    "thinkingStyle:logical_core_detection": ["PRECISION", 1, "PATTERN_SENSE", 1],
    "thinkingStyle:debate_as_processing": ["EXPRESSION", 1, "PRECISION", 1, "COMPETITION", 1],
    "thinkingStyle:fast_approximate_grasp": ["ACTION_TEMPO", 2, "PATTERN_SENSE", 1],
    "thinkingStyle:flaw_detection": ["PRECISION", 2, "PATTERN_SENSE", 1],
    "thinkingStyle:idea_before_detail": ["PATTERN_SENSE", 1, "EXPRESSION", 1],
    "career:verbal_profession_fit": ["EXPRESSION", 2, "ADAPTABILITY", 1],
    "career:tech_problem_solver": ["CREATION", 1, "STRATEGY", 1],
    "career:entrepreneurial_drive": ["CREATION", 1, "RISK_STYLE", 1, "OPPORTUNITY_SENSE", 1],
    "career:performance_and_entertainment": ["SOCIAL_ATTUNEMENT", 1, "EXPRESSION", 1],
    "career:high_variance_outcome": ["CURIOSITY", 1, "CHANGE_ORIENTATION", 1],
    "career:prototype_to_market_path": ["EXPRESSION", 1, "ACTION_TEMPO", 1],
    "workplace:autonomy_required": ["AUTONOMY", 2],
    "workplace:brainstorming_leader": ["CREATION", 2, "EXPRESSION", 1],
    "workplace:constructive_critic": ["PRECISION", 1, "COMMUNICATION_STYLE", 1],
    "workplace:multi_task_starter": ["INITIATIVE", 2, "ADAPTABILITY", 1],
    "workplace:political_misread_risk": ["COMMUNICATION_STYLE", 1],
    "workplace:routine_owner_pairing": "UNSCORED_REFERENCE",
    "money:opportunity_money_sense": ["OPPORTUNITY_SENSE", 2, "EXPANSION", 1],
    "money:high_income_variance": "UNSCORED_REFERENCE",
    "money:spending_on_experience": ["CHANGE_ORIENTATION", 2, "RISK_STYLE", 1],
    "money:idea_to_revenue_filter": ["CREATION", 1, "OPPORTUNITY_SENSE", 1],
    "money:project_cost_sprawl": ["DECISION_STYLE", -1, "CURIOSITY", 1],
    "money:recurring_revenue_system": "ADVICE",
    "investment:idea_driven_investing": ["CURIOSITY", 2, "CHANGE_ORIENTATION", 1],
    "investment:risk_threshold_management": ["RISK_STYLE", 2],
    "investment:investment_memo_rule": ["CREATION", 1],
    "investment:theme_hopping_risk": ["CHANGE_ORIENTATION", 2],
    "investment:experiment_budget_limit": ["CURIOSITY", 1],
    "study:interest_based_learning": ["CURIOSITY", 2, "DEPTH", 1],
    "study:cramming_and_notes": "UNSCORED_REFERENCE",
    "study:question_driven_childhood": ["CURIOSITY", 2, "AUTONOMY", 1],
    "study:short_deadline_sprint": ["ACTION_TEMPO", 1],
    "study:repetition_finish_system": ["PATTERN_SENSE", 1],
    "love:ideal_type_filter": ["RELATION_STYLE", 1, "BOUNDARY", 1, "ACTION_TEMPO", 1],
    "love:fast_start_romance": ["ACTION_TEMPO", 2, "INITIATIVE", 1],
    "love:awkward_true_crush": ["EXPRESSION", 1],
    "love:freedom_in_love": ["AUTONOMY", 2, "ENERGY_DIRECTION", -1],
    "marriage:marriage_needs_space": ["AUTONOMY", 2],
    "marriage:shared_growth_marriage": ["CURIOSITY", 1, "CHANGE_ORIENTATION", 1],
    "marriage:domestic_routine_gap": ["STRUCTURE_STYLE", -1],
    "marriage:promise_money_repeat_system": ["EXPRESSION", 1, "CHANGE_ORIENTATION", 1],
    "marriage:novelty_within_structure": ["CHANGE_ORIENTATION", 2],
    "parenting:free_range_parenting": ["AUTONOMY", 1, "CURIOSITY", 1],
    "parenting:intellectual_parent": ["CURIOSITY", 2, "LEARNING", 1],
    "parenting:traveling_parent": ["CHANGE_ORIENTATION", 1, "LEARNING", 1],
    "parenting:debating_with_child": ["EXPRESSION", 1, "COMPETITION", 1],
    "child:rule_testing_child": ["AUTONOMY", 2, "CURIOSITY", 1],
    "child:curious_knowledge_child": ["CURIOSITY", 2, "LEARNING", 1],
    "child:social_but_independent_child": ["ENERGY_DIRECTION", 1, "AUTONOMY", 1],
    "child:risk_play_child": ["RISK_STYLE", 2],
    "relationships:quick_connection": ["RELATION_STYLE", 2, "EXPRESSION", 1],
    "relationships:selective_loyalty": ["BOUNDARY", 1, "CARE", 1],
    "relationships:emotion_learning": ["SOCIAL_ATTUNEMENT", 1],
    "relationships:cutoff_without_regret": ["AUTONOMY", 1, "BOUNDARY", 1, "DECISION_STYLE", 1],
    "communication:direct_speech": ["COMMUNICATION_STYLE", 2],
    "communication:charming_argument": ["EXPRESSION", 2],
    "communication:why_question_habit": ["CURIOSITY", 2],
    "communication:large_frame_explanation": ["PATTERN_SENSE", 1, "EXPRESSION", 1],
    "strengths:creative_problem_solving": ["CREATION", 2, "ADAPTABILITY", 1],
    "strengths:quick_adaptation": ["ADAPTABILITY", 2, "RISK_STYLE", 1],
    "strengths:people_potential_reader": ["SOCIAL_ATTUNEMENT", 2, "CARE", 1],
    "strengths:accepts_good_criticism": ["ADAPTABILITY", 1],
    "risks:unfinished_projects": ["INITIATIVE", 1, "CHANGE_ORIENTATION", 2],
    "risks:low_routine_tolerance": ["STRUCTURE_STYLE", -1],
    "risks:sharp_tongue_damage": ["PRECISION", 1, "COMMUNICATION_STYLE", 2],
    "risks:manipulative_fe_shadow": ["SOCIAL_ATTUNEMENT", 2],
    "risks:rebellion_without_timing": ["INITIATIVE", 1, "CHANGE_ORIENTATION", 1],
    "growth:narrow_the_attempts": "ADVICE",
    "growth:soften_the_truth": "ADVICE",
    "growth:build_memory_system": "ADVICE",
    "growth:practice_emotional_presence": "ADVICE",
  },
} as const satisfies Record<string, TypeAnnotationManifest>;
