import type { TypeAnnotationManifest } from "./mbtiSemanticCore";

/** Reviewed plainKo leaves. Advice and unsupported concepts intentionally stay unscored. */
export const NF_ANNOTATIONS = {
  INFJ: {
    "identity:quiet_visionary": ["ENERGY_DIRECTION", -1, "PATTERN_SENSE", 2, "STRATEGY", 1],
    "identity:principled_inner_axis": ["BOUNDARY", 2, "MEANING", 1],
    "identity:rare_complex_identity": ["RELATION_STYLE", -1, "RECOVERY_NEED", 2],
    "identity:idealistic_reformer": ["MEANING", 1, "CARE", 1, "CHANGE_ORIENTATION", 1],
    "identity:warm_outer_cold_first": ["ENERGY_DIRECTION", -1, "RELATION_STYLE", -1],
    "identity:romantic_meaning_seeker": ["MEANING", 2],
    "thinkingStyle:ni_pattern_prediction": ["PATTERN_SENSE", 2, "STRATEGY", 1],
    "thinkingStyle:private_analysis_loop": ["ENERGY_DIRECTION", -2, "DEPTH", 1],
    "thinkingStyle:forest_before_tree": ["STRATEGY", 2, "PATTERN_SENSE", 1],
    "thinkingStyle:symbolic_imagination": ["MEANING", 1, "CURIOSITY", 1],
    "thinkingStyle:moral_sensitivity": ["BOUNDARY", 1, "MEANING", 1],
    "thinkingStyle:intuition_needs_questioning": ["PATTERN_SENSE", 1],
    "career:helping_profession_fit": ["CARE", 2],
    "career:creative_language_arts": ["CREATION", 1, "MEANING", 1],
    "career:research_academic_track": "UNSCORED_REFERENCE",
    "career:healthcare_meaning_path": "UNSCORED_REFERENCE",
    "career:low_fit_fieldwork": "UNSCORED_REFERENCE",
    "career:mission_over_income": ["MEANING", 2],
    "career:vision_to_content_strategy": ["STRATEGY", 1, "SOCIAL_ATTUNEMENT", 1],
    "workplace:horizontal_structure_fit": ["AUTONOMY", 1],
    "workplace:calm_deep_work": ["RECOVERY_NEED", 1, "DEPTH", 1],
    "workplace:project_completion_will": ["PERSISTENCE", 2, "DECISION_STYLE", 1],
    "workplace:people_centered_value": ["CARE", 1, "MEANING", 2],
    "workplace:slow_pace_quality": ["ACTION_TEMPO", -2, "MEANING", 1],
    "workplace:emotional_boundary_at_work": ["SOCIAL_ATTUNEMENT", 2, "RECOVERY_NEED", 1],
    "money:meaning_first_income_risk": ["MEANING", 2],
    "money:expertise_compounds_later": "UNSCORED_REFERENCE",
    "money:avoid_impulse_spending_noise": ["RECOVERY_NEED", 2],
    "money:quiet_accumulation_money": ["RESOURCE_SENSE", 1, "DEPTH", 1],
    "money:helping_boundary_spending": ["CARE", 2, "SOCIAL_ATTUNEMENT", 1],
    "money:perfection_delay_income": ["PRECISION", 1, "MEANING", 1, "ACTION_TEMPO", -1],
    "investment:values_based_long_horizon": ["MEANING", 2, "STRATEGY", 1],
    "investment:conviction_delay_risk": ["ACTION_TEMPO", -2],
    "investment:emotional_discomfort_filter": ["MEANING", 1, "BOUNDARY", 1],
    "investment:trust_story_verification": ["SOCIAL_ATTUNEMENT", 1, "MEANING", 1],
    "investment:periodic_principle_review": ["PERSISTENCE", 1],
    "study:graduate_depth_study": ["DEPTH", 2, "PERSISTENCE", 1, "MEANING", 1],
    "study:logical_math_gap": ["PATTERN_SENSE", 1, "MEANING", 1],
    "study:writing_over_speaking": ["ENERGY_DIRECTION", -1, "EXPRESSION", 1],
    "study:curiosity_and_many_questions": ["CURIOSITY", 2, "MEANING", 1],
    "study:quiet_plan_recovery": ["DEPTH", 1, "RECOVERY_NEED", 1],
    "love:careful_start_deep_love": ["ACTION_TEMPO", -1, "RELATION_STYLE", -1, "CARE", 1],
    "love:romantic_ideal_love": ["MEANING", 1],
    "love:quiet_care_partner": ["CARE", 2, "SOCIAL_ATTUNEMENT", 1],
    "love:noise_sensitive_date": ["RECOVERY_NEED", 1, "RELATION_STYLE", -1],
    "marriage:meaningful_long_bond": ["MEANING", 2, "RELATION_STYLE", -1],
    "marriage:private_time_needed": ["ENERGY_DIRECTION", -1, "COMMUNICATION_STYLE", -1],
    "marriage:indirect_conflict_expression": ["COMMUNICATION_STYLE", -2],
    "marriage:trust_repair_pace": ["STABILITY", 1, "DEPTH", 1, "ACTION_TEMPO", -1],
    "marriage:daily_reality_agreement": ["MEANING", 1],
    "parenting:free_thinking_home": ["AUTONOMY", 1, "LEARNING", 1],
    "parenting:values_and_manners_parent": ["MEANING", 1, "BOUNDARY", 1, "SOCIAL_ATTUNEMENT", 1],
    "parenting:expert_parent_model": ["LEARNING", 1, "EXPRESSION", 1],
    "child:written_expression_child": ["ENERGY_DIRECTION", -1, "EXPRESSION", 1],
    "child:sensitive_emotion_sponge_child": ["SOCIAL_ATTUNEMENT", 2, "CARE", 1],
    "child:indoor_dream_child": ["ENERGY_DIRECTION", -1, "CURIOSITY", 1],
    "child:quiet_helper_child": ["CARE", 1],
    "child:generation_conflict_child": ["AUTONOMY", 1, "MEANING", 1],
    "relationships:deep_true_connection": ["RELATION_STYLE", -2, "BOUNDARY", 1],
    "relationships:door_slam_boundary": ["BOUNDARY", 2, "COMMUNICATION_STYLE", -1],
    "relationships:social_chameleon": ["SOCIAL_ATTUNEMENT", 2, "ADAPTABILITY", 1],
    "relationships:control_for_safety": ["STRUCTURE_STYLE", 1, "STABILITY", 1],
    "communication:indirect_expression": ["COMMUNICATION_STYLE", -2, "CARE", 1],
    "communication:gentle_language": ["CARE", 1, "SOCIAL_ATTUNEMENT", 1],
    "communication:infj_stare_analysis": ["SOCIAL_ATTUNEMENT", 2, "PATTERN_SENSE", 1],
    "communication:low_smalltalk_energy": ["RELATION_STYLE", -2, "RECOVERY_NEED", 1],
    "communication:firm_refusal_when_decided": ["BOUNDARY", 2, "DECISION_STYLE", 1],
    "strengths:practical_insight": ["PATTERN_SENSE", 1, "PRACTICALITY", 1, "CARE", 1],
    "strengths:compassion": ["CARE", 2, "SOCIAL_ATTUNEMENT", 1],
    "strengths:peace_keeping": ["SOCIAL_ATTUNEMENT", 1, "CARE", 1],
    "strengths:creative_vision": ["CREATION", 2, "EXPRESSION", 1],
    "risks:empathy_burnout": ["SOCIAL_ATTUNEMENT", 2, "RECOVERY_NEED", 1],
    "risks:conflict_avoidance": ["COMMUNICATION_STYLE", -2],
    "risks:sensitivity_to_rejection": "UNSCORED_REFERENCE",
    "risks:perfectionist_self_blame": ["PRECISION", 2, "GOAL_DRIVE", 1],
    "risks:details_gap": ["STRATEGY", 1, "PATTERN_SENSE", 1],
    "risks:isolation_from_world": ["ENERGY_DIRECTION", -2, "RECOVERY_NEED", 2],
    "growth:question_own_intuition": "ADVICE",
    "growth:accept_disagreement": "ADVICE",
    "growth:meet_extroverts": "ADVICE",
    "growth:help_without_overcontrol": ["CARE", 1],
  },
  INFP: {
    "identity:authentic_inner_values": ["AUTONOMY", 1, "MEANING", 2],
    "identity:gentle_joan_of_arc": ["MEANING", 1, "CARE", 1, "BOUNDARY", 1],
    "identity:romantic_dreamer": ["CREATION", 1, "CURIOSITY", 1],
    "identity:meaning_over_status": ["MEANING", 2],
    "identity:soft_but_private": ["RELATION_STYLE", -2, "RECOVERY_NEED", 1],
    "identity:sensitive_withdrawal": ["RECOVERY_NEED", 2, "ENERGY_DIRECTION", -1],
    "thinkingStyle:fi_inner_alignment": ["MEANING", 2, "AUTONOMY", 1],
    "thinkingStyle:ne_branching_imagination": ["PATTERN_SENSE", 1, "CREATION", 2],
    "thinkingStyle:empathic_projection": ["SOCIAL_ATTUNEMENT", 2, "CARE", 1],
    "thinkingStyle:si_story_memory": ["MEANING", 1, "LEARNING", 1],
    "thinkingStyle:te_execution_gap": ["AUTONOMY", 1],
    "thinkingStyle:contextual_truth_detection": ["PATTERN_SENSE", 2, "SOCIAL_ATTUNEMENT", 1],
    "career:creative_arts_fit": ["CREATION", 1, "EXPRESSION", 1],
    "career:counseling_healing_fit": ["CARE", 2, "SOCIAL_ATTUNEMENT", 1],
    "career:education_gentle_teacher": ["CARE", 1, "AUTONOMY", 1],
    "career:small_independent_business": "UNSCORED_REFERENCE",
    "career:media_community_fit": "UNSCORED_REFERENCE",
    "career:bureaucracy_low_fit": ["AUTONOMY", 2],
    "career:value_to_income_bridge": "ADVICE",
    "workplace:autonomy_required": ["AUTONOMY", 2, "MEANING", 1],
    "workplace:low_competition_environment": "UNSCORED_REFERENCE",
    "workplace:meaning_driven_diligence": ["DUTY", 1, "PERSISTENCE", 1, "MEANING", 1],
    "workplace:soft_conflict_style": ["COMMUNICATION_STYLE", -2, "RELATION_STYLE", -1],
    "workplace:second_leader_fit": "UNSCORED_REFERENCE",
    "workplace:feedback_safety_contract": ["MEANING", 1],
    "money:low_material_drive": ["MEANING", 2],
    "money:creative_income_path": "UNSCORED_REFERENCE",
    "money:generosity_boundary_money": ["CARE", 2, "MEANING", 1],
    "money:value_pricing_gap": ["CARE", 1, "MEANING", 1, "ACTION_TEMPO", -1],
    "money:emotional_spending_shelter": ["RECOVERY_NEED", 2],
    "money:buffer_and_auto_money": ["ACTION_TEMPO", -1],
    "investment:values_first_investment": ["MEANING", 2],
    "investment:loss_check_avoidance": ["ACTION_TEMPO", -1, "ENERGY_DIRECTION", -1],
    "investment:automatic_record_guard": "ADVICE",
    "investment:story_attachment_risk": ["MEANING", 1, "SOCIAL_ATTUNEMENT", 1],
    "investment:small_safe_experiment": "UNSCORED_REFERENCE",
    "study:storytelling_learning": ["CREATION", 1, "MEANING", 1, "LEARNING", 1],
    "study:math_logic_gap": "UNSCORED_REFERENCE",
    "study:foreign_language_strength": ["SOCIAL_ATTUNEMENT", 1, "LEARNING", 1],
    "study:creative_brainstorm_method": ["CREATION", 1],
    "study:deadline_reality_anchor": ["DEPTH", 2, "MEANING", 1],
    "love:deep_emotional_bond": ["RELATION_STYLE", -1, "CARE", 2, "DUTY", 1],
    "love:artistic_dates": ["CURIOSITY", 1, "CREATION", 1],
    "love:criticism_sensitive_love": "UNSCORED_REFERENCE",
    "love:passive_initiation_love": "UNSCORED_REFERENCE",
    "marriage:freedom_romance_marriage": ["AUTONOMY", 1, "MEANING", 1, "RECOVERY_NEED", 1],
    "marriage:devotion_and_boundary": ["CARE", 2, "ADAPTABILITY", 1],
    "marriage:conflict_avoidance_marriage": ["COMMUNICATION_STYLE", -2],
    "marriage:ideal_and_reality_balance": ["MEANING", 1],
    "marriage:inner_world_respect": ["ENERGY_DIRECTION", -2, "MEANING", 1],
    "parenting:autonomy_parent": ["AUTONOMY", 2],
    "parenting:moral_parent": ["CARE", 1, "MEANING", 1, "BOUNDARY", 1],
    "parenting:soft_discipline_parent": ["CARE", 2],
    "child:creative_child": ["CREATION", 2, "SOCIAL_ATTUNEMENT", 1],
    "child:sensitive_to_harshness_child": "UNSCORED_REFERENCE",
    "child:authority_conflict_child": ["AUTONOMY", 2],
    "child:socially_different_child": "UNSCORED_REFERENCE",
    "child:presentation_emotion_child": "UNSCORED_REFERENCE",
    "relationships:deep_value_based_bonds": ["RELATION_STYLE", -2, "MEANING", 1],
    "relationships:boundary_against_cruelty": ["BOUNDARY", 2, "CARE", 1],
    "relationships:emotional_distance": ["SOCIAL_ATTUNEMENT", 1, "BOUNDARY", 1, "RELATION_STYLE", -1],
    "relationships:low_interference_individualism": ["AUTONOMY", 1, "CARE", 1],
    "communication:gentle_metaphoric_speech": ["COMMUNICATION_STYLE", -2, "CARE", 1],
    "communication:slow_to_show_affection": ["ENERGY_DIRECTION", -1, "COMMUNICATION_STYLE", -1],
    "communication:anger_private_processing": ["ENERGY_DIRECTION", -2, "RECOVERY_NEED", 1],
    "communication:authenticity_over_skill": ["MEANING", 2],
    "communication:criticism_fragility": "UNSCORED_REFERENCE",
    "strengths:warm_worldview": ["CARE", 2, "SOCIAL_ATTUNEMENT", 1],
    "strengths:conflict_mediation": ["CARE", 1, "SOCIAL_ATTUNEMENT", 1],
    "strengths:creative_emotional_processing": ["CREATION", 1, "RECOVERY_NEED", 1],
    "strengths:non_interfering_kindness": ["CARE", 1, "AUTONOMY", 1],
    "risks:emotional_overload": ["COMMUNICATION_STYLE", -2],
    "risks:reality_ideal_gap": ["MEANING", 1],
    "risks:weak_decision_execution": "UNSCORED_REFERENCE",
    "risks:over_screening_people": ["BOUNDARY", 2, "MEANING", 1],
    "risks:burnout_from_unfit_work": ["AUTONOMY", 2],
    "risks:overgiving_to_trusted_person": ["CARE", 2],
    "growth:develop_ne_perspective": "ADVICE",
    "growth:small_control_routine": "ADVICE",
    "growth:body_activity_grounding": "ADVICE",
    "growth:express_emotions_for_love": "ADVICE",
  },
  ENFJ: {
    "identity:compassionate_facilitator": ["CARE", 2, "SOCIAL_ATTUNEMENT", 1],
    "identity:visionary_group_leader": ["LEADERSHIP", 2, "EXPRESSION", 1, "STRATEGY", 1],
    "identity:socially_attuned_extrovert": ["ENERGY_DIRECTION", 2, "SOCIAL_ATTUNEMENT", 2],
    "identity:value_driven_conviction": ["MEANING", 2, "PERSISTENCE", 1],
    "identity:relationship_centered_identity": ["CARE", 1, "MEANING", 1],
    "thinkingStyle:fe_first_judgment": ["SOCIAL_ATTUNEMENT", 2, "CARE", 1],
    "thinkingStyle:future_meaning_orientation": ["STRATEGY", 1, "MEANING", 2],
    "thinkingStyle:fast_people_reading": ["SOCIAL_ATTUNEMENT", 2, "ADAPTABILITY", 1],
    "thinkingStyle:meaningful_discussion": ["MEANING", 2, "EXPRESSION", 1],
    "thinkingStyle:self_reflective_growth": ["LEARNING", 1, "DUTY", 1],
    "career:teacher_facilitator_fit": ["CARE", 2],
    "career:counseling_and_welfare": ["CARE", 1, "SOCIAL_ATTUNEMENT", 1],
    "career:public_communication_fit": ["EXPRESSION", 2, "SOCIAL_ATTUNEMENT", 1],
    "career:diplomatic_bridge": ["SOCIAL_ATTUNEMENT", 2, "CARE", 1],
    "career:activist_leadership": ["LEADERSHIP", 1, "MEANING", 1, "INITIATIVE", 1],
    "career:people_growth_business": ["CARE", 1, "LEADERSHIP", 1],
    "workplace:collaborative_environment": ["ENERGY_DIRECTION", 2, "DUTY", 1],
    "workplace:tension_sensitive_work": ["SOCIAL_ATTUNEMENT", 1, "RECOVERY_NEED", 1],
    "workplace:persuasive_presenter": ["EXPRESSION", 2, "SOCIAL_ATTUNEMENT", 1],
    "workplace:care_overload_at_work": ["CARE", 2],
    "workplace:criticism_avoidance": ["COMMUNICATION_STYLE", -2],
    "workplace:role_boundary_for_leadership": ["CARE", 1, "DUTY", 1],
    "money:generous_spending": ["CARE", 2],
    "money:reputation_linked_money": ["STATUS_DRIVE", 2, "MEANING", 1],
    "money:cause_based_money": ["MEANING", 2, "PERSISTENCE", 1],
    "money:growth_based_income": ["CARE", 1, "LEADERSHIP", 1],
    "money:status_and_care_spending": ["STATUS_DRIVE", 1, "CARE", 1],
    "money:support_limit_rule": ["CARE", 2],
    "investment:values_aligned_investment": ["MEANING", 2, "CARE", 1],
    "investment:emotion_separation_in_investment": ["SOCIAL_ATTUNEMENT", 1],
    "investment:relationship_info_boundary": ["SOCIAL_ATTUNEMENT", 2],
    "investment:support_limit_guard": ["CARE", 2],
    "investment:public_image_bias": ["STATUS_DRIVE", 1, "SOCIAL_ATTUNEMENT", 1],
    "study:fast_social_learning": ["LEARNING", 2, "CURIOSITY", 1],
    "study:meaning_based_study": ["MEANING", 2, "DEPTH", 1],
    "study:answer_leader_child": ["EXPRESSION", 2, "LEARNING", 1, "ENERGY_DIRECTION", 1],
    "study:protected_solo_study_time": ["SOCIAL_ATTUNEMENT", 1],
    "study:objective_logic_drill": ["EXPRESSION", 1],
    "love:full_hearted_love": ["CARE", 1, "STRATEGY", 1],
    "love:emotional_confirmation_need": ["STABILITY", 1, "SOCIAL_ATTUNEMENT", 1],
    "love:attuned_partner": ["CARE", 2, "SOCIAL_ATTUNEMENT", 2],
    "love:hard_to_end_relationship": ["CARE", 1, "MEANING", 1],
    "marriage:future_planning_partner": ["STRATEGY", 1, "MEANING", 1, "STABILITY", 1],
    "marriage:marital_emotional_labor": ["CARE", 2, "SOCIAL_ATTUNEMENT", 1],
    "marriage:values_based_family": ["STRUCTURE_STYLE", 1, "CARE", 1, "MEANING", 1],
    "marriage:shared_care_responsibility": ["CARE", 2, "SOCIAL_ATTUNEMENT", 1],
    "marriage:family_social_boundary": ["RELATION_STYLE", 1, "STATUS_DRIVE", 1, "CARE", 1],
    "parenting:free_but_guiding_parent": ["AUTONOMY", 1, "CARE", 1, "DUTY", 1],
    "parenting:emotional_anchor_parent": ["CARE", 2],
    "parenting:travel_and_dialogue_parent": ["CHANGE_ORIENTATION", 1, "LEARNING", 1],
    "child:popular_helper_child": ["RELATION_STYLE", 1, "CARE", 2],
    "child:encouraging_speaker_child": ["EXPRESSION", 2, "CARE", 1],
    "child:tearful_empath_child": ["SOCIAL_ATTUNEMENT", 2],
    "relationships:wide_social_bonding": ["RELATION_STYLE", 2, "ENERGY_DIRECTION", 1],
    "relationships:warm_but_selective_cutoff": ["CARE", 1, "BOUNDARY", 1],
    "relationships:idealizing_people": ["CARE", 1, "MEANING", 1],
    "communication:eloquent_social_speech": ["EXPRESSION", 2, "SOCIAL_ATTUNEMENT", 1],
    "communication:gentle_feedback": ["COMMUNICATION_STYLE", -2, "CARE", 1],
    "communication:expressive_face": ["EXPRESSION", 1, "SOCIAL_ATTUNEMENT", 1],
    "strengths:mobilizing_people": ["LEADERSHIP", 2, "GOAL_DRIVE", 1, "MEANING", 1],
    "strengths:growth_support": ["CARE", 2],
    "strengths:social_humor": ["SOCIAL_ATTUNEMENT", 2, "EXPRESSION", 1],
    "risks:empathy_burnout": ["SOCIAL_ATTUNEMENT", 2, "RECOVERY_NEED", 1],
    "risks:surface_emotion_bias": ["SOCIAL_ATTUNEMENT", 1],
    "risks:over_involvement": ["CARE", 2],
    "risks:moral_dividing": "UNSCORED_REFERENCE",
    "growth:separate_self_and_others": "ADVICE",
    "growth:practice_clear_criticism": ["COMMUNICATION_STYLE", -1, "CARE", 1],
    "growth:fact_structure_training": ["SOCIAL_ATTUNEMENT", 1],
  },
  ENFP: {
    "identity:spark_of_possibility": ["CHANGE_ORIENTATION", 2, "PATTERN_SENSE", 1, "INITIATIVE", 1],
    "identity:people_centered_energy": ["ENERGY_DIRECTION", 2, "RELATION_STYLE", 1],
    "identity:warm_individualist": ["AUTONOMY", 1, "MEANING", 1, "SOCIAL_ATTUNEMENT", 1],
    "identity:expressive_authenticity": ["EXPRESSION", 2],
    "identity:outer_bright_inner_quiet": ["ENERGY_DIRECTION", 1, "RECOVERY_NEED", 1],
    "thinkingStyle:ne_connection_thinking": ["PATTERN_SENSE", 2, "MEANING", 1],
    "thinkingStyle:imaginative_storytelling": ["EXPRESSION", 2, "CREATION", 1],
    "thinkingStyle:meaning_before_fact": ["MEANING", 2],
    "thinkingStyle:question_burst_pattern": ["CURIOSITY", 2, "CHANGE_ORIENTATION", 1],
    "thinkingStyle:emotion_amplified_processing": "UNSCORED_REFERENCE",
    "career:counseling_fit": ["SOCIAL_ATTUNEMENT", 2, "CARE", 1],
    "career:education_motivator": ["EXPRESSION", 1, "CARE", 1, "MEANING", 1],
    "career:arts_and_creative_field": ["CREATION", 1, "EXPRESSION", 1],
    "career:community_event_starter": ["INITIATIVE", 2],
    "career:idea_to_campaign_path": ["CREATION", 1, "EXPRESSION", 1],
    "career:portfolio_project_income": "UNSCORED_REFERENCE",
    "workplace:novelty_required_work": ["CHANGE_ORIENTATION", 2, "CURIOSITY", 1],
    "workplace:deadline_sprint_style": ["STRUCTURE_STYLE", -1, "ADAPTABILITY", 1],
    "workplace:social_mood_maker": ["SOCIAL_ATTUNEMENT", 1, "EXPRESSION", 1],
    "workplace:autonomy_over_control": ["AUTONOMY", 2],
    "workplace:follow_through_system": ["INITIATIVE", 1, "EXPANSION", 1],
    "workplace:open_culture_fit": ["AUTONOMY", 1, "CURIOSITY", 1, "MEANING", 1],
    "money:experience_spending": ["CHANGE_ORIENTATION", 2, "EXPRESSION", 1],
    "money:income_needs_interest": ["CURIOSITY", 1, "AUTONOMY", 1],
    "money:project_based_income": ["OPPORTUNITY_SENSE", 2, "RELATION_STYLE", 1],
    "money:possibility_spending_spread": ["OPPORTUNITY_SENSE", 1, "CURIOSITY", 1, "ACTION_TEMPO", 1],
    "money:recurring_income_anchor": "ADVICE",
    "money:emotion_purchase_pause": ["ACTION_TEMPO", 2, "RISK_STYLE", 1],
    "investment:story_driven_investment": ["OPPORTUNITY_SENSE", 1, "MEANING", 1],
    "investment:impulse_control_investment": ["ACTION_TEMPO", 2, "RISK_STYLE", 1],
    "investment:theme_spread_risk": ["CHANGE_ORIENTATION", 2, "OPPORTUNITY_SENSE", 1],
    "investment:investment_memo_exit_rule": "ADVICE",
    "investment:cooling_period_guard": ["ACTION_TEMPO", 1, "OPPORTUNITY_SENSE", 1],
    "study:interest_switch_learning": ["MEANING", 1, "CURIOSITY", 1],
    "study:logic_practice_needed": ["PATTERN_SENSE", 1],
    "study:language_conversation_strength": ["EXPRESSION", 2, "ENERGY_DIRECTION", 1],
    "study:completion_checkpoint": ["INITIATIVE", 1, "ACTION_TEMPO", 1],
    "study:repeat_training_anchor": ["PATTERN_SENSE", 1, "CHANGE_ORIENTATION", 1],
    "love:passionate_romance": ["EXPRESSION", 2, "INITIATIVE", 1, "SOCIAL_ATTUNEMENT", 1],
    "love:warm_confidant_partner": ["CARE", 2, "SOCIAL_ATTUNEMENT", 1],
    "love:spontaneous_love_risk": ["STRUCTURE_STYLE", -1, "ACTION_TEMPO", 1],
    "love:rejection_difficulty": ["COMMUNICATION_STYLE", -1, "CARE", 1],
    "marriage:creative_family_life": ["CHANGE_ORIENTATION", 2],
    "marriage:freedom_in_marriage": ["AUTONOMY", 2, "RELATION_STYLE", 1],
    "marriage:domestic_follow_through_gap": "UNSCORED_REFERENCE",
    "marriage:freedom_with_agreement": ["AUTONOMY", 2, "CHANGE_ORIENTATION", 1],
    "marriage:emotional_novelty_loop": ["CHANGE_ORIENTATION", 2],
    "parenting:understanding_parent": ["SOCIAL_ATTUNEMENT", 2, "CARE", 1],
    "parenting:affectionate_support_parent": ["CARE", 2, "EXPRESSION", 1],
    "parenting:travel_parent": ["CHANGE_ORIENTATION", 1, "LEARNING", 1],
    "child:playful_social_child": ["RELATION_STYLE", 1, "ENERGY_DIRECTION", 1],
    "child:all_or_nothing_study_child": ["CURIOSITY", 1],
    "child:sensitive_emotional_child": ["SOCIAL_ATTUNEMENT", 1, "EXPRESSION", 1],
    "child:anti_conservative_child": ["AUTONOMY", 2],
    "relationships:wide_light_network": ["RELATION_STYLE", 2, "ADAPTABILITY", 1],
    "relationships:joy_giver": ["CARE", 1, "SOCIAL_ATTUNEMENT", 1, "EXPRESSION", 1],
    "relationships:likes_and_dislikes_visible": ["EXPRESSION", 1],
    "communication:easy_conversation": ["ENERGY_DIRECTION", 2, "EXPRESSION", 1],
    "communication:random_but_charming_speech": ["EXPRESSION", 1, "PATTERN_SENSE", 1],
    "communication:encouragement_over_criticism": ["CARE", 1],
    "strengths:creative_imagination": ["CREATION", 2, "CURIOSITY", 1],
    "strengths:friendly_leadership": ["LEADERSHIP", 1, "INITIATIVE", 1, "SOCIAL_ATTUNEMENT", 1],
    "strengths:crisis_big_picture": ["ADAPTABILITY", 2, "ACTION_TEMPO", 1],
    "risks:unfinished_many_starts": ["INITIATIVE", 1, "CHANGE_ORIENTATION", 2],
    "risks:detail_boredom": ["CHANGE_ORIENTATION", 1],
    "risks:criticism_sensitivity": "UNSCORED_REFERENCE",
    "risks:recognition_dependence": ["STATUS_DRIVE", 2],
    "growth:make_completion_structure": "ADVICE",
    "growth:train_fact_and_logic": ["MEANING", 1, "SOCIAL_ATTUNEMENT", 1],
    "growth:practice_boundaries": ["COMMUNICATION_STYLE", -1],
  },
} as const satisfies Record<string, TypeAnnotationManifest>;
