import type { TypeAnnotationManifest } from "./mbtiSemanticCore";

export const SP_ANNOTATIONS = {
  ISTP: {
    "identity:quiet_tool_mind": ["PRACTICALITY", 2, "ENERGY_DIRECTION", -1],
    "identity:selective_energy_use": ["DEPTH", 2],
    "identity:freedom_first_identity": ["AUTONOMY", 2, "ENERGY_DIRECTION", -1],
    "identity:cool_surface_warm_core": ["RELATION_STYLE", -1, "CARE", 1],
    "identity:present_moment_operator": ["ACTION_TEMPO", 2, "ADAPTABILITY", 1],
    "identity:private_confidence": ["BOUNDARY", 1, "ENERGY_DIRECTION", -1],
    "thinkingStyle:internal_logic_frame": ["AUTONOMY", 1, "DEPTH", 1],
    "thinkingStyle:contradiction_intolerance": ["PRECISION", 2],
    "thinkingStyle:causal_principle_focus": ["PRECISION", 1, "PRACTICALITY", 1],
    "thinkingStyle:practical_insight": ["PATTERN_SENSE", 1, "PRACTICALITY", 1],
    "thinkingStyle:minimal_effort_efficiency": ["PRACTICALITY", 2],
    "career:hands_on_technical_fit": ["PRACTICALITY", 2],
    "career:crisis_response_work": ["ACTION_TEMPO", 2, "ADAPTABILITY", 1],
    "career:precision_sensory_work": ["PRECISION", 1, "ADAPTABILITY", 1],
    "career:autonomy_required_work": ["AUTONOMY", 2, "DEPTH", 1],
    "career:resourceful_reformer": ["PRACTICALITY", 1, "CHANGE_ORIENTATION", 1],
    "career:boredom_sensitive_work": ["CHANGE_ORIENTATION", 1, "PRACTICALITY", 1],
    "career:technical_problem_income": ["PRECISION", 1, "PRACTICALITY", 1],
    "workplace:anti_micromanagement": ["AUTONOMY", 2],
    "workplace:quiet_but_social_when_needed": ["RELATION_STYLE", -1, "ADAPTABILITY", 1],
    "workplace:competence_respect_needed": ["BOUNDARY", 1],
    "workplace:practical_peer_work": ["AUTONOMY", 1, "PRACTICALITY", 1],
    "workplace:action_over_meeting": ["PRACTICALITY", 2, "ACTION_TEMPO", 1],
    "workplace:minimal_report_protocol": ["AUTONOMY", 1, "PERSISTENCE", 1],
    "money:practical_spending": ["RESOURCE_SENSE", 1, "PRACTICALITY", 2],
    "money:efficiency_money_style": ["PRACTICALITY", 2, "RESOURCE_SENSE", 1],
    "money:freedom_income_preference": ["AUTONOMY", 2],
    "money:technical_problem_income": ["PRACTICALITY", 1],
    "money:tool_hobby_budget_limit": ["CURIOSITY", 1, "PRACTICALITY", 1],
    "money:automated_finance_minimum": "ADVICE",
    "investment:quality_asset_preference": ["PRACTICALITY", 2, "RESOURCE_SENSE", 1],
    "investment:risk_thrill_caution": ["RISK_STYLE", 2, "CHANGE_ORIENTATION", 1],
    "investment:practical_data_check": ["PRACTICALITY", 2, "PRECISION", 1],
    "investment:auto_review_needed": "ADVICE",
    "investment:simple_rule_preference": ["PRACTICALITY", 1],
    "study:hands_on_learning": ["PRACTICALITY", 1, "LEARNING", 1],
    "study:math_science_interest": ["CURIOSITY", 1, "PRACTICALITY", 1],
    "study:short_long_goal_split": "ADVICE",
    "study:theory_to_tool_bridge": ["LEARNING", 1, "PRACTICALITY", 1],
    "study:repeat_check_system": ["DEPTH", 1, "STRUCTURE_STYLE", -1],
    "love:freedom_love_boundary": ["AUTONOMY", 2, "RELATION_STYLE", -1],
    "love:old_bond_keeper": ["CHANGE_ORIENTATION", -1, "CARE", 1],
    "love:quiet_warm_affection": ["CARE", 1, "ENERGY_DIRECTION", -1],
    "marriage:space_based_marriage": ["AUTONOMY", 2, "RELATION_STYLE", -1],
    "marriage:shared_hobby_bond": ["PRACTICALITY", 1, "CURIOSITY", 1],
    "marriage:practical_responsibility_signal": ["DUTY", 1, "PRACTICALITY", 1],
    "marriage:personal_time_agreement": ["ENERGY_DIRECTION", -1, "RECOVERY_NEED", 1],
    "marriage:money_and_tool_boundary": ["PRACTICALITY", 1],
    "parenting:open_non_controlling_parent": ["AUTONOMY", 2, "DUTY", 1],
    "parenting:privacy_respecting_parent": ["AUTONOMY", 2, "BOUNDARY", 1],
    "parenting:emotion_blind_parenting": ["PRACTICALITY", 1],
    "child:rule_resistant_child": ["AUTONOMY", 1, "DEPTH", 1],
    "child:solo_play_precision_child": ["ENERGY_DIRECTION", -1, "PRECISION", 1],
    "child:brief_answer_child": ["COMMUNICATION_STYLE", 1],
    "relationships:low_intrusion_relation": ["AUTONOMY", 2, "BOUNDARY", 1],
    "relationships:comfortable_people_only": ["RELATION_STYLE", -2, "RECOVERY_NEED", 1],
    "relationships:emotion_distance_when_overwhelmed": ["RELATION_STYLE", -1, "RECOVERY_NEED", 1],
    "communication:few_words_direct": ["COMMUNICATION_STYLE", 2, "ENERGY_DIRECTION", -1],
    "communication:no_fake_comfort": ["COMMUNICATION_STYLE", 1, "PRACTICALITY", 1],
    "strengths:crisis_calm_action": ["ACTION_TEMPO", 2, "ADAPTABILITY", 1],
    "strengths:strong_mental_filter": ["BOUNDARY", 1],
    "strengths:adaptable_realism": ["ADAPTABILITY", 2, "PRACTICALITY", 1],
    "risks:emotional_blind_spot": "UNSCORED_REFERENCE",
    "risks:risk_seeking_impulse": ["RISK_STYLE", 2, "CHANGE_ORIENTATION", 1],
    "risks:boredom_dropoff": ["CHANGE_ORIENTATION", 1],
    "growth:minimum_emotion_translation": "ADVICE",
    "growth:long_term_mission_structure": "ADVICE",
  },
  ISFP: {
    "identity:quiet_warm_artist": ["CARE", 1, "MEANING", 1, "ACTION_TEMPO", -1],
    "identity:private_inner_world": ["ENERGY_DIRECTION", -2, "BOUNDARY", 1],
    "identity:value_first_individualist": ["AUTONOMY", 2, "MEANING", 1],
    "identity:gentle_but_not_weak": ["BOUNDARY", 2, "CARE", 1],
    "identity:present_small_happiness": ["ACTION_TEMPO", -1],
    "identity:low_ego_honesty": "UNSCORED_REFERENCE",
    "thinkingStyle:fi_value_alignment": ["MEANING", 2, "BOUNDARY", 1],
    "thinkingStyle:sensory_truth_detector": ["SOCIAL_ATTUNEMENT", 2, "PRECISION", 1],
    "thinkingStyle:third_ni_hunch": ["PATTERN_SENSE", 1],
    "thinkingStyle:open_but_undecided": ["DECISION_STYLE", -2, "ADAPTABILITY", 1],
    "thinkingStyle:weak_long_term_structure": ["STRUCTURE_STYLE", -1, "PRACTICALITY", 1],
    "career:artistic_expression_fit": ["CREATION", 1, "EXPRESSION", 1],
    "career:field_service_mission": ["CARE", 1, "PRACTICALITY", 1],
    "career:autonomous_field_work": ["AUTONOMY", 2],
    "career:horizontal_team_fit": ["AUTONOMY", 1],
    "career:ordinary_office_possible_but_limited": ["AUTONOMY", 1, "MEANING", 1],
    "career:burst_focus_work": ["DEPTH", 2, "STRUCTURE_STYLE", -1],
    "career:taste_to_service_value": ["CREATION", 1, "PRACTICALITY", 1],
    "workplace:conflict_silent_exit": ["COMMUNICATION_STYLE", -2, "RELATION_STYLE", -1],
    "workplace:anti_authority_control": ["AUTONOMY", 2, "BOUNDARY", 1],
    "workplace:low_competition_best": ["STABILITY", 1],
    "workplace:direct_with_close_people": ["COMMUNICATION_STYLE", 1],
    "workplace:extravert_energy_fatigue": ["RECOVERY_NEED", 2],
    "workplace:gentle_feedback_space": ["RECOVERY_NEED", 1, "STABILITY", 1],
    "money:low_income_risk_due_to_softness": "UNSCORED_REFERENCE",
    "money:experience_spending": ["RECOVERY_NEED", 1],
    "money:creative_side_income": "UNSCORED_REFERENCE",
    "money:taste_service_income": ["CREATION", 1, "CARE", 1],
    "money:comfort_spending_limit": ["RECOVERY_NEED", 1],
    "money:steady_income_boundary": ["AUTONOMY", 1],
    "investment:needs_simple_money_structure": "ADVICE",
    "investment:avoid_hype_and_pressure": "ADVICE",
    "investment:comfort_based_risk_filter": ["STABILITY", 1],
    "investment:small_experiment_record": ["PRACTICALITY", 1],
    "investment:aesthetic_attachment_risk": "UNSCORED_REFERENCE",
    "study:hands_on_learning": ["PRACTICALITY", 1, "LEARNING", 1],
    "study:flexible_goal_study": ["STRUCTURE_STYLE", -1],
    "study:concrete_praise_learning": ["PRACTICALITY", 1],
    "study:arts_literature_preference": "UNSCORED_REFERENCE",
    "study:comfortable_exam_routine": ["STABILITY", 1],
    "love:slow_open_romantic": ["ACTION_TEMPO", -2, "CARE", 1],
    "love:unspoken_crush_pattern": ["ENERGY_DIRECTION", -1, "CARE", 1],
    "love:devoted_to_partner_wishes": ["CARE", 2, "COMMUNICATION_STYLE", -1],
    "love:breakup_aftershock": "UNSCORED_REFERENCE",
    "marriage:freedom_needed_marriage": ["AUTONOMY", 2],
    "marriage:romantic_daily_care": ["CARE", 1],
    "marriage:silent_conflict_marriage": ["COMMUNICATION_STYLE", -2],
    "marriage:comfort_space_agreement": ["RECOVERY_NEED", 1, "STABILITY", 1],
    "marriage:quiet_budget_and_role": ["AUTONOMY", 1],
    "parenting:free_respecting_parent": ["AUTONOMY", 1, "LEARNING", 1],
    "parenting:friend_like_parent": ["CARE", 1, "RELATION_STYLE", 1],
    "parenting:experience_based_parenting": ["PRACTICALITY", 1, "LEARNING", 1],
    "child:fun_first_child": ["AUTONOMY", 1, "STRUCTURE_STYLE", -1],
    "child:visual_art_child": ["CREATION", 1, "EXPRESSION", 1],
    "child:peaceful_peer_child": ["CARE", 1, "RELATION_STYLE", -1],
    "child:nature_animals_child": "UNSCORED_REFERENCE",
    "relationships:harmony_before_argument": ["COMMUNICATION_STYLE", -1, "AUTONOMY", 1],
    "relationships:accepting_but_boundaried": ["ADAPTABILITY", 1, "BOUNDARY", 1],
    "relationships:easily_trusting": ["ADAPTABILITY", 1],
    "relationships:quiet_social_acceptance": ["RELATION_STYLE", 1, "ENERGY_DIRECTION", -1],
    "communication:silent_when_angry": ["COMMUNICATION_STYLE", -2, "ENERGY_DIRECTION", -1],
    "communication:hard_to_state_opinion": ["ACTION_TEMPO", -1],
    "communication:no_bad_words_to_others": ["COMMUNICATION_STYLE", -2],
    "strengths:aesthetic_sense": ["CREATION", 1, "PRECISION", 1],
    "strengths:embodied_expression": ["EXPRESSION", 2, "CREATION", 1],
    "strengths:real_time_empathy": ["SOCIAL_ATTUNEMENT", 2],
    "strengths:gentle_acceptance": ["ADAPTABILITY", 1, "CARE", 1],
    "risks:decision_delay": ["DECISION_STYLE", -2],
    "risks:low_self_esteem_from_acceptance": ["ADAPTABILITY", 1],
    "risks:mental_recovery_slow": ["RECOVERY_NEED", 2],
    "risks:comfort_over_ambition": "UNSCORED_REFERENCE",
    "risks:unhealthy_emotional_outburst": "UNSCORED_REFERENCE",
    "growth:practice_direct_boundaries": "ADVICE",
    "growth:decision_deadline": ["DECISION_STYLE", -1],
    "growth:structure_for_talent": "ADVICE",
    "growth:recover_before_withdrawing": "ADVICE",
  },
  ESTP: {
    "identity:action_first_realist": ["PRACTICALITY", 2, "ACTION_TEMPO", 1],
    "identity:sensory_thrill_seeker": ["RISK_STYLE", 1, "CHANGE_ORIENTATION", 1],
    "identity:open_minded_adapter": ["ADAPTABILITY", 2],
    "identity:playful_center_stage": ["EXPRESSION", 1, "STATUS_DRIVE", 1, "COMMUNICATION_STYLE", 1],
    "identity:freedom_over_control": ["AUTONOMY", 2],
    "identity:trouble_and_solution": ["RISK_STYLE", 1, "ADAPTABILITY", 1],
    "thinkingStyle:se_now_data": ["PRECISION", 1, "SOCIAL_ATTUNEMENT", 1, "ACTION_TEMPO", 1],
    "thinkingStyle:ti_practical_analysis": ["PRACTICALITY", 2],
    "thinkingStyle:fast_decision_objectivity": ["DECISION_STYLE", 1, "ACTION_TEMPO", 2, "PRACTICALITY", 1],
    "thinkingStyle:weak_ni_long_term_gap": ["OPPORTUNITY_SENSE", 1, "ACTION_TEMPO", 1],
    "thinkingStyle:fe_social_adjustment": ["SOCIAL_ATTUNEMENT", 1, "ADAPTABILITY", 1],
    "career:live_content_fit": ["EXPRESSION", 1, "ADAPTABILITY", 1],
    "career:fitness_sports_fit": ["COMPETITION", 1],
    "career:field_emergency_fit": ["ACTION_TEMPO", 1, "ADAPTABILITY", 1],
    "career:teacher_activity_fit": ["EXPRESSION", 1, "PRACTICALITY", 1],
    "career:travel_game_handson_fit": ["ADAPTABILITY", 1],
    "career:deal_to_repeat_business": ["OPPORTUNITY_SENSE", 2, "ACTION_TEMPO", 1],
    "workplace:crisis_solver": ["ADAPTABILITY", 2, "ACTION_TEMPO", 1],
    "workplace:low_tolerance_for_boredom": ["CHANGE_ORIENTATION", 1, "PRACTICALITY", 1],
    "workplace:flexible_negotiator": ["ADAPTABILITY", 2, "PRACTICALITY", 1],
    "workplace:visible_charisma": ["CHARISMA", 1, "ENERGY_DIRECTION", 1, "LEADERSHIP", 1],
    "workplace:fast_approval_lane": ["ACTION_TEMPO", 1, "AUTONOMY", 1],
    "money:high_income_action_drive": ["OPPORTUNITY_SENSE", 1, "ACTION_TEMPO", 1],
    "money:pleasure_spending_risk": ["CHANGE_ORIENTATION", 1],
    "money:deal_and_sales_income": ["SOCIAL_ATTUNEMENT", 1, "OPPORTUNITY_SENSE", 1],
    "money:quick_cashflow_volatility": ["ACTION_TEMPO", 2, "OPPORTUNITY_SENSE", 1],
    "money:thrill_spending_limit": ["RISK_STYLE", 1, "COMPETITION", 1],
    "money:loss_limit_rule": ["RISK_STYLE", 1, "COMPETITION", 1],
    "investment:risk_appetite": ["RISK_STYLE", 2, "OPPORTUNITY_SENSE", 1],
    "investment:short_term_market_sense": ["ACTION_TEMPO", 1, "ADAPTABILITY", 1],
    "investment:entry_limit_before_action": ["ACTION_TEMPO", 2, "OPPORTUNITY_SENSE", 1],
    "investment:short_term_bias_guard": ["ACTION_TEMPO", 1, "ADAPTABILITY", 1],
    "investment:loss_revenge_control": ["COMPETITION", 1, "ACTION_TEMPO", 1],
    "study:experiential_learning": ["PRACTICALITY", 1, "LEARNING", 1],
    "study:short_goal_strategy": "ADVICE",
    "study:low_gpa_but_practical_skill": "UNSCORED_REFERENCE",
    "study:error_record_short_loop": ["ACTION_TEMPO", 1, "COMPETITION", 1],
    "study:long_exam_pacing": ["ACTION_TEMPO", 1],
    "love:fun_active_love": ["CHANGE_ORIENTATION", 1, "RELATION_STYLE", 1],
    "love:freedom_in_love": ["AUTONOMY", 2],
    "love:active_affection": ["EXPRESSION", 2, "INITIATIVE", 1],
    "love:social_boundary_issue": ["RELATION_STYLE", 2],
    "marriage:dynamic_marriage": ["CHANGE_ORIENTATION", 1, "AUTONOMY", 1],
    "marriage:commitment_structure_need": ["AUTONOMY", 1],
    "marriage:fast_decision_cooling_rule": ["ACTION_TEMPO", 2, "DECISION_STYLE", 1],
    "marriage:freedom_time_contract": ["AUTONOMY", 2, "STRUCTURE_STYLE", -1],
    "marriage:risk_spending_limit": ["OPPORTUNITY_SENSE", 1, "ACTION_TEMPO", 1],
    "parenting:free_parenting": ["AUTONOMY", 2],
    "parenting:adventure_parent": ["CHANGE_ORIENTATION", 1, "CARE", 1],
    "parenting:self_development_support": ["CARE", 1, "PRACTICALITY", 1],
    "child:bet_and_play_child": ["COMPETITION", 1, "RISK_STYLE", 1],
    "child:easygoing_friend_child": ["ADAPTABILITY", 1],
    "child:serious_talk_avoidance_child": ["COMMUNICATION_STYLE", 1, "PRACTICALITY", 1],
    "child:happy_active_child": ["ENERGY_DIRECTION", 1],
    "relationships:wide_social_circle": ["RELATION_STYLE", 2, "ENERGY_DIRECTION", 1],
    "relationships:slow_to_cut_off": ["BOUNDARY", 1, "DECISION_STYLE", 1],
    "relationships:intent_reader": ["SOCIAL_ATTUNEMENT", 2, "PRECISION", 1],
    "relationships:low_grudge_high_motion": ["ADAPTABILITY", 1, "ACTION_TEMPO", 1],
    "communication:straight_humor": ["COMMUNICATION_STYLE", 2, "EXPRESSION", 1],
    "communication:short_explanation_preference": ["COMMUNICATION_STYLE", 1, "PRACTICALITY", 1],
    "communication:no_poker_face": ["EXPRESSION", 2],
    "communication:emotion_impatience": ["ACTION_TEMPO", 1, "DECISION_STYLE", 1],
    "strengths:instant_adaptation": ["ADAPTABILITY", 2],
    "strengths:sharp_observation": ["PRECISION", 2, "SOCIAL_ATTUNEMENT", 1],
    "strengths:fearless_initiative": ["INITIATIVE", 2, "RISK_STYLE", 1, "OPPORTUNITY_SENSE", 1],
    "strengths:social_energy": ["ENERGY_DIRECTION", 2, "RELATION_STYLE", 1],
    "risks:impulsive_risk": ["RISK_STYLE", 2, "ACTION_TEMPO", 1],
    "risks:low_long_term_persistence": "UNSCORED_REFERENCE",
    "risks:emotional_bluntness": "UNSCORED_REFERENCE",
    "risks:freedom_responsibility_conflict": ["AUTONOMY", 2],
    "risks:destructive_unhealthy_gap": "UNSCORED_REFERENCE",
    "growth:build_short_to_long_goals": "ADVICE",
    "growth:check_impact_before_action": "ADVICE",
    "growth:design_responsible_freedom": ["AUTONOMY", 1],
    "growth:use_observation_with_verification": ["PRECISION", 1],
  },
  ESFP: {
    "identity:present_moment_star": ["SOCIAL_ATTUNEMENT", 1, "ACTION_TEMPO", 1],
    "identity:social_easy_openness": ["RELATION_STYLE", 2, "ADAPTABILITY", 1],
    "identity:sensory_realist": ["PRACTICALITY", 2],
    "identity:joy_first_life": ["CHANGE_ORIENTATION", 1, "RELATION_STYLE", 1],
    "identity:personal_preference_clarity": ["BOUNDARY", 1],
    "identity:spotlight_identity": ["STATUS_DRIVE", 1, "EXPRESSION", 2],
    "thinkingStyle:experience_based_learning": ["PRACTICALITY", 1, "LEARNING", 1],
    "thinkingStyle:anti_theory_bias": ["PRACTICALITY", 1, "CURIOSITY", 1],
    "thinkingStyle:broad_shallow_curiosity": ["CURIOSITY", 2],
    "thinkingStyle:late_start_pressure": ["ACTION_TEMPO", -1, "STRUCTURE_STYLE", -1],
    "thinkingStyle:emotion_protective_optimism": ["RELATION_STYLE", 1, "RECOVERY_NEED", 1],
    "career:entertainment_fit": ["EXPRESSION", 1, "SOCIAL_ATTUNEMENT", 1],
    "career:sales_service_fit": ["RELATION_STYLE", 1, "SOCIAL_ATTUNEMENT", 1],
    "career:free_environment_performance": ["AUTONOMY", 1],
    "career:atmosphere_role": ["EXPRESSION", 1, "SOCIAL_ATTUNEMENT", 1],
    "career:responsibility_avoidance_risk": "UNSCORED_REFERENCE",
    "career:experience_content_revenue": ["SOCIAL_ATTUNEMENT", 1, "EXPRESSION", 1],
    "workplace:anti_bureaucracy_work": ["AUTONOMY", 2],
    "workplace:people_nearby_energy": ["ENERGY_DIRECTION", 2, "RELATION_STYLE", 1],
    "workplace:improvised_action": ["ADAPTABILITY", 2, "STRUCTURE_STYLE", -1],
    "workplace:finish_line_weakness": ["INITIATIVE", 1],
    "workplace:messy_detail_risk": ["ACTION_TEMPO", 1],
    "workplace:responsive_team_needed": ["RELATION_STYLE", 1, "STATUS_DRIVE", 1],
    "money:experience_spending": ["CHANGE_ORIENTATION", 1, "RELATION_STYLE", 1],
    "money:income_from_people_contact": "UNSCORED_REFERENCE",
    "money:short_term_reward_bias": ["ACTION_TEMPO", 1],
    "money:expression_service_income": ["EXPRESSION", 1, "SOCIAL_ATTUNEMENT", 1],
    "money:beauty_social_spending": ["RELATION_STYLE", 1, "EXPRESSION", 1],
    "money:auto_saving_before_fun": "ADVICE",
    "investment:impulse_investment_risk": ["ACTION_TEMPO", 1, "SOCIAL_ATTUNEMENT", 1],
    "investment:cooling_time_rule": ["ACTION_TEMPO", 2],
    "investment:auto_diversification_rule": ["CHANGE_ORIENTATION", 1],
    "investment:social_reaction_filter": ["SOCIAL_ATTUNEMENT", 2],
    "investment:short_goal_money_plan": "ADVICE",
    "study:study_sitting_dislike": ["CHANGE_ORIENTATION", 1],
    "study:short_memory_subject_strength": "UNSCORED_REFERENCE",
    "study:goal_split_strategy": "ADVICE",
    "study:social_explain_learning": ["EXPRESSION", 1, "RELATION_STYLE", 1],
    "study:boring_repeat_reward": ["ACTION_TEMPO", -1],
    "love:expressive_love_style": ["EXPRESSION", 2, "RELATION_STYLE", 1],
    "love:romantic_surprise": ["CARE", 1, "STRUCTURE_STYLE", -1],
    "love:quick_change_love": ["CHANGE_ORIENTATION", 1],
    "love:together_time_need": ["RELATION_STYLE", 2],
    "marriage:fun_household_partner": ["CHANGE_ORIENTATION", 1, "RELATION_STYLE", 1],
    "marriage:freedom_in_marriage": ["AUTONOMY", 2, "STRUCTURE_STYLE", -1],
    "marriage:post_break_low_attachment": "UNSCORED_REFERENCE",
    "marriage:expression_budget_rhythm": ["EXPRESSION", 2, "CARE", 1],
    "marriage:shared_attention_security": ["RELATION_STYLE", 2],
    "parenting:open_parenting": ["AUTONOMY", 1, "RELATION_STYLE", 1],
    "parenting:travel_parenting": ["CHANGE_ORIENTATION", 1, "LEARNING", 1],
    "parenting:fun_support_parent": ["CARE", 1],
    "parenting:social_child_growth": ["RELATION_STYLE", 1],
    "child:active_outdoor_child": ["ENERGY_DIRECTION", 2, "RELATION_STYLE", 1],
    "child:popular_class_energy": ["RELATION_STYLE", 1, "LEADERSHIP", 1],
    "child:style_sensitive_child": ["EXPRESSION", 1],
    "child:arts_sports_child": ["EXPRESSION", 1],
    "relationships:no_prejudice_acceptance": ["ADAPTABILITY", 1, "RELATION_STYLE", 1],
    "relationships:story_and_episode_talk": ["EXPRESSION", 2],
    "relationships:emotion_visible_relation": ["EXPRESSION", 2],
    "relationships:introvert_bridge": ["CARE", 1, "SOCIAL_ATTUNEMENT", 1],
    "communication:honest_self_disclosure": ["EXPRESSION", 1, "COMMUNICATION_STYLE", 1, "RELATION_STYLE", 1],
    "communication:many_words_low_structure": ["EXPRESSION", 1],
    "communication:not_saying_real_point": ["COMMUNICATION_STYLE", -1, "EXPRESSION", 1],
    "communication:value_opinion_talk": ["MEANING", 1, "EXPRESSION", 1],
    "strengths:high_adaptability": ["ADAPTABILITY", 2, "PRACTICALITY", 1],
    "strengths:optimistic_energy": ["CARE", 1],
    "strengths:practical_common_sense": ["PRACTICALITY", 2],
    "strengths:surprise_generosity": ["CARE", 2, "INITIATIVE", 1],
    "risks:boredom_intolerance": ["CHANGE_ORIENTATION", 1],
    "risks:impulsive_emotion": ["ACTION_TEMPO", 1, "EXPRESSION", 1],
    "risks:irresponsible_fun_loop": "UNSCORED_REFERENCE",
    "risks:control_conflict": ["AUTONOMY", 2],
    "risks:low_deep_focus": ["CURIOSITY", 1],
    "growth:make_fun_responsible": "ADVICE",
    "growth:build_finish_system": ["INITIATIVE", 1],
    "growth:practice_depth": "ADVICE",
    "growth:slow_down_emotion_decision": "ADVICE",
  },
} as const satisfies Record<string, TypeAnnotationManifest>;
