import { HUMAN_GOLDEN_LANGUAGE as golden } from "./humanDescription";
import { r, a, all, any, claim, fusion, risk, limited, synthesis } from "./personalResonanceRules";

export const WORK_VALUE_RESONANCE = [
  r("PR025", "CRISIS_BEHAVIOR", "PRESSURE_LEADERSHIP", ["LEADERSHIP", "DUTY"], all(a("LEADERSHIP"), a("DUTY"), risk("PRESSURE")),
    "평소에는 굳이 앞에 나서지 않아도 일이 꼬이면 결국 직접 정리하려는 편입니다.", { contexts: ["work", "stress"], arcTheme: "LEADERSHIP_AND_RESPONSIBILITY",
      positiveMeaning: "일이 복잡해질 때 해야 할 일을 정리하고 책임지는 데 강점이 있습니다.", specificityBase: .9 }),
  r("PR026", "STRENGTH_TO_SHADOW", "DO_IT_MYSELF", ["AUTONOMY", "DUTY", "GOAL_DRIVE"], all(a("AUTONOMY", "STRONG"), any(a("DUTY"), a("GOAL_DRIVE"))), "남에게 맡길 수 있는 일도 내가 하는 게 더 빠르다고 생각하면 직접 가져올 때가 있습니다.", { contexts: ["identity", "work"], polarity: "shadow" }),
  r("PR027", "VALUE", "RESULT_BEFORE_PRAISE", ["PRACTICALITY", "GOAL_DRIVE"], all(a("PRACTICALITY"), a("GOAL_DRIVE")), "잘했다는 말보다 실제 결과가 남았을 때 더 만족하는 편입니다.", { semanticGroup: "RESULT_SATISFACTION" }),
  r("PR028", "ACHIEVEMENT_PATTERN", "NEXT_GOAL_FAST", ["GOAL_DRIVE", "EXPANSION"], all(a("GOAL_DRIVE", "STRONG"), a("EXPANSION")), "하나를 해내도 오래 만족하기보다 다음에 더 잘할 방법부터 생각합니다.", { arcTheme: "GROWTH_AND_EXPANSION", positiveMeaning: "분명한 목표가 있을 때 추진력과 집중력이 살아납니다." }),
  r("PR029", "VALUE", "RECOGNITION_MATTERS", ["STATUS_DRIVE", "GOAL_DRIVE"], all(a("STATUS_DRIVE"), a("GOAL_DRIVE")), "잘하는 것만큼 그 결과를 제대로 인정받는 것도 중요하게 생각합니다.", { semanticGroup: "RECOGNITION" }),
  r("PR030", "ACHIEVEMENT_PATTERN", "HIGH_POSITION_DESIRE", ["STATUS_DRIVE", "LEADERSHIP"], any(claim("S03"), all(claim("S07"), any(claim("S01"), claim("S02")))),
    "실력을 쌓는 데서 끝나기보다 더 높은 직책에서 직접 결정하고 인정받고 싶어 하는 마음도 있습니다.", { contexts: ["work"], semanticGroup: "RECOGNITION" }),
  r("PR031", "ACHIEVEMENT_PATTERN", "EXPERT_THEN_RECOGNITION", ["LEARNING", "DEPTH", "STATUS_DRIVE"], all(claim("SU04"), a("STATUS_DRIVE")),
    "높은 자리를 원하더라도 실력 없이 자리만 얻는 것보다는 전문성을 인정받아 올라가고 싶어 합니다.", { contexts: ["work", "learning"], semanticGroup: "RECOGNITION" }),
  r("PR032", "ACHIEVEMENT_PATTERN", "COMPETITION_AS_FUEL", ["COMPETITION", "GOAL_DRIVE"], all(a("COMPETITION"), a("GOAL_DRIVE")), "남과 경쟁하고 싶지 않다고 생각해도 잘하는 사람이 가까이 있으면 은근히 더 세게 움직일 수 있습니다."),
  r("PR033", "VALUE", "RULE_WITH_REASON", ["AUTONOMY", "CURIOSITY", "DUTY"], synthesis("BETTER_RULE_NOT_BLIND_RULE"), "'시키니까 그냥 해'라는 말보다 왜 해야 하는지 납득돼야 더 잘 움직입니다.", { contexts: ["work", "social"] }),
  r("PR034", "ACHIEVEMENT_PATTERN", "OWN_METHOD_RESULT", ["AUTONOMY", "CREATION", "PRACTICALITY"], all(a("AUTONOMY"), any(a("CREATION"), a("PRACTICALITY"))), "남이 정해준 방식대로 잘하는 것보다 자기 방법으로 실제 결과를 만드는 데 더 만족합니다."),
  r("PR035", "ACHIEVEMENT_PATTERN", "RELIABLE_ACCURACY", ["DUTY", "PRECISION"], all(a("DUTY"), a("PRECISION")), "맡은 일을 끝내는 것뿐 아니라 틀리지 않게 제대로 끝내려고 합니다.", { semanticGroup: "HIGH_STANDARDS" }),
  r("PR036", "ACHIEVEMENT_PATTERN", "BIG_SCALE_MOTIVATION", ["EXPANSION", "OPPORTUNITY_SENSE"], any(claim("SU03"), all(a("EXPANSION", "STRONG"), a("OPPORTUNITY_SENSE"))), "작은 일을 반복할 때보다 점점 더 큰 일이나 새로운 기회를 맡을 때 동기가 살아나는 편입니다."),
  r("PR037", "MONEY_VALUE", "MONEY_AND_MEANING", ["RESOURCE_SENSE", "MEANING"], any(claim("M07"), fusion("C040")), golden.moneyMeaning,
    { contexts: ["identity", "work", "money"], semanticGroup: "MONEY_MEANING", arcTheme: "MONEY_AND_REALITY", specificityBase: .9,
      positiveMeaning: "돈과 시간이 실제로 얼마나 남는지를 현실적으로 판단하는 데 강점이 있습니다." }),
  r("PR038", "MONEY_VALUE", "MONEY_AND_TIME", ["RESOURCE_SENSE", "AUTONOMY"], all(a("RESOURCE_SENSE"), a("AUTONOMY")), "돈을 많이 받아도 내 시간을 지나치게 빼앗기면 좋은 거래라고 느끼지 않습니다.", { contexts: ["identity", "work", "money"], optionalSupport: [fusion("C041")] }),
  r("PR039", "MONEY_VALUE", "SAVE_AND_KEEP", ["RESOURCE_SENSE", "STABILITY"], claim("M02"), "버는 것만큼 남기고 쌓아두는 것도 중요하게 생각합니다.", { contexts: ["money", "identity"], arcTheme: "MONEY_AND_REALITY", positiveMeaning: "한 번의 수입보다 오래 남을 돈과 생활의 기반을 살피는 데 장점이 있습니다." }),
  r("PR040", "MONEY_VALUE", "MONEY_OPPORTUNITY", ["RESOURCE_SENSE", "OPPORTUNITY_SENSE"], claim("M03"), "새로운 사람이나 상황을 볼 때 재미뿐 아니라 돈이 될 가능성도 같이 봅니다.", { contexts: ["money", "work"] }),
  r("PR041", "MONEY_VALUE", "CAREFUL_MONEY", ["RESOURCE_SENSE", "RISK_STYLE"], all(a("RESOURCE_SENSE"), a("RISK_STYLE", "MAIN", -1)), "돈 문제에서는 좋은 기회보다 손해가 얼마나 날 수 있는지부터 확인하는 편입니다.", { contexts: ["money"] }),
  r("PR042", "MONEY_VALUE", "MONEY_GOAL", ["RESOURCE_SENSE", "GOAL_DRIVE"], claim("M06"), "원하는 수입이나 재산 규모가 생기면 그것도 하나의 목표처럼 생각하고 움직입니다.", { contexts: ["money", "identity"] }),
  r("PR043", "DUAL_DESIRE", "MONEY_AND_RECOGNITION", ["RESOURCE_SENSE", "STATUS_DRIVE"], all(a("RESOURCE_SENSE"), a("STATUS_DRIVE")), "돈만 많이 버는 것도 부족하고, 인정만 받는 것도 부족하다고 느낄 수 있습니다.", { contexts: ["money", "identity", "work"], semanticGroup: "MONEY_RECOGNITION" }),
  r("PR044", "DUAL_DESIRE", "STABLE_MONEY_NEW_OPPORTUNITY", ["STABILITY", "RESOURCE_SENSE", "OPPORTUNITY_SENSE"], all(claim("M05"), any(claim("M03"), a("OPPORTUNITY_SENSE"))), "꾸준히 들어오는 돈은 필요하지만 새로운 기회까지 놓치고 싶지는 않아 합니다.", { contexts: ["money", "work"] }),
  r("PR045", "STRENGTH_TO_SHADOW", "MEANING_OVER_MONEY_RISK", ["MEANING", "RESOURCE_SENSE"], all(a("MEANING", "STRONG"), any(limited("RESOURCE_SENSE"), risk("MEANING_OVER_MONEY"))), "좋아하고 의미 있는 일이라면 돈 문제를 뒤로 미루고 싶어질 때가 있습니다.", { contexts: ["money", "work"], polarity: "shadow", semanticGroup: "MONEY_MEANING" }),
  r("PR046", "STRENGTH_TO_SHADOW", "MONEY_OVER_MEANING_RISK", ["RESOURCE_SENSE", "MEANING"], all(a("RESOURCE_SENSE", "STRONG"), limited("MEANING"), risk("MONEY_OVER_MEANING")), "현실적인 보상에 집중하다 보면 내가 왜 이 일을 시작했는지를 뒤늦게 다시 생각할 때가 있을 수 있습니다.", { contexts: ["money", "work"], polarity: "shadow", semanticGroup: "MONEY_MEANING" }),
  r("PR047", "MONEY_VALUE", "OPPORTUNITY_BUT_CALCULATED", ["OPPORTUNITY_SENSE", "PRACTICALITY", "RISK_STYLE"], all(a("OPPORTUNITY_SENSE"), any(a("PRACTICALITY"), a("RISK_STYLE", "MAIN", -1))), "새로운 기회를 좋아해도 실제로 돈과 시간이 남는지는 꼭 계산하는 편입니다.", { contexts: ["money", "work"] }),
  r("PR048", "DUAL_DESIRE", "WEALTH_AND_HONOR_DESIRE", ["RESOURCE_SENSE", "STATUS_DRIVE", "GOAL_DRIVE"], any(claim("S08", 3), all(claim("M06"), claim("S07"))), "돈도 벌고 싶고, 그 결과를 제대로 인정받고도 싶어 합니다.", { contexts: ["identity", "work", "money"], semanticGroup: "MONEY_RECOGNITION" }),
];
