import { HUMAN_GOLDEN_LANGUAGE as golden } from "./humanDescription";
import { r, a, all, any, claim, fusion, split, risk, limited } from "./personalResonanceRules";

export const THINKING_ACTION_RESONANCE = [
  r("PR001", "BEHAVIOR_PROCESS", "THINK_THEN_MOVE", ["DEPTH", "ACTION_TEMPO"], any(all(a("DEPTH"), a("ACTION_TEMPO")), split("BEFORE_AFTER_DECISION")), golden.thinkMove,
    { optionalSupport: [split("BEFORE_AFTER_DECISION")], positiveMeaning: "신중함과 실행 속도를 따로 쓸 수 있습니다.", specificityBase: .94, semanticGroup: "DECISION_RHYTHM" }),
  r("PR002", "PERSONALITY", "SOFT_SPEECH_FIRM_BELIEF", ["AUTONOMY", "BOUNDARY", "COMMUNICATION_STYLE"], all(any(a("AUTONOMY"), a("BOUNDARY")), a("COMMUNICATION_STYLE", "MAIN", -1)), golden.softBelief,
    { semanticGroup: "SOFT_FIRM", specificityBase: .92 }),
  r("PR003", "PERCEPTION_STYLE", "PRECISE_FIRST", ["PRECISION"], a("PRECISION", "STRONG"), golden.precision,
    { semanticGroup: "HIGH_STANDARDS", arcTheme: "PRECISION_AND_STANDARDS", optionalSupport: [claim("F03")],
      positiveMeaning: "다른 사람이 놓친 오류를 찾고 결과물의 완성도를 높이는 데 강점이 있습니다." }),
  r("PR004", "BEHAVIOR_PROCESS", "WHY_UNTIL_CONVINCED", ["DEPTH", "CURIOSITY"], all(a("DEPTH"), a("CURIOSITY")), "대충 맞는 설명보다 왜 그런지 스스로 납득될 때까지 확인하는 편입니다.",
    { arcTheme: "DEEP_UNDERSTANDING", positiveMeaning: "복잡한 문제를 깊게 이해하는 데 강점이 있습니다." }),
  r("PR005", "BEHAVIOR_PROCESS", "MANY_OPTIONS_SLOW_CHOICE", ["PATTERN_SENSE", "CURIOSITY", "DECISION_STYLE", "ACTION_TEMPO"],
    all(any(a("PATTERN_SENSE"), a("CURIOSITY")), any(a("DECISION_STYLE", "MAIN", -1), a("ACTION_TEMPO", "MAIN", -1))), "가능성을 많이 보는 만큼 하나를 고르는 순간은 늦어질 수 있습니다.", { polarity: "shadow", semanticGroup: "DECISION_RHYTHM" }),
  r("PR006", "PERSONALITY", "BIG_PICTURE_SMALL_ERROR", ["STRATEGY", "PRECISION"], all(a("STRATEGY"), a("PRECISION")), "멀리 보면서도 작은 틀림까지 같이 보는 편입니다.", { semanticGroup: "HIGH_STANDARDS" }),
  r("PR007", "BEHAVIOR_PROCESS", "THINK_AND_RECHECK", ["DEPTH", "PRECISION"], all(a("DEPTH"), a("PRECISION")), "답을 낸 뒤에도 빠진 게 없는지 한 번 더 확인하는 편입니다.", { semanticGroup: "HIGH_STANDARDS", optionalSupport: [claim("F03"), claim("F05")] }),
  r("PR008", "CRISIS_BEHAVIOR", "CLEAR_HEAD_UNDER_PRESSURE", ["STRATEGY", "DECISION_STYLE", "DUTY"], all(a("STRATEGY"), a("DECISION_STYLE"), a("DUTY"), risk("PRESSURE")),
    "일이 급해지면 먼저 해야 할 순서를 정하고 해결 쪽으로 움직이는 편입니다.", { contexts: ["stress", "work"], alternatives: [{ when: risk("CALM_PRESSURE"), text: golden.calmPressure }], specificityBase: .94 }),
  r("PR009", "BEHAVIOR_PROCESS", "IDEA_FLEX_EXECUTE_STRUCTURED", ["STRUCTURE_STYLE", "ADAPTABILITY"], any(fusion("C090"), split("IDEA_EXECUTION")),
    "아이디어를 생각할 때는 유연하지만, 실제로 움직일 때는 기준과 계획을 세우고 싶어 합니다.", { specificityBase: .93 }),
  r("PR010", "PERSONALITY", "FAST_BUT_NOT_RECKLESS", ["ACTION_TEMPO", "STRATEGY", "PRECISION"], all(a("ACTION_TEMPO"), any(a("STRATEGY"), a("PRECISION"))),
    "움직이는 속도는 빠르지만, 아무 생각 없이 덤비는 사람은 아닙니다.", { semanticGroup: "DECISION_RHYTHM" }),
  r("PR011", "BEHAVIOR_PROCESS", "LEARN_IN_OWN_WAY", ["LEARNING", "AUTONOMY"], all(a("LEARNING"), a("AUTONOMY")),
    "남에게 배워도 마지막에는 자기 방식으로 이해해야 제대로 알았다고 느끼는 편입니다.", { contexts: ["identity", "learning", "work"], optionalSupport: [fusion("C069")] }),
  r("PR012", "BEHAVIOR_PROCESS", "QUESTION_TO_OUTPUT", ["CURIOSITY", "CREATION"], all(a("CURIOSITY"), a("CREATION")),
    "궁금한 것을 알아보는 데서 끝내지 않고 결국 자기 생각이나 결과로 꺼내고 싶어 합니다.", { contexts: ["identity", "learning", "work"], positiveMeaning: "새롭게 알아낸 것을 남이 볼 수 있는 결과로 만드는 데 장점이 있습니다." }),
  r("PR013", "ACHIEVEMENT_PATTERN", "FAST_START_STRONG_FINISH", ["INITIATIVE", "PERSISTENCE"], all(a("INITIATIVE"), a("PERSISTENCE")), "시작도 빠른 편이고, 한번 시작한 일도 쉽게 놓지 않습니다.", { semanticGroup: "EXECUTION_ENDURANCE" }),
  r("PR014", "STRENGTH_TO_SHADOW", "FAST_START_WEAK_FINISH", ["INITIATIVE", "PERSISTENCE"], all(a("INITIATIVE"), any(limited("PERSISTENCE"), risk("FINISH_DROP"))),
    "시작할 때는 힘이 잘 붙지만 재미가 떨어진 뒤 마무리까지 끌고 가는 건 별개의 문제일 수 있습니다.", { polarity: "shadow", semanticGroup: "EXECUTION_ENDURANCE", forbiddenConditions: [a("PERSISTENCE", "STRONG")] }),
  r("PR015", "BEHAVIOR_PROCESS", "SLOW_START_LONG_RUN", ["ACTION_TEMPO", "PERSISTENCE"], all(a("ACTION_TEMPO", "MAIN", -1), a("PERSISTENCE")), "시작은 빠르지 않아도 한번 시작한 일은 꽤 오래 갑니다.", { semanticGroup: "EXECUTION_ENDURANCE" }),
  r("PR016", "BEHAVIOR_PROCESS", "START_AND_ADJUST", ["INITIATIVE", "ADAPTABILITY"], all(a("INITIATIVE"), a("ADAPTABILITY")), "처음부터 완벽한 답을 기다리기보다 일단 움직인 뒤 방법을 바꿔가는 편입니다."),
  r("PR017", "PERSONALITY", "GOAL_FIXED_METHOD_FLEXIBLE", ["GOAL_DRIVE", "ADAPTABILITY"], all(a("GOAL_DRIVE"), a("ADAPTABILITY")), "어디로 갈지는 쉽게 바꾸지 않지만, 가는 방법은 상황에 맞게 바꾸는 편입니다."),
  r("PR018", "DUAL_DESIRE", "GROWTH_AND_STABILITY", ["EXPANSION", "STABILITY"], all(a("EXPANSION"), a("STABILITY")), "더 성장하고 싶어 하면서도 생활과 기반까지 불안정해지는 건 원하지 않습니다.", { semanticGroup: "CHANGE_AND_BASE", specificityBase: .90 }),
  r("PR019", "DUAL_DESIRE", "NEW_WORK_STABLE_LIFE", ["CHANGE_ORIENTATION", "STABILITY"], all(a("CHANGE_ORIENTATION"), a("STABILITY")), golden.newStable, { semanticGroup: "CHANGE_AND_BASE", specificityBase: .93 }),
  r("PR020", "STRENGTH_TO_SHADOW", "TOO_MANY_STARTS", ["INITIATIVE", "EXPANSION"], all(a("INITIATIVE", "STRONG"), a("EXPANSION"), any(claim("F08"), claim("M10"), risk("FINISH_DROP"))),
    "하고 싶은 일이 생길 때마다 시작해서 벌여놓은 일이 많아질 수 있습니다.", { polarity: "shadow" }),
  r("PR021", "ACHIEVEMENT_PATTERN", "RESULT_REQUIRED", ["GOAL_DRIVE", "PRACTICALITY"], all(a("GOAL_DRIVE"), a("PRACTICALITY")), "잘 생각했다는 것보다 실제로 결과가 남아야 만족하는 편입니다.", { semanticGroup: "RESULT_SATISFACTION" }),
  r("PR022", "BEHAVIOR_PROCESS", "BUILD_AND_SHOW", ["CREATION", "EXPRESSION"], all(a("CREATION"), a("EXPRESSION")), "생각만 하고 끝내기보다 직접 만들어 보여줘야 만족하는 편입니다.", { positiveMeaning: "머릿속 생각을 다른 사람에게 전달할 수 있는 결과로 만드는 데 강점이 있습니다." }),
  r("PR023", "BEHAVIOR_PROCESS", "GROW_AND_CORRECT", ["EXPANSION", "PRECISION"], all(a("EXPANSION"), a("PRECISION")), "앞으로 나아가면서도 잘못 가고 있는 부분은 바로 고치고 싶어 합니다.", { semanticGroup: "GROWTH_STANDARDS" }),
  r("PR024", "DUAL_DESIRE", "CHANGE_WITH_BASE", ["CHANGE_ORIENTATION", "STABILITY"], all(a("CHANGE_ORIENTATION"), a("STABILITY")), "새로운 걸 해보고 싶어도 돌아올 기본 생활과 기준 하나는 있어야 편합니다.", { semanticGroup: "CHANGE_AND_BASE", optionalSupport: [fusion("C024"), fusion("C096")] }),
];
