import type { FusionKnowledgeRule } from "./fusionKnowledgeTypes";

type FusionRuleInput = Omit<FusionKnowledgeRule, "phraseSeeds"> & {
  readonly phraseSeeds?: readonly string[];
};

function createFusionRule(input: FusionRuleInput): FusionKnowledgeRule {
  return {
    ...input,
    phraseSeeds:
      input.phraseSeeds ??
      [
        input.summary,
        input.advice ?? input.caution ?? input.interpretation,
      ],
  };
}

export const FUSION_KNOWLEDGE_BASE: readonly FusionKnowledgeRule[] = [
  createFusionRule({
    id: "fusion_wealth_strong_entj_achievement",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_pian_cai", "ten_god_zheng_cai", "pattern_jaeda_sinyak"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["money_orientation"],
    requiredMbtiTags: ["achievement_drive"],
    topic: "money_asset",
    priority: 100,
    summary: "재성 강함 + ENTJ 성취욕",
    interpretation:
      "사주에서 재성의 현실 감각이 강하고 ENTJ의 성취 지향이 겹치면 돈을 목표와 구조로 보는 힘이 커집니다.",
    caution: "자원 관리가 곧 자기 가치처럼 느껴지면 쉬는 시간이 밀릴 수 있습니다.",
    advice: "돈 목표와 회복 기준을 같은 표 안에 넣어야 지속성이 생깁니다.",
  }),
  createFusionRule({
    id: "fusion_gapsin_entj_leadership_control",
    kind: "reinforcement",
    sajuEntryIds: ["day_pillar_gapsin", "day_master_gabmok"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["leadership"],
    requiredMbtiTags: ["control_need"],
    topic: "personality",
    priority: 99,
    summary: "갑신일주 + ENTJ leadership/control",
    interpretation:
      "갑목의 방향성과 갑신일주의 압박 대응력 위에 ENTJ의 통제 욕구가 얹히면 판을 직접 잡고 싶어집니다.",
    caution: "주도권이 강해질수록 상대의 속도를 놓치기 쉽습니다.",
    advice: "목표 공유를 먼저 하고 지시를 나중에 두면 장악력이 협업력으로 바뀝니다.",
  }),
  createFusionRule({
    id: "fusion_qi_sha_entj_responsibility",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_qi_sha"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["responsibility_pressure"],
    requiredMbtiTags: ["responsibility_pressure"],
    topic: "personality",
    priority: 98,
    summary: "편관 + ENTJ responsibility_pressure",
    interpretation:
      "편관의 압박 감각과 ENTJ의 책임 지향이 겹치면 위기나 과제가 있을 때 더 빠르게 지휘 모드로 들어갑니다.",
    caution: "긴장을 성과로 바꾸는 힘이 있지만 몸의 피로 신호는 늦게 알아차릴 수 있습니다.",
    advice: "책임을 맡는 기준과 내려놓는 기준을 함께 정해 두는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_zheng_guan_entj_authority",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_zheng_guan"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["authority_orientation"],
    requiredMbtiTags: ["authority_orientation"],
    topic: "personality",
    priority: 97,
    summary: "정관 + ENTJ authority_orientation",
    interpretation:
      "정관의 질서와 ENTJ의 조직 장악력이 맞물리면 기준을 세우고 역할을 공식화하는 힘이 강해집니다.",
    caution: "기준이 높아질수록 사람을 평가하는 시선도 날카로워질 수 있습니다.",
    advice: "기준을 말하기 전에 왜 필요한지 설명하면 권위가 신뢰로 전달됩니다.",
  }),
  createFusionRule({
    id: "fusion_hyeonchim_entj_direct_speech",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_hyeonchim"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["sharp_analysis"],
    requiredMbtiTags: ["direct_speech"],
    topic: "human_relations",
    priority: 96,
    summary: "현침살 + ENTJ 직설성",
    interpretation:
      "현침살의 예리함과 ENTJ의 바로 말하는 방식이 겹치면 핵심을 빠르게 짚지만 상대가 압박으로 받을 수 있습니다.",
    caution: "정답을 말하는 속도보다 상대가 받아들일 여백이 중요합니다.",
    advice: "결론 전에 의도 한 문장을 붙이면 날카로움이 실력으로 남습니다.",
  }),
  createFusionRule({
    id: "fusion_water_no_resource_entj_dryness",
    kind: "compensation",
    sajuEntryIds: ["element_water_missing", "pattern_no_resource"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["emotional_dryness"],
    requiredMbtiTags: ["emotional_dryness"],
    topic: "weaknesses",
    priority: 95,
    summary: "수 부족/무인성 + ENTJ emotional_dryness",
    interpretation:
      "수 부족과 무인성의 회복 약점에 ENTJ의 해결 중심 태도가 더해지면 감정을 처리하기 전에 결론부터 내기 쉽습니다.",
    caution: "감정이 없는 것이 아니라 감정이 순환되는 통로가 좁아질 수 있습니다.",
    advice: "판단 전에 감정 확인 루틴을 넣어야 관계와 체력이 같이 버팁니다.",
  }),
  createFusionRule({
    id: "fusion_water_missing_entj_emotional_dryness",
    kind: "reinforcement",
    sajuEntryIds: ["element_water_missing"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["emotional_dryness"],
    requiredMbtiTags: ["emotional_dryness"],
    topic: "love_relationship",
    priority: 94,
    summary: "수 부족 + ENTJ 감정 건조함",
    interpretation:
      "수 부족의 감정 완충 약점과 ENTJ의 결과 우선성이 겹치면 관계에서 공감보다 해결책이 먼저 나올 수 있습니다.",
    caution: "상대는 해결보다 정서 확인을 먼저 원할 수 있습니다.",
    advice: "조언 전에 감정 확인을 한 번 넣으면 관계 피로가 줄어듭니다.",
  }),
  createFusionRule({
    id: "fusion_fire_no_output_entj_expression_contrast",
    kind: "contrast",
    sajuEntryIds: ["element_fire_missing", "pattern_no_output"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["expression_weakness"],
    requiredMbtiTags: ["leadership"],
    topic: "personality",
    priority: 93,
    summary: "화 부족 + ENTJ 외향성 contrast",
    interpretation:
      "ENTJ처럼 밖으로 밀고 가는 자기상이 있어도 사주에서 화나 식상이 약하면 표현 온도는 생각보다 늦게 켜질 수 있습니다.",
    caution: "활동성과 애정 표현은 같은 능력이 아닙니다.",
    advice: "성과 언어와 감정 언어를 분리해 준비하면 오해가 줄어듭니다.",
  }),
  createFusionRule({
    id: "fusion_no_output_entj_self_promotion",
    kind: "contrast",
    sajuEntryIds: ["pattern_no_output"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["expression_weakness"],
    requiredMbtiTags: ["leadership"],
    topic: "work_career",
    priority: 92,
    summary: "무식상 + ENTJ 자기 어필 contrast",
    interpretation:
      "ENTJ의 추진력은 강하지만 무식상 구조가 있으면 실력은 있는데 자기 어필이 딱딱하거나 늦게 나올 수 있습니다.",
    caution: "성과를 낸 뒤 설명이 부족하면 주변은 의도를 놓칠 수 있습니다.",
    advice: "일의 목적, 과정, 결과를 짧게 공개하는 루틴이 필요합니다.",
  }),
  createFusionRule({
    id: "fusion_jaeda_sinyak_entj_workaholic",
    kind: "reinforcement",
    sajuEntryIds: ["pattern_jaeda_sinyak"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["burnout_risk"],
    requiredMbtiTags: ["achievement_drive"],
    topic: "weaknesses",
    priority: 91,
    summary: "재다신약 + ENTJ 워커홀릭",
    interpretation:
      "재다신약의 책임 압박과 ENTJ의 목표 몰입이 겹치면 일을 멈추는 기준이 흐려질 수 있습니다.",
    caution: "성과가 나와도 몸과 감정의 잔고는 따로 확인해야 합니다.",
    advice: "일정표에 쉬는 칸을 먼저 고정하는 방식이 맞습니다.",
  }),
  createFusionRule({
    id: "fusion_earth_excess_entj_reality",
    kind: "reinforcement",
    sajuEntryIds: ["element_earth_excess"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["asset_building"],
    requiredMbtiTags: ["efficiency_focus"],
    topic: "money_asset",
    priority: 90,
    summary: "토 과다 + ENTJ 현실성",
    interpretation:
      "토의 저장성과 ENTJ의 효율감이 겹치면 자원, 일정, 사람을 결과 중심으로 재배치하는 힘이 생깁니다.",
    caution: "모든 것을 관리 대상으로 보면 가까운 사람이 피곤해질 수 있습니다.",
    advice: "관리할 것과 믿고 맡길 것을 나누는 기준이 필요합니다.",
  }),
  createFusionRule({
    id: "fusion_metal_strong_entj_judgment",
    kind: "reinforcement",
    sajuEntryIds: ["element_metal_strong"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["sharp_analysis"],
    requiredMbtiTags: ["strategic_thinking"],
    topic: "work_career",
    priority: 89,
    summary: "금 강함 + ENTJ 판단력",
    interpretation:
      "금의 기준 세우기와 ENTJ의 전략성이 겹치면 복잡한 판을 빠르게 자르고 우선순위를 세웁니다.",
    caution: "판단이 빠른 만큼 설명이 짧아지면 차갑게 보일 수 있습니다.",
    advice: "판단 근거를 한 줄만 더 보여줘도 신뢰가 올라갑니다.",
  }),
  createFusionRule({
    id: "fusion_gabmok_gapsin_entj_command",
    kind: "topic_specialization",
    sajuEntryIds: ["day_master_gabmok", "day_pillar_gapsin"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["leadership"],
    requiredMbtiTags: ["control_need"],
    topic: "personality",
    priority: 88,
    summary: "갑목/갑신 + ENTJ 지휘 욕구",
    interpretation:
      "갑목의 방향성, 갑신일주의 판단력, ENTJ의 통제 욕구가 맞물리면 앞에서 구조를 세우고 싶어집니다.",
    caution: "지휘가 강해질수록 상대의 속도를 놓치기 쉽습니다.",
    advice: "지시보다 목표 공유를 먼저 하면 추진력이 덜 날카롭게 전달됩니다.",
  }),
  createFusionRule({
    id: "fusion_gwan_entj_leadership_work",
    kind: "topic_specialization",
    sajuEntryIds: ["ten_god_qi_sha", "ten_god_zheng_guan"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["leadership"],
    requiredMbtiTags: ["leadership"],
    topic: "work_career",
    priority: 87,
    summary: "편관/정관 + ENTJ 리더십",
    interpretation:
      "관성의 역할감과 ENTJ 리더십이 만나면 조직 장악, 책임직, 기준 설정에서 힘이 선명해집니다.",
    caution: "역할을 빨리 떠안는 만큼 책임 과부하도 같이 생기기 쉽습니다.",
    advice: "권한과 책임 범위를 먼저 합의하면 리더십이 안정됩니다.",
  }),
  createFusionRule({
    id: "fusion_hyeonchim_entj_strategy_work",
    kind: "topic_specialization",
    sajuEntryIds: ["sinsal_hyeonchim"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["precision_skill"],
    requiredMbtiTags: ["strategic_thinking"],
    topic: "work_career",
    priority: 86,
    summary: "현침살 + ENTJ strategic thinking",
    interpretation:
      "현침살의 정밀 감각과 ENTJ의 전략성이 겹치면 개발, 분석, 법률, 기술처럼 디테일을 다루는 영역에서 강점이 납니다.",
    caution: "문제를 보는 눈이 빨라 상대의 준비 시간을 과소평가할 수 있습니다.",
    advice: "문제 지적과 개선 경로를 함께 제시해야 전문성이 부드럽게 전달됩니다.",
  }),
  createFusionRule({
    id: "fusion_water_missing_entj_burnout_work",
    kind: "compensation",
    sajuEntryIds: ["element_water_missing"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["low_rest_capacity"],
    requiredMbtiTags: ["burnout_risk"],
    topic: "work_career",
    priority: 85,
    summary: "수 부족 + ENTJ 번아웃 관리",
    interpretation:
      "수 부족의 회복 약점과 ENTJ의 목표 몰입이 만나면 과열을 실력으로 착각하기 쉽습니다.",
    caution: "멈추는 시간이 없으면 판단력도 같이 마릅니다.",
    advice: "성과 목표 옆에 회복 목표를 함께 두는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_wealth_entj_money_design",
    kind: "topic_specialization",
    sajuEntryIds: ["ten_god_pian_cai", "ten_god_zheng_cai"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["money_orientation"],
    requiredMbtiTags: ["strategic_thinking"],
    topic: "money_asset",
    priority: 84,
    summary: "편재/정재 + ENTJ 돈 구조 설계",
    interpretation:
      "편재와 정재의 자원 감각에 ENTJ의 설계력이 붙으면 돈을 버는 방식과 지키는 방식을 함께 세우려 합니다.",
    caution: "돈의 흐름을 통제하려는 힘이 강해지면 관계까지 손익으로 볼 수 있습니다.",
    advice: "수익, 안정, 관계 비용을 나누어 보는 기준이 필요합니다.",
  }),
  createFusionRule({
    id: "fusion_jaeda_entj_money_risk",
    kind: "topic_specialization",
    sajuEntryIds: ["pattern_jaeda_sinyak"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["burnout_risk"],
    requiredMbtiTags: ["achievement_drive"],
    topic: "money_asset",
    priority: 83,
    summary: "재다신약 + ENTJ 돈/성과 소모",
    interpretation:
      "돈과 성과를 크게 보려는 구조가 강해지면 목표는 빨리 커지지만 회복 자원은 뒤로 밀릴 수 있습니다.",
    caution: "성과 압박이 누적되면 돈을 벌수록 피로도 같이 커질 수 있습니다.",
    advice: "수익 목표와 손실 제한, 휴식 기준을 한 세트로 관리해야 합니다.",
  }),
  createFusionRule({
    id: "fusion_jaego_entj_asset",
    kind: "topic_specialization",
    sajuEntryIds: ["gwiin_jaego", "nobleman_jaego"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["asset_building"],
    requiredMbtiTags: ["money_orientation"],
    topic: "money_asset",
    priority: 82,
    summary: "재고귀인 + ENTJ 자산화",
    interpretation:
      "재고귀인의 축적 감각과 ENTJ의 구조화가 만나면 돈을 흘려보내기보다 문서화하고 묶어 두려는 힘이 생깁니다.",
    advice: "계좌, 계약, 기록으로 남길수록 자산 감각이 현실화됩니다.",
  }),
  createFusionRule({
    id: "fusion_hongyeom_entj_charisma",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_hongyeom"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["romantic_attraction"],
    requiredMbtiTags: ["leadership"],
    topic: "love_relationship",
    priority: 81,
    summary: "홍염살 + ENTJ 카리스마",
    interpretation:
      "홍염살의 분위기와 ENTJ의 주도성이 겹치면 말투와 결정력이 매력으로 보일 수 있습니다.",
    caution: "일의 속도와 호감의 속도가 섞이면 관계 해석이 복잡해질 수 있습니다.",
    advice: "호감과 역할을 구분하는 말이 관계를 더 안정시킵니다.",
  }),
  createFusionRule({
    id: "fusion_dohwa_entj_public_love",
    kind: "topic_specialization",
    sajuEntryIds: ["sinsal_dohwa"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["public_presence"],
    requiredMbtiTags: ["leadership"],
    topic: "love_relationship",
    priority: 80,
    summary: "도화살 + ENTJ public_presence",
    interpretation:
      "도화살의 노출성과 ENTJ의 주도성이 겹치면 드러나는 자리에서 관심을 받는 방식이 선명해집니다.",
    caution: "대중적 관심과 개인적 호감을 구분해야 관계가 깔끔합니다.",
    advice: "공적인 역할과 사적인 마음을 분리해 표현하는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_fire_missing_entj_love_expression",
    kind: "contrast",
    sajuEntryIds: ["element_fire_missing"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["expression_weakness"],
    requiredMbtiTags: ["workplace_romance"],
    topic: "love_relationship",
    priority: 79,
    summary: "화 부족 + ENTJ 애정표현 contrast",
    interpretation:
      "외향적인 자기상과 별개로 화가 부족하면 애정표현은 일 처리보다 건조하게 나올 수 있습니다.",
    caution: "상대는 능력보다 온도를 확인하고 싶어 할 수 있습니다.",
    advice: "고마움, 보고 싶음, 걱정 같은 감정어를 짧게라도 직접 말하는 연습이 필요합니다.",
  }),
  createFusionRule({
    id: "fusion_wealth_entj_love_realism",
    kind: "topic_specialization",
    sajuEntryIds: ["ten_god_pian_cai", "ten_god_zheng_cai"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["money_orientation"],
    requiredMbtiTags: ["workplace_romance"],
    topic: "love_relationship",
    priority: 78,
    summary: "재성 강함 + ENTJ 현실적 연애",
    interpretation:
      "재성의 현실 기준과 ENTJ의 성장 지향이 만나면 연애에서도 능력, 비전, 생활 감각을 중요하게 봅니다.",
    caution: "현실성을 보는 눈이 강하면 감정 표현이 평가처럼 들릴 수 있습니다.",
    advice: "기준을 말할 때 애정의 이유를 함께 말하면 차가움이 줄어듭니다.",
  }),
  createFusionRule({
    id: "fusion_no_resource_entj_listening",
    kind: "compensation",
    sajuEntryIds: ["pattern_no_resource"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["emotional_dryness"],
    requiredMbtiTags: ["control_need"],
    topic: "human_relations",
    priority: 77,
    summary: "무인성 + ENTJ 들어주는 힘",
    interpretation:
      "무인성의 수용 약점과 ENTJ의 통제 성향이 겹치면 듣기보다 정리하고 지시하는 반응이 먼저 나올 수 있습니다.",
    caution: "상대는 해결 전에 자기 말이 받아들여졌는지를 봅니다.",
    advice: "질문을 하나 더 하고 결론을 말하는 순서가 관계를 부드럽게 만듭니다.",
  }),
  createFusionRule({
    id: "fusion_gwan_entj_high_standard",
    kind: "contrast",
    sajuEntryIds: ["ten_god_qi_sha", "ten_god_zheng_guan"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["authority_orientation"],
    requiredMbtiTags: ["control_need"],
    topic: "human_relations",
    priority: 76,
    summary: "관성 강함 + ENTJ 높은 기준",
    interpretation:
      "관성의 기준 의식과 ENTJ의 효율 기준이 겹치면 사람을 빠르게 평가하고 역할을 나누려는 경향이 나타나기 쉽습니다.",
    caution: "기준이 명확한 만큼 관계가 평가처럼 느껴질 수 있습니다.",
    advice: "사람을 고치기 전에 역할 기대치를 합의하는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_bijie_entj_competition",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_bijian", "ten_god_jie_cai"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["competition"],
    requiredMbtiTags: ["competition"],
    topic: "human_relations",
    priority: 75,
    summary: "비겁 + ENTJ competition",
    interpretation:
      "비겁의 동료·경쟁 신호와 ENTJ의 승부 감각이 겹치면 동료를 협력자이자 경쟁자로 동시에 보게 됩니다.",
    caution: "경쟁심이 강점이지만 가까운 관계에서는 피로가 될 수 있습니다.",
    advice: "승부를 걸 관계와 신뢰를 쌓을 관계를 구분해야 합니다.",
  }),
  createFusionRule({
    id: "fusion_wood_nt_strategy",
    kind: "reinforcement",
    sajuEntryIds: ["element_wood", "day_master_gabmok"],
    mbtiTypes: ["INTJ", "INTP", "ENTJ", "ENTP"],
    requiredSajuTags: ["growth_orientation"],
    requiredMbtiTags: ["strategic_thinking"],
    topic: "study_growth",
    priority: 74,
    summary: "목 + NT 방향성/전략",
    interpretation:
      "목의 성장 방향과 NT의 추상 전략이 겹치면 큰 그림을 세우고 다음 판을 설계하는 힘이 강해집니다.",
    advice: "아이디어를 실행 순서로 나누면 방향성이 현실에 닿습니다.",
  }),
  createFusionRule({
    id: "fusion_wood_missing_j_rigidity",
    kind: "contrast",
    sajuEntryIds: ["element_wood_missing"],
    mbtiTypes: ["INTJ", "ENTJ", "INFJ", "ENFJ", "ISTJ", "ESTJ", "ISFJ", "ESFJ"],
    requiredSajuTags: ["flexibility_need"],
    requiredMbtiTags: ["stability_need"],
    topic: "final_advice",
    priority: 73,
    summary: "목 부족 + J 유형 rigidity risk",
    interpretation:
      "J의 계획성과 목 부족의 전환 약점이 겹치면 기준이 흔들리는 상황을 불편하게 느끼기 쉽습니다.",
    caution: "계획을 지키는 힘이 강점이지만 변화 대응 칸도 필요합니다.",
    advice: "처음부터 예비 선택지를 두 개 만들어 두면 유연성이 올라갑니다.",
  }),
  createFusionRule({
    id: "fusion_fire_e_expression",
    kind: "reinforcement",
    sajuEntryIds: ["element_fire", "ten_god_shi_shen", "ten_god_shang_guan"],
    mbtiTypes: ["ENTJ", "ENTP", "ENFJ", "ENFP", "ESTJ", "ESFJ", "ESTP", "ESFP"],
    requiredSajuTags: ["public_presence"],
    requiredMbtiTags: ["public_presence"],
    topic: "strengths",
    priority: 72,
    summary: "화/식상 + E 표현력",
    interpretation:
      "화와 식상의 output에 E의 대외 반응성이 겹치면 발표, 콘텐츠, 현장 대응에서 힘이 납니다.",
    advice: "보여주는 방식이 곧 실력이 되므로 기록과 발표 루틴을 잡는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_fire_missing_e_expression_contrast",
    kind: "contrast",
    sajuEntryIds: ["element_fire_missing"],
    mbtiTypes: ["ENTJ", "ENTP", "ENFJ", "ENFP", "ESTJ", "ESFJ", "ESTP", "ESFP"],
    requiredSajuTags: ["expression_weakness"],
    topic: "human_relations",
    priority: 71,
    summary: "화 부족 + E 유형 expression contrast",
    interpretation:
      "E 성향처럼 밖으로 향해도 사주 화가 약하면 친밀한 표현은 덜 자연스럽게 느껴질 수 있습니다.",
    caution: "활동량과 정서 표현량은 같은 것이 아닙니다.",
    advice: "말수보다 온도를 보여주는 작은 표현을 늘리는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_earth_tj_asset",
    kind: "reinforcement",
    sajuEntryIds: ["element_earth", "element_earth_excess"],
    mbtiTypes: ["INTJ", "ENTJ", "ISTJ", "ESTJ"],
    requiredSajuTags: ["asset_building"],
    requiredMbtiTags: ["efficiency_focus"],
    topic: "money_asset",
    priority: 70,
    summary: "토 + TJ 현실/성과/자산 관리",
    interpretation:
      "토의 현실 기반과 TJ의 관리 성향이 겹치면 자원을 숫자와 책임 단위로 다루는 능력이 커집니다.",
    advice: "현실 감각을 장기 자산 기준으로 연결하면 힘이 오래 갑니다.",
  }),
  createFusionRule({
    id: "fusion_earth_excess_j_overload",
    kind: "contrast",
    sajuEntryIds: ["element_earth_excess"],
    mbtiTypes: ["INTJ", "ENTJ", "INFJ", "ENFJ", "ISTJ", "ESTJ", "ISFJ", "ESFJ"],
    requiredSajuTags: ["responsibility_pressure"],
    requiredMbtiTags: ["self_discipline"],
    topic: "weaknesses",
    priority: 69,
    summary: "토 과다 + J 책임 과부하",
    interpretation:
      "토 과다의 무거움과 J의 마감 의식이 겹치면 책임을 오래 붙들고 놓지 못하는 흐름이 생기기 쉽습니다.",
    caution: "책임감이 강점이지만 과해지면 몸이 먼저 무거워집니다.",
    advice: "완료 기준과 중단 기준을 같은 문서에 적어 두는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_metal_t_precision",
    kind: "reinforcement",
    sajuEntryIds: ["element_metal", "element_metal_strong", "sinsal_hyeonchim"],
    mbtiTypes: ["INTJ", "INTP", "ENTJ", "ENTP", "ISTJ", "ISTP", "ESTJ", "ESTP"],
    requiredSajuTags: ["precision_skill"],
    requiredMbtiTags: ["precision_skill"],
    topic: "work_career",
    priority: 68,
    summary: "금/현침살 + T 판단력",
    interpretation:
      "금의 기준과 T의 논리 기준이 겹치면 정확도, 검토, 판단, 문제 절단 능력이 강해집니다.",
    caution: "정확함이 강할수록 말의 온도가 낮아질 수 있습니다.",
    advice: "판단 뒤에 맥락 설명을 붙이면 신뢰가 올라갑니다.",
  }),
  createFusionRule({
    id: "fusion_metal_excess_t_coldness",
    kind: "contrast",
    sajuEntryIds: ["element_metal_strong"],
    mbtiTypes: ["INTJ", "INTP", "ENTJ", "ENTP", "ISTJ", "ISTP", "ESTJ", "ESTP"],
    requiredSajuTags: ["direct_speech"],
    requiredMbtiTags: ["direct_speech"],
    topic: "human_relations",
    priority: 67,
    summary: "금 강함 + T 차가운 비판성",
    interpretation:
      "금의 절단력과 T의 기준 언어가 겹치면 말은 정확하지만 관계에서는 차갑게 읽힐 수 있습니다.",
    caution: "상대는 내용보다 톤을 먼저 기억할 수 있습니다.",
    advice: "비판 전에 인정 한 줄을 넣으면 관계 손상이 줄어듭니다.",
  }),
  createFusionRule({
    id: "fusion_water_nf_inner_flow",
    kind: "reinforcement",
    sajuEntryIds: ["element_water", "ten_god_zheng_yin", "ten_god_pian_yin"],
    mbtiTypes: ["INFJ", "INFP", "ENFJ", "ENFP"],
    requiredSajuTags: ["emotional_depth"],
    requiredMbtiTags: ["emotional_depth"],
    topic: "personality",
    priority: 66,
    summary: "수/인성 + NF 감정 직관",
    interpretation:
      "수와 인성의 내면 흐름에 NF의 의미 감각이 붙으면 감정과 상징을 깊게 해석하는 힘이 커집니다.",
    advice: "감정을 말로 정리하면 예민함이 통찰로 바뀝니다.",
  }),
  createFusionRule({
    id: "fusion_water_missing_t_empathy_gap",
    kind: "compensation",
    sajuEntryIds: ["element_water_missing", "pattern_no_resource"],
    mbtiTypes: ["INTJ", "INTP", "ENTJ", "ENTP", "ISTJ", "ISTP", "ESTJ", "ESTP"],
    requiredSajuTags: ["emotional_dryness"],
    topic: "love_relationship",
    priority: 65,
    summary: "수 부족 + T 감정 처리 건조",
    interpretation:
      "수 부족의 감정 순환 약점과 T의 기준 언어가 겹치면 공감보다 분석이 먼저 나오기 쉽습니다.",
    caution: "분석은 맞아도 상대의 마음은 아직 준비되지 않았을 수 있습니다.",
    advice: "감정 확인과 해결책을 분리해 말하는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_pian_cai_e_business",
    kind: "topic_specialization",
    sajuEntryIds: ["ten_god_pian_cai"],
    mbtiTypes: ["ENTJ", "ENTP", "ESTP", "ENFP"],
    requiredSajuTags: ["money_orientation"],
    topic: "money_asset",
    priority: 64,
    summary: "편재 + E/ENTJ/ESTP/ENTP 외부 기회",
    interpretation:
      "편재의 외부 기회 감각과 활동형 MBTI가 만나면 사람, 시장, 프로젝트에서 돈의 가능성을 빨리 봅니다.",
    caution: "기회가 많아 보일수록 손실 제한 기준이 필요합니다.",
    advice: "확장 전 회수 계획을 먼저 세우면 사업성이 안정됩니다.",
  }),
  createFusionRule({
    id: "fusion_zheng_cai_sj_asset",
    kind: "topic_specialization",
    sajuEntryIds: ["ten_god_zheng_cai"],
    mbtiTypes: ["ISTJ", "ISFJ", "ESTJ", "ESFJ"],
    requiredSajuTags: ["asset_building"],
    requiredMbtiTags: ["stability_need"],
    topic: "money_asset",
    priority: 63,
    summary: "정재 + SJ 안정 자산",
    interpretation:
      "정재의 안정 관리와 SJ의 지속성이 겹치면 급한 승부보다 오래 지키는 돈에 강합니다.",
    advice: "예산표, 적립, 고정비 관리처럼 반복되는 시스템이 잘 맞습니다.",
  }),
  createFusionRule({
    id: "fusion_qi_sha_tj_pressure_leadership",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_qi_sha"],
    mbtiTypes: ["INTJ", "ENTJ", "ESTJ"],
    requiredSajuTags: ["leadership"],
    requiredMbtiTags: ["strategic_thinking"],
    topic: "work_career",
    priority: 62,
    summary: "편관 + TJ 압박 속 리더십",
    interpretation:
      "편관의 압박 대응력과 TJ의 구조화가 겹치면 위기 상황에서 방향을 잡는 힘이 살아납니다.",
    caution: "긴급 모드가 일상이 되면 관계와 건강이 마를 수 있습니다.",
    advice: "위기 해결 뒤에는 반드시 회복 구간을 설계해야 합니다.",
  }),
  createFusionRule({
    id: "fusion_zheng_guan_j_system",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_zheng_guan"],
    mbtiTypes: ["INTJ", "ENTJ", "INFJ", "ENFJ", "ISTJ", "ESTJ", "ISFJ", "ESFJ"],
    requiredSajuTags: ["authority_orientation"],
    requiredMbtiTags: ["self_discipline"],
    topic: "work_career",
    priority: 61,
    summary: "정관 + J 책임/명예/조직 적합",
    interpretation:
      "정관의 체계성과 J의 마감 감각이 겹치면 조직, 직함, 책임 있는 역할에서 안정감이 생깁니다.",
    advice: "역할이 커질수록 규칙보다 사람의 상황을 함께 보는 장치가 필요합니다.",
  }),
  createFusionRule({
    id: "fusion_shi_shen_fp_soft_expression",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_shi_shen"],
    mbtiTypes: ["INFP", "ENFP", "ISFP", "ESFP", "ISFJ", "ESFJ"],
    requiredSajuTags: ["public_presence"],
    topic: "human_relations",
    priority: 60,
    summary: "식신 + FP/SF 부드러운 표현",
    interpretation:
      "식신의 안정된 표현과 FP/SF의 생활 감각이 만나면 주변을 편하게 만드는 방식으로 능력이 드러납니다.",
    advice: "작은 생산물과 꾸준한 돌봄이 신뢰를 만듭니다.",
  }),
  createFusionRule({
    id: "fusion_shang_guan_np_critique",
    kind: "contrast",
    sajuEntryIds: ["ten_god_shang_guan"],
    mbtiTypes: ["INTP", "ENTP", "INFP", "ENFP", "ISTP", "ESTP"],
    requiredSajuTags: ["direct_speech"],
    topic: "human_relations",
    priority: 59,
    summary: "상관 + NP/TP 창의적 반항",
    interpretation:
      "상관의 비판성과 NP/TP의 실험성이 겹치면 기존 규칙을 빨리 의심하고 다른 길을 찾습니다.",
    caution: "좋은 아이디어도 말투가 공격적으로 들리면 저항을 부릅니다.",
    advice: "반박보다 대안을 먼저 보여주면 창의성이 더 잘 받아들여집니다.",
  }),
  createFusionRule({
    id: "fusion_zheng_yin_nf_recovery",
    kind: "compensation",
    sajuEntryIds: ["ten_god_zheng_yin"],
    mbtiTypes: ["INFJ", "INFP", "ENFJ", "ENFP"],
    requiredSajuTags: ["emotional_depth"],
    requiredMbtiTags: ["empathy_need"],
    topic: "final_advice",
    priority: 58,
    summary: "정인 + NF 내면 회복",
    interpretation:
      "정인의 보호성과 NF의 의미 감각이 겹치면 마음을 이해받는 경험이 회복의 핵심이 됩니다.",
    advice: "회복은 혼자 버티기보다 안전한 사람과 언어를 찾을 때 빨라집니다.",
  }),
  createFusionRule({
    id: "fusion_pian_yin_n_immersion",
    kind: "topic_specialization",
    sajuEntryIds: ["ten_god_pian_yin"],
    mbtiTypes: ["INTJ", "INTP", "INFJ", "INFP", "ENTP", "ENFP"],
    requiredSajuTags: ["strategic_thinking"],
    topic: "study_growth",
    priority: 57,
    summary: "편인 + N 독특한 몰입",
    interpretation:
      "편인의 비주류 학습 감각과 N의 패턴 인식이 겹치면 남들이 지나치는 주제에 깊게 들어갑니다.",
    caution: "몰입이 깊어질수록 현실 일정과 분리될 수 있습니다.",
    advice: "몰입 결과를 글, 도표, 산출물로 꺼내야 실력이 쌓입니다.",
  }),
  createFusionRule({
    id: "fusion_bijian_ej_self_assertion",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_bijian"],
    mbtiTypes: ["ENTJ", "ENFJ", "ESTJ", "ESFJ"],
    requiredSajuTags: ["independence"],
    topic: "human_relations",
    priority: 56,
    summary: "비견 + E/J 독립성과 자기 주장",
    interpretation:
      "비견의 자기 중심축과 E/J의 명확한 표현이 겹치면 입장과 기준을 분명히 세웁니다.",
    caution: "분명함이 강점이지만 주변에는 고집으로 읽힐 수 있습니다.",
    advice: "내 기준과 상대 선택권을 함께 말하면 갈등이 줄어듭니다.",
  }),
  createFusionRule({
    id: "fusion_jie_cai_ep_competition_risk",
    kind: "compensation",
    sajuEntryIds: ["ten_god_jie_cai"],
    mbtiTypes: ["ENTJ", "ENTP", "ESTP", "ENFP", "ESFP"],
    requiredSajuTags: ["competition"],
    topic: "money_asset",
    priority: 55,
    summary: "겁재 + E/P 경쟁과 리스크",
    interpretation:
      "겁재의 경쟁 감각과 활동형 MBTI가 겹치면 기회 감각은 빠르지만 사람을 통한 손실도 주의해야 합니다.",
    caution: "친분, 승부, 돈이 섞이면 판단이 흐려질 수 있습니다.",
    advice: "사람과 돈이 연결되는 일은 기록과 기준을 먼저 두는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_hyeonchim_t_precision",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_hyeonchim"],
    mbtiTypes: ["INTJ", "INTP", "ENTJ", "ENTP", "ISTJ", "ISTP", "ESTJ", "ESTP"],
    requiredSajuTags: ["precision_skill"],
    topic: "work_career",
    priority: 54,
    summary: "현침살 + T 말/분석/정밀성",
    interpretation:
      "현침살의 찌르는 감각과 T의 기준 사고가 겹치면 분석, 검수, 디버깅, 판단 영역에서 강점이 납니다.",
    caution: "정확한 말도 사람에게는 날카롭게 남을 수 있습니다.",
    advice: "문제와 사람을 분리해 말하면 정밀함이 신뢰로 남습니다.",
  }),
  createFusionRule({
    id: "fusion_hongyeom_ef_charm",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_hongyeom"],
    mbtiTypes: ["ENFJ", "ENFP", "ESFJ", "ESFP", "ENTJ"],
    requiredSajuTags: ["romantic_attraction"],
    topic: "love_relationship",
    priority: 53,
    summary: "홍염살 + E/F/ENTJ 매력 발현",
    interpretation:
      "홍염살의 분위기는 외향성이나 관계 감각과 만나면 말투, 표정, 현장 장악력으로 다르게 드러납니다.",
    advice: "관심을 받을수록 관계 속도를 조절하는 표현이 필요합니다.",
  }),
  createFusionRule({
    id: "fusion_dohwa_e_public",
    kind: "topic_specialization",
    sajuEntryIds: ["sinsal_dohwa"],
    mbtiTypes: ["ENTJ", "ENTP", "ENFJ", "ENFP", "ESTJ", "ESFJ", "ESTP", "ESFP"],
    requiredSajuTags: ["public_presence"],
    topic: "environment_luck",
    priority: 52,
    summary: "도화살 + E 대중성/노출",
    interpretation:
      "도화살의 노출성과 E의 대외 에너지가 겹치면 사람 앞에 서는 자리에서 기회가 생기기 쉽습니다.",
    advice: "노출을 목적과 연결하면 관심이 기회로 정리됩니다.",
  }),
  createFusionRule({
    id: "fusion_hwagae_inf_art_depth",
    kind: "topic_specialization",
    sajuEntryIds: ["sinsal_hwagae"],
    mbtiTypes: ["INFJ", "INFP", "INTJ", "INTP", "ISFP"],
    requiredSajuTags: ["loneliness"],
    topic: "study_growth",
    priority: 51,
    summary: "화개살 + I/N/F 고독과 예술성",
    interpretation:
      "화개살의 고독한 깊이와 내향·직관 성향이 겹치면 취향, 예술, 철학, 연구의 밀도가 올라갑니다.",
    caution: "깊이가 강해질수록 고립도 같이 커질 수 있습니다.",
    advice: "작품, 글, 공부 결과로 밖에 꺼내야 고독이 자원이 됩니다.",
  }),
  createFusionRule({
    id: "fusion_yeokma_pen_change",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_yeokma"],
    mbtiTypes: ["ENTP", "ENFP", "ESTP", "ESFP", "INTP", "INFP", "ISTP", "ISFP"],
    requiredSajuTags: ["flexibility_need"],
    topic: "environment_luck",
    priority: 50,
    summary: "역마살 + P/E/N 이동과 확장",
    interpretation:
      "역마살의 이동 신호와 P/E/N의 탐색성이 겹치면 환경이 바뀔수록 정보와 기회가 늘어납니다.",
    caution: "움직임이 많아질수록 정착 기준이 흐려질 수 있습니다.",
    advice: "이동 목적과 회수 계획을 함께 세우면 변화가 자산이 됩니다.",
  }),
  createFusionRule({
    id: "fusion_gwimun_nfi_sensitivity",
    kind: "contrast",
    sajuEntryIds: ["sinsal_gwimun"],
    mbtiTypes: ["INFJ", "INFP", "INTJ", "INTP", "ENFP"],
    requiredSajuTags: ["loneliness"],
    topic: "weaknesses",
    priority: 49,
    summary: "귀문관살 + N/F/I 예민한 촉",
    interpretation:
      "귀문관살의 예민한 포착력과 N/F/I의 내부 처리 성향이 겹치면 촉은 깊지만 생각이 혼자 커질 수 있습니다.",
    caution: "몰입과 의심이 붙으면 관계 해석이 과열될 수 있습니다.",
    advice: "확인 가능한 사실과 느낌을 분리해서 적어 보는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_wonjin_relationship_distance",
    kind: "compensation",
    sajuEntryIds: ["sinsal_wonjin"],
    requiredSajuTags: ["relationship_distance"],
    topic: "love_relationship",
    priority: 48,
    summary: "원진살 + 관계 오해/거리감",
    interpretation:
      "원진살은 가까운 관계에서 끌림과 불편함이 같이 생기는 신호라 MBTI 성향과 관계없이 표현 조절이 필요합니다.",
    caution: "상대의 말뜻을 혼자 단정하면 거리감이 커질 수 있습니다.",
    advice: "불편한 지점은 해석보다 확인 질문으로 다루는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_munchang_nt_nf_writing",
    kind: "topic_specialization",
    sajuEntryIds: ["nobleman_munchang"],
    mbtiTypes: ["INTJ", "INTP", "ENTJ", "ENTP", "INFJ", "INFP", "ENFJ", "ENFP"],
    requiredSajuTags: ["precision_skill"],
    topic: "study_growth",
    priority: 47,
    summary: "문창귀인 + NT/NF 글/기획/학습",
    interpretation:
      "문창귀인의 언어·문서 감각과 N 계열의 패턴 인식이 겹치면 글, 기획, 학습 구조화가 강점이 됩니다.",
    advice: "생각을 문서로 남길수록 전문성이 쌓입니다.",
  }),
  createFusionRule({
    id: "fusion_cheoneul_fj_support",
    kind: "compensation",
    sajuEntryIds: ["nobleman_cheoneul"],
    mbtiTypes: ["INFJ", "ENFJ", "ISFJ", "ESFJ", "ISTJ", "ESTJ"],
    requiredSajuTags: ["empathy_need"],
    topic: "human_relations",
    priority: 46,
    summary: "천을귀인 + F/J/SJ/NF 도움과 보호",
    interpretation:
      "천을귀인의 도움 신호와 관계·책임형 MBTI가 만나면 어려운 장면에서 조언자나 완충자가 들어오기 쉽습니다.",
    advice: "혼자 버티기보다 질문을 잘 던질 때 도움 운이 현실화됩니다.",
  }),
  createFusionRule({
    id: "fusion_jaego_tj_sj_storage",
    kind: "topic_specialization",
    sajuEntryIds: ["gwiin_jaego", "nobleman_jaego"],
    mbtiTypes: ["INTJ", "ENTJ", "ISTJ", "ESTJ", "ISFJ", "ESFJ"],
    requiredSajuTags: ["asset_building"],
    topic: "money_asset",
    priority: 45,
    summary: "재고귀인 + TJ/SJ 자산화/축적",
    interpretation:
      "재고귀인의 저장성은 TJ/SJ의 관리 성향과 만나 돈, 문서, 부동산, 자료를 묶어두는 힘으로 나타납니다.",
    advice: "흩어진 자원을 한곳에 모으는 체계가 곧 강점입니다.",
  }),
  createFusionRule({
    id: "fusion_f_metal_officer_coldness",
    kind: "contrast",
    sajuEntryIds: ["element_metal_strong", "ten_god_zheng_guan", "ten_god_qi_sha"],
    mbtiTypes: ["INFJ", "INFP", "ENFJ", "ENFP", "ISFJ", "ISFP", "ESFJ", "ESFP"],
    requiredSajuTags: ["authority_orientation"],
    topic: "human_relations",
    priority: 44,
    summary: "F 유형 + 금/관성 strong 기준과 책임",
    interpretation:
      "F 성향이라도 금이나 관성이 강하면 감정보다 기준과 책임이 먼저 나와 차갑게 보일 수 있습니다.",
    caution: "스스로는 배려라고 느껴도 상대는 평가로 들을 수 있습니다.",
    advice: "기준을 말하기 전에 마음을 먼저 확인하는 문장이 필요합니다.",
  }),
  createFusionRule({
    id: "fusion_t_water_emotional_depth",
    kind: "contrast",
    sajuEntryIds: ["element_water", "ten_god_zheng_yin", "ten_god_pian_yin"],
    mbtiTypes: ["INTJ", "INTP", "ENTJ", "ENTP", "ISTJ", "ISTP", "ESTJ", "ESTP"],
    requiredSajuTags: ["emotional_depth"],
    topic: "personality",
    priority: 43,
    summary: "T 유형 + 수 강함 감정 깊이",
    interpretation:
      "T 유형처럼 논리형으로 보이더라도 수와 인성이 강하면 감정의 깊이와 직관적 공감이 안쪽에 크게 흐를 수 있습니다.",
    advice: "논리와 감정을 경쟁시키기보다 순서를 나누면 균형이 좋아집니다.",
  }),
  createFusionRule({
    id: "fusion_p_zheng_guan_responsibility",
    kind: "contrast",
    sajuEntryIds: ["ten_god_zheng_guan"],
    mbtiTypes: ["INTP", "ENTP", "INFP", "ENFP", "ISTP", "ESTP", "ISFP", "ESFP"],
    requiredSajuTags: ["responsibility_pressure"],
    topic: "work_career",
    priority: 42,
    summary: "P 유형 + 정관 strong 규칙 책임",
    interpretation:
      "P 유형처럼 자유롭다고 느껴도 정관이 강하면 실제 삶에서는 규칙, 책임, 역할에 묶이기 쉽습니다.",
    caution: "자유 욕구와 책임감이 충돌하면 미루기와 죄책감이 반복될 수 있습니다.",
    advice: "최소 규칙만 정하고 나머지는 유연하게 두는 방식이 맞습니다.",
  }),
  createFusionRule({
    id: "fusion_j_yeokma_change",
    kind: "contrast",
    sajuEntryIds: ["sinsal_yeokma"],
    mbtiTypes: ["INTJ", "ENTJ", "INFJ", "ENFJ", "ISTJ", "ESTJ", "ISFJ", "ESFJ"],
    requiredSajuTags: ["flexibility_need"],
    topic: "environment_luck",
    priority: 41,
    summary: "J 유형 + 역마살 변화 욕구",
    interpretation:
      "J 유형처럼 계획형이어도 역마살이 강하면 환경 변화와 이동 욕구가 동시에 움직일 수 있습니다.",
    caution: "계획을 세워도 몸은 새 판을 찾을 수 있습니다.",
    advice: "계획 안에 이동과 탐색 구간을 넣는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_i_dohwa_hongyeom_presence",
    kind: "contrast",
    sajuEntryIds: ["sinsal_dohwa", "sinsal_hongyeom"],
    mbtiTypes: ["INTJ", "INTP", "INFJ", "INFP", "ISTJ", "ISFJ", "ISTP", "ISFP"],
    requiredSajuTags: ["romantic_attraction"],
    topic: "love_relationship",
    priority: 40,
    summary: "I 유형 + 도화/홍염 존재감",
    interpretation:
      "내향형이어도 도화나 홍염이 있으면 조용한 방식의 존재감이나 이성적 끌림이 생길 수 있습니다.",
    advice: "많이 드러내지 않아도 어떤 자리에서 매력이 켜지는지 알아두면 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_s_resource_munchang_planning",
    kind: "contrast",
    sajuEntryIds: ["ten_god_zheng_yin", "nobleman_munchang"],
    mbtiTypes: ["ISTJ", "ISFJ", "ESTJ", "ESFJ", "ISTP", "ISFP", "ESTP", "ESFP"],
    requiredSajuTags: ["precision_skill"],
    topic: "study_growth",
    priority: 39,
    summary: "S 유형 + 인성/문창 학습 기획",
    interpretation:
      "현실형이어도 인성이나 문창이 강하면 문서화, 학습, 기획 능력이 깊어질 수 있습니다.",
    advice: "현장 경험을 기록으로 바꾸면 성장 속도가 안정됩니다.",
  }),
  createFusionRule({
    id: "fusion_n_earth_excess_reality_weight",
    kind: "contrast",
    sajuEntryIds: ["element_earth_excess"],
    mbtiTypes: ["INTJ", "INTP", "ENTJ", "ENTP", "INFJ", "INFP", "ENFJ", "ENFP"],
    requiredSajuTags: ["responsibility_pressure"],
    topic: "final_advice",
    priority: 38,
    summary: "N 유형 + 토 과다 현실 책임",
    interpretation:
      "N 유형의 이상과 가능성은 크지만 토 과다가 있으면 현실 책임이 발목을 잡는 느낌이 강해질 수 있습니다.",
    caution: "비전이 커질수록 처리해야 할 현실도 같이 커집니다.",
    advice: "아이디어를 일정, 돈, 사람 단위로 쪼개야 압박이 줄어듭니다.",
  }),
  createFusionRule({
    id: "fusion_gwansal_honjob_relationship_pressure",
    kind: "compensation",
    sajuEntryIds: ["pattern_gwansal_honjob"],
    requiredSajuTags: ["relationship_distance"],
    topic: "love_relationship",
    priority: 37,
    summary: "관살혼잡 + 관계 기준 압박",
    interpretation:
      "관살혼잡은 관계와 역할에서 기준이 복잡해지기 쉬운 구조라 MBTI 성향과 함께 거리 조절을 봐야 합니다.",
    caution: "상대의 기대와 내 기준이 겹치면 부담이 커질 수 있습니다.",
    advice: "관계 초반부터 역할 기대치를 말로 확인하는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_siksang_saengjae_expression_money",
    kind: "topic_specialization",
    sajuEntryIds: ["pattern_siksang_saengjae"],
    requiredSajuTags: ["money_orientation"],
    topic: "money_asset",
    priority: 36,
    summary: "식상생재 + 표현이 돈이 되는 구조",
    interpretation:
      "식상생재는 생산물과 표현이 재성으로 이어지는 구조라 콘텐츠, 영업, 상품화에서 돈의 흐름을 만들기 쉽습니다.",
    advice: "결과물을 보이는 단위로 만들수록 수익 구조가 선명해집니다.",
  }),
  createFusionRule({
    id: "fusion_jaesaenggwan_role_reputation",
    kind: "topic_specialization",
    sajuEntryIds: ["pattern_jaesaenggwan"],
    requiredSajuTags: ["authority_orientation"],
    topic: "work_career",
    priority: 35,
    summary: "재생관 + 돈이 역할과 평판으로 연결",
    interpretation:
      "재생관은 현실 성과가 역할, 평판, 책임으로 이어지는 구조라 조직 안에서 결과를 공식화하기 좋습니다.",
    advice: "성과를 개인 만족에만 두지 말고 역할과 신뢰로 연결해야 합니다.",
  }),
  createFusionRule({
    id: "fusion_salin_growth_pressure",
    kind: "compensation",
    sajuEntryIds: ["pattern_salin_sangsaeng"],
    requiredSajuTags: ["growth_orientation"],
    topic: "study_growth",
    priority: 34,
    summary: "살인상생 + 압박을 실력으로 전환",
    interpretation:
      "압박이 강한 구조라도 배움과 전문성으로 바꾸면 긴장이 실력의 재료가 됩니다.",
    advice: "불안할수록 더 큰 목표보다 작은 학습 단위가 필요합니다.",
  }),
  createFusionRule({
    id: "fusion_singang_independence",
    kind: "reinforcement",
    sajuEntryIds: ["pattern_singang"],
    requiredSajuTags: ["independence"],
    topic: "personality",
    priority: 33,
    summary: "신강 + 독립성과 버티는 힘",
    interpretation:
      "신강 구조는 자기 중심축이 강해 MBTI가 무엇이든 결정과 실행에서 버티는 힘을 줍니다.",
    advice: "강한 중심을 협업 언어로 바꾸면 영향력이 커집니다.",
  }),
  createFusionRule({
    id: "fusion_sinyak_support_need",
    kind: "compensation",
    sajuEntryIds: ["pattern_sinyak"],
    requiredSajuTags: ["empathy_need"],
    topic: "final_advice",
    priority: 32,
    summary: "신약 + 지지 구조 필요",
    interpretation:
      "신약 구조는 목표보다 지지 기반을 먼저 봐야 오래 가므로 MBTI 강점도 환경 설계와 함께 써야 합니다.",
    advice: "혼자 밀어붙이기보다 도움, 루틴, 회복 장치를 먼저 잡는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_toda_maegeum_standard_pressure",
    kind: "contrast",
    sajuEntryIds: ["pattern_toda_maegeum"],
    requiredSajuTags: ["responsibility_pressure"],
    topic: "weaknesses",
    priority: 31,
    summary: "토다매금 + 기준이 묻히는 압박",
    interpretation:
      "토가 금을 묻는 구조는 기준은 있는데 현실 책임이 두꺼워 판단을 바로 꺼내기 어려운 느낌을 만들 수 있습니다.",
    caution: "참고 버티다 한 번에 자르는 방식이 되지 않도록 조절이 필요합니다.",
    advice: "판단 기준을 평소에 문서화하면 압박 속에서도 덜 흔들립니다.",
  }),
  createFusionRule({
    id: "fusion_geumda_mokjeol_correction",
    kind: "contrast",
    sajuEntryIds: ["pattern_geumda_mokjeol"],
    requiredSajuTags: ["direct_speech"],
    topic: "human_relations",
    priority: 30,
    summary: "금다목절 + 성장보다 교정이 앞섬",
    interpretation:
      "금이 목을 자르는 구조는 성장 방향보다 교정과 판단이 앞설 수 있어 관계에서는 차갑게 읽힐 수 있습니다.",
    advice: "고치기 전에 키워야 할 방향을 먼저 말하면 균형이 좋아집니다.",
  }),
  createFusionRule({
    id: "fusion_mokda_hwasik_output",
    kind: "topic_specialization",
    sajuEntryIds: ["pattern_mokda_hwasik"],
    requiredSajuTags: ["public_presence"],
    topic: "strengths",
    priority: 29,
    summary: "목다화식 + 성장 에너지의 표현화",
    interpretation:
      "목이 화로 이어지는 구조는 계획과 성장 욕구가 표현, 발표, 결과물로 나가기 쉬운 흐름입니다.",
    advice: "생각을 오래 키우기보다 보이는 산출물로 자주 꺼내는 편이 좋습니다.",
  }),
  createFusionRule({
    id: "fusion_suda_mokbu_overthinking",
    kind: "compensation",
    sajuEntryIds: ["pattern_suda_mokbu"],
    requiredSajuTags: ["low_rest_capacity"],
    topic: "weaknesses",
    priority: 28,
    summary: "수다목부 + 생각이 성장을 눌러 둠",
    interpretation:
      "수 기운이 많아 목이 뜨는 구조는 생각과 감정 흐름이 많아 방향을 잡는 데 시간이 걸릴 수 있습니다.",
    caution: "많이 느끼고 생각하지만 실행은 늦어질 수 있습니다.",
    advice: "작은 실행 단위를 먼저 정해야 생각이 성장으로 연결됩니다.",
  }),
  createFusionRule({
    id: "fusion_goegang_tj_force",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_goegang"],
    mbtiTypes: ["ENTJ", "ESTJ", "INTJ"],
    requiredSajuTags: ["leadership"],
    topic: "work_career",
    priority: 27,
    summary: "괴강살 + TJ 강한 추진",
    interpretation:
      "괴강살의 강한 추진력과 TJ의 실행 기준이 만나면 어려운 판을 밀고 가는 힘이 강합니다.",
    caution: "강하게 밀수록 주변의 속도 차이를 봐야 합니다.",
    advice: "압박의 크기를 조절하면 추진력이 더 오래 갑니다.",
  }),
  createFusionRule({
    id: "fusion_yangin_competition",
    kind: "compensation",
    sajuEntryIds: ["sinsal_yangin"],
    requiredSajuTags: ["competition"],
    topic: "weaknesses",
    priority: 26,
    summary: "양인살 + 경쟁심 조절",
    interpretation:
      "양인살은 강한 자존과 승부 감각을 만들 수 있어 MBTI 강점이 과열되지 않도록 조절해야 합니다.",
    caution: "이기는 것보다 지키는 것이 필요한 장면이 있습니다.",
    advice: "경쟁 기준과 관계 기준을 나누는 훈련이 필요합니다.",
  }),
  createFusionRule({
    id: "fusion_cheonmun_n_insight",
    kind: "topic_specialization",
    sajuEntryIds: ["sinsal_cheonmun"],
    mbtiTypes: ["INTJ", "INTP", "INFJ", "INFP", "ENTP", "ENFP"],
    requiredSajuTags: ["strategic_thinking"],
    topic: "study_growth",
    priority: 25,
    summary: "천문성 + N 통찰",
    interpretation:
      "천문성의 관찰 감각과 N의 패턴 인식이 만나면 복잡한 현상을 상징과 구조로 이해하려 합니다.",
    advice: "직관을 검증 가능한 메모로 남기면 통찰이 실력이 됩니다.",
  }),
  createFusionRule({
    id: "fusion_jangseong_leadership",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_jangseong"],
    requiredSajuTags: ["leadership"],
    topic: "work_career",
    priority: 24,
    summary: "장성살 + 역할 중심 리더십",
    interpretation:
      "장성살은 앞에 서는 힘과 역할 의식을 주기 때문에 리더십 성향과 만나면 책임직에서 존재감이 생깁니다.",
    advice: "앞에 설수록 명령보다 방향 제시가 중요합니다.",
  }),
  createFusionRule({
    id: "fusion_banan_status_support",
    kind: "topic_specialization",
    sajuEntryIds: ["sinsal_banan"],
    requiredSajuTags: ["authority_orientation"],
    topic: "environment_luck",
    priority: 23,
    summary: "반안살 + 위치 상승과 주변 조건",
    interpretation:
      "반안살은 주변 조건과 위치가 올라가는 흐름을 보조하므로 역할, 평판, 환경 선택과 함께 봐야 합니다.",
    advice: "좋은 자리에 올라갈수록 책임의 형식을 정리해야 합니다.",
  }),
] as const;
