import type { FusionKnowledgeRule } from "./fusionKnowledgeTypes";

export const FUSION_KNOWLEDGE_BASE: readonly FusionKnowledgeRule[] = [
  {
    id: "fusion_wealth_strong_entj_achievement",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_pian_cai", "ten_god_zheng_cai", "pattern_jaeda_sinyak"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["money_orientation"],
    requiredMbtiTags: ["achievement_drive"],
    topic: "money_asset",
    priority: 95,
    summary: "재성 강함 + ENTJ 성취욕",
    interpretation: "사주에서 재성의 현실 감각이 강하고 ENTJ의 성취 지향이 겹치면 돈을 목표와 구조로 보는 힘이 커집니다.",
    caution: "자원 관리가 곧 자기 가치처럼 느껴지면 쉬는 시간이 밀릴 수 있습니다.",
    advice: "돈 목표와 회복 기준을 같은 표 안에 넣어야 지속성이 생깁니다.",
    phraseSeeds: ["재성의 현실 감각이 ENTJ식 목표 관리와 맞물립니다."],
  },
  {
    id: "fusion_hyeonchim_entj_direct_speech",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_hyeonchim"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["sharp_analysis"],
    requiredMbtiTags: ["direct_speech"],
    topic: "human_relations",
    priority: 94,
    summary: "현침살 + ENTJ 직설성",
    interpretation: "현침살의 예리함과 ENTJ의 바로 말하는 방식이 겹치면 핵심을 빠르게 짚지만 상대가 압박으로 받을 수 있습니다.",
    caution: "정답을 말하는 속도보다 상대가 받아들일 여백이 중요합니다.",
    advice: "결론 전에 의도 한 문장을 붙이면 날카로움이 실력으로 남습니다.",
    phraseSeeds: ["사주에도 말의 칼날이 있고 MBTI도 직선으로 밀어줍니다."],
  },
  {
    id: "fusion_officer_entj_leadership",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_qi_sha", "ten_god_zheng_guan"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["leadership"],
    requiredMbtiTags: ["leadership"],
    topic: "work_career",
    priority: 93,
    summary: "편관/정관 + ENTJ 리더십",
    interpretation: "관성의 책임 구조와 ENTJ의 지휘 성향이 겹치면 역할을 맡고 기준을 세우는 장면에서 힘이 납니다.",
    caution: "책임이 많아질수록 통제욕도 같이 올라올 수 있습니다.",
    advice: "권한, 책임, 휴식선을 문서로 나누는 편이 좋습니다.",
    phraseSeeds: ["관성의 역할감이 ENTJ 리더십을 더 공식적으로 만듭니다."],
  },
  {
    id: "fusion_water_missing_entj_emotional_dryness",
    kind: "reinforcement",
    sajuEntryIds: ["element_water_missing"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["emotional_dryness"],
    requiredMbtiTags: ["emotional_dryness"],
    topic: "love_relationship",
    priority: 92,
    summary: "수 부족 + ENTJ 감정 건조함",
    interpretation: "수 부족의 회복·감정 완충 약점과 ENTJ의 결과 우선성이 겹치면 관계에서 감정보다 해결책이 먼저 나올 수 있습니다.",
    caution: "상대는 해결보다 정서 확인을 먼저 원할 수 있습니다.",
    advice: "조언 전에 감정 확인을 한 번 넣으면 관계 피로가 줄어듭니다.",
    phraseSeeds: ["감정이 없는 게 아니라 물길을 여는 순서가 늦을 수 있습니다."],
  },
  {
    id: "fusion_fire_missing_entj_extraversion_contrast",
    kind: "contrast",
    sajuEntryIds: ["element_fire_missing"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["expression_weakness"],
    requiredMbtiTags: ["leadership"],
    topic: "personality",
    priority: 91,
    summary: "화 부족 + ENTJ 외향성 contrast",
    interpretation: "ENTJ처럼 밖으로 밀고 가는 자기상이 있어도 사주에서 화가 약하면 표현 온도는 생각보다 늦게 켜질 수 있습니다.",
    caution: "겉으로 강해 보여도 친밀한 감정 표현은 따로 연습이 필요합니다.",
    advice: "성과 언어와 감정 언어를 분리해 준비하면 오해가 줄어듭니다.",
    phraseSeeds: ["MBTI는 밖으로 보이지만 사주 화는 표현 온도를 조절합니다."],
  },
  {
    id: "fusion_hongyeom_entj_charisma",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_hongyeom"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["romantic_attraction"],
    requiredMbtiTags: ["leadership"],
    topic: "love_relationship",
    priority: 90,
    summary: "홍염살 + ENTJ 카리스마",
    interpretation: "홍염살의 분위기와 ENTJ의 주도성이 겹치면 말투와 결정력이 매력으로 보일 수 있습니다.",
    caution: "일의 속도와 호감의 속도가 섞이면 관계 해석이 복잡해질 수 있습니다.",
    advice: "호감과 역할을 구분하는 말이 관계를 더 안정시킵니다.",
    phraseSeeds: ["홍염의 분위기에 ENTJ의 추진력이 붙으면 존재감이 강해집니다."],
  },
  {
    id: "fusion_jaeda_sinyak_entj_workaholic",
    kind: "reinforcement",
    sajuEntryIds: ["pattern_jaeda_sinyak"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["burnout_risk"],
    requiredMbtiTags: ["achievement_drive"],
    topic: "weaknesses",
    priority: 89,
    summary: "재다신약 + ENTJ 워커홀릭",
    interpretation: "재다신약의 책임 압박과 ENTJ의 목표 몰입이 겹치면 일을 멈추는 기준이 흐려질 수 있습니다.",
    caution: "성과가 나와도 몸과 감정의 잔고는 따로 확인해야 합니다.",
    advice: "일정표에 쉬는 칸을 먼저 고정하는 방식이 맞습니다.",
    phraseSeeds: ["돈과 성취가 같이 켜질수록 회복 기준이 필요합니다."],
  },
  {
    id: "fusion_earth_excess_entj_reality",
    kind: "reinforcement",
    sajuEntryIds: ["element_earth_excess"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["asset_building"],
    requiredMbtiTags: ["efficiency_focus"],
    topic: "money_asset",
    priority: 88,
    summary: "토 과다 + ENTJ 현실성",
    interpretation: "토의 저장성과 ENTJ의 효율감이 겹치면 자원, 일정, 사람을 결과 중심으로 재배치하는 힘이 생깁니다.",
    caution: "모든 것을 관리 대상으로 보면 가까운 사람이 피곤해질 수 있습니다.",
    advice: "관리할 것과 믿고 맡길 것을 나누는 기준이 필요합니다.",
    phraseSeeds: ["현실감이 강해서 목표가 구체적인 숫자로 내려옵니다."],
  },
  {
    id: "fusion_metal_strong_entj_judgment",
    kind: "reinforcement",
    sajuEntryIds: ["element_metal_strong"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["sharp_analysis"],
    requiredMbtiTags: ["strategic_thinking"],
    topic: "work_career",
    priority: 87,
    summary: "금 강함 + ENTJ 판단력",
    interpretation: "금의 기준 세우기와 ENTJ의 전략성이 겹치면 복잡한 판을 빠르게 자르고 우선순위를 세웁니다.",
    caution: "판단이 빠른 만큼 설명이 짧아지면 차갑게 보일 수 있습니다.",
    advice: "판단 근거를 한 줄만 더 보여줘도 신뢰가 올라갑니다.",
    phraseSeeds: ["금의 절단력과 ENTJ의 구조화가 함께 움직입니다."],
  },
  {
    id: "fusion_gabmok_gapsin_entj_command",
    kind: "topic_specialization",
    sajuEntryIds: ["day_master_gabmok", "day_pillar_gapsin"],
    mbtiTypes: ["ENTJ"],
    requiredSajuTags: ["leadership"],
    requiredMbtiTags: ["control_need"],
    topic: "personality",
    priority: 86,
    summary: "갑목/갑신 + ENTJ 지휘 욕구",
    interpretation: "갑목의 방향성, 갑신일주의 판단력, ENTJ의 통제 욕구가 맞물리면 앞에서 구조를 세우고 싶어집니다.",
    caution: "지휘가 강해질수록 상대의 속도를 놓치기 쉽습니다.",
    advice: "지시보다 목표 공유를 먼저 하면 추진력이 덜 날카롭게 전달됩니다.",
    phraseSeeds: ["사주에도 앞에서 길을 내는 구조가 있습니다."],
  },
  {
    id: "fusion_water_missing_f_emotional_need",
    kind: "compensation",
    sajuEntryIds: ["element_water_missing"],
    mbtiTypes: ["INFJ", "INFP", "ENFJ", "ENFP", "ISFJ", "ISFP", "ESFJ", "ESFP"],
    requiredSajuTags: ["emotional_dryness"],
    requiredMbtiTags: ["empathy_need"],
    topic: "love_relationship",
    priority: 80,
    summary: "수 부족 + F 유형 emotional need",
    interpretation: "F 성향은 정서 확인을 원하지만 사주에서 수가 부족하면 감정의 흐름을 말로 풀기까지 시간이 걸릴 수 있습니다.",
    caution: "공감 욕구와 표현 속도가 다르면 스스로도 헷갈릴 수 있습니다.",
    advice: "감정 단어를 미리 준비하면 관계 반응이 부드러워집니다.",
    phraseSeeds: ["MBTI는 공감을 원하고 사주는 감정 물길을 보완하라고 말합니다."],
  },
  {
    id: "fusion_fire_missing_e_expression_contrast",
    kind: "contrast",
    sajuEntryIds: ["element_fire_missing"],
    mbtiTypes: ["ENTJ", "ENTP", "ENFJ", "ENFP", "ESTJ", "ESFJ", "ESTP", "ESFP"],
    requiredSajuTags: ["expression_weakness"],
    requiredMbtiTags: ["public_presence"],
    topic: "human_relations",
    priority: 79,
    summary: "화 부족 + E 유형 expression contrast",
    interpretation: "E 성향처럼 밖으로 향해도 사주 화가 약하면 친밀한 표현은 덜 자연스럽게 느껴질 수 있습니다.",
    caution: "활동량과 정서 표현량은 같은 것이 아닙니다.",
    advice: "말수보다 온도를 보여주는 작은 표현을 늘리는 편이 좋습니다.",
    phraseSeeds: ["외향성과 표현 온도는 다르게 움직일 수 있습니다."],
  },
  {
    id: "fusion_wood_missing_j_rigidity",
    kind: "compensation",
    sajuEntryIds: ["element_wood_missing"],
    mbtiTypes: ["INTJ", "ENTJ", "INFJ", "ENFJ", "ISTJ", "ESTJ", "ISFJ", "ESFJ"],
    requiredSajuTags: ["flexibility_need"],
    requiredMbtiTags: ["stability_need"],
    topic: "final_advice",
    priority: 78,
    summary: "목 부족 + J 유형 rigidity risk",
    interpretation: "J의 계획성과 목 부족의 전환 약점이 겹치면 기준이 무너지는 상황을 불편하게 느끼기 쉽습니다.",
    caution: "계획을 지키는 힘이 강점이지만 변화 대응 칸도 필요합니다.",
    advice: "처음부터 예비 선택지를 두 개 만들어 두면 유연성이 올라갑니다.",
    phraseSeeds: ["계획형 성향 위에 목 부족이 얹히면 전환 연습이 중요합니다."],
  },
  {
    id: "fusion_wealth_tj_money_structure",
    kind: "topic_specialization",
    sajuEntryIds: ["ten_god_pian_cai", "ten_god_zheng_cai"],
    mbtiTypes: ["INTJ", "ENTJ", "ISTJ", "ESTJ"],
    requiredSajuTags: ["money_orientation"],
    requiredMbtiTags: ["efficiency_focus"],
    topic: "money_asset",
    priority: 77,
    summary: "재성 강함 + TJ money/structure",
    interpretation: "재성의 자원 감각과 TJ의 구조화가 겹치면 돈을 감정보다 관리 체계로 보려는 힘이 커집니다.",
    advice: "예산, 우선순위, 손익 기준을 보이는 곳에 두는 방식이 맞습니다.",
    phraseSeeds: ["돈을 벌 감각보다 관리 구조가 더 중요해집니다."],
  },
  {
    id: "fusion_officer_j_responsibility",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_qi_sha", "ten_god_zheng_guan"],
    mbtiTypes: ["INTJ", "ENTJ", "INFJ", "ENFJ", "ISTJ", "ESTJ", "ISFJ", "ESFJ"],
    requiredSajuTags: ["responsibility_pressure"],
    requiredMbtiTags: ["self_discipline"],
    topic: "work_career",
    priority: 76,
    summary: "관성 강함 + J responsibility",
    interpretation: "관성의 책임 신호와 J의 자기관리 성향이 겹치면 역할과 마감에 강하지만 부담도 커집니다.",
    advice: "책임의 범위를 먼저 정하고 시작해야 오래 갑니다.",
    phraseSeeds: ["책임을 잘 지는 만큼 책임선을 정해야 합니다."],
  },
  {
    id: "fusion_output_e_expression",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_shi_shen", "ten_god_shang_guan"],
    mbtiTypes: ["ENTJ", "ENTP", "ENFJ", "ENFP", "ESTJ", "ESFJ", "ESTP", "ESFP"],
    requiredSajuTags: ["public_presence"],
    requiredMbtiTags: ["public_presence"],
    topic: "strengths",
    priority: 75,
    summary: "식상 강함 + E expression",
    interpretation: "식상의 output과 E의 대외 반응성이 겹치면 말, 발표, 콘텐츠, 현장 대응에서 강점이 살아납니다.",
    advice: "보여주는 방식이 곧 실력이 되므로 기록과 발표 루틴을 잡는 편이 좋습니다.",
    phraseSeeds: ["밖으로 내보내는 힘이 MBTI의 활동성과 맞물립니다."],
  },
  {
    id: "fusion_resource_n_introspection",
    kind: "topic_specialization",
    sajuEntryIds: ["ten_god_pian_yin", "ten_god_zheng_yin"],
    mbtiTypes: ["INTJ", "INTP", "ENTJ", "ENTP", "INFJ", "INFP", "ENFJ", "ENFP"],
    requiredSajuTags: ["strategic_thinking"],
    requiredMbtiTags: ["strategic_thinking"],
    topic: "study_growth",
    priority: 74,
    summary: "인성 강함 + N introspection",
    interpretation: "인성의 흡수력과 N의 추상화가 겹치면 배움이 단순 정보보다 관점과 체계로 쌓입니다.",
    advice: "읽고 끝내기보다 자기 언어로 구조화할 때 전문성이 커집니다.",
    phraseSeeds: ["사주도 MBTI도 생각을 안쪽에서 숙성시키는 쪽을 가리킵니다."],
  },
  {
    id: "fusion_peer_e_competition",
    kind: "reinforcement",
    sajuEntryIds: ["ten_god_bijian", "ten_god_jie_cai"],
    mbtiTypes: ["ENTJ", "ENTP", "ENFJ", "ENFP", "ESTJ", "ESFJ", "ESTP", "ESFP"],
    requiredSajuTags: ["competition"],
    requiredMbtiTags: ["public_presence"],
    topic: "human_relations",
    priority: 73,
    summary: "비겁 강함 + E social/competition",
    interpretation: "비겁의 동료·경쟁 신호와 E의 사회성이 겹치면 사람 속에서 에너지가 올라오지만 비교 피로도 생깁니다.",
    advice: "경쟁할 관계와 협력할 관계를 구분하면 소모가 줄어듭니다.",
    phraseSeeds: ["사람 속에서 힘이 올라오지만 비교도 같이 켜집니다."],
  },
  {
    id: "fusion_yeokma_p_flexibility",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_yeokma"],
    mbtiTypes: ["INTP", "ENTP", "INFP", "ENFP", "ISTP", "ESTP", "ISFP", "ESFP"],
    requiredSajuTags: ["flexibility_need"],
    requiredMbtiTags: ["flexibility_need"],
    topic: "environment_luck",
    priority: 72,
    summary: "역마살 + P flexibility",
    interpretation: "역마살의 이동 신호와 P의 유연성이 겹치면 낯선 환경에서 기회 감각이 올라옵니다.",
    advice: "움직임을 충동으로만 쓰지 말고 탐색 목표와 연결하면 좋습니다.",
    phraseSeeds: ["움직일수록 정보와 기회가 열리는 편입니다."],
  },
  {
    id: "fusion_cheoneul_relationship_support",
    kind: "compensation",
    sajuEntryIds: ["nobleman_cheoneul"],
    requiredSajuTags: ["empathy_need"],
    topic: "human_relations",
    priority: 71,
    summary: "천을귀인 + relationship support",
    interpretation: "천을귀인은 어려운 장면에서 조언자나 완충자가 들어오기 쉬운 관계 도움 신호입니다.",
    advice: "혼자 버티기보다 질문을 잘 던질 때 도움 운이 현실화됩니다.",
    phraseSeeds: ["귀인은 태도와 연결망을 통해 작동합니다."],
  },
  {
    id: "fusion_munchang_nt_intellectual_skill",
    kind: "topic_specialization",
    sajuEntryIds: ["nobleman_munchang"],
    mbtiTypes: ["INTJ", "INTP", "ENTJ", "ENTP"],
    requiredSajuTags: ["precision_skill"],
    requiredMbtiTags: ["strategic_thinking"],
    topic: "study_growth",
    priority: 70,
    summary: "문창귀인 + N/T intellectual skill",
    interpretation: "문창귀인의 언어·학습 감각과 NT의 분석성이 겹치면 복잡한 내용을 구조화하는 힘이 커집니다.",
    advice: "글, 도식, 발표 자료로 남길수록 실력이 선명해집니다.",
    phraseSeeds: ["지적 감각이 말과 글로 정리될 때 강점이 됩니다."],
  },
  {
    id: "fusion_hongyeom_e_social_charm",
    kind: "reinforcement",
    sajuEntryIds: ["sinsal_hongyeom"],
    mbtiTypes: ["ENTJ", "ENTP", "ENFJ", "ENFP", "ESTJ", "ESFJ", "ESTP", "ESFP"],
    requiredSajuTags: ["romantic_attraction"],
    requiredMbtiTags: ["public_presence"],
    topic: "love_relationship",
    priority: 69,
    summary: "홍염살 + E social charm",
    interpretation: "홍염살의 분위기와 E의 대외 에너지가 겹치면 첫인상과 현장 매력이 강하게 남습니다.",
    advice: "호감이 빠르게 붙을 수 있어 관계 속도를 조절하는 말이 필요합니다.",
    phraseSeeds: ["존재감이 관계 신호로 읽히기 쉬운 조합입니다."],
  },
  {
    id: "fusion_gwimun_infp_inner_depth",
    kind: "topic_specialization",
    sajuEntryIds: ["sinsal_gwimun"],
    mbtiTypes: ["INFP", "INFJ", "INTJ", "INTP"],
    requiredSajuTags: ["loneliness"],
    requiredMbtiTags: ["independence"],
    topic: "personality",
    priority: 68,
    summary: "귀문관살 + 내향 직관 깊이",
    interpretation: "귀문관살의 예민한 포착력과 내향형의 내부 처리 성향이 겹치면 생각이 깊고 오래 갑니다.",
    advice: "기록으로 밖에 꺼내야 생각이 고립되지 않습니다.",
    phraseSeeds: ["내면의 감각이 깊지만 밖으로 꺼내는 장치가 필요합니다."],
  },
  {
    id: "fusion_jaego_money_storage",
    kind: "topic_specialization",
    sajuEntryIds: ["nobleman_jaego"],
    requiredSajuTags: ["asset_building"],
    topic: "money_asset",
    priority: 67,
    summary: "재고귀인 + 자산 저장 감각",
    interpretation: "재고귀인은 빠른 소비보다 보관, 축적, 나중에 꺼내 쓰는 돈 감각과 잘 맞습니다.",
    advice: "계좌, 예산, 물건의 위치까지 정리할수록 안정감이 올라갑니다.",
    phraseSeeds: ["돈은 흘러가는 것보다 담아 두는 방식에서 강점이 납니다."],
  },
  {
    id: "fusion_salin_growth_pressure",
    kind: "compensation",
    sajuEntryIds: ["pattern_salin_sangsaeng"],
    requiredSajuTags: ["growth_orientation"],
    topic: "study_growth",
    priority: 66,
    summary: "살인상생 + 압박을 실력으로 전환",
    interpretation: "압박이 강한 구조라도 배움과 전문성으로 바꾸면 긴장이 실력의 재료가 됩니다.",
    advice: "불안할수록 더 큰 목표보다 작은 학습 단위가 필요합니다.",
    phraseSeeds: ["압박을 공부와 체계로 바꾸는 순간 강점이 됩니다."],
  },
] as const;
