import type { InterpretationTagId } from "./interpretationTags";
import type {
  FiveElement,
  KnowledgePhraseSeeds,
  SajuKnowledgeEntry,
  SajuKnowledgeTopic,
  TenGod,
} from "./sajuKnowledgeTypes";

const allTopics: readonly SajuKnowledgeTopic[] = [
  "personality",
  "strengths",
  "weaknesses",
  "work_career",
  "money_asset",
  "love_relationship",
  "human_relations",
  "family_independence",
  "study_growth",
  "environment_luck",
  "final_advice",
];

export const FIVE_ELEMENTS = [
  "wood",
  "fire",
  "earth",
  "metal",
  "water",
] as const satisfies readonly FiveElement[];

export const TEN_GODS = [
  "bijian",
  "jie_cai",
  "shi_shen",
  "shang_guan",
  "pian_cai",
  "zheng_cai",
  "qi_sha",
  "zheng_guan",
  "pian_yin",
  "zheng_yin",
] as const satisfies readonly TenGod[];

function topicWeights(
  entries: readonly [SajuKnowledgeTopic, number][],
): Partial<Record<SajuKnowledgeTopic, number>> {
  return Object.fromEntries(entries) as Partial<Record<SajuKnowledgeTopic, number>>;
}

function broadTopicWeights(weight = 0.4): Partial<Record<SajuKnowledgeTopic, number>> {
  return Object.fromEntries(allTopics.map((topic) => [topic, weight])) as Partial<
    Record<SajuKnowledgeTopic, number>
  >;
}

function phraseSeeds(labelKo: string): KnowledgePhraseSeeds {
  return {
    analytical: [`${labelKo}은 구조를 보는 핵심 단서입니다.`],
    conversational: [`${labelKo}이 있으면 이런 식으로 체감될 수 있습니다.`],
    caution: [`${labelKo}은 강점이 과해질 때 조절이 필요합니다.`],
    advice: [`${labelKo}은 쓸 자리와 쉬게 할 자리를 나누는 편이 좋습니다.`],
  };
}

function entry(input: SajuKnowledgeEntry): SajuKnowledgeEntry {
  return input;
}

function fiveElementEntry(input: {
  readonly id: string;
  readonly labelKo: string;
  readonly aliases: readonly string[];
  readonly summary: string;
  readonly meaning: string;
  readonly positiveTags: readonly InterpretationTagId[];
  readonly riskTags: readonly InterpretationTagId[];
  readonly mbtiBridgeTags: readonly InterpretationTagId[];
}): SajuKnowledgeEntry {
  return entry({
    id: input.id,
    category: "five_element",
    labelKo: input.labelKo,
    aliases: input.aliases,
    summary: input.summary,
    meaning: input.meaning,
    positiveTags: input.positiveTags,
    riskTags: input.riskTags,
    topicWeights: broadTopicWeights(0.35),
    mbtiBridgeTags: input.mbtiBridgeTags,
    phraseSeeds: phraseSeeds(input.labelKo),
  });
}

export const SAJU_KNOWLEDGE_BASE = [
  fiveElementEntry({
    id: "element_wood",
    labelKo: "목",
    aliases: ["wood", "나무", "생장"],
    summary: "성장, 확장, 방향성, 기획의 기운입니다.",
    meaning: "목은 위로 뻗고 길을 만드는 힘이라 계획, 성장 욕구, 시작의 감각과 연결됩니다.",
    positiveTags: ["growth_orientation", "strategic_thinking"],
    riskTags: ["flexibility_need"],
    mbtiBridgeTags: ["growth_orientation", "strategic_thinking"],
  }),
  fiveElementEntry({
    id: "element_fire",
    labelKo: "화",
    aliases: ["fire", "불", "표현"],
    summary: "표현, 가시성, 매력, 자기 드러냄의 기운입니다.",
    meaning: "화는 밖으로 밝아지는 힘이라 말, 표정, 존재감, 빠른 반응과 연결됩니다.",
    positiveTags: ["public_presence", "romantic_attraction"],
    riskTags: ["burnout_risk"],
    mbtiBridgeTags: ["public_presence", "direct_speech"],
  }),
  fiveElementEntry({
    id: "element_earth",
    labelKo: "토",
    aliases: ["earth", "흙", "저장"],
    summary: "현실감, 책임, 저장, 자산화의 기운입니다.",
    meaning: "토는 흐름을 받아 담는 힘이라 돈, 안정, 역할 부담, 현실 처리와 연결됩니다.",
    positiveTags: ["asset_building", "responsibility_pressure"],
    riskTags: ["low_rest_capacity", "stability_need"],
    mbtiBridgeTags: ["asset_building", "stability_need"],
  }),
  fiveElementEntry({
    id: "element_metal",
    labelKo: "금",
    aliases: ["metal", "쇠", "판단"],
    summary: "규칙, 판단, 정밀성, 권위의 기운입니다.",
    meaning: "금은 자르고 정리하는 힘이라 기준, 분석, 선 긋기, 공식 역할과 연결됩니다.",
    positiveTags: ["sharp_analysis", "precision_skill", "authority_orientation"],
    riskTags: ["direct_speech", "relationship_distance"],
    mbtiBridgeTags: ["sharp_analysis", "precision_skill"],
  }),
  fiveElementEntry({
    id: "element_water",
    labelKo: "수",
    aliases: ["water", "물", "회복"],
    summary: "휴식, 지혜, 유연성, 감정 흐름, 학습의 기운입니다.",
    meaning: "수는 내려가고 흐르는 힘이라 회복, 감정 처리, 공부, 적응력과 연결됩니다.",
    positiveTags: ["flexibility_need", "growth_orientation", "empathy_need"],
    riskTags: ["loneliness"],
    mbtiBridgeTags: ["flexibility_need", "empathy_need"],
  }),
  entry({
    id: "element_earth_excess",
    category: "element_balance",
    labelKo: "토 과다",
    aliases: ["earth_excess", "토 많음", "토 강함"],
    summary: "현실감과 책임이 강하지만 무거움과 과부하도 커질 수 있습니다.",
    meaning: "토가 강하면 결과를 남기고 자원을 묶는 힘이 좋지만, 책임을 너무 빨리 떠안을 수 있습니다.",
    positiveTags: ["asset_building", "responsibility_pressure", "stability_need"],
    riskTags: ["low_rest_capacity", "burnout_risk"],
    topicWeights: topicWeights([
      ["money_asset", 0.9],
      ["work_career", 0.65],
      ["weaknesses", 0.6],
      ["final_advice", 0.5],
    ]),
    mbtiBridgeTags: ["asset_building", "efficiency_focus"],
    phraseSeeds: phraseSeeds("토 과다"),
  }),
  entry({
    id: "element_water_missing",
    category: "element_balance",
    labelKo: "수 부족",
    aliases: ["water_missing", "수 약함", "수 기운 부족"],
    summary: "감정의 물길과 회복 리듬이 부족해지기 쉬운 구조입니다.",
    meaning: "수 부족은 판단은 빠른데 쉬는 법, 감정 완충, 유연한 전환이 늦게 따라오는 신호입니다.",
    positiveTags: ["self_discipline"],
    riskTags: ["emotional_dryness", "flexibility_need", "low_rest_capacity"],
    topicWeights: topicWeights([
      ["personality", 0.65],
      ["weaknesses", 0.85],
      ["love_relationship", 0.6],
      ["human_relations", 0.55],
      ["final_advice", 0.7],
    ]),
    mbtiBridgeTags: ["emotional_dryness", "low_rest_capacity", "flexibility_need"],
    phraseSeeds: phraseSeeds("수 부족"),
  }),
  entry({
    id: "element_fire_missing",
    category: "element_balance",
    labelKo: "화 부족",
    aliases: ["fire_missing", "화 약함", "화 기운 부족"],
    summary: "표현과 온도가 늦게 켜져 겉보기와 내면 추진력이 다르게 보일 수 있습니다.",
    meaning: "화 부족은 말로 드러내는 속도보다 내부 판단이 먼저 움직이는 구조입니다.",
    positiveTags: ["strategic_thinking"],
    riskTags: ["expression_weakness", "relationship_distance"],
    topicWeights: topicWeights([
      ["personality", 0.55],
      ["love_relationship", 0.6],
      ["human_relations", 0.6],
      ["final_advice", 0.55],
    ]),
    mbtiBridgeTags: ["expression_weakness", "emotional_dryness"],
    phraseSeeds: phraseSeeds("화 부족"),
  }),
  entry({
    id: "element_wood_missing",
    category: "element_balance",
    labelKo: "목 부족",
    aliases: ["wood_missing", "목 약함", "목 기운 부족"],
    summary: "새 길을 여는 유연함보다 기존 기준을 붙잡기 쉬운 흐름입니다.",
    meaning: "목 부족은 방향 전환과 장기 확장보다 현재 책임과 규칙이 앞서는 신호입니다.",
    positiveTags: ["self_discipline"],
    riskTags: ["flexibility_need", "stability_need"],
    topicWeights: topicWeights([
      ["weaknesses", 0.55],
      ["study_growth", 0.55],
      ["final_advice", 0.55],
    ]),
    mbtiBridgeTags: ["stability_need", "flexibility_need"],
    phraseSeeds: phraseSeeds("목 부족"),
  }),
  entry({
    id: "element_metal_strong",
    category: "element_balance",
    labelKo: "금 강함",
    aliases: ["metal_strong", "금 강세", "금 기운 강함"],
    summary: "판단, 기준, 정밀성이 선명하게 살아나는 구조입니다.",
    meaning: "금이 강하면 일과 관계를 흐릿하게 두기보다 기준을 세워 정리하려 합니다.",
    positiveTags: ["sharp_analysis", "precision_skill", "authority_orientation"],
    riskTags: ["direct_speech", "relationship_distance"],
    topicWeights: topicWeights([
      ["personality", 0.65],
      ["work_career", 0.75],
      ["human_relations", 0.5],
      ["weaknesses", 0.5],
    ]),
    mbtiBridgeTags: ["sharp_analysis", "direct_speech"],
    phraseSeeds: phraseSeeds("금 강함"),
  }),
  entry({
    id: "ten_god_bijian",
    category: "ten_god",
    labelKo: "비견",
    aliases: ["bijian", "견줄 비견"],
    summary: "자기 기준, 동료성, 독립적 추진을 뜻합니다.",
    meaning: "비견은 나와 같은 결의 힘이라 주도성, 동료 경쟁, 독립 욕구와 연결됩니다.",
    positiveTags: ["independence", "self_discipline"],
    riskTags: ["competition"],
    topicWeights: topicWeights([
      ["personality", 0.55],
      ["human_relations", 0.5],
      ["work_career", 0.45],
    ]),
    mbtiBridgeTags: ["independence", "competition"],
    phraseSeeds: phraseSeeds("비견"),
  }),
  entry({
    id: "ten_god_jie_cai",
    category: "ten_god",
    labelKo: "겁재",
    aliases: ["jie_cai", "겁재"],
    summary: "경쟁, 분산, 강한 동료 자극을 뜻합니다.",
    meaning: "겁재는 나와 비슷한 힘이 자원을 흔드는 구조라 협업과 경쟁이 함께 올라옵니다.",
    positiveTags: ["competition", "leadership"],
    riskTags: ["money_orientation", "relationship_distance"],
    topicWeights: topicWeights([
      ["human_relations", 0.65],
      ["money_asset", 0.55],
      ["weaknesses", 0.5],
    ]),
    mbtiBridgeTags: ["competition", "control_need"],
    phraseSeeds: phraseSeeds("겁재"),
  }),
  entry({
    id: "ten_god_shi_shen",
    category: "ten_god",
    labelKo: "식신",
    aliases: ["shi_shen", "식신"],
    summary: "표현, 생산, 꾸준한 output을 뜻합니다.",
    meaning: "식신은 내가 만들어 밖으로 내보내는 힘이라 결과물, 말, 콘텐츠, 안정적 생산성과 연결됩니다.",
    positiveTags: ["public_presence", "growth_orientation"],
    riskTags: ["low_rest_capacity"],
    topicWeights: topicWeights([
      ["work_career", 0.65],
      ["study_growth", 0.5],
      ["love_relationship", 0.45],
    ]),
    mbtiBridgeTags: ["public_presence", "growth_orientation"],
    phraseSeeds: phraseSeeds("식신"),
  }),
  entry({
    id: "ten_god_shang_guan",
    category: "ten_god",
    labelKo: "상관",
    aliases: ["shang_guan", "상관"],
    summary: "날카로운 표현, 반박, 창의적 해체를 뜻합니다.",
    meaning: "상관은 기존 권위를 건드리는 output이라 말의 힘, 기획력, 예민한 표현과 연결됩니다.",
    positiveTags: ["direct_speech", "sharp_analysis", "public_presence"],
    riskTags: ["relationship_distance", "authority_orientation"],
    topicWeights: topicWeights([
      ["personality", 0.6],
      ["work_career", 0.65],
      ["human_relations", 0.55],
    ]),
    mbtiBridgeTags: ["direct_speech", "sharp_analysis"],
    phraseSeeds: phraseSeeds("상관"),
  }),
  entry({
    id: "ten_god_pian_cai",
    category: "ten_god",
    labelKo: "편재",
    aliases: ["pian_cai", "편재", "재성"],
    summary: "큰 자원, 거래 감각, 외부 기회를 뜻합니다.",
    meaning: "편재는 고정급보다 흐름 속 자원을 읽는 힘이라 사업성, 사람 자원, 기회 포착과 연결됩니다.",
    positiveTags: ["money_orientation", "asset_building", "strategic_thinking"],
    riskTags: ["burnout_risk", "responsibility_pressure"],
    topicWeights: topicWeights([
      ["money_asset", 0.9],
      ["work_career", 0.65],
      ["love_relationship", 0.45],
    ]),
    mbtiBridgeTags: ["money_orientation", "efficiency_focus"],
    phraseSeeds: phraseSeeds("편재"),
  }),
  entry({
    id: "ten_god_zheng_cai",
    category: "ten_god",
    labelKo: "정재",
    aliases: ["zheng_cai", "정재", "재성"],
    summary: "관리 가능한 돈, 안정적 축적, 현실 감각을 뜻합니다.",
    meaning: "정재는 예측 가능한 자원을 관리하는 힘이라 예산, 안정, 소유, 책임과 연결됩니다.",
    positiveTags: ["asset_building", "stability_need", "self_discipline"],
    riskTags: ["responsibility_pressure"],
    topicWeights: topicWeights([
      ["money_asset", 0.85],
      ["family_independence", 0.5],
      ["final_advice", 0.45],
    ]),
    mbtiBridgeTags: ["asset_building", "stability_need"],
    phraseSeeds: phraseSeeds("정재"),
  }),
  entry({
    id: "ten_god_qi_sha",
    category: "ten_god",
    labelKo: "편관",
    aliases: ["qi_sha", "칠살", "편관", "관성"],
    summary: "압박, 위기 대응, 강한 책임을 뜻합니다.",
    meaning: "편관은 긴장 속에서 기준을 세우는 힘이라 추진력, 리더십, 압박감과 연결됩니다.",
    positiveTags: ["leadership", "authority_orientation", "self_discipline"],
    riskTags: ["responsibility_pressure", "burnout_risk"],
    topicWeights: topicWeights([
      ["work_career", 0.85],
      ["weaknesses", 0.6],
      ["final_advice", 0.55],
    ]),
    mbtiBridgeTags: ["leadership", "responsibility_pressure"],
    phraseSeeds: phraseSeeds("편관"),
  }),
  entry({
    id: "ten_god_zheng_guan",
    category: "ten_god",
    labelKo: "정관",
    aliases: ["zheng_guan", "정관", "관성"],
    summary: "공식 책임, 질서, 역할 안정성을 뜻합니다.",
    meaning: "정관은 사회적 기준을 내 안에 세우는 힘이라 직함, 신뢰, 조직 감각과 연결됩니다.",
    positiveTags: ["authority_orientation", "self_discipline", "leadership"],
    riskTags: ["responsibility_pressure", "control_need"],
    topicWeights: topicWeights([
      ["work_career", 0.8],
      ["human_relations", 0.5],
      ["family_independence", 0.45],
    ]),
    mbtiBridgeTags: ["authority_orientation", "leadership"],
    phraseSeeds: phraseSeeds("정관"),
  }),
  entry({
    id: "ten_god_pian_yin",
    category: "ten_god",
    labelKo: "편인",
    aliases: ["pian_yin", "편인", "인성"],
    summary: "비정형 학습, 감각적 통찰, 독특한 몰입을 뜻합니다.",
    meaning: "편인은 남들과 다른 방식으로 받아들이는 힘이라 직관, 연구, 고립된 집중과 연결됩니다.",
    positiveTags: ["strategic_thinking", "precision_skill", "independence"],
    riskTags: ["loneliness", "relationship_distance"],
    topicWeights: topicWeights([
      ["study_growth", 0.8],
      ["personality", 0.55],
      ["human_relations", 0.45],
    ]),
    mbtiBridgeTags: ["strategic_thinking", "loneliness"],
    phraseSeeds: phraseSeeds("편인"),
  }),
  entry({
    id: "ten_god_zheng_yin",
    category: "ten_god",
    labelKo: "정인",
    aliases: ["zheng_yin", "정인", "인성"],
    summary: "정리된 학습, 보호, 안정적 흡수를 뜻합니다.",
    meaning: "정인은 지식과 돌봄을 받아 내면을 채우는 힘이라 공부, 자격, 신뢰와 연결됩니다.",
    positiveTags: ["stability_need", "self_discipline", "growth_orientation"],
    riskTags: ["low_rest_capacity"],
    topicWeights: topicWeights([
      ["study_growth", 0.75],
      ["family_independence", 0.5],
      ["final_advice", 0.45],
    ]),
    mbtiBridgeTags: ["stability_need", "growth_orientation"],
    phraseSeeds: phraseSeeds("정인"),
  }),
  entry({
    id: "pattern_jaeda_sinyak",
    category: "special_pattern",
    labelKo: "재다신약",
    aliases: ["재다신약", "재성 강하고 일간 약함"],
    summary: "돈과 책임 신호가 강한데 자신을 받치는 힘은 약해질 수 있는 구조입니다.",
    meaning: "재다신약은 현실 책임과 자원 관리 압박이 커져 성취욕과 소모가 같이 올라오는 후보 구조입니다.",
    positiveTags: ["money_orientation", "achievement_drive"],
    riskTags: ["burnout_risk", "responsibility_pressure", "low_rest_capacity"],
    topicWeights: topicWeights([
      ["money_asset", 0.9],
      ["work_career", 0.75],
      ["weaknesses", 0.75],
      ["final_advice", 0.7],
    ]),
    mbtiBridgeTags: ["achievement_drive", "burnout_risk"],
    phraseSeeds: phraseSeeds("재다신약"),
  }),
  entry({
    id: "pattern_gwansal_honjob",
    category: "special_pattern",
    labelKo: "관살혼잡",
    aliases: ["관살혼잡", "정관 편관 혼재"],
    summary: "공식 책임과 압박 책임이 함께 들어오는 구조입니다.",
    meaning: "관살혼잡은 기준은 강하지만 어느 기준을 따라야 하는지 혼선이 생기기 쉬운 후보 구조입니다.",
    positiveTags: ["responsibility_pressure", "authority_orientation"],
    riskTags: ["control_need", "burnout_risk"],
    topicWeights: topicWeights([
      ["work_career", 0.75],
      ["weaknesses", 0.65],
      ["final_advice", 0.55],
    ]),
    mbtiBridgeTags: ["authority_orientation", "control_need"],
    phraseSeeds: phraseSeeds("관살혼잡"),
  }),
  entry({
    id: "pattern_siksang_saengjae",
    category: "special_pattern",
    labelKo: "식상생재",
    aliases: ["식상생재", "output to money"],
    summary: "표현과 생산이 돈과 기회로 이어지는 구조입니다.",
    meaning: "식상생재는 내가 만든 결과물이 시장성, 교환, 자원 흐름으로 연결되는 후보 구조입니다.",
    positiveTags: ["money_orientation", "public_presence", "efficiency_focus"],
    riskTags: ["burnout_risk"],
    topicWeights: topicWeights([
      ["work_career", 0.8],
      ["money_asset", 0.85],
      ["strengths", 0.65],
    ]),
    mbtiBridgeTags: ["efficiency_focus", "money_orientation"],
    phraseSeeds: phraseSeeds("식상생재"),
  }),
  entry({
    id: "pattern_jaesaenggwan",
    category: "special_pattern",
    labelKo: "재생관",
    aliases: ["재생관", "money to authority"],
    summary: "자원 관리가 역할과 신뢰로 이어지는 구조입니다.",
    meaning: "재생관은 현실 성과가 공식 역할, 직함, 책임으로 이어지는 후보 구조입니다.",
    positiveTags: ["asset_building", "authority_orientation", "leadership"],
    riskTags: ["responsibility_pressure"],
    topicWeights: topicWeights([
      ["work_career", 0.75],
      ["money_asset", 0.65],
      ["environment_luck", 0.55],
    ]),
    mbtiBridgeTags: ["leadership", "asset_building"],
    phraseSeeds: phraseSeeds("재생관"),
  }),
  entry({
    id: "pattern_salin_sangsaeng",
    category: "special_pattern",
    labelKo: "살인상생",
    aliases: ["살인상생", "압박이 학습으로 전환"],
    summary: "압박을 공부와 전문성으로 바꾸는 구조입니다.",
    meaning: "살인상생은 긴장을 실력으로 전환할 때 강해지는 후보 구조입니다.",
    positiveTags: ["precision_skill", "self_discipline", "growth_orientation"],
    riskTags: ["responsibility_pressure"],
    topicWeights: topicWeights([
      ["study_growth", 0.8],
      ["work_career", 0.7],
      ["final_advice", 0.55],
    ]),
    mbtiBridgeTags: ["precision_skill", "growth_orientation"],
    phraseSeeds: phraseSeeds("살인상생"),
  }),
  entry({
    id: "pattern_singang",
    category: "special_pattern",
    labelKo: "신강",
    aliases: ["신강", "일간 강함"],
    summary: "자기 중심축과 버티는 힘이 강한 구조입니다.",
    meaning: "신강은 외부 압력보다 자기 기준이 먼저 서는 후보 구조입니다.",
    positiveTags: ["independence", "self_discipline"],
    riskTags: ["control_need", "competition"],
    topicWeights: topicWeights([
      ["personality", 0.7],
      ["strengths", 0.6],
      ["weaknesses", 0.5],
    ]),
    mbtiBridgeTags: ["independence", "control_need"],
    phraseSeeds: phraseSeeds("신강"),
  }),
  entry({
    id: "pattern_sinyak",
    category: "special_pattern",
    labelKo: "신약",
    aliases: ["신약", "일간 약함"],
    summary: "외부 역할과 환경 압력이 자기 리듬보다 크게 느껴질 수 있는 구조입니다.",
    meaning: "신약은 주변 조건을 잘 읽는 대신 회복과 자기 기준 보강이 중요해지는 후보 구조입니다.",
    positiveTags: ["empathy_need", "strategic_thinking"],
    riskTags: ["low_rest_capacity", "relationship_distance"],
    topicWeights: topicWeights([
      ["weaknesses", 0.7],
      ["human_relations", 0.55],
      ["final_advice", 0.65],
    ]),
    mbtiBridgeTags: ["low_rest_capacity", "empathy_need"],
    phraseSeeds: phraseSeeds("신약"),
  }),
  entry({
    id: "sinsal_hyeonchim",
    category: "sinsal",
    labelKo: "현침살",
    aliases: ["현침", "현침살"],
    summary: "말, 판단, 감각이 예리하게 찌르는 신호입니다.",
    meaning: "현침살은 분석과 검수에는 강점이 되지만 말의 강도가 높아질 때 조절이 필요합니다.",
    positiveTags: ["sharp_analysis", "precision_skill"],
    riskTags: ["direct_speech", "relationship_distance"],
    topicWeights: topicWeights([
      ["personality", 0.7],
      ["work_career", 0.65],
      ["human_relations", 0.65],
      ["weaknesses", 0.6],
    ]),
    mbtiBridgeTags: ["sharp_analysis", "direct_speech"],
    phraseSeeds: phraseSeeds("현침살"),
  }),
  entry({
    id: "sinsal_hongyeom",
    category: "sinsal",
    labelKo: "홍염살",
    aliases: ["홍염", "홍염살"],
    summary: "분위기, 말투, 표정이 관계 관심으로 이어지는 신호입니다.",
    meaning: "홍염살은 매력과 존재감을 키우지만 관계 기대가 빠르게 붙을 때 거리를 조절해야 합니다.",
    positiveTags: ["romantic_attraction", "public_presence"],
    riskTags: ["workplace_romance", "relationship_distance"],
    topicWeights: topicWeights([
      ["love_relationship", 0.85],
      ["human_relations", 0.6],
      ["personality", 0.45],
    ]),
    mbtiBridgeTags: ["romantic_attraction", "public_presence", "workplace_romance"],
    phraseSeeds: phraseSeeds("홍염살"),
  }),
  entry({
    id: "sinsal_mangsin",
    category: "sinsal",
    labelKo: "망신살",
    aliases: ["망신", "망신살"],
    summary: "내 모습이 외부 평가와 시선에 드러나는 신호입니다.",
    meaning: "망신살은 노출과 평가가 커지는 신호라 발표, 공개 활동, 평판 관리와 연결됩니다.",
    positiveTags: ["public_presence", "self_discipline"],
    riskTags: ["relationship_distance"],
    topicWeights: topicWeights([
      ["human_relations", 0.6],
      ["work_career", 0.55],
      ["environment_luck", 0.45],
    ]),
    mbtiBridgeTags: ["public_presence", "self_discipline"],
    phraseSeeds: phraseSeeds("망신살"),
  }),
  entry({
    id: "sinsal_baekho",
    category: "sinsal",
    labelKo: "백호대살",
    aliases: ["백호", "백호대살"],
    summary: "강한 압축 에너지와 긴장성을 가진 신호입니다.",
    meaning: "백호대살은 위기 대응과 몰입에는 강하지만 몸과 마음의 긴장을 풀 루틴이 필요합니다.",
    positiveTags: ["self_discipline", "precision_skill"],
    riskTags: ["burnout_risk", "low_rest_capacity"],
    topicWeights: topicWeights([
      ["work_career", 0.55],
      ["weaknesses", 0.65],
      ["final_advice", 0.6],
    ]),
    mbtiBridgeTags: ["self_discipline", "burnout_risk"],
    phraseSeeds: phraseSeeds("백호대살"),
  }),
  entry({
    id: "sinsal_yeokma",
    category: "sinsal",
    labelKo: "역마살",
    aliases: ["역마", "역마살"],
    summary: "이동, 변화, 외부 경험을 통해 흐름이 열리는 신호입니다.",
    meaning: "역마살은 움직임과 변화 속에서 기회가 보이는 신호라 고정된 환경만 고집하면 답답해질 수 있습니다.",
    positiveTags: ["flexibility_need", "growth_orientation"],
    riskTags: ["stability_need"],
    topicWeights: topicWeights([
      ["environment_luck", 0.8],
      ["work_career", 0.55],
      ["final_advice", 0.5],
    ]),
    mbtiBridgeTags: ["flexibility_need", "growth_orientation"],
    phraseSeeds: phraseSeeds("역마살"),
  }),
  entry({
    id: "sinsal_gwimun",
    category: "sinsal",
    labelKo: "귀문관살",
    aliases: ["귀문", "귀문관살"],
    summary: "감각적 몰입과 예민한 포착력이 강해지는 신호입니다.",
    meaning: "귀문관살은 남들이 놓친 분위기와 단서를 잡는 대신 생각이 안쪽으로 깊게 말릴 수 있습니다.",
    positiveTags: ["sharp_analysis", "strategic_thinking"],
    riskTags: ["loneliness", "emotional_dryness"],
    topicWeights: topicWeights([
      ["personality", 0.6],
      ["study_growth", 0.55],
      ["weaknesses", 0.55],
    ]),
    mbtiBridgeTags: ["sharp_analysis", "loneliness"],
    phraseSeeds: phraseSeeds("귀문관살"),
  }),
  entry({
    id: "sinsal_wonjin",
    category: "sinsal",
    labelKo: "원진살",
    aliases: ["원진", "원진살"],
    summary: "가까울수록 미묘한 불편감이 생기기 쉬운 관계 신호입니다.",
    meaning: "원진살은 호감과 불편함이 함께 움직일 수 있어 감정 해석을 서두르지 않는 편이 좋습니다.",
    positiveTags: ["empathy_need"],
    riskTags: ["relationship_distance", "loneliness"],
    topicWeights: topicWeights([
      ["love_relationship", 0.7],
      ["human_relations", 0.65],
      ["family_independence", 0.45],
    ]),
    mbtiBridgeTags: ["relationship_distance", "empathy_need"],
    phraseSeeds: phraseSeeds("원진살"),
  }),
  entry({
    id: "nobleman_cheoneul",
    category: "nobleman",
    labelKo: "천을귀인",
    aliases: ["천을", "천을귀인"],
    summary: "막힌 상황에서 조언, 중재, 완충이 들어오기 쉬운 도움 신호입니다.",
    meaning: "천을귀인은 누군가가 알아서 해결해 준다는 뜻보다 도움을 받을 태도와 연결망이 열리는 신호입니다.",
    positiveTags: ["stability_need", "empathy_need"],
    riskTags: [],
    topicWeights: topicWeights([
      ["environment_luck", 0.85],
      ["human_relations", 0.55],
      ["final_advice", 0.5],
    ]),
    mbtiBridgeTags: ["empathy_need", "stability_need"],
    phraseSeeds: phraseSeeds("천을귀인"),
  }),
  entry({
    id: "nobleman_cheondeok",
    category: "nobleman",
    labelKo: "천덕귀인",
    aliases: ["천덕", "천덕귀인"],
    summary: "갈등을 부드럽게 낮추는 완충과 보호의 도움 신호입니다.",
    meaning: "천덕귀인은 극단으로 치닫는 흐름을 누그러뜨리는 주변 조건과 연결됩니다.",
    positiveTags: ["stability_need", "empathy_need"],
    riskTags: [],
    topicWeights: topicWeights([
      ["environment_luck", 0.75],
      ["human_relations", 0.5],
    ]),
    mbtiBridgeTags: ["empathy_need"],
    phraseSeeds: phraseSeeds("천덕귀인"),
  }),
  entry({
    id: "nobleman_woldeok",
    category: "nobleman",
    labelKo: "월덕귀인",
    aliases: ["월덕", "월덕귀인"],
    summary: "관계와 환경에서 부드러운 도움을 받기 쉬운 신호입니다.",
    meaning: "월덕귀인은 주변의 호의와 완충 장치가 생기기 쉬운 도움 신호입니다.",
    positiveTags: ["stability_need", "public_presence"],
    riskTags: [],
    topicWeights: topicWeights([
      ["environment_luck", 0.75],
      ["human_relations", 0.55],
    ]),
    mbtiBridgeTags: ["public_presence", "stability_need"],
    phraseSeeds: phraseSeeds("월덕귀인"),
  }),
  entry({
    id: "nobleman_munchang",
    category: "nobleman",
    labelKo: "문창귀인",
    aliases: ["문창", "문창귀인"],
    summary: "글, 공부, 기획, 언어 감각이 살아나는 지적 도움 신호입니다.",
    meaning: "문창귀인은 생각을 정리해 말과 글로 풀어내는 능력과 연결됩니다.",
    positiveTags: ["precision_skill", "strategic_thinking"],
    riskTags: [],
    topicWeights: topicWeights([
      ["study_growth", 0.85],
      ["work_career", 0.55],
      ["strengths", 0.55],
    ]),
    mbtiBridgeTags: ["precision_skill", "strategic_thinking"],
    phraseSeeds: phraseSeeds("문창귀인"),
  }),
  entry({
    id: "nobleman_taegeuk",
    category: "nobleman",
    labelKo: "태극귀인",
    aliases: ["태극", "태극귀인"],
    summary: "큰 흐름을 읽고 의미를 붙이는 감각의 도움 신호입니다.",
    meaning: "태극귀인은 사건보다 구조와 의미를 보려는 관점과 연결됩니다.",
    positiveTags: ["strategic_thinking", "growth_orientation"],
    riskTags: ["loneliness"],
    topicWeights: topicWeights([
      ["study_growth", 0.65],
      ["environment_luck", 0.6],
      ["final_advice", 0.5],
    ]),
    mbtiBridgeTags: ["strategic_thinking", "growth_orientation"],
    phraseSeeds: phraseSeeds("태극귀인"),
  }),
  entry({
    id: "nobleman_jaego",
    category: "nobleman",
    labelKo: "재고귀인",
    aliases: ["재고", "재고귀인"],
    summary: "돈과 자원을 저장하고 필요할 때 꺼내 쓰는 도움 신호입니다.",
    meaning: "재고귀인은 재물이 바로 튀어나오기보다 관리, 보관, 축적 감각으로 작동하는 신호입니다.",
    positiveTags: ["asset_building", "money_orientation"],
    riskTags: ["stability_need"],
    topicWeights: topicWeights([
      ["money_asset", 0.8],
      ["environment_luck", 0.55],
      ["final_advice", 0.45],
    ]),
    mbtiBridgeTags: ["asset_building", "money_orientation"],
    phraseSeeds: phraseSeeds("재고귀인"),
  }),
  entry({
    id: "day_master_gabmok",
    category: "day_master",
    labelKo: "갑목",
    aliases: ["甲木", "갑목", "큰 나무"],
    summary: "큰 줄기를 세우고 위로 뻗는 시작과 지휘의 일간입니다.",
    meaning: "갑목은 방향을 세우고 앞에서 길을 내는 힘이라 성장, 기준, 리더십과 연결됩니다.",
    positiveTags: ["growth_orientation", "leadership", "strategic_thinking"],
    riskTags: ["control_need"],
    topicWeights: topicWeights([
      ["personality", 0.8],
      ["work_career", 0.65],
      ["strengths", 0.6],
    ]),
    mbtiBridgeTags: ["leadership", "growth_orientation"],
    phraseSeeds: phraseSeeds("갑목"),
  }),
  entry({
    id: "day_master_gito",
    category: "day_master",
    labelKo: "기토",
    aliases: ["己土", "기토", "논밭의 흙"],
    summary: "현실을 받아 정리하고 키우는 섬세한 토의 일간입니다.",
    meaning: "기토는 돌보고 관리하며 현실을 재배치하는 힘이라 안정, 실무, 축적과 연결됩니다.",
    positiveTags: ["stability_need", "asset_building", "self_discipline"],
    riskTags: ["low_rest_capacity"],
    topicWeights: topicWeights([
      ["personality", 0.75],
      ["money_asset", 0.6],
      ["family_independence", 0.55],
    ]),
    mbtiBridgeTags: ["stability_need", "asset_building"],
    phraseSeeds: phraseSeeds("기토"),
  }),
  entry({
    id: "day_pillar_gapsin",
    category: "day_pillar",
    labelKo: "갑신일주",
    aliases: ["甲申", "갑신", "갑신일주"],
    summary: "큰 나무가 날카로운 금 위에 앉은 구조로 지휘 욕구와 판단력이 함께 살아납니다.",
    meaning: "갑신일주는 성장하려는 갑목과 정리하려는 신금이 맞물려 추진과 판단이 동시에 강해지는 seed입니다.",
    positiveTags: ["leadership", "sharp_analysis", "strategic_thinking"],
    riskTags: ["direct_speech", "control_need"],
    topicWeights: topicWeights([
      ["personality", 0.8],
      ["work_career", 0.75],
      ["human_relations", 0.55],
    ]),
    mbtiBridgeTags: ["leadership", "sharp_analysis", "control_need"],
    phraseSeeds: phraseSeeds("갑신일주"),
  }),
  entry({
    id: "day_pillar_gihae",
    category: "day_pillar",
    labelKo: "기해일주",
    aliases: ["己亥", "기해", "기해일주"],
    summary: "섬세한 토가 깊은 물 위에 놓여 현실감과 내면 감각이 함께 움직입니다.",
    meaning: "기해일주는 현실을 관리하는 기토와 깊게 흐르는 해수가 만나 돌봄, 감정, 저장감이 섞이는 seed입니다.",
    positiveTags: ["stability_need", "empathy_need", "strategic_thinking"],
    riskTags: ["loneliness", "low_rest_capacity"],
    topicWeights: topicWeights([
      ["personality", 0.7],
      ["family_independence", 0.55],
      ["love_relationship", 0.5],
    ]),
    mbtiBridgeTags: ["empathy_need", "stability_need"],
    phraseSeeds: phraseSeeds("기해일주"),
  }),
] as const satisfies readonly SajuKnowledgeEntry[];

export const SAJU_KNOWLEDGE_BY_ID = new Map(
  SAJU_KNOWLEDGE_BASE.map((item) => [item.id, item]),
);
